### ISSUE TITLE
Why do I get #NAME? in a formula cell?

### ISSUE THREAD

**Issue by Osram-Gru** [qax-os/excelize#1000]
Hi, I'm just starting to use excelize and I'm stuck with creating a formula:

```
err = f.SetCellFormula("shee", fmt.Sprintf("E%d", row+2), fmt.Sprintf("=MONTHS(D%d,TODAY(),1)", row+2))
```
`err` is nil.

When I open the sheet, all cells with this formula show `#NAME?` and I don't get why.  When I click on the cell, there's this in the edit line:
```
=months(D3,TODAY(),1)
```

There's awfully little documentation for this function, btw.

How do I set  a formula in the right way?

**Comment by Osram-Gru** [comment]
:partying_face:  #1000

**Comment by stanim** [comment]
I think formulas don't start with the equal sign, try:

`err = f.SetCellFormula("shee", fmt.Sprintf("E%d", row+2), fmt.Sprintf("=MONTHS(D%d,TODAY(),1)", row+2))`

**Comment by Osram-Gru** [comment]
I tested with libreoffice which offers `MONTHS()`. Strange thing: When I clicked on the = sign in libreoffice, the cells turned into a working formula....

But you're right: When I open it in MS Excel, I get an error message. If I replace `MONTHS()` by `sin(...)`, it works, including the `=` sign.

Thanks for your help!
