### ISSUE TITLE
Implement MATCH function

### ISSUE THREAD

**Issue by stanim** [qax-os/excelize#1008]
**Description**

The **MATCH** function searches for a specified item in a range of cells, and then returns the relative position of that item in the range. For example, if the range A1:A3 contains the values 5, 25, and 38, then the formula =MATCH(25,A1:A3,0) returns the number 2, because 25 is the second item in the range.
https://support.microsoft.com/en-us/office/match-function-e8dffd45-c762-47d6-bf89-533f4a37673a

**Syntax**

MATCH(lookup_value, lookup_array, [match_type])

The MATCH function syntax has the following arguments:

- lookup_value    Required. The value that you want to match in lookup_array. For example, when you look up someone's number in a telephone book, you are using the person's name as the lookup value, but the telephone number is the value you want. 

  The lookup_value argument can be a value (number, text, or logical value) or a cell reference to a number, text, or logical value.

- lookup_array    Required. The range of cells being searched.

- match_type    Optional. The number -1, 0, or 1. The match_type argument specifies how Excel matches lookup_value with values in lookup_array. The default value for this argument is 1.

**Comment by xuri** [comment]
Thanks for your issue, I have initialized the `MATCH` formula function support, please try to upgrade to the `master` branch.
