### ISSUE TITLE
setting the col width before writing the row  but not applied

### ISSUE THREAD

**Issue by rbucker** [qax-os/excelize#1009]
https://github.com/qax-os/excelize/blob/933159f9391f9be1b41b51e85885722124f8a7aa/stream.go#L368-L374

This function makes the request that it is called before adding the actual data row. However, it is incomplete in the entire context.

- should setcolwidth() be called before the first row is added
- what happens when it is called multiple times on the same column(s)) in the sheet while writing data to the sheet?

**Comment by xuri** [comment]
Thanks for your issue, if you set columns width in the stream mode multiple times on the same columns, the result is the same with call it once, but if you set columns with overlaps, it will overwrite the width settings for overlapped columns, for example:

```go
streamWriter.SetColWidth(2, 3, 20)
streamWriter.SetColWidth(3, 4, 40)
```

the width of column `B` is 20, and the width `C:D` is 40.

**Comment by rbucker** [comment]
I can try that. Seems weird. In this example I have 3 columns... in order example you have 4  columns... Would this work...

```
streamWriter.SetColWidth(2, 3, 20)
streamWriter.SetColWidth(3, 3, 40)
```
Thanks

**Comment by xuri** [comment]
You're welcome.
