### ISSUE TITLE
Feature: Ignore macrosheet when calling UpdateLinkedValue()

### ISSUE THREAD

**Issue by Ralim** [qax-os/excelize#1014]
**Description**
I have a file that has a sheet that is a macrosheet instead of a normal sheet.
I don't need to edit this sheet at all, just have it be left-alone.

The current code throws an error when calling `UpdateLinkedValue()` as it cant parse this sheet.
`xml decode error: expected element type <worksheet> but have <macrosheet>`

Would love even if it would be possible to add this to the `UpdateLinkedValue()` call, like we do for chart sheets

```
if err.Error() == "xml decode error: expected element type <worksheet> but have <macrosheet>" {
     continue
}
```

**Steps to reproduce the issue:**

Can't currently publicly share the file sadly, but if desired can try and make a minimal example.

**Describe the results you received:**
`xml decode error: expected element type <worksheet> but have <macrosheet>`
**Describe the results you expected:**

No errors 😓 

**Output of `go version`:**

```text
go version go1.17 linux/amd64
```

**Excelize version or commit ID:**

```text
v2 latest / a2d449708cf72928394b4bc4aea41c0c6a606fa2
```

**Environment details (OS, Microsoft Excel™ version, physical, etc.):**

Have been using this patch for now, and everything is working 😂 
https://github.com/Ralim/excelize/commit/83555e7df1b4cc4510fc788e3b0bae4aac0f5a0e

**Comment by xuri** [comment]
Thanks for your feedback, could you provide a spreadsheet xlsx attachment without confidential info?

**Comment by xuri** [comment]
Thanks for your feedback. I have fixed this issue, please try to upgrade the master branch code
