### ISSUE TITLE
print titles

### ISSUE THREAD

**Issue by victotyone** [qax-os/excelize#1015]
Is it possible to set repeat print titles for specific lines in print settings?

**Comment by xuri** [comment]
Thanks for your issue, please reference the documentation of the [`SetDefinedName`](https://xuri.me/excelize/en/workbook.html#SetDefinedName), for example, set print titles with rows to repeat at the top using the first row on `Sheet1` like this:

```go
f.SetDefinedName(&excelize.DefinedName{
    Name:     "_xlnm.Print_Titles",
    RefersTo: "Sheet1!$A:$A,Sheet1!$1:$1",
    Scope:    "Sheet1",
})
```

**Comment by dami-izolan-axon** [comment]
@xuri

I found out today (v2.8.1) that if you fill the `RefersTo` property with only one range without a comma (instead of two separated with a comma), it will work as row title only. You don't need to fill a column title.

It would be cool if this was added to the docs.

**Comment by xuri** [comment]
Hi @dami-izolan-axon, thanks for your suggestion. I updated documentation and godoc for this.
