### ISSUE TITLE
Images are duplicated

### ISSUE THREAD

**Issue by ipopa** [qax-os/excelize#1017]
**Description**

We currently have an excel file containing 3 sheets. When adding an image in the sheet 2 and another image in the sheet 3, we have a duplication of this image when saving this file: both of the images are in both sheet 2 and sheet 3.
By removing sheet 1, the issue doesn’t occur anymore, but the thing is we cannot remove it. We guess something is wrong with this first sheet that we want to identify.

**Steps to reproduce the issue:**
```
package main

import (
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/xuri/excelize/v2"
)

func TestAddPicture(t *testing.T) {
	xlsx, err := excelize.OpenFile("./test.xlsx")

	assert.Nil(t, err)

	xlsx.AddPicture("sheet2", "B3", "./image1.png", "{}")
	xlsx.AddPicture("sheet3", "L1", "./image2.png", "{}")

	xlsx.SaveAs("./test_output.xlsx")
}

```

**Describe the results you received:**
output preview:
<img width="1448" alt="output preview" src="https://user-images.githubusercontent.com/14199839/132829674-54364104-48e7-49b4-b8ad-60a7bd9226e5.png">

excel:
[test.xlsx](https://github.com/qax-os/excelize/files/7142678/test.xlsx)

output excel:
[test_output.xlsx](https://github.com/qax-os/excelize/files/7142638/test_output.xlsx)

images:
<img width="156" alt="image1" src="https://user-images.githubusercontent.com/14199839/132829503-aeb3bdb8-0fcd-4160-a23d-ec64388fd86a.png">
<img width="211" alt="image2" src="https://user-images.githubusercontent.com/14199839/132829506-e11bfe5d-0701-443a-be14-0a2f5c7a0575.png">

**Describe the results you expected:**
Each image should be added in the sheet it belongs to: Image 1 in sheet 2 and image 2 in sheet 3

**Output of `go version`:**

```text
1.16
```

**Excelize version or commit ID:**

```text
2.4.1
```

**Environment details (OS, Microsoft Excel™ version, physical, etc.):**
OS: macOS Big Sur 11.5.2
Microsoft Excel™ version: Microsoft Excel for Mac 16.52

**Comment by xuri** [comment]
Thanks for your issue, I have fixed it, please try to use the master branch code.

**Comment by ipopa** [comment]
It works, thank you
