### ISSUE TITLE
Which URL is it?

### ISSUE THREAD

**Issue by DaleEMoore** [qax-os/excelize#1020]
I'm confused! I don't know which URL is correct and I wonder how things got into this mess?

	"github.com/360EntSecGroup-Skylar/excelize" 	// This appears to be the right thing!
	//"github.com/xuri/excelize"					// Documentation says this works.
	//"github.com/qax-os/excelize"				// Code specifies.

And especially I wonder where the mess will go in the future.

It looks like you've got a great product except that it's hard for me to know how to use it.

When will GitHub recognize "github.com/360EntSecGroup-Skylar"? Or will it ever?

I look forward to hearing from you!

**Comment by xuri** [comment]
Thanks for your issue, I'm sorry for bringing you confusion, the new go modules import path `github.com/xuri/excelize/v2` took effect since version 2.4.1, please use this URL, also ref #973.

**Comment by xuri** [comment]
I'll close this issue, if you have any questions, please let me know.

**Comment by DaleEMoore** [comment]
I don't mean to re-open this issue because "github.com/xuri/excelize/v2" works perfectly and I'm delighted to see that it will be here forever! Thanks for clarifying my confusion!
