### ISSUE TITLE
Cells containing line breaks

### ISSUE THREAD

**Issue by zhangzhe532** [qax-os/excelize#1021]
**Description**：

I want to realize the function of displaying the title with line break in the center of the merged cell.

![](https://ae02.alicdn.com/kf/Hb809e2de18d14b08a53ab133e217df2eW.png)

**Steps to reproduce the issue:**

1. I did it with line breaks in the title:

```
title: "标签名称：xxxxx" + "\r\n" + "打上标签时间: xxxx"
```

**When i click on this cell：**

![](https://ae05.alicdn.com/kf/H5d32dfe30d3c4e1abb5ad79b4cad88cbs.png)

**I finally achieved it by hiding the cell line：**

![](https://ae01.alicdn.com/kf/H1b93b75fa6d2429e82794bcf2374fe81B.png)

**Describe the results you received:**

![](https://ae05.alicdn.com/kf/H63da9c57497a47ab9f0e529fc83c66ecc.png)

**Describe the results you expected:**

![](https://ae05.alicdn.com/kf/H4c424d37ad47469bb4b436eaff9096c5d.png)

Hope this project can support Excel line break: char(10)

**Output of `go version`:**

```text
go version go1.17.1 linux/amd64
```

**Excelize version or commit ID:**

```text
excelize v2.3.2
```

**Environment details (OS, Microsoft Excel™ version, physical, etc.):**

OS: Ubuntu 20.04 LTS

Excel version: wps 2019、Microsoft Excel 2016

**Comment by xuri** [comment]
Thanks for your issue, this duplicate with #405, please also reference the documentation of the [`SetCellStyle`](https://xuri.me/excelize/zh-hans/cell.html#SetCellStyle) and [`NewStyle`](https://xuri.me/excelize/zh-hans/style.html#NewStyle).
