### ISSUE TITLE
Reading file in streaming style to save memory

### ISSUE THREAD

**Issue by beantowel** [qax-os/excelize#1022]
**Reading file in streaming style to save memory**

This issue #855 works fine, but it still cost too much memory when there are too many empty lines. Recently we encountered an xlsx file with 100w empty lines: [Metadata.xlsx](https://github.com/qax-os/excelize/files/7175730/Metadata.xlsx), it would alloc about 3GB memory when reading this file.

**Steps to reproduce the issue:**
```go
func BenchmarkExcelize(b *testing.B) {
	for i := 0; i < b.N; i++ {
		f, err := excelize.OpenFile("/home/xxx/Downloads/Metadata.xlsx")
		if err != nil {
			b.Error(err)
		}
		rows, err := f.GetRows("Sheet1")
		if err != nil {
			b.Error(err)
		}
		b.Logf("rows=%v", len(rows))
	}
}
```
**Describe the results you received:**
```text
BenchmarkExcelize-8
       1	15342146976 ns/op	3669757792 B/op	78659374 allocs/op
```

**Describe the results you expected:**
we expect less memory usage for this one-line xlsx file, maybe 10MB?

**Output of `go version`:**

```text
go version go1.16.3 linux/amd64
```

**Excelize version or commit ID:**

```text
github.com/xuri/excelize/v2 v2.4.1
```

**Environment details (OS, Microsoft Excel™ version, physical, etc.):**

**Comment by xuri** [comment]
Thanks for your issue, I've tested count non-empty cells with your spreadsheet by streaming reading, and the RSS (resident set size) about 479MB, the excelize doesn't skip the empty row, to make the developer know some rows seems blank but not empty in the worksheet.

**Comment by beantowel** [comment]
Yes RSS is much smaller than allocation space, but 400MB memory is still a bit unacceptable for a 9MB xlsx file.
```text
time go test -benchmem -run=^$ -bench BenchmarkExcelize xxx/test -v -count=1 
ETCD: use bagent to access ETCD
goos: linux
goarch: amd64
pkg: xxx/test
cpu: Intel(R) Xeon(R) Platinum 8260 CPU @ 2.40GHz
BenchmarkExcelize
    xlsx_test.go:34: rows=2
BenchmarkExcelize-8            1        15194605717 ns/op       3669690264 B/op 78659361 allocs/op
PASS
ok      xxx/test    15.266s
go test -benchmem -run=^$ -bench BenchmarkExcelize xxx/test -v    17.58s  user 1.38s system 115% cpu 16.426 total
avg shared (code):         0 KB
avg unshared (data/stack): 0 KB
total (sum):               0 KB
max memory:                499 MB
page faults from disk:     27
other page faults:         138005
```

**Comment by xuri** [comment]
Hi @beantowel, I have improved the streaming reader performance for the rows iterator, memory usage decrease by about 93.7%. Please upgrade to the master branch code. This is a breaking change, the user should be close the stream after using the row's iterator, and close the spreadsheet after opening an existing spreadsheet like this:

```go
package main

import (
    "fmt"

    "github.com/xuri/excelize/v2"
)

func main() {
    f, err := excelize.OpenFile("Book1.xlsx")
    if err != nil {
        fmt.Println(err)
        return
    }
    rows, err := f.Rows("Sheet1")
    if err != nil {
        fmt.Println(err)
        return
    }
    for rows.Next() {
        row, err := rows.Columns()
        if err != nil {
            fmt.Println(err)
        }
        for _, colCell := range row {
            fmt.Print(colCell, "\t")
        }
        fmt.Println()
    }
    // Close the stream
    if err = rows.Close(); err != nil {
        fmt.Println(err)
    }
    // Close the workbook
    if err := f.Close(); err != nil {
        fmt.Println(err)
    }
}
```
