### ISSUE TITLE
time parse accuracy

### ISSUE THREAD

**Issue by HeliOs-Dou** [qax-os/excelize#1026]
i'm using v2.4.1.
content to be read is "2021/7/8  5:00:00" with format "yyyy/m/d h:mm".
with this format,cell shows like "2021/7/8 5:00",but the value i got is "7/8/21 04:59“,lose 1 minute.

**Comment by xuri** [comment]
Thanks for your issue, I have fixed it, please try to use the master branch code.

**Comment by HeliOs-Dou** [comment]
thank u
