### ISSUE TITLE
Value in scientific notifications format will be rounded

### ISSUE THREAD

**Issue by weeee9** [qax-os/excelize#1027]
**Description**
Cell value in scientific notifications format will be rounded
For example, `2.23E+00` will be round to `2e+00` 

**Steps to reproduce the issue:**
1. Change cell value to scientific notifications format
2. Read rows

**Describe the results you received:**
`2e+00`

**Describe the results you expected:**
`2.23E+00` or `2.23`

**Output of `go version`:**

```text
go version go1.16.5 darwin/arm64
```

**Excelize version or commit ID:**

```text
v2.3.2
```

**Comment by xuri** [comment]
Thanks for your issue, I have fixed it, please upgrade to the master branch code, and this patch will be released in the next version.
