### ISSUE TITLE
Insert Row - break page

### ISSUE THREAD

**Issue by ipopa** [qax-os/excelize#1032]
**Description**

When inserting a new row via Excel the feature "break page" of Excel is working, but is not working if we do it via this library

**Steps to reproduce the issue:**
```
package main

import (
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/xuri/excelize/v2"
)

func TestAddPicture(t *testing.T) {
	xlsx, err := excelize.OpenFile("./test.xlsx")

	assert.Nil(t, err)

	xlsx.InsertRow("sheet1", 2)

	xlsx.SaveAs("./test_output.xlsx")
}

```

**Describe the results you received:**
output preview:
<img width="1212" alt="Screenshot 2021-10-06 at 13 54 20" src="https://user-images.githubusercontent.com/14199839/136197410-2d71a26f-51f1-4e30-ac13-d5ef9b751a83.png">

excel:
[test.xlsx](https://github.com/qax-os/excelize/files/7293458/test.xlsx)

output excel:
[test_output.xlsx](https://github.com/qax-os/excelize/files/7293457/test_output.xlsx)

**Describe the results you expected:**
The new row must be inside the page

**Output of `go version`:**

```text
1.16
```

**Excelize version or commit ID:**

```text
28841af9804243205a9693be0cb501ce2d980302
```

**Environment details (OS, Microsoft Excel™ version, physical, etc.):**
OS: macOS Big Sur 11.5.2
Microsoft Excel™ version: Microsoft Excel for Mac 16.52

**Comment by ipopa** [comment]
Yes, i understand, but i don't know the real impact if i do that, we have a generic solution (something like that https://docxtemplater.com/modules/xlsx/), i don't know the files in advance

**Comment by xuri** [comment]
Once the Defined Name has been affected, it will impact the actual content anywhere referenced that defined name, such as calculated value, styles of the cell.
