### ISSUE TITLE
Sheet Index 0 Zero Rows

### ISSUE THREAD

**Issue by masdikaid** [qax-os/excelize#1033]
Helo everyone need your help.

I had one file that I get from daily report download with xlsx extension. Then I want to insert to MongoDB for analytic cause per day can be 100K rows, and I use golang with excelize to extract excel data then insert them to mongoDB, there is the problem :

When I GetRows("Sheet 1") the result is 0 and when I check the sheet with ```GetSeetMap()``` result is ```[0:Sheet 1]``` and it is still 0 rows.

But when I renamed sheet name (ie: rename to another Sheet) and I check the sheet map it change to [1:another Sheet] and rows detected when the sheet map key is 1, how to fix this?

Thanks for advance

**Comment by xuri** [comment]
Thanks for your feedback, which version of Excelize are you using? Can you show us a complete, standalone example program? And provide spreadsheet attachment if you can.

**Comment by masdikaid** [comment]
iam sory iam in wrong library, all's done when i use this library
