### ISSUE TITLE
row count

### ISSUE THREAD

**Issue by jacket-code** [qax-os/excelize#1036]
**Description**
一个excel表，只有448行，但是读取的时候，rows, err := f.GetRows(f.GetSheetName(0))，这个rows长度为5000行
代码：
![image](https://user-images.githubusercontent.com/2426679/137446293-12cde269-39e0-468b-ae85-2885987110dc.png)
excel:
![image](https://user-images.githubusercontent.com/2426679/137446328-6833b4e2-9e9f-4d2b-8b5f-0ef6edf1112e.png)

应该返回448才对呢，448到表结束都没有数据，却返回有5000行

**Comment by xuri** [comment]
Thanks for your issue, which version of Excelize are you using? I recommend the upgrade to the latest version, as the documentation of the `GetRow` says: it fetched the rows with value or formula cells (these cells the value is blank but that maybe not empty), the tail continuously empty cell will be skipped, if you still got the issue, please provide a spreadsheet attachment without confidential info.

**Comment by xuri** [comment]
It seems still not have enough info of code and attachments to reproduce this issue, so I'll close this issue, if you have any questions, please let me know.
