### ISSUE TITLE
[FEATURE REQUEST] - Parse Spreadsheet from html table

### ISSUE THREAD

**Issue by sujit-baniya** [qax-os/excelize#1043]
**Description**
Using style functions to format the worksheet can be a lot time consuming. So maybe introduce a feature that would parse existing html table to create worksheet.

**New Functions**
- `Parse(htmlPage string, data map[string]interface{}) Worksheet` - This function would create the html table on the htmlPage using the data and parse the html to be used further

**Comment by xuri** [comment]
This issue about the `DuplicateRow` function similar with #772. I close this and merge it into issue #772 is still discussing this.
