### ISSUE TITLE
Add picture function don't work correctly

### ISSUE THREAD

**Issue by hofarah** [qax-os/excelize#1050]
**Steps to reproduce the issue:**
1.add some picture into different rows
2.change other pictures on the file!!
**3.multi sheet excel file**

```text
Hello.
when  i want to add some picture in one xlsx file multi sheet(in for loop) they don't set correctly and one or 2 image only set .
also 1 picture that was in template file also change!
```
```text
        f, err := excelize.OpenFile("./FORM_EXCEL.xlsx")
	if err != nil {
		return  err
	}
	err = f.AddPicture("sheet1", "C10", "."+"/images/82018600.png", `{"autofit": true }`) //picture
	err = f.AddPicture("sheet1", "C11", "."+"/images/82018601.png", `{"autofit": true }`) //picture
	err = f.AddPicture("sheet1", "C12", "."+"/images/82018602.png", `{"autofit": true }`) //picture
        f.save()
```

![screenshot-2021-11-03_18:04:12](https://user-images.githubusercontent.com/53389261/140080658-fe0be6ff-cd7b-4281-822b-434eb698e9a8.png)

**Comment by hofarah** [comment]
3 pictures are different but you see this ...👆👆👆👆👆👆

**Comment by xuri** [comment]
Thanks for your feedback, could you show us a complete, standalone example program or reproducible demo? Which version of the Excelize are you using, please gave a try the master branch code. And provide your input file attachment without confidential info if you can.

**Comment by xuri** [comment]
It seems still not have enough info of code and attachments to reproduce this issue, so I'll close this issue, if you have any questions, please let me know to reopen this anytime.
