### ISSUE TITLE
Read data from excel but get an unexpected result

### ISSUE THREAD

**Issue by Rorke76753** [qax-os/excelize#1051]
Here is my cell value like
|----|
| 12  |
| 13  |
|----|

I am using the lib in this way 
```
rows ,_ := file.GetRows(sheetName)
for _ ,data := range rows{
   fmt.Println(data)
}
```

The result I expect
"12","13"

But I got the result
"12.0","13.0"

How can I get the result I expect and what cause the unexpected result

**Comment by Rorke76753** [comment]
btw  I am using release v2.3.2

**Comment by xuri** [comment]
Thanks for your feedback, could you provide the file attachment without confidential info? and before that please give a try the master branch code.

**Comment by xuri** [comment]
It seems still not have enough info of code and attachments to reproduce this issue, so I'll close this issue, if you have any questions, please let me know.
