### ISSUE TITLE
Is there any way to write stream to the file before flush by StreamWriter?

### ISSUE THREAD

**Issue by woostundy** [qax-os/excelize#1052]
The background is that I have 10,000+ rows of data in DB to export.
The data will be queried by several times, and it really costs time.
So can I format the rows and write to `io.writer` when every query is finished, and call flush() to write the file tail when all parts are finished? Like a whole stream process.

**Comment by xuri** [comment]
Just flush once for each worksheet, data will be storage in the memory and system temporary directory before save the spreadsheet.

**Comment by woostundy** [comment]
so it's impossible to export and download at the same time?

**Comment by woostundy** [comment]
I wonder that if the data could be stored in the memory, Can I write it to `io.writer` directly? and append the tail of the worksheet when the whole worksheet is finished.
it would save lots of time if it's possible.

**Comment by xuri** [comment]
This issue is duplicated with #753.

**Comment by woostundy** [comment]
Okay, I see.
Is this impossible from the underlying principle?
will it be supported in the future?

**Comment by xuri** [comment]
Please reference @753, with the spreadsheet [specification](https://www.ecma-international.org/publications-and-standards/standards/ecma-376/) limit (OPC part), the workbook serialization should be waiting all worksheet has been ready.

**Comment by xuri** [comment]
Please reference #753, with the spreadsheet [specification](https://www.ecma-international.org/publications-and-standards/standards/ecma-376/) limit (OPC part), the workbook serialization should be waiting all worksheet has been ready.
