### ISSUE TITLE
Get cell value which applied number format

### ISSUE THREAD

**Issue by csg2008** [qax-os/excelize#1055]
**Description**

1、将非日期的单元格格式设置为日期，在WPS Office与Onlyoffice中显示为原始内容，在excelize解析为日期内容就错了
2、复杂的数字格式解析错误，最后显示为部分格式字符串

**Steps to reproduce the issue:**
1. 问题一重现过程：在A1单元格输入87812，将单元格格式设置为yyyy/m/d，解析结果为：06-01-40
2. 问题二重现过程：在A2单元格输入 12930，将单元格格式设置为_([$USD] * #,##0.00_);_([$USD] * (#,##0.00);_([$USD] * "-"???_);_(@_)，解析结果为：_( * -???_)
3.

**Describe the results you received:**
解析结果与Office一样

**Describe the results you expected:**

**Output of `go version`:**

```text
go version go1.17.2 windows/amd64
```

**Excelize version or commit ID:**

```text
v2.4.1
```

**Environment details (OS, Microsoft Excel™ version, physical, etc.):**
WIN10, WPS Office 11.1.0.10938, Onlyoffice 6.4.1

**Comment by xuri** [comment]
This issue is duplicated with #660, as the documentation says, if the cell format can be applied to the value of a cell, the applied value will be returned, otherwise the original value will be returned.
