### ISSUE TITLE
Defined names - Break page

### ISSUE THREAD

**Issue by ipopa** [qax-os/excelize#1056]
**Description**

I have an excel with 3 break pages, but GetDefinedName does not return them.

**Steps to reproduce the issue:**
```
package main

import (
        "fmt"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/xuri/excelize/v2"
)

func TestAddPicture(t *testing.T) {
	xlsx, err := excelize.OpenFile("./test.xlsx")

	assert.Nil(t, err)

	definedNames := xlsx.GetDefinedName()

	for _, definedName := range definedNames {
		fmt.Println(definedName.RefersTo)
	}
}

```

**Describe the results you received:**
excel:
[test.xlsx](https://github.com/qax-os/excelize/files/7498196/test.xlsx)

`go test`

```
Test!#REF!
Test!$D$16
Test!$D$17
Test!#REF!
Test!#REF!
```

**Describe the results you expected:**
```
Test!$A$1:$N$13
Test!$A$14:$N$20
Test!$A$21:$N$31
```

**Output of `go version`:**

```text
1.16
```

**Excelize version or commit ID:**

```text
8f82d8b02909ca96a9c7f7c3431d1ae990c90191
```

**Environment details (OS, Microsoft Excel™ version, physical, etc.):**
OS: macOS Big Sur 11.5.2
Microsoft Excel™ version: Microsoft Excel for Mac 16.52

**Comment by xuri** [comment]
Thanks for your issue, The `GetDefinedName` function can't be used for retrieve page breaks of the spreadsheet, I'll consider to add the `GetPageBreak`s to do that.

**Comment by Jonham** [comment]
I've extract `test.xlsx` and find
```xml
<pageSetup paperSize="9" scale="43" fitToHeight="0" orientation="portrait" r:id="rId1"/>
<rowBreaks count="2" manualBreakCount="2">
  <brk id="13" max="16383" man="1"/>
  <brk id="20" max="16383" man="1"/>
</rowBreaks>
<colBreaks count="2" manualBreakCount="2">
  <brk id="2" max="1048575" man="1"/>
  <brk id="13" max="1048575" man="1"/>
</colBreaks>
```
in which: `<pageSetup ... fitToHeight="0" ..>` results print setting `adjust to 1 page wide` and two brk in `colBreaks` lose their effect.

let's define result `Test!$A$1:$N$13` as `${sheetName}!${StartCol}${StartRow}:${EndCol}${EndRow}`.
in this case, currently `GetPageBreak` can only get startRow and endRow, cannot get StartCol or EndCol.

By looking at `test/xl/worksheets/_rels/sheet1.xml.rels`, I think sheet print setting has something to do with `../printerSettings/printerSettings1.bin` file, which has type of `http://schemas.openxmlformats.org/officeDocument/2006/relationships/printerSettings` and it's [one DEVMODE structure](https://docs.microsoft.com/zh-cn/windows/win32/api/wingdi/ns-wingdi-devmodea) according to [Printer Settings | Microsoft Docs](https://docs.microsoft.com/en-us/openspecs/office_file_formats/ms-xlsb/1cdc4cb9-836d-41d6-a5b5-9ac0428f491c).

### suggestion for @ipopa 
if you just need to read and column width is fixed (A to N), add `GetPageBreaksRow ?` and return breaks in rowBreaks can help.
but if printing column range will grow, `GetPageBreaksRow` can't help as far as I know.

And if you need to generate Print Setting as `test.xlsx` you provided, it will still lead to `printerSettings1.bin` generation, which `excelize` has yet not implemented.

### some related doc:

- [2.1.7.41 Printer Settings | Microsoft Docs](https://docs.microsoft.com/en-us/openspecs/office_file_formats/ms-xlsb/1cdc4cb9-836d-41d6-a5b5-9ac0428f491c)
- [DEVMODEA structure (wingdi.h) | Microsoft Docs](https://docs.microsoft.com/zh-cn/windows/win32/api/wingdi/ns-wingdi-devmodea)

**Comment by Jonham** [comment]
can `DefinedName` be 'define' as pointer or shortname for Excel inner object like cell, range, etc ?

**Comment by ipopa** [comment]
thanks @Jonham 
I think that `GetPageBreaksRow` can help
How can I implement that ?

**Comment by Jonham** [comment]
I think you need to read implementation of `RemovePageBreak` and `InsertPageBreak`, then range `ws.RowBreaks.Brk` and turn `xlsxBrk` into a exported struct.

**Comment by ipopa** [comment]
@xuri This https://github.com/qax-os/excelize/commit/b96329cc88b87da25a4389f1d4d5ad08cd40605a fixes also page breaks.
And with this implementation I succeeded. 
```
func (f *File) GetPageBreaksRow(sheet string) []*xlsxBrk {
	ws, _ := f.workSheetReader(sheet)

	if ws.RowBreaks == nil {
		ws.RowBreaks = &xlsxBreaks{}
	}

	return ws.RowBreaks.Brk
}

func (f *File) MovePageBreakRow(brk *xlsxBrk, toRow int) {
	brk.ID = toRow
}

**Comment by xuri** [comment]
Thanks for your feedback.
