### ISSUE TITLE
Setting Font Style to Bold not working on Apple Numbers (Big Sur)

### ISSUE THREAD

**Issue by btnmasher** [qax-os/excelize#1059]
**Description**

Upgrading from an old 1.3 version of Excelize to 2.4.1 to gain the StreamWriter feature, setting a cell style as described by the documentation results in the bold styling not displaying in Apple Numbers on Big Sur version of MacOS. Other styling options such as Alignment and Font Color are working. Viewing the resulting excel file in Google Sheets does display the formatting as expected.

**Steps to reproduce the issue:**
1. Start a write flow using StreamWriter
2. Create a `NewStyle()` with `{"font":{"bold":true},"alignment":{"horizontal":"center"}}`
3. Allocate some `excelize.Cell{}` structs, setting each `StyleID` with the previously created style, and add them to a slice
4. Use `SetRow()` to write the slice to a row (in my case, the row begins at "C1")
4. Flush and Save the file
5. Open the file in Apple Numbers and observe the styling.

**Describe the results you received:**

The cells in the row are styled with the correct alignment, but not the correct Bold font styling. (font colors also work)

**Describe the results you expected:**

The cells row to be styled with the correct Bold font styling.

**Output of `go version`:**

```text
go version go1.17.2 darwin/amd64
```

**Excelize version or commit ID:**

```text
2.4.1
```

**Environment details (OS, Microsoft Excel™ version, physical, etc.):**

MacOS Big Sur

**Comment by xuri** [comment]
Thanks for your issue, I have fixed it, please upgrade to the master branch code, and this patch will be released in the next version.

**Comment by btnmasher** [comment]
Worked great, thanks!
