### ISSUE TITLE
multi-byte language length support

### ISSUE THREAD

**Issue by lbz-sugimoto** [qax-os/excelize#1061]
**Description**

Current code treats one multi byte character (some Eastern Asian languages) as 3 words. It restricts word count more than expected, especially in header/footer section.

https://github.com/qax-os/excelize/blob/master/sheet.go#L1094-L1098
```
for i := 4; i < v.NumField()-1; i++ {
    if v.Field(i).Len() >= 255 {
        return fmt.Errorf("field %s must be less than 255 characters", v.Type().Field(i).Name)
    }
}
```

**Comment by xuri** [comment]
Thanks for your issue, I have fixed it, please upgrade to the master branch code, and this patch will be released in the next version.

**Comment by lbz-sugimoto** [comment]
Appreciate your quick fix. Thanks!
