### ISSUE TITLE
Temp files created at /tmp are not cleaned up

### ISSUE THREAD

**Issue by sandeepatil1288** [qax-os/excelize#1062]
I am using excelize to read a bunch of xls/xlsx files.

Following is the outline of the usage,

f, err := excelize.OpenFile("Book1.xlsx")
if err != nil {
    return
}

rows, err := f.GetRows("Sheet1")
if err != nil {
    fmt.Println(err)
    return
}

for _, row := range rows {
    for _, colCell := range row {
        fmt.Print(colCell, "\t")
    }
	fmt.Println()
	if <Any Validation Fails>
		break;
}

Issue Observed: 
During reading of the files some temporary files are created like, excelize-1448635484 at the following path, /tmp/ and never gets cleaned up.
This is leading to eating up the memory of system causing more problems.

Go Version: 1.16

Excelize Version: 2.4.1

Can someone please share us some insight on what is causing the temp file creations and what is preventing from the same being cleared.?

**Comment by xuri** [comment]
Thanks for your feedback, are you sure you're using the version 2.4.1? Excelize only created temporary files when using the [`stream writer`](https://pkg.go.dev/github.com/xuri/excelize/v2#File.NewStreamWriter) to create the spreadsheet in the version 2.4.1, call [`Flush`](https://pkg.go.dev/github.com/xuri/excelize/v2#StreamWriter.Flush) function after streaming writing finished, it will be cleanup the temporary files, reading data with `GetRows` won't be touch the temporary files, and note that, after commit [`790c363`](https://github.com/xuri/excelize/commit/790c363cceaaa09e91ad579e2d25cb13c1582bba) (this breaking change will be released in thenext version), temporary files maybe created when reading data (depends on data scale and open options `WorksheetUnzipMemLimit` values ) and the user should be close the stream after using the row's iterator, and close the spreadsheet after opening an existing spreadsheet, also reference the issue #833.

**Comment by sandeepatil1288** [comment]
Thanks for the quick response.
I am confirming the details requested, 
Exact tag we are on is, v2.4.1-35-g58fd279.
Package usage(Code details) is as mentioned in the description of the issue.
Only APIs used are, 
-> excelize.OpenFile()
 -> f.GetRows()

One point to note is that, rows([][]string) returned by GetRows are sometimes not fully iterated through.
Hope that doesn't make any difference.

Please help us on how to avoid these temp files from flooding the system.

**Comment by xuri** [comment]
Hi @sandeepatil1288, could you provide your input file attachment without confidential info?

**Comment by sandeepatil1288** [comment]
Hi @xuri, 
I am attaching the input file samples, on reading which we are seeing the issue.
[ExcelizeInputFileSamples.zip](https://github.com/qax-os/excelize/files/7607010/ExcelizeInputFileSamples.zip)

**Comment by xuri** [comment]
Thanks for your feedback, I haved tested each spreadsheet in your attachment, and it works well, could you show us a complete, standalone example program or reproducible demo? and please try to upgrade to the master branch code, and call Close for each opened spreadsheet.

**Comment by xuri** [comment]
It seems still not have enough info of code and attachments to reproduce this issue, so I'll close this issue, if you have any questions, please let me know.
