### ISSUE TITLE
excel time format error

### ISSUE THREAD

**Issue by tickscn** [qax-os/excelize#1073]
**Description**
GetCellValue return time is not equal to the excel file input
![image](https://user-images.githubusercontent.com/28886445/143391711-86b8e37d-65b9-46f0-a3c6-bd213ae5bcb0.png)
![image](https://user-images.githubusercontent.com/28886445/143391767-eff8c03e-2415-40c4-9a96-d896b77b5076.png)

```go
package main

import (
	"fmt"

	"github.com/xuri/excelize/v2"
)

func main() {
	f, err := excelize.OpenFile("test.xlsx")
	if err != nil {
		fmt.Println(err)
		return
	}

	cell, err := f.GetCellValue("Sheet1", "A1")
	if err != nil {
		fmt.Println(err)
		return
	}
	fmt.Println(cell)
}

```

[test.xlsx](https://github.com/qax-os/excelize/files/7600734/test.xlsx)

**Describe the results you received:**
2021-01-21 08:30
**Describe the results you expected:**
2021-01-21 08:31
**Output of `go version`:**
go version go1.17.2 darwin/amd64 && go version go1.16.5 linux/amd64
```text
go version go1.17.2 darwin/amd64 
go version go1.16.5 linux/amd64
```

**Excelize version or commit ID:**

```text
v2.4.1
```

**Environment details (OS, Microsoft Excel™ version, physical, etc.):**

**Comment by xuri** [comment]
This issue is duplicated with #764, #1030, and #1070, please give a try the master branch code, this issue has been re-fixed by commit [`58fd279`](https://github.com/xuri/excelize/commit/58fd279dc845ebd9ccd4ba336d7c664824e70e43), and will be released in the next version.
