### ISSUE TITLE
Is module path changing?

### ISSUE THREAD

**Issue by dolmen** [qax-os/excelize#1079]
**Description**

The repository is now at https://github.com/qax-os/excelize/
But `go.mod` still says: `github.com/xuri/excelize/v2`

What is happening?

**Comment by dolmen** [comment]
The import/module path not matching the repository URL is still confusing.

**Comment by dolmen** [comment]
@xuri You should have switched to `v3` because in practice a module path change is like a change of major version for end users. Every body has to change go.mod/go.sum and all imports in Go files.

**Comment by xuri** [comment]
Thanks for your advice, but this module path change has been take effect since already released verion `2.4.1`, so I hope to using the `2.5.0` for next version, and I'd like to follwing the semantic version practice in the future versions release.
