### ISSUE TITLE
When i use latest version of v2.4.1.  There is no  function of GetCellType?

### ISSUE THREAD

**Issue by zhaoxun-github** [qax-os/excelize#1085]
it tell me   no such of  function ,   how can i use the  function?

**Comment by zhaoxun-github** [comment]
@xuri  excuse me,  can  you  give me a hand?

**Comment by xuri** [comment]
Thanks for your issue, this feature will be released in the [next version 2.5.0](https://xuri.me/excelize/en/releases/v2.5.0.html).

**Comment by zhaoxun-github** [comment]
> Thanks for your issue, this feature will be released in the [next version 2.5.0](https://xuri.me/excelize/en/releases/v2.5.0.html).

got it , any way , thanks
