### ISSUE TITLE
Whether this type of chart is supported

### ISSUE THREAD

**Issue by 17660472762** [qax-os/excelize#1086]
![image](https://user-images.githubusercontent.com/38678761/145169062-3800d8a8-d564-4918-aed5-6a216a6cda8e.png)
是否支持此种格式的图表？

**Comment by xuri** [comment]
Thanks for your issue. You can create a combo chart by [`AddChart`](https://xuri.me/excelize/zh-hans/chart.html#AddChart), but not support double Y axis currently, also ref #518.

**Comment by 17660472762** [comment]
Thank you～
