### ISSUE TITLE
Text isn't set to bold

### ISSUE THREAD

**Issue by laker31** [qax-os/excelize#1087]
I saw that this was previously reported in issue #1059, but I just downloaded the latest version of excelize today and it still doesn't work.

I set the font to green and bold with this:

```
            Font: &excelize.Font{
                Bold: true,
                Color: "00FFAA",
            },
```

When I apply the style to the cells, the text is set to green but it is not bold. Am I doing something wrong?

**Comment by xuri** [comment]
Thanks for your feedback, did you try with master branch code? I have tested and it works well with Apple Numbers 11.2 (7032.0.145), could you show us a complete, standalone example program or reproducible demo?

**Comment by laker31** [comment]
Thanks for replying @xuri. I apologize, but could you explain, how can I make sure I am using the master branch code?

**Comment by xuri** [comment]
Upgrade to master branch code by: 

```
go get -u github/xuri/excelize/v2@master
```

**Comment by laker31** [comment]
After doing this:

`go get -u github.com/xuri/excelize/v2@master`

and using this code:

`package main

import (
    "github.com/xuri/excelize/v2"
)

func main() {
    f := excelize.NewFile()

    f.SetCellValue("Sheet1", "A1", "Column A")
    f.SetCellValue("Sheet1", "B1", "Column B")
    f.SetCellValue("Sheet1", "C1", "Column C")
    f.SetColWidth("Sheet1", "A", "C", 15)
    f.SetRowHeight("Sheet1", 1, 40)

    styleHeaders, _ := f.NewStyle(`{ "border": [ { "type": "left", "color": "000000", "style": 1 }, { "type": "right", "color": "000000", "style": 1 }, { "type": "top", "color": "000000", "style": 1 }, { "type": "bottom", "color": "000000", "style": 1 } ], "fill": { "type": "pattern", "pattern": 1, "color": ["#D3D3D3"] }, "font": { "bold": true, "color": "000000" }, "alignment": { "horizontal": "center", "vertical": "center", "wrap_text": true } }`)
    styleContentCells, _ := f.NewStyle(`{ "border": [ { "type": "left", "color": "000000", "style": 1 }, { "type": "right", "color": "000000", "style": 1 }, { "type": "top", "color": "000000", "style": 1 }, { "type": "bottom", "color": "000000", "style": 1 } ], "alignment": { "horizontal": "center", "vertical": "center", "wrap_text": true } }`)

    f.SetCellStyle("Sheet1", "A1", "C1", styleHeaders)
    f.SetCellStyle("Sheet1", "A2", "C31", styleContentCells)

    f.SaveAs("Test.xlsx")

}`

the text in the header cells still isn't set to bold. Every other style setting works (for example, setting the border to be black and thick, setting the header fill colour to be grey, etc.).

**Comment by laker31** [comment]
After doing this:

`go get -u github.com/xuri/excelize/v2@master`

and using this code:

```
package main

import (
    "github.com/xuri/excelize/v2"
)

func main() {
    f := excelize.NewFile()

    f.SetCellValue("Sheet1", "A1", "Column A")
    f.SetCellValue("Sheet1", "B1", "Column B")
    f.SetCellValue("Sheet1", "C1", "Column C")
    f.SetColWidth("Sheet1", "A", "C", 15)
    f.SetRowHeight("Sheet1", 1, 40)

    styleHeaders, _ := f.NewStyle(`{ "border": [ { "type": "left", "color": "000000", "style": 1 }, { "type": "right", "color": "000000", "style": 1 }, { "type": "top", "color": "000000", "style": 1 }, { "type": "bottom", "color": "000000", "style": 1 } ], "fill": { "type": "pattern", "pattern": 1, "color": ["#D3D3D3"] }, "font": { "bold": true, "color": "000000" }, "alignment": { "horizontal": "center", "vertical": "center", "wrap_text": true } }`)
    styleContentCells, _ := f.NewStyle(`{ "border": [ { "type": "left", "color": "000000", "style": 1 }, { "type": "right", "color": "000000", "style": 1 }, { "type": "top", "color": "000000", "style": 1 }, { "type": "bottom", "color": "000000", "style": 1 } ], "alignment": { "horizontal": "center", "vertical": "center", "wrap_text": true } }`)

    f.SetCellStyle("Sheet1", "A1", "C1", styleHeaders)
    f.SetCellStyle("Sheet1", "A2", "C31", styleContentCells)

    f.SaveAs("Test.xlsx")

}
```

the text in the header cells still isn't set to bold. Every other style setting works (for example, setting the border to be black and thick, setting the header fill colour to be grey, etc.).

**Comment by xuri** [comment]
Which version of Apple Numbers are you using? Could you try to upgrade to the lasted version?

**Comment by laker31** [comment]
I did upgrade to the latest version but it still doesn't work.

Does using the following command ensure I will use master branch code?

`go get -u github.com/xuri/excelize/v2@master`

**Comment by laker31** [comment]
I managed to use the version on master of the package (and the headers are now in bold) by adding the following line to my go.mod, then running **go mod tidy**.

`replace github.com/xuri/excelize/v2 => github.com/xuri/excelize/v2 master`
