### ISSUE TITLE
excelize v2 no file close method

### ISSUE THREAD

**Issue by spawn6123** [qax-os/excelize#1091]
**Description**
I am using "github.com/xuri/excelize" , Have f.Colse() this method，But after I use the go module, there is a problem with this f.Colse() this method.
 

**Steps to reproduce the issue:**
1. import "github.com/xuri/excelize/v2"
2. f, err := excelize.OpenFile("template.xlsx")
3.if err := f.Close(); <== undefined 

**Describe the results you received:**
f.Close undefined (type *excelize.File has no field or method Close)compilerMissingFieldOrMethod
**Describe the results you expected:**
Can join this method ?
**Output of `go version`:**

```text
go version go1.17.3 windows/amd64
```

**Excelize version or commit ID:**

```text
v2.4.1
```

**Environment details (OS, Microsoft Excel™ version, physical, etc.):**
win10
Microsoft Excel 2016

**Comment by xuri** [comment]
Thanks for your issue, this issue duplicate with #1025 and #1042, the `Close` method will be released in the next version: [v2.5.0](https://xuri.me/excelize/en/releases/v2.5.0.html).

**Comment by spawn6123** [comment]
Sorry, I didn't notice the duplicate report
thanks
