### ISSUE TITLE
Change generated document application name

### ISSUE THREAD

**Issue by lafriks** [qax-os/excelize#1095]
Currently it's constant `Go Excelize` with no way to change it.
https://github.com/qax-os/excelize/blob/471f4f8d2ba13a7ee50039aef0bc3df16c329818/templates.go#L26

**Comment by xuri** [comment]
Thanks for your issue. I have added two APIs: `SetAppProps` and `GetAppProps` to support set and get document application properties, please upgrade to the master branch code, and this feature will released in the next version.

**Comment by lafriks** [comment]
Thanks for prompt response, great library 👍
