### ISSUE TITLE
XLOOKUP functions

### ISSUE THREAD

**Issue by undee** [qax-os/excelize#1097]
Can Versin 2.5.0 prioritize the implementation of XLOOKUP functions? Because this is a very general function. Thank you evry much!

**Comment by xuri** [comment]
Thanks for your issue, I'll implement it prioritize, the XLOOKUP is a little bit complex, I need to support reverse search, match mode, search mode, and so on, it also needs a lot of testing cases, so this function maybe won't appear in the next version.

**Comment by undee** [comment]
Thank you! 
Hard work! 
This function is more complex and combines many functions.

**Comment by xuri** [comment]
I have just initialized the `XLOOKUP` function, and it still a lot of work for this, include some known issue for calculation result when specified `match_mode` and `search_mode`.
