### ISSUE TITLE
How to add image with url without store in file?

### ISSUE THREAD

**Issue by IAkumaI** [qax-os/excelize#1098]
Is there any way to add image to sheet which not stored in xlsx file, but just contains url to an image. Excel will load and show this images.

For example, Google Sheets has IMAGE() function:
=IMAGE("https://miro.medium.com/max/1400/1*mk1-6aYaf_Bes1E3Imhc0A.jpeg")

May be, there are something similar in excelize?

I have thousands images. But this is too long to download and inline them all. Better just add images urls to excel.

**Comment by xuri** [comment]
Thanks for your issue, you can set any cell formula with `SetCellFormula` by excelize, but currently the formula function IMAGE maybe unavailable in Microsoft Excel, Apple Numbers, OpenOffice, LibreOffice and another spreadsheet application.

**Comment by IAkumaI** [comment]
Thanks
