### ISSUE TITLE
Please set the maximum number of rows

### ISSUE THREAD

**Issue by songning4** [qax-os/excelize#1099]
I use Excelize to generate xlsx files, but it stops running at line 886. How should I set it?(my data is about 6000+ lines)

total length: 4829

<img width="881" alt="iShot2021-12-22 16 14 37" src="https://user-images.githubusercontent.com/65797035/147058874-4f16209c-8368-4694-9758-bc349fbb4c0e.png">

**Comment by xuri** [comment]
Can you show us a complete, standalone example program or reproducible demo? And provide your input file, or at least tell us about it?

**Comment by songning4** [comment]
> 

Thank you very much for your reply. The error occurred in my code logic and has been solved. Thank you again
