### ISSUE TITLE
How to set file encoding

### ISSUE THREAD

**Issue by 18211167516** [qax-os/excelize#1102]
**Description**

**Steps to reproduce the issue:**
1.
2.
3.

**Describe the results you received:**

**Describe the results you expected:**

**Output of `go version`:**

```text
(paste your output here)
```

**Excelize version or commit ID:**

```text
(paste here)
```

**Environment details (OS, Microsoft Excel™ version, physical, etc.):**

**Comment by xuri** [comment]
Thanks for your issue, this library support specified codepage transcoder function via [`CharsetTranscoder`](https://pkg.go.dev/github.com/xuri/excelize/v2#File.CharsetTranscoder) for opening the spreadsheet from non-UTF-8 encoding but doesn't support generating non-UTF encoding spreadsheets.
