### ISSUE TITLE
数据量很大超过20万行的时候，写入表格速度很慢，有什么方法能优化吗？

### ISSUE THREAD

**Issue by boteman0206** [qax-os/excelize#1106]
目前使用的方式大概都是这种，循环写入的方式
for i := 0; i < len(header); i++ {
		f.SetCellValue("Sheet1", string(65+i)+"1", header[i])
}

**Comment by xuri** [comment]
This issue is duplcate with #364 and #382, please using [stream writer](https://pkg.go.dev/github.com/xuri/excelize/v2#File.NewStreamWriter) for generating a new worksheet with huge amounts of data.

**Comment by xuri** [comment]
This issue is duplicate with #364 and #382, please using [stream writer](https://pkg.go.dev/github.com/xuri/excelize/v2#File.NewStreamWriter) for generating a new worksheet with huge amounts of data.

**Comment by boteman0206** [comment]
感谢大佬
