### ISSUE TITLE
Excel time always output in float format using StreamWriter

### ISSUE THREAD

**Issue by KuanYuLai** [qax-os/excelize#1107]
**Description**

I try to output excel time from time.Time variable using streamWriter, however, it seems like the value will always be in float format.

**Steps to reproduce the issue:**
1. Create variable in time.Time type
2. Write to excel using stream writer

**Describe the results you received:**
float format: 44090.5179861111

**Describe the results you expected:**
excel time format: 2021/12/29 19:26

**Output of `go version`:**

```text
go version go1.17.5 darwin/arm64
```

**Excelize version or commit ID:**

```text
excelize/v2 v2.4.2
```

**Environment details (OS, Microsoft Excel™ version, physical, etc.):**
OS: Mac with M1 chip
Microsoft Excel: Mac Version 16.12 (180410)

**Comment by xuri** [comment]
Thanks for your feedback, please create a style with number format, and bind style ID for the cell in streaming writing.

**Comment by KuanYuLai** [comment]
ok! Thanks for the solution, may I know the reason why stream writer won't convert Time variable to excel time automatically?

**Comment by xuri** [comment]
Thanks for your issue, I've to make stream writer auto-create a time number format for time type cells, and this feature will be released in the next version.
