### ISSUE TITLE
Set cell value by column

### ISSUE THREAD

**Issue by Googuai** [qax-os/excelize#1109]
就类似按行赋值那样整一个 SetSheetColumn 咯

**Comment by xuri** [comment]
Thanks for your issue. The cell data was stored row by row in the spreadsheet document, so setting cells by rows is the typical scenario, and it's better for performance, there is no plan to support set cell by column recently, the developer can implement it by existing set cell value APIs.

**Comment by xuri** [comment]
Issue #1247 was similar to this, 8 months later, I merged a pull request which implement this feature, please upgrade to the master branch code, and this feature will be released in the next version.
