### ISSUE TITLE
can not read  real  float value  with precision format mode

### ISSUE THREAD

**Issue by dw130** [qax-os/excelize#1110]
write a float value in precision format mode

![image](https://user-images.githubusercontent.com/43978442/147819366-76e68132-4ab8-4fd2-a9fb-8c5890f95f2b.png)

read value is 1.32

not 1.32342

**Comment by dw130** [comment]
@xuri

**Comment by xuri** [comment]
Thanks for your issue, this duplicate with #991, the value of the cell should be the same as in the Excel formula bar, and as the [documents say](https://pkg.go.dev/github.com/xuri/excelize/v2#File.GetCellValue): If it is possible to apply a format to the cell value, it will do so, if not then an error will be returned, along with the raw value of the cell.

**Comment by dw130** [comment]
It works on version 25, thanks
