### ISSUE TITLE
streamwriter 流式写入,怎么实现一个cell中的文字有不同的font 或者mergeCell 这个方法扩展的cell 不会overlap ?

### ISSUE THREAD

**Issue by tiancai110a** [qax-os/excelize#1111]
**Description**

**Steps to reproduce the issue:**
1.
```
for i, s := range ss {
		styleID, err := file.NewStyle(&excelize.Style{
			Font: s.Font,
		})
		if err != nil {
			return nil, err
		}
		commentFields [i] = excelize.Cell{StyleID: styleID, Value: s.Text}
	}
```
2. 
```
streamWriter.MergeCell("A1", "E1")
```
3.
```
streamWriter.SetRow("A1", commentFields, excelize.RowOpts{Height: sheet.RowConfigs.ColHeight, StyleID: fillStyleID})
```
4. 或者像 setrow的时候能直接像file.SetCellRichText 这个接口一样直接解析richtext的数组设置到一个cell中也是可以的

**Describe the results you received:**

**Describe the results you expected:**

**Output of `go version`:**

```text
(paste your output here)
```

**Excelize version or commit ID:**

```text
(paste here)
```

**Environment details (OS, Microsoft Excel™ version, physical, etc.):**

**Comment by xuri** [comment]
Sorry, I don't understand exactly what you mean, but note that merging cells only keeps the upper-left cell value and style.

**Comment by tiancai110a** [comment]
> Sorry, I don't understand exactly what you mean, but note that merging cells only keeps the upper-left cell value and style.
sorry i thought you know chinese
i want  multy font in one cell ,like SetCellRichText , but with streamwriter

**Comment by xuri** [comment]
The library doesn't support set cell rich-text in streaming writing mode currently.

**Comment by tiancai110a** [comment]
thks
