### ISSUE TITLE
value from datetime format cell is wrong 

### ISSUE THREAD

**Issue by dw130** [qax-os/excelize#1112]
![image](https://user-images.githubusercontent.com/43978442/148024952-55d7806a-1a9b-4f98-aff3-c2966ce08bff.png)
![image](https://user-images.githubusercontent.com/43978442/148024966-8bcd4fd8-90db-44f9-b381-a41e71a0f719.png)

use GetRows function
read value is  44087

golang 16
excelize version: v2.5.0

**Comment by dw130** [comment]
@xuri

**Comment by xuri** [comment]
Thanks for your feedback, this issue is similar to #1093, the library support parsing build-in date and time number format under English (United States) currently, and I'll consider implementing number format lexer and parser to support multi-language location and custom number format.

**Comment by eqinox76** [comment]
In the meantime i think you have to convert the date via `excelize.ExcelDateToTime` as 44087 is a correct excel date see [here](https://stackoverflow.com/questions/981655/how-to-represent-a-datetime-in-excel).

**Comment by dw130** [comment]
@xuri Is there any way to fetch the raw  value current now ？
I use the GetCellType function, return value is  CellTypeUnset CellType
If the GetCellType  returns right value (CellTypeDate), I can use excelize.ExcelDateToTime function
But GetCellType  seems not work

**Comment by xuri** [comment]
Hi @dw130, please specify [`RawCellValue`](https://pkg.go.dev/github.com/xuri/excelize/v2#Options) field as `true` in the options of the `GetCellValue`, `GetRows` or rows/columns iterator, and reference details about the result of `GetCellType` in [this comment](./1041#issuecomment-950164580) of the issue.

**Comment by xuri** [comment]
Hi @dw130, @eqinox76, the excelize library improvements for reading cell value with number format in the recently released version. Please upgrade to the lasted version or use the master branch code. The date time cell result can be read correctly. I closed this issue. If you have any questions, please let me know, and you can reopen this anytime.
