### ISSUE TITLE
Scale a worksheet - automatic become 1

### ISSUE THREAD

**Issue by ipopa** [qax-os/excelize#1117]
**Description**

I have an excel with Scale Height - Automatic. When I'm using GetMergeCells or something else that it's using `f.workSheetReader(sheet)`, it breaks, Automatic become 1.

**Steps to reproduce the issue:**
```
package main

import (
        "fmt"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/xuri/excelize/v2"
)

func TestLocalFile(t *testing.T) {
	xlsx, err := excelize.OpenFile("./test.xlsx")

	assert.Nil(t, err)

	mergedCells, err := xlsx.GetMergeCells("Sheet1")

	assert.Nil(t, err)

	fmt.Println(mergedCells)

	filenameXLSX := "./test_output.xlsx"

	xlsx.SaveAs(filenameXLSX)
}

```
<img width="974" alt="test" src="https://user-images.githubusercontent.com/14199839/148748585-ed65a8bf-8bcd-4bad-911d-3eee690f8c5d.png">

excel:
[test.xlsx](https://github.com/qax-os/excelize/files/7838042/test.xlsx)

**Describe the results you received:**
`go test`

<img width="974" alt="test_output" src="https://user-images.githubusercontent.com/14199839/148748551-af6e892a-3803-4191-af73-fb247d83a917.png">

excel:
[test_output.xlsx](https://github.com/qax-os/excelize/files/7838043/test_output.xlsx)

**Describe the results you expected:**
It must remain Automatic

**Output of `go version`:**

```text
1.16
```

**Excelize version or commit ID:**

```text
2245fccca0beb25a1bf309a1c9cbd273512f125a
```

**Environment details (OS, Microsoft Excel™ version, physical, etc.):**
OS: macOS Big Sur 11.5.2
Microsoft Excel™ version: Microsoft Excel for Mac 16.52

**Comment by xuri** [comment]
Thanks for your issue. I have fixed it, please try upgrading to the master branch code, and this patch will be released in the next version.

**Comment by ipopa** [comment]
thank you
