### ISSUE TITLE
Can not Load </b> from xl/styles.xml

### ISSUE THREAD

**Issue by hans-cn** [qax-os/excelize#1119]
styles.xml source data:
    
![image](https://user-images.githubusercontent.com/19524400/149309004-07409529-69db-4c05-98da-ae54271796ac.png)

When open a existing file && save, data will be:
        
![image](https://user-images.githubusercontent.com/19524400/149309055-00500019-974a-4c53-833f-70db6f7a0917.png)

Then, the cell will be lost "B" style.  I think the following fields have the same problem：

type xlsxFont struct {
	B        *attrValBool   `xml:"b,omitempty"`
	I        *attrValBool   `xml:"i,omitempty"`
	Strike   *attrValBool   `xml:"strike,omitempty"`
	Outline  *attrValBool   `xml:"outline,omitempty"`
	Shadow   *attrValBool   `xml:"shadow,omitempty"`
	Condense *attrValBool   `xml:"condense,omitempty"`
	Extend   *attrValBool   `xml:"extend,omitempty"`
...

**Comment by xuri** [comment]
Thanks for your issue. I have fixed it, please try upgrading to the master branch code, and this patch will be released in the next version.
