### ISSUE TITLE
Autofilter doesn't work on LibreOffice if the sheet name has spaces

### ISSUE THREAD

**Issue by harrison3000** [qax-os/excelize#1122]
**Description**

When using LibreOffice, the autofilter only works if the sheet name doesn't have spaces
It works fine on Google Sheets, I didn't test on MS Office

**Steps to reproduce the issue:**

1. Code: 
``` Go

package main

import "github.com/xuri/excelize/v2"

func main() {
	f := excelize.NewFile()

	fill := func(s string) {
		f.SetCellStr(s, "A1", "hi")
		f.SetCellStr(s, "A2", "2")
		f.SetCellStr(s, "A3", "3")

		f.AutoFilter(s, "A1", "A3", "")
	}

	f.SetSheetName("Sheet1", "works")
	fill("works")

	f.NewSheet("Doesnt work")
	fill("Doesnt work")

	f.SaveAs("testoutput.xlsx")
}
```

**Output of `go version`:**

```text
go version go1.17.6 linux/amd64
```

**Excelize version or commit ID:**

```text
v2.5.0
```

**Environment details (OS, Microsoft Excel™ version, physical, etc.):**
LibreOffice 7.2.5
ArchLinux, up to date

**Comment by xuri** [comment]
Thanks for your issue. I have fixed it, please try upgrading to the master branch code, and this patch will be released in the next version.
