### ISSUE TITLE
How to read date from excel sheet

### ISSUE THREAD

**Issue by ifat420** [qax-os/excelize#1126]
In the Excel file there is a cell:
E7 => 3/14/2000

I'm trying to get it... 
```
cell, err := f.GetCellValue("Sheet1", "E7")
    if err != nil {
        fmt.Println(err)
        return
    }
println(cell)
```
Output: 03-14-00

output as sting format. 
How can I convert it into go time.Time format 
Thanks

**Comment by xuri** [comment]
Thanks for your issue, you can read raw cell values and convert them to `time.Time` by [`ExcelDateToTime`](https://pkg.go.dev/github.com/xuri/excelize/v2#ExcelDateToTime) like this:

```go
cell, err := f.GetCellValue("Sheet1", "E7", excelize.Options{RawCellValue: true})
if err != nil {
    fmt.Println(err)
    return
}
excelDate, err := strconv.ParseFloat(cell, 64)
if err != nil {
    fmt.Println(err)
    return
}
excelTime, err := excelize.ExcelDateToTime(excelDate, false)
if err != nil {
    fmt.Println(err)
    return
}
fmt.Println(excelTime)
```

**Comment by ifat420** [comment]
> Thanks for your issue, you can read raw cell values and convert them to `time.Time` by [`ExcelDateToTime`](https://pkg.go.dev/github.com/xuri/excelize/v2#ExcelDateToTime) like this:
> 
> ```go
> cell, err := f.GetCellValue("Sheet1", "E7", excelize.Options{RawCellValue: true})
> if err != nil {
>     fmt.Println(err)
>     return
> }
> excelDate, err := strconv.ParseFloat(cell, 64)
> if err != nil {
>     fmt.Println(err)
>     return
> }
> excelTime, err := excelize.ExcelDateToTime(excelDate, false)
> if err != nil {
>     fmt.Println(err)
>     return
> }
> fmt.Println(excelTime)
> ```

Thanks dude

**Comment by SmartZou** [comment]
When I use `f.GetRows` mode to read data, the above reference code output is a fixed value. The code is as follows
`rows, _ := f.GetRows(config.BasicInformationSheetName)`

![image](https://user-images.githubusercontent.com/36814127/159629269-a6ec2482-0068-48e2-b3a3-6d02fdabdbc1.png)

**Comment by xuri** [comment]
Hi @SmartZou, which version of the library you're using? Please give a try with the master branch code, and if it still not work please provide your input file attachment without confidential info if you can.
