### ISSUE TITLE
Question: Custom Data Validation

### ISSUE THREAD

**Issue by rizaldirnm** [qax-os/excelize#1128]
Hello guys, thank you for this library helping me so much.

I have question about Custom Data Validation like this image.

<img width="825" alt="Screen Shot 2022-01-24 at 20 51 23" src="https://user-images.githubusercontent.com/26857590/150795054-c17dfca9-a0a9-4b3b-9d2f-8a636a40a976.png">

is it support yet? I saw `DataValidationTypeCustom` type in `datavalidation.go` but I don't know how to use it because I cant find Docs in `https://xuri.me/excelize/en/data.html#AddDataValidation`.

Thank you in advance!

**Comment by xuri** [comment]
Thanks for your issue, I'll add support for this feature later.

**Comment by xuri** [comment]
Thanks for your issue, you can create custom data validation like this:

```go
f := excelize.NewFile()
dvRange := excelize.NewDataValidation(true)
dvRange.ShowErrorMessage = true
dvRange.ShowInputMessage = true
dvRange.Sqref = "A1:A301"
if err := dvRange.SetRange("COUNTIF($A$1:$A$301,A1)=1", "", excelize.DataValidationTypeCustom, excelize.DataValidationOperatorEqual); err != nil {
	fmt.Println(err)
}
if err := f.AddDataValidation("Sheet1", dvRange); err != nil {
	fmt.Println(err)
}
if err := f.SaveAs("Book1.xlsx"); err != nil {
	fmt.Println(err)
}
```
