### ISSUE TITLE
help wanted| 修改单元格内的数据格式 转为数字

### ISSUE THREAD

**Issue by EsqerYasen** [qax-os/excelize#1131]
数据写入以后怎么修改单元格里面的数据格式到数字

<img width="401" alt="Screen Shot 2022-01-26 at 2 28 59 PM" src="https://user-images.githubusercontent.com/36286533/151115708-e111abad-5707-4214-af77-237c081627d0.png">

**Comment by EsqerYasen** [comment]
先不折腾这个 ， 先用go处理数据格式再写入了

**Comment by EsqerYasen** [comment]
close

**Comment by xuri** [comment]
This issue similar with #1132, the `SetlCellValue` function can accept multiple cell value data types, please convert the value to float or integer data type before setting the cell value.
