### ISSUE TITLE
Is it possible to define the data type of a column?

### ISSUE THREAD

**Issue by eduardo-mior** [qax-os/excelize#1132]
Is it possible to define the data type of a column?

----------------------------------------------------------------------

I'm currently creating an excel spreadsheet and setting the data through the `setCellValue` and `setCellStr` functions, but when I open the file in Excel a warning keeps popping up.

_"Number stored as text"_

Is there any way to solve this problem without having to convert this string to `int` and using `setCellInt`? Is there any way to indicate to Excel that my data is a string?

**Comment by xuri** [comment]
The `SetlCellValue` function can accept multiple cell value data types, please convert the value to float or integer data type before setting the cell value.

**Comment by eduardo-mior** [comment]
@xuri 
Thank you very much.

I'm formatting them in string and I was inserting them in excel. Now I'm inserting as float64 and formatting with excel masks.

Maybe this tip could be somewhere in the documentation? Maybe other people also have this doubt.

It is very common for people to format numbers and then want to do calculations using formulas. To make this work, the data must be inserted as float64 and the excel mask must be used to format.

**Comment by xuri** [comment]
Hi @eduardo-mior, using the numeric data type value when setting the cell value by SetCellValue, the written cell's value would support working with formula reference and calculation. I think this requires no additional explanation. Set the number format (as your say masks) for cells is optional, it just formats the number.
