### ISSUE TITLE
Get Wrong Value From rows.Columns()

### ISSUE THREAD

**Issue by AngangGuo** [qax-os/excelize#1137]
**Description**

The values get from `rows.Columns()` deoesn't match the row `rows.CurrentRow()`

Here is a simple version(no error for simplicity)

```go
func main() {
	f, _ := excelize.OpenFile("Book1.xlsx")
	defer f.Close()

	rows, _ := f.Rows("Sheet1")
	defer rows.Close()

	for rows.Next() {
		n := rows.CurrentRow()

		// col, _ := rows.Columns() // AA
		switch n {
		case 1:
			col, _ := rows.Columns() // BB
			fmt.Println(n, col[:])
		case 5, 6:
			col, _ := rows.Columns() // BB
			fmt.Println(n, col[0])
		default:
			// skip
		}
	}
}
```

**Excel File**
Line 1/Col 1 | Col 2 | Col 3 | Col 4
---|---|---|---
Line 2 |  |  |
Line 3 |  |  |
Line 4 |  |  |
Line 5 |  |  |
Line 6 |  |  |
Line 7 |  |  |
Line 8 |  |  |

**Describe the results you received:**
```text
1 [Line 1 / Col1 Col 2 Col 3 Col 4]
5 Line 2
6 Line 4
```
**Describe the results you expected:**
```text
1 [Line 1 / Col1 Col 2 Col 3 Col 4]
5 Line 5
6 Line 6
```

**Excelize version or commit ID:**

```text
github.com/xuri/excelize/v2 v2.5.0
```

Note: If I comment out the two BB lines and uncomment the AA line, everything works.

Do we **must** call `rows.Columns()` every time or it's a bug?

**Comment by xuri** [comment]
Thanks for your feedback, this issue is similar to #644. The Next function still won't skip the rows in version 2.5.0. I have to reconsider this design and make a change on commit [`4daa6ed`](https://github.com/xuri/excelize/commit/4daa6ed0b46fdd994e46403feb049b162eca19b8), this change will be released in the next version, please try to upgrade to the master version if you can.

**Comment by AngangGuo** [comment]
I updated to the latest version and it works find. 

The only problem is that the `rows.CurrentRow()` method is missing. Please verify.

```
go get -u github.com/xuri/excelize/v2@862dc9dc1324e11a517b03267d07dd95051d5e6e
```

**Comment by AngangGuo** [comment]
I found the reason why the `CurrentRow()` is removed from https://github.com/qax-os/excelize/pull/1054
