### ISSUE TITLE
When Edit excel file，show warning "发现“22.xlsx”中的部分内容有问题。是否让我们尽量尝试恢复? 如果您信任此工作簿的源，请单击“是”。"

### ISSUE THREAD

**Issue by songxk** [qax-os/excelize#1139]
**Description**
when edit the excel file with excelize , show the warning "发现“22.xlsx”中的部分内容有问题。是否让我们尽量尝试恢复? 如果您信任此工作簿的源，请单击“是"。"

**Steps to reproduce the issue:**
1. create a empty excel file,saved  as "22.xlsx"
2. use code edit it .

	f, _ := excelize.OpenFile("/Users/dev/Downloads/22.xlsx")
	f.SetActiveSheet(0)
	sheetName := f.GetSheetName(0)
	fmt.Println(sheetName)
	er := f.SetCellDefault(sheetName, "C4", "test")
	fmt.Println(er)
	f.Save()

3. open the 22.xlsx file

**Describe the results you received:**

**Describe the results you expected:**

**Output of `go version`:**

```text
go version go1.16.4 darwin/amd64
```

**Excelize version or commit ID:**

```text
excelize 2.4.1
```

**Environment details (OS, Microsoft Excel™ version, physical, etc.):**
macOS Big Sur 11.4
Go 1.16.4
excelize 2.4.1
Excel 16.29（19090802）

**Comment by xuri** [comment]
Thanks for your issue. Could you provide your input file attachment without confidential info?

**Comment by songxk** [comment]
[](url
[22.xlsx](https://github.com/qax-os/excelize/files/8012814/22.xlsx)
)

**Comment by xuri** [comment]
Please using `SetCellValue` instead of `SetCellDefault` currently, I'll fix this issue later.

**Comment by songxk** [comment]
SetCellValue works, thanks

**Comment by xuri** [comment]
I have fixed it, please try upgrading to the master branch code, and this patch will be released in the next version.

**Comment by zohu** [comment]
> I have fixed it, please try upgrading to the master branch code, and this patch will be released in the next version.

`SetRow` has the same problem. excelize version is v2.6.0.

**Comment by xuri** [comment]
@zohu Thanks for your feedback. Can you show us a complete, standalone example program or reproducible demo? or give a try to upgrade to v2.6.1?

**Comment by zohu** [comment]
> @zohu Thanks for your feedback. Can you show us a complete, standalone example program or reproducible demo? or give a try to upgrade to v2.6.1?

it's fine after the upgrade. thank you.

**Comment by floki2020** [comment]
Hey,guys,I have the same problem.  I upgrade to v2.6.1! I use the StreamWrieter.Just Like 	
```
for rowID := 0; rowID < len(data); rowID++ {
		row := make([]interface{}, 4)
		row[0] = data[rowID].StockyardName
		row[1] = data[rowID].InNumber
		row[2] = data[rowID].OutNumber
		row[3] = utils.ConvertToShortString(data[rowID].CreateAt)
		//从第A3位置开始插入 起始为0  :rowID+3
		cell, _ := excelize.CoordinatesToCellName(1, rowID+3)
		if err := streamWriter.SetRow(cell, row); err != nil {
			return "", err
		}
	}
```

**Comment by zohu** [comment]
> Hey,guys,I have the same problem.It can open by WPS,but Office doen't work. I upgrade to v2.6.1! I use the **StreamWrieter** for set values .Just Like
> 
> ```
> for rowID := 0; rowID < len(data); rowID++ {
> 		row := make([]interface{}, 4)
> 		row[0] = data[rowID].StockyardName
> 		row[1] = data[rowID].InNumber
> 		row[2] = data[rowID].OutNumber
> 		row[3] = utils.ConvertToShortString(data[rowID].CreateAt)
> 		cell, _ := excelize.CoordinatesToCellName(1, rowID+3)
> 		if err := streamWriter.SetRow(cell, row); err != nil {
> 			return "", err
> 		}
> 	}
> ```
> 
> Go: 1.17 Excelize:v2.6.1 Microsoft Excel：16.0.156

Is it possible that you forgot to call streamWriter.Flush() ?

**Comment by floki2020** [comment]
> 

Thanks for your answer，and I Flush() it in the end  after method setRows.It works in WPS! DONT WORK IN MAC & PC MicroSoft Excel！
```go
	if err := streamWriter.Flush(); err != nil {
		fmt.Println(err)
		return "", err
	}
```

**Comment by xuri** [comment]
Hi @floki2020, thanks for your feedback. Can you show us a complete, standalone example program or reproducible demo?

**Comment by floki2020** [comment]
> Hi @floki2020, thanks for your feedback. Can you show us a complete, standalone example program or reproducible demo?

thanks for your answer,bleow is my test code.
```go
file := excelize.NewFile()
	streamWriter, err := file.NewStreamWriter("Sheet1")
	if err != nil {
		fmt.Println(err)
		return "", err
	}
	sHead, _ := file.NewStyle(&excelize.Style{Alignment: &excelize.Alignment{Horizontal: "Center"}, Font: &excelize.Font{Bold: true}})
	sRow, err := file.NewStyle(&excelize.Style{Alignment: &excelize.Alignment{Horizontal: "Center"}})
	if err != nil {
		fmt.Println(err)
		return "", err
	}
	sl := len(data) + 4

	rowTotal := "A" + cast.ToString(sl+1)

	numStr := cast.ToString(sl)


	subStart := "A" + numStr
	subEnd := "D" + numStr

	subHead := "A" + numStr

	err = streamWriter.MergeCell("A1", "D1")
	if err != nil {
		fmt.Print(err)
	}
	streamWriter.MergeCell(subStart, subEnd)

	streamWriter.SetColWidth(1, 4, 20)

	if err := streamWriter.SetRow("A1", []interface{}{
		excelize.Cell{StyleID: sHead, Value: dist}}); err != nil {

		return "", err
	}
	if err := streamWriter.SetRow(subHead, []interface{}{
		excelize.Cell{StyleID: sHead, Value: "综合统计"}}); err != nil {

		return "", err
	}
	if err := streamWriter.SetRow("A2", []interface{}{
		excelize.Cell{StyleID: sRow, Value: "所属矿场"}, excelize.Cell{StyleID: sRow, Value: "进口车次"}, excelize.Cell{StyleID: sRow, Value: "出口车次"}, excelize.Cell{StyleID: sRow, Value: "日期"}}); err != nil {

		return "", err
	}
	if err := streamWriter.SetRow(rowTotal, []interface{}{
		excelize.Cell{StyleID: sRow, Value: "所属"}, excelize.Cell{StyleID: sRow, Value: "进口车次"}, excelize.Cell{StyleID: sRow, Value: "出口车次"}, excelize.Cell{StyleID: sRow, Value: "日期"}}); err != nil {
		return "", err
	}

	for rowID := 0; rowID < len(data); rowID++ {
		row := make([]interface{}, 4)
		row[0] = data[rowID].StockyardName
		row[1] = data[rowID].InNumber
		row[2] = data[rowID].OutNumber
		row[3] = utils.ConvertToShortString(data[rowID].CreateAt)
		cell, _ := excelize.CoordinatesToCellName(1, rowID+3)
		if err := streamWriter.SetRow(cell, row); err != nil {
			fmt.Println(err)
			return "", err
		}
	}

	for i := 0; i < len(total); i++ {
		row := make([]interface{}, 4)
		row[0] = total[i].StockyardName
		row[1] = total[i].InNumber
		row[2] = total[i].OutNumber
		row[3] = utils.ConvertToShortString(total[i].CreateAt)
		cell, _ := excelize.CoordinatesToCellName(1, i+sl+2)
		if err := streamWriter.SetRow(cell, row); err != nil {
			fmt.Println(err)
			return "", err
		}
	}
	if hasChart {
		strIdx := cast.ToString(sl - 1)
		chart := fmt.Sprintf(`{
			"type": "col",
			"series": [
			{
					"name": "Sheet1!$B$2",
					"categories": "Sheet1!$A$3:$A$%s",
					"values": "Sheet1!$B$3:$B$%s"
			},
			{
					"name": "Sheet1!$C$2",
					"categories": "Sheet1!$A$3:$A$%s",
					"values": "Sheet1!$C$3:$C$%s"
			}],
			"format":
			{
					"x_scale": 1.0,
					"y_scale": 1.0,
					"x_offset": 15,
					"y_offset": 10,
					"print_obj": true,
					"lock_aspect_ratio": false,
					"locked": false
			},
			"legend":
			{
					"position": "left",
					"show_legend_key": false
			},
			"title":
			{
					"name": "矿场进出情况统计分析"
			},
			"plotarea":
			{
					"show_bubble_size": true,
					"show_cat_name": false,
					"show_leader_lines": false,
					"show_percent": true,
					"show_series_name": true,
					"show_val": true
			},
			"show_blanks_as": "zero"
	}`, strIdx, strIdx, strIdx, strIdx)

		if err := file.AddChart("Sheet1", "E1", chart); err != nil {
			fmt.Println(err)
		}
	}
	if err := streamWriter.Flush(); err != nil {
		fmt.Println(err)
		return "", err
	}

	file.NewSheet("Sheet2")
	truckStm, err := file.NewStreamWriter("Sheet2")
	if err != nil {
		fmt.Println(err)
		return "", err
	}
	truckStm.SetColWidth(1, 4, 20)
	if err := truckStm.SetRow("A1", []interface{}{
		excelize.Cell{StyleID: sRow, Value: "所属矿场"}, excelize.Cell{StyleID: sRow, Value: "车牌号"}, excelize.Cell{StyleID: sRow, Value: "位置"}, excelize.Cell{StyleID: sRow, Value: "日期"}}); err != nil {
		fmt.Println(err)
		return "", err
	}
	for idx := 0; idx < len(trucks); idx++ {
		row := make([]interface{}, 4)
		row[0] = trucks[idx].StockyardName
		row[1] = trucks[idx].PlateNumber
		status := trucks[idx].Status
		switch status {
		case 1:
			row[2] = "入口"
		case 2:
			row[2] = "出口"
		case 3:
			row[2] = "未知"
		}
		row[3] = utils.ConvertToStringAdd8(trucks[idx].CreateAt)
		cell, _ := excelize.CoordinatesToCellName(1, idx+2)
		if err := truckStm.SetRow(cell, row); err != nil {
			fmt.Println(err)
			return "", err
		}
	}
	if err := truckStm.Flush(); err != nil {
		fmt.Println(err)
		return "", err
	}
	path := "report/" + dist + ".xlsx"
	if err := file.SaveAs(path); err != nil {
		fmt.Println(err)
		return "", err
	}
	return path, nil
```

**Comment by xuri** [comment]
Could you provide a simple and executable reproducible code? There is no definition of the valid `data` and `utils`, please reduce the code scope and simplify the code first.

**Comment by floki2020** [comment]
> Could you provide a simple and executable reproducible code? There is no definition of the valid `data` and `utils`, please reduce the code scope and simplify the code first.

```go
func BuilderExcel() (string, error) {
	file := excelize.NewFile()
	streamWriter, err := file.NewStreamWriter("Sheet1")
	if err != nil {
		fmt.Println(err)
		return "", err
	}
	sHead, _ := file.NewStyle(&excelize.Style{Alignment: &excelize.Alignment{Horizontal: "Center"}, Font: &excelize.Font{Bold: true}})
	sRow, err := file.NewStyle(&excelize.Style{Alignment: &excelize.Alignment{Horizontal: "Center"}})
	if err != nil {
		fmt.Println(err)
		return "", err
	}

	rowTotal := "A9"

	numStr := "8"

	//副标题 Merge 起始未知
	subStart := "A" + numStr
	subEnd := "D" + numStr

	subHead := "A" + numStr

	err = streamWriter.MergeCell("A1", "D1")
	if err != nil {
		fmt.Print(err)
	}

	streamWriter.MergeCell(subStart, subEnd)

	streamWriter.SetColWidth(1, 4, 20)

	if err := streamWriter.SetRow("A1", []interface{}{
		excelize.Cell{StyleID: sHead, Value: "123"}}); err != nil {

		return "", err
	}
	if err := streamWriter.SetRow(subHead, []interface{}{
		excelize.Cell{StyleID: sHead, Value: "综合统计"}}); err != nil {

		return "", err
	}
	if err := streamWriter.SetRow("A2", []interface{}{
		excelize.Cell{StyleID: sRow, Value: "所属矿场"}, excelize.Cell{StyleID: sRow, Value: "进口车次"}, excelize.Cell{StyleID: sRow, Value: "出口车次"}, excelize.Cell{StyleID: sRow, Value: "日期"}}); err != nil {

		return "", err
	}
	if err := streamWriter.SetRow(rowTotal, []interface{}{
		excelize.Cell{StyleID: sRow, Value: "所属"}, excelize.Cell{StyleID: sRow, Value: "进口车次"}, excelize.Cell{StyleID: sRow, Value: "出口车次"}, excelize.Cell{StyleID: sRow, Value: "日期"}}); err != nil {
		return "", err
	}

	for rowID := 0; rowID < 4; rowID++ {
		row := make([]interface{}, 2)
		row[0] = rowID * 2
		row[1] = rowID + 1

		cell, _ := excelize.CoordinatesToCellName(1, rowID+3)
		if err := streamWriter.SetRow(cell, row); err != nil {
			fmt.Println(err)
			return "", err
		}
	}

	for i := 0; i < 6; i++ {
		row := make([]interface{}, 2)
		row[0] = i * 3
		row[1] = i + 1
		cell, _ := excelize.CoordinatesToCellName(1, i+6)
		if err := streamWriter.SetRow(cell, row); err != nil {
			fmt.Println(err)
			return "", err
		}
	}
	if err := streamWriter.Flush(); err != nil {
		fmt.Println(err)
		return "", err
	}

	file.NewSheet("Sheet2")
	truckStm, err := file.NewStreamWriter("Sheet2")
	if err != nil {
		fmt.Println(err)
		return "", err
	}
	truckStm.SetColWidth(1, 4, 20)
	if err := truckStm.SetRow("A1", []interface{}{
		excelize.Cell{StyleID: sRow, Value: "所属矿场"}, excelize.Cell{StyleID: sRow, Value: "车牌号"}, excelize.Cell{StyleID: sRow, Value: "位置"}, excelize.Cell{StyleID: sRow, Value: "日期"}}); err != nil {
		fmt.Println(err)
		return "", err
	}
	for idx := 0; idx < 5; idx++ {
		row := make([]interface{}, 2)
		row[0] = "123"
		row[1] = idx * 2
		cell, _ := excelize.CoordinatesToCellName(1, idx+2)
		if err := truckStm.SetRow(cell, row); err != nil {
			fmt.Println(err)
			return "", err
		}
	}
	if err := truckStm.Flush(); err != nil {
		fmt.Println(err)
		return "", err
	}
	path := "report/" + "test" + ".xlsx"
	if err := file.SaveAs(path); err != nil {
		fmt.Println(err)
		return "", err
	}
	return path, nil
}
```

**Comment by xuri** [comment]
As the documentation of the [`NewStreamWriter`](https://pkg.go.dev/github.com/xuri/excelize/v2#File.NewStreamWriter) function says: "ensure that the order of line numbers is ascending".

**Comment by floki2020** [comment]
> As the documentation of the [`NewStreamWriter`](https://pkg.go.dev/github.com/xuri/excelize/v2#File.NewStreamWriter) function says: "ensure that the order of row numbers is ascending".

My oder line number is ascending. I don't think it's wrong :).  Written according to the demo,i just use the funciton MergeCell

**Comment by xuri** [comment]
The order of row numbers is not ascending in your code. The variable `subHead` was `A8`, which is in row 8, so you need to set this row after the second row, for example, using: 

```go
if err := streamWriter.SetRow("A2", []interface{}{
    excelize.Cell{StyleID: sRow, Value: "所属矿场"}, excelize.Cell{StyleID: sRow, Value: "进口车次"}, excelize.Cell{StyleID: sRow, Value: "出口车次"}, excelize.Cell{StyleID: sRow, Value: "日期"}}); err != nil {
    return "", err
}
if err := streamWriter.SetRow(subHead, []interface{}{
    excelize.Cell{StyleID: sHead, Value: "综合统计"}}); err != nil {
    return "", err
}
```

instead of

```go
if err := streamWriter.SetRow(subHead, []interface{}{
    excelize.Cell{StyleID: sHead, Value: "综合统计"}}); err != nil {

    return "", err
}
if err := streamWriter.SetRow("A2", []interface{}{
    excelize.Cell{StyleID: sRow, Value: "所属矿场"}, excelize.Cell{StyleID: sRow, Value: "进口车次"}, excelize.Cell{StyleID: sRow, Value: "出口车次"}, excelize.Cell{StyleID: sRow, Value: "日期"}}); err != nil {

    return "", err
}
```

Please also check the row number in the for loop statements.

**Comment by floki2020** [comment]
I'm so sorry. I forget this scope.Maybe it can works~ Thanks again

**Comment by floki2020** [comment]
> The order of row numbers is not ascending in your code. The variable `subHead` was `A8`, which is in row 8, so you need to set this row after the second row, for example, using:
> 
> ```go
> if err := streamWriter.SetRow("A2", []interface{}{
>     excelize.Cell{StyleID: sRow, Value: "所属矿场"}, excelize.Cell{StyleID: sRow, Value: "进口车次"}, excelize.Cell{StyleID: sRow, Value: "出口车次"}, excelize.Cell{StyleID: sRow, Value: "日期"}}); err != nil {
>     return "", err
> }
> if err := streamWriter.SetRow(subHead, []interface{}{
>     excelize.Cell{StyleID: sHead, Value: "综合统计"}}); err != nil {
>     return "", err
> }
> ```
> 
> instead of
> 
> ```go
> if err := streamWriter.SetRow(subHead, []interface{}{
>     excelize.Cell{StyleID: sHead, Value: "综合统计"}}); err != nil {
> 
>     return "", err
> }
> if err := streamWriter.SetRow("A2", []interface{}{
>     excelize.Cell{StyleID: sRow, Value: "所属矿场"}, excelize.Cell{StyleID: sRow, Value: "进口车次"}, excelize.Cell{StyleID: sRow, Value: "出口车次"}, excelize.Cell{StyleID: sRow, Value: "日期"}}); err != nil {
> 
>     return "", err
> }
> ```
> 
> Please also check the row number in the for loop statements. I'll consider checking the row number in the stream writer and returning the error to avoid this issue.

I'm so sorry. I forget this scope.Maybe it can works~ Thanks again

**Comment by xuri** [comment]
I have added a check of the row number in the stream writer and returned the error: `row %d has already been written` to avoid row numbers is not ascending mistake. This feature will be released in the next version.
