### ISSUE TITLE
Set cell style

### ISSUE THREAD

**Issue by emaborsa** [qax-os/excelize#1140]
I just started to use this library, was trying to set a style to some cells. Do I really have to pass a JSON string to the NewStyle function and then just set the styleId?

Example:

```golang
styleId, err := xlsx.NewStyle(`{"font":{"color":"#FFFFFF"},"fill":{"type":"pattern","color":["#4F81BD"],"pattern":1}}`)
if err != nil {
  fmt.Println(err)
}
xlsx.SetCellStyle("ScheetName", "A1", "F1", styleId)
```

Is there a reason why a JSON string and not creating a Style and use it:

```golang
style := excelize.Style{
  Font: &excelize.Font{
    Color: "#FFFFFF",
  },
  Fill: excelize.Fill{
    Type: "pattern",
    Color: []string{"#4F81BD"},
    Pattern: 1,
  },
}
xlsx := excelize.NewFile()
xlsx.SetCellStyle("ScheetName", "A1", "F1", style)
```

or maybe 

```golang
style := excelize.Style{
  Font: &excelize.Font{
    Color: "#FFFFFF",
  },
  Fill: excelize.Fill{
    Type: "pattern",
    Color: []string{"#4F81BD"},
    Pattern: 1,
  },
}
xlsx := excelize.NewFile()
styleId, err := xlsx.AddStyle(style)
xlsx.SetCellStyle("ScheetName", "A1", "F1", styleId)
```

**Comment by xuri** [comment]
Thanks for your feedback, I recommend using `Style` structure data type instead of legacy JSON string as an argument when you call the `NewStyle` function for better performance, also ref issue #203.

**Comment by emaborsa** [comment]
Oh man, didn't see the function `func (f *File) NewStyle(style interface{}) (int, error)`.
Thanks for the hint!
