### ISSUE TITLE
Set borders on cell range

### ISSUE THREAD

**Issue by emaborsa** [qax-os/excelize#1141]
I am trying to set a border to each row, but to the range and not to each cell of the range.

My actual code:

```golang
style := excelize.Style{
  Fill: excelize.Fill{
    Type: "pattern",
    Color: []string{"#4F81BD"},
    Pattern: 1,
  },
  Border: []excelize.Border{
    {
      Type:  "top",
      Color: "#000000",
      Style: 1,
    },
    {
      Type:  "right",
      Color: "#000000",
      Style: 1,
    },
    {
      Type:  "bottom",
      Color: "#000000",
      Style: 1,
    },
    {
      Type:  "left",
      Color: "#000000",
      Style: 1,
    },
  },
}

styleId := excelize.NewStyle(&style)

for index, row := range rows {
  if index%2 == 0 {
    xlsx.SetCellStyle("ScheetName", fmt.Sprintf("A%d", index+1), "fmt.Sprintf("F%d", index+1)", styleId)
  }
}
```

The output:
![go_2](https://user-images.githubusercontent.com/9129912/152773332-0fbf7f2c-5f8f-42ca-bc48-af23dcaa3031.png)

The desired output:
![go_1](https://user-images.githubusercontent.com/9129912/152773341-1efb95fe-f9a3-48e3-9669-8d96e6978131.png)

**Comment by xuri** [comment]
Thanks for your issue, please reference issue #37, set cell styles for each different style.

**Comment by emaborsa** [comment]
Thanks,
I have seen it, however it is the same. It does not set the style to the range, but to the single sell. Actually we have to define 9 different styles, iterate and set them to the sheet. 

What if we need someting like followings?
![go_3](https://user-images.githubusercontent.com/9129912/152780139-759b842b-d979-44db-b2c2-e42ddcd8943b.png)

We need to create 20 (or more?) styles?

**Comment by xuri** [comment]
Yep, we need create style for each kind of cells with difference styles, and the SetCellStyle function could be help us setting the cells style in a range with same style at once.

**Comment by emaborsa** [comment]
I understand,
I close.
