### ISSUE TITLE
File not compressed? Xlsx 50 Mb to 1.5mb

### ISSUE THREAD

**Issue by IAkumaI** [qax-os/excelize#1142]
I create file with stream writer. Nothing special, just text (file attached).
File has size ~50Mb.
But if I open it and save via Excel/Numbers to same xlsx format - file size will be 1.5 Mb.

Why there is so large difference?

File created by exelize (just in zip for github):
[treolink.ru.xlsx.zip](https://github.com/qax-os/excelize/files/8021920/treolink.ru.xlsx.zip)

File open&exported via Numbers:
[treolink--2.xlsx](https://github.com/qax-os/excelize/files/8021912/treolink--2.xlsx)

**Comment by xuri** [comment]
Thanks for your issue. For faster generate speed and lower memory usage, the non-numeric type cell value won't be stored as a shared string in streaming mode currently. If you want to get a smaller size for generating spreadsheet files, please use the normal mode functions, such as `SetSheetRow` or `SetCellValue`, please also reference pull request #1123.

**Comment by xuri** [comment]
I'll close this issue, if you have any questions, please let me know to reopen this anytime.

**Comment by cucumber12121** [comment]
[test.zip](https://github.com/user-attachments/files/20940190/test.zip)
save xlsx to xlsx, file size be incressed @xuri
