### ISSUE TITLE
Rename/Remove default sheet name as Sheet1

### ISSUE THREAD

**Issue by sbhardwaj8717** [qax-os/excelize#1143]
**Description**
I am trying to looking for some method so that I can rename the default sheet name or I can remove the default sheet named as Sheet1  

go version go1.17.6 darwin/amd64

**Describe the results you received:**
![image](https://user-images.githubusercontent.com/53724086/153163024-e66fec1e-9f04-4f61-86b3-f35cebed2137.png)

**Comment by xuri** [comment]
Please rename sheet name with [`SetSheetName`](https://xuri.me/excelize/en/sheet.html#SetSheetName).

**Comment by microo8** [comment]
And how it can be deleted?

**Comment by sbhardwaj8717** [comment]
>

**Comment by sbhardwaj8717** [comment]
@xuri  I am stuck in resizing the cell width according to the cell data. Is there any way to may it possible to resize the cell size automatically?

**Comment by xuri** [comment]
This library support setting the text font size fit cell by setting the [`ShrinkToFit`](https://pkg.go.dev/github.com/xuri/excelize/v2#Alignment) style for cells, but doesn't support set columns width or rows height to fit the cell, also reference issue #92.

**Comment by esodell** [comment]
I was also wondering about deleting Sheet 1 after creating other named sheets in a loop. Found out you can with DeleteSheet() but only after you've added other sheets, so just append the delete after your loop

**Comment by xuri** [comment]
Hi @esodell, as the documentation of the [`DeleteSheet`](https://pkg.go.dev/github.com/xuri/excelize/v2#File.DeleteSheet) function says: it will be invalid when only one worksheet is left. This behavior was similar to Excel.
