### ISSUE TITLE
GetCellRichText doesn't work correctly

### ISSUE THREAD

**Issue by hstm** [qax-os/excelize#1145]
**Description**

The function GetCellRichText only works correctly for cells that have been formatted with SetCellRichText, but not for cells that have been formatted within Excel (or LibreOffice).

**Steps to reproduce the issue:**
1. Load partially formatted Excel table with Excelize with cell c2:c4 formatted (strikethrough) in Excel

|Column A|Column B|Column C|
|---|---|---|
|a2|b2|~~c2~~|
|a3|b3|~~c3~~|
|a4|b4|~~c4~~|

[Test.xlsx](https://github.com/qax-os/excelize/files/8040592/Test.xlsx)

2. SetCellRichText (bold, red, underline, strikethrough, code taken from cell_test.go) on b3 and c2, save file, reload

**Describe the results you received:**

- GetCellRichText on c2:c3 returns an empty array [] NOK
- GetCellRichText on b3 and c1 returns cell rich text formatting/text OK

**Describe the results you expected:**
GetCellRichText returns cell rich text formatting/text for cells formatted with Excel (c2, c3)

**Output of `go version`:**

```text
go version go1.17.6 darwin/amd64
```

**Excelize version or commit ID:**

```text
github.com/xuri/excelize/v2 v2.5.0
```

**Environment details (OS, Microsoft Excel™ version, physical, etc.):**
MacOS 12.2 (Intel)

**Comment by xuri** [comment]
Thanks for your issue. There are two kinds of style storage in your attachment spreadsheet. The styles of characters "a" and "b" in B3 has been stored in the SST (shared string table), that's the rich text, the styles of character "a" in C2 following a cell scope style, that's not rich text, but the styles of character "b" in C2 also has been stored in the SST (shared string table), the function `GetCellRichText` only support get the rich text but not cell style.

**Comment by hstm** [comment]
Thanks for your reply. You're absolutely right, I'm just looking at the unzipped Excel file. I didn't know cell formatting (e. g. a strikethrough) can be stored in different ways. Since GetCellRichText works as expected then, I'm going to close this issue.

If I understand correctly, there's currently no way in Excelize to read cell style details, right?

**Comment by xuri** [comment]
Yep, the library doesn't provide the get style details function currently, but the parsed style sheet:  [`Styles`](https://pkg.go.dev/github.com/xuri/excelize/v2@v2.5.0#File) has been exported, if you are familiar with [OOXML specification](https://www.iso.org/standard/71691.html), you can find out the style by style ID, here are [examples for getting cell background color](https://xuri.me/excelize/en/utils.html#ThemeColor) for your reference.

**Comment by hstm** [comment]
Thanks, I'll take a look at it!
