### ISSUE TITLE
Does Excelize support to add combined chart that one chart contains line and column

### ISSUE THREAD

**Issue by MrHanson** [qax-os/excelize#1147]
As title says, I can't find any way to add a combined chart in the document curently

**Comment by xuri** [comment]
Thanks for your issue. The parameter `combo` of [`AddChart`](https://xuri.me/excelize/en/chart.html#AddChart) specifies the create a chart that combines two or more chart types in a single chart.

**Comment by MrHanson** [comment]
Thanks！> Thanks for your issue. The parameter `combo` of [`AddChart`](https://xuri.me/excelize/en/chart.html#AddChart) specifies the create a chart that combines two or more chart types in a single chart.
