### ISSUE TITLE
View and SetRuler shown undeclared

### ISSUE THREAD

**Issue by aanilyildiz** [qax-os/excelize#1156]
**Description**

View and SetRuler options are shown not declared when tried to use inside SetSheetViewOptions

![image](https://user-images.githubusercontent.com/69147432/154973713-109068fd-efec-4f72-a5ec-c6836df06f2f.png)

**Output of `go version`:**

```text
go version go1.17.3 windows/amd64
```

**Excelize version or commit ID:**

```text
2.5.0
```

**Comment by xuri** [comment]
Thanks for your issue. The feature of support specifies sheet should display ruler will be released in the next version, please upgrade to the master branch code currently.

**Comment by xuri** [comment]
I'll close this issue. Since v2.6.0 was released, the library supported workbook views mode and ruler display settings.
