### ISSUE TITLE
my data date format is in yy-mm-dd but excel taking as dd-mm-yy 

### ISSUE THREAD

**Issue by satya0210** [qax-os/excelize#1157]
**Description**

**Steps to reproduce the issue:**
1.by giving yy-mm-dd
2.yy-month-dd
3.

**what I have
13-12-31 what it showing 13-12-2031:**

**i want calculate by using this dates
:**

**:**

```text
(paste your output here)
```

**Excelize version or commit ID:**

```text
(paste here)
```

**Environment details (OS, Microsoft Excel™2019.):**
windows 2019 is my version

**Comment by xuri** [comment]
Thanks for your feedback, Which version of the Excelize are you using? I have tested with the latest version and master branch code and it works well. Could you show us a complete, standalone example program or reproducible demo, and provide your input file attachment without confidential info if you can.

**Comment by satya0210** [comment]
Sir i have used power query sir to merge the files

**Comment by satya0210** [comment]
Sir Microsoft excel 2019 and my file extension is  xlsx

**Comment by huitingzhou15** [comment]
> 感谢您的反馈，您使用的是哪个版本的 Excelize？我已经使用最新版本和主分支代码进行了测试，效果很好。您能否向我们展示一个完整的、独立的示例程序或可重现的演示，如果可以的话，请提供您的输入文件附件而不提供机密信息。

I also have the same problem

**Comment by huitingzhou15** [comment]
> **Description**
> 
> **Steps to reproduce the issue:** 1.by giving yy-mm-dd 2.yy-month-dd 3.
> 
> **what I have 13-12-31 what it showing 13-12-2031:**
> 
> **i want calculate by using this dates :**
> 
> **:**
> 
> ```
> (paste your output here)
> ```
> 
> **Excelize version or commit ID:**
> 
> ```
> (paste here)
> ```
> 
> **Environment details (OS, Microsoft Excel™2019.):** windows 2019 is my version

I also have the same problem，can it be resolved as soon as possible

**Comment by satya0210** [comment]
may how many years data do u have

**Comment by xuri** [comment]
It seems still not have enough info of code and attachments to reproduce this issue, so I'll close this issue, if you have any questions, please let me know.

**Comment by xuri** [comment]
Hi @satya0210, this issue seem similar with #1199. Now, the library support to specified system date and time format code in the options when creating or opening the workbook, you can open a workbook with custom date and time options like this:

```go
f, err := excelize.OpenFile("Book1.xlsx", excelize.Options{
    ShortDatePattern: "dd-mm-yy",
})
```

This feature will be released in the next version.
