### ISSUE TITLE
 I have to average the data to every hour for 365 days

### ISSUE THREAD

**Issue by haritha1022** [qax-os/excelize#1158]
[saple.xlsx](https://github.com/qax-os/excelize/files/8130158/saple.xlsx)

**Description**

i have 43 rows and 16000 columns of data
for 365 days data 24 hours to every hour I have 6 values with 10 min interval
some dates are missing and for some hours there is only 3 values with 10 mins interval even though I have to average the data

**Steps to reproduce the issue:**
1.please check my attached file
2.
3.

**Describe the results you received:**

**Describe the results you expected:**
if the entire date or hour is missing it doesn't matter if an hour have  3 values I have to average the value and I want make a single hourly data
**Output of `go version`:**

```text
how can i get it
```

**Excelize version or commit ID:**

```text
i dont know what does it mean
```

**Environment details (OS, Microsoft Excel™ version, physical, etc.):**
Microsoft Excel 2019

**Comment by xuri** [comment]
Sorry, I can't understand what's your means. Can you show us a complete, standalone example program or reproducible demo? You can check installed Go language version by run `go version`.

**Comment by haritha1022** [comment]
sir
i have attached my data format
please check it

**Comment by xuri** [comment]
It seems still not have enough info of code and attachments to reproduce this issue, so I'll close this issue, if you have any questions, please let me know.
