### ISSUE TITLE
Control of showSheetTabs in workbook.xml

### ISSUE THREAD

**Issue by Ralim** [qax-os/excelize#1160]
**Description**
Hello, 

At the moment Excelize appears to be stripping the `showSheetTabs` control out of the `bookViews` tag in `workbook xml`.

For my use case I just want the tag to persist through unchanged, but control would be nice.

**Steps to reproduce the issue:**
1. Create excel xlsm with `showSheetTabs="0"` by [turning off showing sheet tabs](https://www.solveyourtech.com/how-to-hide-sheet-tabs-in-excel-2010/)
2. Open the file, then save the file to a new location through excelize
3. Notice that in `workbook.xml` the option is no longer present 

**Describe the results you received:**

In `workbook.xml` we have the following before excelize:

```
<bookViews>
        <workbookView showSheetTabs="0" xWindow="-108" yWindow="-108" windowWidth="23256" windowHeight="12576" tabRatio="834" xr2:uid="{00000000-000D-0000-FFFF-FFFF00000000}"/>
    </bookViews>
```
and after running through Excelize we have:

```
<bookViews>
        <workbookView xWindow="-105" yWindow="-105" windowWidth="23250" windowHeight="12570" tabRatio="834" xr2:uid="{00000000-000D-0000-FFFF-FFFF00000000}"/>
    </bookViews>
```
**Describe the results you expected:**

In `workbook.xml` we have the following before excelize:

```
<bookViews>
        <workbookView showSheetTabs="0" xWindow="-108" yWindow="-108" windowWidth="23256" windowHeight="12576" tabRatio="834" xr2:uid="{00000000-000D-0000-FFFF-FFFF00000000}"/>
    </bookViews>
```
and after running through Excelize we would like:

```
<bookViews>
        <workbookView showSheetTabs="0" xWindow="-105" yWindow="-105" windowWidth="23250" windowHeight="12570" tabRatio="834" xr2:uid="{00000000-000D-0000-FFFF-FFFF00000000}"/>
    </bookViews>
```
**Output of `go version`:**

```text
go version go1.17.4 linux/arm64
```

**Excelize version or commit ID:**

```text
	github.com/xuri/excelize/v2 v2.5.0
```

**Environment details (OS, Microsoft Excel™ version, physical, etc.):**

Tested on Linux and Mac OSX; go 1.17 and 1.18.
Files are edited with latest office365.

**Notes**

Happy to help in any way I can for this :)

**Comment by xuri** [comment]
Thanks for your issue. I have fixed it, please upgrade to the master branch code, and this patch will be released in the next version.

**Comment by Ralim** [comment]
Confirmed fixed.

Thank you ❤️
