### ISSUE TITLE
SetRowStyle is not replacing the previous style of a cell

### ISSUE THREAD

**Issue by kukaki** [qax-os/excelize#1163]
SetRowStyle is not replacing the style of a cell (part of the row) which was previously set using SetColStyle .

For eg. Let's say I have set style to column B using SetColStyle. Now if I set style to row 1 using SetRowStyle, the row style is applied to entire row 1 except cell B1 (col style prevailing here).

i.e. SetRowStyle is setting style to only the cells which do not have a previous style.

**Steps to reproduce the issue:**
1. Set style to column B using SetColStyle
2. Set style to row 1 using SetRowStyle

**Describe the results you received:**
The row style is applied to entire row 1 except cell B1 (col style prevailing here).

**Describe the results you expected:**
As row style is the latest one, it should be applied to entire row 1.
And col style should be applied to entire Column B (except B1 cell).

**Output of `go version`:**

```text
go1.18beta2
```

**Excelize version or commit ID:**

```text
github.com/xuri/excelize/v2 v2.5.1-0.20220222002218-8a6815fcccc1
```

**Environment details (OS, Microsoft Excel™ version, physical, etc.):**
Windows 11
Microsoft Office 2007

**Comment by xuri** [comment]
Thanks for your issue. I have fix it, please upgrade to the master branch code, and this patch will be release in the next version.
