### ISSUE TITLE
Nested Formular Error with CalCellValue

### ISSUE THREAD

**Issue by ffleader1** [qax-os/excelize#1164]
**Description**
Cannot use nested function with calculate cell value. It produces incorrect result.

Try this function: ```=IF((ROUNDUP(IF(A1=16,(A2*2+4*0.3+1+1),IF(A1=4,(A2+2*0.3+1+1),(A3*SQRT(A1/2)+(SQRT(A1/2)*0.3)+1+1))),0))<=A4,(ROUNDUP(IF(A1=16,(A2*2+4*0.3+1+1),IF(A1=4,(A2+2*0.3+1+1),(A3*SQRT(A1/2)+(SQRT(A1/2)*0.3)+1+1))),0)),-1)```

It works in excel but will not work with the plugin. It gives this error: ```IF accepts at most 3 arguments```

**Excelize version:**

```text
v2.5.0
```

**Comment by xuri** [comment]
Thanks for your feedback, I have fixed this issue, please try upgrade to the master branch code, and this patch will be released in the next version.
