### ISSUE TITLE
Write Performance

### ISSUE THREAD

**Issue by duke-git** [qax-os/excelize#1168]
使用write方法写入gin返回给前端，非常慢，截图是文件大小70M，用了41s. 请问有什么优化方法吗？
// file -> *excelize.File, c -> *gin.Context
_ = file.Write(c.Writer) 
[](https://user-images.githubusercontent.com/5037603/156536560-02dc22a9-eb8a-49e0-8a79-6b1214087846.png)

**Comment by duke-git** [comment]
<img width="575" alt="image" src="https://user-images.githubusercontent.com/5037603/156536936-49103a2c-985b-46b0-ba56-0152d39f94d8.png">

**Comment by xuri** [comment]
Can you show us a complete, standalone example program or reproducible demo? And provide your input file, or at least tell us about it?

**Comment by duke-git** [comment]
我写一个实际业务的模拟方法，请参考截图：file.Write(c.Writer)，70M文件要写入40s左右。
![image](https://user-images.githubusercontent.com/5037603/156689430-c7e28eb0-99c9-4464-a273-8fdabbe413eb.png)

**Comment by xuri** [comment]
Thanks for your feedback, please using [stream writer](https://pkg.go.dev/github.com/xuri/excelize/v2#File.NewStreamWriter) for generating a new worksheet with huge amounts of data, and also reference the [performance benchmark report](https://xuri.me/excelize/en/performance.html).

**Comment by duke-git** [comment]
好的，用的是这个库：github.com/360EntSecGroup-Skylar/excelize/v2 v2.3.2， 和 github.com/xuri/excelize/v2 是同一个吗？

**Comment by xuri** [comment]
Yep, please using `github.com/xuri/excelize/v2`, and also reference the issues #973, #1020, and #1079.

**Comment by duke-git** [comment]
谢谢
