### ISSUE TITLE
Upgrading to master branch nukes program (maybe)

### ISSUE THREAD

**Issue by jacoblockett** [qax-os/excelize#1171]
**Description**
Forgive me if I'm doing something incredibly stupid, I'm new to Go as of a few days ago.

I need to be able to rely on styles, specifically `<b/>` styles when saving some spreadsheets I'm parsing and updating. I've seen a few issues where the fix was to upgrade to master. So, I did just that: `go get github.com/xuri/excelize/v2@master`. This is where the "maybe" comes in; is that command correct? If it is, then please keep reading :)

I looked into the XML and everything _seemed_ ok, but I've gone cross-eyed at this point. The highlights I found are the xl/styles.xml and xl/workbook.xml have some noticeable changes from the original. Otherwise, everything is identical. I'll attach the in/out for review. They had sensitive info on them which is why they're practically bare, but they still produce the same issue as described.
[test COPY.zip](https://github.com/qax-os/excelize/files/8191994/test.COPY.zip)
[test.zip](https://github.com/qax-os/excelize/files/8191995/test.zip)

**Steps to reproduce the issue:**
1. `go get github.com/xuri/excelize/v2@master`
2. Simple file copy and save
```go
package main

import "github.com/xuri/excelize/v2"

func main() {
	f, err := excelize.OpenFile("./test.xlsx")
	if err != nil {
		panic(err)
	}

	if err := f.SaveAs("./test COPY.xlsx"); err != nil {
		panic(err)
	}

	f.Close()
}
```

**Describe the results you received:**
Received message from Excel when opening: We found a problem with some content in 'test COPY.xlsx'. Do you want us to try to recover as much as we can? If you trust the source of this workbook, click Yes.

Clicking Yes results in: The workbook cannot be opened or repaired by Microsoft Excel because it is corrupt.

**Describe the results you expected:**
Workbook to open without any change in behavior

**Output of `go version`:**

```text
go version go1.17.8 windows/amd64
```

**Excelize version or commit ID:**

```text
v2.5.1-0.20220305162933-354d1696d899
```

**Environment details (OS, Microsoft Excel™ version, physical, etc.):**
Windows 11 Pro - build 22000.527, version 21H2
MS Excel - build 14931.20120, version 2202

**Comment by xuri** [comment]
Thanks for your feedback, I have fixed this issue. Please try to re-upgrade to the master branch code.

**Comment by jacoblockett** [comment]
Awesome! I've tested a couple of my use cases and everything seems to be working as normal. Thanks for checking on this so soon
