### ISSUE TITLE
Imporve the writing operation when write streaming data to the result(希望在流式写入生成结果的时候优化一下，减少内存占用)

### ISSUE THREAD

**Issue by Jirath-Liu** [qax-os/excelize#1174]
here are code that i think need to improve
when copy the data from streaming to the result, the framework use ` _, err = io.Copy(fi, from)` this may cause high memory when copy the data, acually, i was in trouble of this, the streaming still cause high memory occupyed when generate the result. could we copy the data from buffer to the result solwly? or use no copy ? 

中文版本：
这段代码感觉可能需要做一下改进，
这里在生成结果Excel的时候，使用了一段代码` _, err = io.Copy(fi, from)`  这个直接从buffer里面复制了完整的sheet信息到结果流中，代码简单但是导致发生了大量内存占用，我这边已经遇到这个问题了， 不知道可以不可以保持流式的风格， 一点一点写进去， 或者直接不要复制数据了， 复制数据还会导致两份磁盘，（我们的场景，磁盘还是比较有限）
```
// writeToZip provides a function to write to zip.Writer
func (f *File) writeToZip(zw *zip.Writer) error {
	f.calcChainWriter()
	f.commentsWriter()
	f.contentTypesWriter()
	f.drawingsWriter()
	f.vmlDrawingWriter()
	f.workBookWriter()
	f.workSheetWriter()
	f.relsWriter()
	f.sharedStringsLoader()
	f.sharedStringsWriter()
	f.styleSheetWriter()

	for path, stream := range f.streams {
		fi, err := zw.Create(path)
		if err != nil {
			return err
		}
		var from io.Reader
		from, err = stream.rawData.Reader()
		if err != nil {
			_ = stream.rawData.Close()
			return err
		}
		_, err = io.Copy(fi, from)
		if err != nil {
			return err
		}
		_ = stream.rawData.Close()
	}
	
```

**Comment by xuri** [comment]
Which version of Excelize are you using, and how much data is in your spreadsheet, how much memory cost? Can you show us a complete, standalone example program or reproducible demo or detail the issue by the template?

**Comment by Jirath-Liu** [comment]
v2.4.1, the data is about 2-4GB,
as we using, program create a temp file for streaming,
and when export the answer to the file or the stream,
io.Copy(fi, from) has occupy double of the original memory, 4-8GB

**Comment by xuri** [comment]
The library needs to add the temporary file to the archive when saving the workbook, the data copy cannot be skipped in this step.

**Comment by xuri** [comment]
The library needs to add the temporary file to the archive when saving the workbook, the data copy cannot be skipped in this step. I've closed this issue, and if you have any suggestions, please let me know.
