### ISSUE TITLE
Close() function not available when File opened with excelize.OpenReader()

### ISSUE THREAD

**Issue by dwschulze** [qax-os/excelize#1179]
### Discussed in https://github.com/qax-os/excelize/discussions/1178

<div type='discussions-op-text'>

<sup>Originally posted by **dwschulze** March  9, 2022</sup>
I get an `*excelize.File` with

	`f, err := excelize.OpenReader(file)`

where the file argument is a `multipart.File`.  If I try to do

    `defer f.Close()`

I get this error:

     _f.Close undefined (type *excelize.File has no field or method Close)_

If I get an `*excelize.File` with

    `f, err := excelize.OpenFile(fileName)`

then I can call `.Close()` on it.

How do I assure that the `excelize.File` obtained from `OpenReader()` gets closed?

</div>

**Comment by xuri** [comment]
Thanks for your issue, this issue is duplicated with #1025, #1042, and #1091, the Close function has been introduced since v2.5.0, if you're using the version early than v2.5.0, needn't call this function.

**Comment by xuri** [comment]
I will close this issue. If you still have any questions, please let me know.
