### ISSUE TITLE
MS Office Cann't Open the Excel files created by the excelize package

### ISSUE THREAD

**Issue by shuhaohe** [qax-os/excelize#1180]
Here is the screenshot

<img width="1388" alt="image" src="https://user-images.githubusercontent.com/35570117/157586377-8fc56715-f506-4f5c-ab5f-86146825dcd6.png">

But the output excel file can be open by WPS normally. 

Here is the output file.
[Batch-20220309180252.xlsx](https://github.com/qax-os/excelize/files/8220193/Batch-20220309180252.xlsx)

**Comment by shuhaohe** [comment]
The version of the package is :

github.com/xuri/excelize/v2 v2.3.2

**Comment by xuri** [comment]
Thanks for your issue. Can you show us a complete, standalone example program or reproducible demo? And provide your input file, or at least tell us about it?

**Comment by shuhaohe** [comment]
```go
func ConvertToExcel(dataMap map[string][][]string) (*bytes.Buffer, error) {
	formatRow := func(originData []string) []interface{} {
		result := make([]interface{}, 0)
		for _, item := range originData {
			result = append(result, item)
		}

		return result
	}

	file := excelize.NewFile()

	for templateName, data := range dataMap {
		_ = file.NewSheet(templateName)
		streamWriter, err := file.NewStreamWriter(templateName)
		if err != nil {
			logkit.Error("ConvertToExcel: NewStreamWriter failed",
				zap.Any("templateName", templateName),
				zap.Error(err))
			continue
		}

		for idx, originRow := range data {
			rowID := idx + 1
			row := formatRow(originRow)
			cell, _ := excelize.CoordinatesToCellName(1, rowID)
			if err := streamWriter.SetRow(cell, row); err != nil {
				logkit.Error(fmt.Sprintf("ConvertToExcel: NewStreamWriter write <row:%d> failed", rowID),
					zap.Any("templateName", templateName),
					zap.Error(err))
			}
		}

		err = streamWriter.Flush()
		if err != nil {
			logkit.Error(fmt.Sprintf("ConvertToExcel: NewStreamWriter write flush failed"),
				zap.Any("templateName", templateName),
				zap.Error(err))
		}
	}

	// delete the default sheet
	file.DeleteSheet("Sheet1")

	buf := &bytes.Buffer{}
	if err := file.Write(buf); err != nil {
		logkit.Error("file.Write failed",
			zap.Error(err))
		return nil, err
	}

	return buf, nil
}

```

and then 
```go
        // it will call the above function: ConvertToExcel
	buf, err := m.service.TaskProgressBatchExport(taskIDs)
	if err != nil {
		m.Error(ctx, err)
		return nil
	}

	contentLength := int64(len(buf.Bytes()))
	contentType := "application/octet-stream"
	filename := fmt.Sprintf("Batch-%s.xlsx", time.Now().Format(util.TimeLayoutYYYYMMDDHHmmss))
	extraHeaders := map[string]string{
		"Content-Disposition": `attachment; filename="` + filename + `"`,
	}
	return ginweb.FileResponse(http.StatusOK, contentLength, contentType, buf, extraHeaders)
```

**Comment by shuhaohe** [comment]
I try to follow this issue https://github.com/qax-os/excelize/issues/148, and add Set("Content-Transfer-Encoding", "binary") to header, it doesn't work still.

**Comment by xuri** [comment]
Thanks for your feedback, could you provides **a simple standalone example** program or reproducible demo?

**Comment by shuhaohe** [comment]
demo case
```
func ConvertToExcel(dataMap map[string][][]string) (*bytes.Buffer, error) {
	formatRow := func(originData []string) []interface{} {
		result := make([]interface{}, 0)
		for _, item := range originData {
			result = append(result, item)
		}

		return result
	}

	file := excelize.NewFile()

	for templateName, data := range dataMap {
		_ = file.NewSheet(templateName)
		streamWriter, err := file.NewStreamWriter(templateName)
		if err != nil {
			logkit.Error("ConvertToExcel: NewStreamWriter failed",
				zap.Any("templateName", templateName),
				zap.Error(err))
			continue
		}

		for idx, originRow := range data {
			rowID := idx + 1
			row := formatRow(originRow)
			cell, _ := excelize.CoordinatesToCellName(1, rowID)
			if err := streamWriter.SetRow(cell, row); err != nil {
				logkit.Error(fmt.Sprintf("ConvertToExcel: NewStreamWriter write <row:%d> failed", rowID),
					zap.Any("templateName", templateName),
					zap.Error(err))
			}
		}

		err = streamWriter.Flush()
		if err != nil {
			logkit.Error(fmt.Sprintf("ConvertToExcel: NewStreamWriter write flush failed"),
				zap.Any("templateName", templateName),
				zap.Error(err))
		}
	}

	file.DeleteSheet("Sheet1")
        // cannot be open with MS Office 
	file.SaveAs("test3.xlsx")

	buf := &bytes.Buffer{}
	if err := file.Write(buf); err != nil {
		logkit.Error("file.Write failed",
			zap.Error(err))
		return nil, err
	}

	return buf, nil
}
```

```
func TestUnitConvertToExcel(t *testing.T) {
	var dataMap = map[string][][]string{
		"test1": {
			{"hello", "world"},
			{"hello", "world"},
		},
		"test2": {
			{"hello", "world"},
			{"hello", "world"},
		},
	}

	ConvertToExcel(dataMap)
}
```

**Comment by ac5tin** [comment]
using v2.5.0 doesn't work. 
I converted the `xlsx` file into a `zip` file and opened the sheet xml file,
seems like the sheet xml file is missing a closing `worksheet` tag

**Comment by xuri** [comment]
Hi @ac5tin, thanks for your feedback, please give a try with the master branch code, and if it still not work please provide your input file attachment without confidential info if you can.

**Comment by ac5tin** [comment]
[test.xlsx](https://github.com/qax-os/excelize/files/8330740/test.xlsx)

**Comment by xuri** [comment]
The spreadsheet in the attachment can't open normally by Excel application. Please make sure your file is a valid spreadsheet.

**Comment by xuri** [comment]
@ac5tin, please try to upgrade to the master branch code and use the `GetRow` or rows iterator to stream read worksheet data.

**Comment by xuri** [comment]
@ac5tin, please try to upgrade to the master branch code and use the `GetRows` or rows iterator to stream read worksheet data.

**Comment by xuri** [comment]
How did you generate this file? If you are using the stream writer to create the spreadsheet, as the document says that you must call the [`Flush`](https://pkg.go.dev/github.com/xuri/excelize/v2#StreamWriter.Flush) method to end the streaming writing process before saving the file, otherwise the crouped file will be generated. In addition, it works if you upgrade to the master branch code and use the [`GetRows`](https://pkg.go.dev/github.com/xuri/excelize/v2#File.GetRows) or [rows iterator](https://pkg.go.dev/github.com/xuri/excelize/v2#File.Rows) to stream read worksheet data.

**Comment by ac5tin** [comment]
im using `StreamWriter` to create spreadsheet, then finally use `writeToBuffer` to get the final file binary

**Comment by xuri** [comment]
As previously I said, you should be **called the `Flush` function** before saving the file. Please also reference the example in the documentation. If is still have a problem, please show us a complete, standalone example program or reproducible demo.

**Comment by xuri** [comment]
Thanks for your feedback, did you called the `Flush` function before saving the file? Could you show us a complete, standalone example program or reproducible demo?

**Comment by ac5tin** [comment]
yes, can confirm after adding `Flush`, it works now. Thanks @xuri  
:D
