### ISSUE TITLE
Newlines not properly interpreted by SetCellValue

### ISSUE THREAD

**Issue by adamwoolhether** [qax-os/excelize#1187]
**Description**

I have a string var created iteratively in a loop: `stringVar += fmt.Sprintf()` that has a series of `\n` newlines within. When I write this string to a cell with `SetCellValue`, the newlines are removed, and the cell is one long line of text.

**Steps to reproduce the issue:**
1.
```
var testString string
source := fmt.Sprintf("%s %s %s\n", "a", "string", "with newlines")
testString = source
testString += source

File.SetCellValue("Sheet1", "A1", testString)
```
**Describe the results you received:**

a string with no newlines in the cell:
```
a string with newlinesa string with newlines
```

**Describe the results you expected:**
A formatted cell, same as printing it to stdout:
```
a string with newlines
a string with newlines
```
**Output of `go version`:**

```text
go version go1.18 darwin/amd64
```

**Excelize version or commit ID:**

```text
v2.5.0
```

**Environment details (OS, Microsoft Excel™ version, physical, etc.):**

MacOS Darwin Kernel Version 21.4.0

Excel 16.53

**Comment by adamwoolhether** [comment]
Strangely enough, double-clicking the cell in the file fixes the issue, per: https://github.com/qax-os/excelize/issues/69#issuecomment-323526996

kind of inconvenient to manually double click hundreds of cells though. Any workaround for this?

**Comment by xuri** [comment]
Thanks for your feedback. This problem was similar to issues #405 and #1021. Please create a style with wrap text with the `NewStyle` function, and bind the style ID to the cell with the `SetCellStyle` function.

**Comment by adamwoolhether** [comment]
啊，我沒注意到那個function，非常感謝你迅速的回覆！
