### ISSUE TITLE
streamWriter.SetRow can't fill all cells in a row

### ISSUE THREAD

**Issue by programspace** [qax-os/excelize#1188]
**Description**
streamWriter.SetRow can't fill all cells in a row.
No value cell is filled. 

**Steps to reproduce the issue:**

1.set style
> style1, err := file.NewStyle(&excelize.Style{Fill: excelize.Fill{Type: "pattern", Color: []string{"#FFFF00"}, Pattern: 1}})  
> if err != nil {  
> 	fmt.Println(err)  
> }  

2.stream and flush
> row := make([]interface{}, 50)  
> for colID := 0; colID < 50; colID++ {  
> 	row[colID] = rand.Intn(640000)  
> }  
> for rowID := 2; rowID <= 100; rowID++ {  
> 	cell, _ := excelize.CoordinatesToCellName(1, rowID)  
> 	if err := streamWriter.SetRow(cell, row, excelize.RowOpts{StyleID: style1}); err != nil {  
> 		fmt.Println(err)  
> 	}	  
> }  
> if err := streamWriter.Flush(); err != nil {  
> 	fmt.Println(err)  
> }  

**Describe the results you received:**

streamWriter.SetRow can't fill cells have a value.

**Describe the results you expected:**

streamWriter.SetRow fills all cells in a row

**Output of `go version`:**

```text
go1.17.6
```

**Excelize version or commit ID:**

```text
v2.5.0
```

**Environment details (OS, Microsoft Excel™ version, physical, etc.):**

Windows 10, Excel 2016

**Comment by xuri** [comment]
Thanks for your issue. Please binding style for no-empty cells for each row, using

```go
row[colID] = excelize.Cell{StyleID: style1, Value: rand.Intn(640000)}
```

instead of

```go
row[colID] = rand.Intn(640000)
```

**Comment by programspace** [comment]
@xuri 
 I appreciate your quick reply.
 That works for me!
