### ISSUE TITLE
How to get chart to a file like getpicture?

### ISSUE THREAD

**Issue by 3xxx** [qax-os/excelize#1190]
Thank you the excelize team.
I want export the excel chart to a image file,just like [getpicture](https://xuri.me/excelize/en/image.html#GetPicture),can you give me some advice?

**Comment by xuri** [comment]
Thanks for your issue. The graphical objects such as pictures, shapes, charts, and diagrams were defined with drawing mark up language in the spreadsheet, its difference with image, so you can't get it like get pictures.

**Comment by 3xxx** [comment]
I got it，thank you.

**Comment by xuri** [comment]
I will close this issue. If you have any questions, please let me know.
