### ISSUE TITLE
Multiple dependent dropdown doesn't work when opening document until reentering the function

### ISSUE THREAD

**Issue by bennewland123** [qax-os/excelize#1193]
Multi dependent dropdowns do not work until after the file is loaded and the validation entered again.

I'm generating a sheet where the output of printing the validation is as follows:

`*excelize.DataValidation=&{true 0xc0050df280 <nil> 0xc0050df260  <nil> <nil> false true false Q2:Q1000 list <formula1>=OFFSET(other_sheet!$C$1,SUM(MATCH(1,(N2=other_sheet!A$2:A$17010)*(M2=other_sheet!B$2:B$17010),0),0),0,COUNTIFS(other_sheet!$A$1:$A$17010,N2,other_sheet!$B$1:$B$17010,M2),1)</formula1>`

For whatever reason, the COUNTIFS (only needed for lists with a primary and secondary controlling field) causes the dropdown not to work until the sheet has been opened and the same formula re-entered, which leads me to believe that there is an issue with how these are formatted when they are written by excelize.

**Comment by xuri** [comment]
Thanks for your issue. Which version of the library and Excel application are you using? Can you show us a complete, standalone example program or reproducible demo? And please provide the expected and generated spreadsheet file attachment without confidential info if you can.

**Comment by xuri** [comment]
It seems still not have enough info of code and attachments to reproduce this issue, so I'll close this issue, if you have any questions, please let me know to reopen this anytime.
