### ISSUE TITLE
Excel value is "+INF" without real value

### ISSUE THREAD

**Issue by csomix** [qax-os/excelize#1197]
I read a lot of excel files and found a special value that returns "+Inf".

For example
- If the value of the field is "44E517048111", the program returns "+Inf" both when reading the line and with the GetCellValue function. 

Excelize version:
- go: finding module for package github.com/xuri/excelize/v2
- go: found github.com/xuri/excelize/v2 in github.com/xuri/excelize/v2 v2.5.0

Environment details (OS, Microsoft Excel™ version, physical, etc.):
- go version go1.18 windows/amd64

**Comment by xuri** [comment]
The new version 2.6.0 has been released, I closed this issue. If you have any questions, please let me know.
