### ISSUE TITLE
write data by streamwriter but the file has some problem

### ISSUE THREAD

**Issue by Crearns** [qax-os/excelize#1202]
**Description**

**Steps to reproduce the issue:**
1.
2.
3.

**Describe the results you received:**
I wrote some data by streamwirter,and the row data is no order,  the result is that the output file has some problem
![image](https://user-images.githubusercontent.com/26384257/162564728-eeb1c857-92be-4d1e-bab5-b11e32cc29fa.png)

here is my code
```go
func main() {
	var (
		err  error
		data []interface{}
	)
	file := excelize.NewFile()
	writer, err := file.NewStreamWriter("Sheet1")
	if err != nil {
		return
	}
	//
	d := []interface{}{"A", "B", "C", "D", "E", "F", "G"}
	err = writer.SetRow("A1", d)
	if err != nil {
		return
	}

	data = []interface{}{"A1", "B1", "C1", "D1", "E1", "F1"}
	err = writer.SetRow("A2", data)
	if err != nil {
		return
	}

	data = []interface{}{"A2", "B2", "C2", "D2", "E2", "F2"}
	err = writer.SetRow("A3", data)
	if err != nil {
		return
	}

	data = []interface{}{"A3", "B3", "C3", "D3", "E3", "F3"}
	err = writer.SetRow("A4", data)
	if err != nil {
		return
	}

        // back to the second row and write the data G2
	err = writer.SetRow("G2", []interface{}{"G2"})
	if err != nil {
		return
	}

	err = writer.Flush()
	if err != nil {
		return
	}

	err = file.SaveAs("/Users/cc/Desktop/test2.xlsx")
	if err != nil {
		return
	}
}

```

**Describe the results you expected:**

**Output of `go version`:**

```text
go version go1.16.5 darwin/amd64
```

**Excelize version or commit ID:**

```text
github.com/xuri/excelize/v2 v2.4.1
```

**Environment details (OS, Microsoft Excel™ version, physical, etc.):**
Microsoft Excel™ 16.59
macOS 12.1
2019 MacBook Pro 16 inch

**Comment by xuri** [comment]
Thanks for your issue. Note that as the [document says](https://pkg.go.dev/github.com/xuri/excelize/v2#File.NewStreamWriter), please ensure that the order of line numbers is ascending in the streaming writing process.

**Comment by Crearns** [comment]
> Thanks for your issue. Note that as the [document says](https://pkg.go.dev/github.com/xuri/excelize/v2#File.NewStreamWriter), please ensure that the order of line numbers is ascending in the streaming writing process.

Although the line numbers are not in order, the data written is not in conflict, is this not allowed?

**Comment by xuri** [comment]
Yep, if you wanna write cell back around, please using the normal API.

**Comment by Crearns** [comment]
> Yep, if you wanna write cell back around, please using the normal API.

ok, thanks

**Comment by xuri** [comment]
I closed this issue. If you have any questions, please let me know.
