### ISSUE TITLE
If same field of colums or rows is used for data, "Pivot table content error" is displayed when excel file is opened.

### ISSUE THREAD

**Issue by sis6789** [qax-os/excelize#1203]
**Description**

If same field of colums or rows for data, "Pivot table content error" is displayed when excel file is opened.

**Steps to reproduce the issue:**
1. run follwoing code. I have changed line 36 from your pivot example.
2. open the generated excel file.
3. excel complains content error and prompts recovery of excel file.

**Describe the results you received:**
Pivot table content error and recovery prompt.

**Describe the results you expected:**
Normal open of generated excel fie without complain.

**Output of `go version`:**

```text
go version go1.18 windows/amd64
```

**Excelize version or commit ID:**

```text
github.com/xuri/excelize/v2 v2.6.0
```

**Environment details (OS, Microsoft Excel™ version, physical, etc.):**
Windows11, Excel 2203(build 15028.20204)

**Comment by sis6789** [comment]
[main.txt](https://github.com/qax-os/excelize/files/8509005/main.txt)

**Comment by xuri** [comment]
Thanks for your issue. I have fixed it. Please upgrade to the master branch code, and this patch will be released in the next version.
