### ISSUE TITLE
403 Forbidden

### ISSUE THREAD

**Issue by mraxrorxon** [qax-os/excelize#1205]
**Steps to reproduce the issue:**
1. I use corporative proxy
2. go get github.com/xuri/excelize/v2  does not working in my project

**Describe the results you received:**
![image](https://user-images.githubusercontent.com/32955674/163990648-b6d7dbc4-5418-4488-9107-21e182b4782e.png)

**Describe the results you expected:**

**Output of `go version`:**
go version is 1.17

```text
(paste here)
```

**Comment by xuri** [comment]
Thanks for your feedback, but that's outside the scope of this repo. Could you try using another proxy or download source from the release page?

**Comment by xuri** [comment]
I will close this issue. If you have any questions, please let me know.
