### ISSUE TITLE
读取excel文本框数据出错

### ISSUE THREAD

**Issue by wxywizard** [qax-os/excelize#1206]
**Description**

读取excel文本框数据出错，
excel文本数据为0102E001
读取的数据为1020
excel单元格设置为纯文本，读取数据采用string切片接收
![screenshot-20220421-174424](https://user-images.githubusercontent.com/28422371/164428108-e37fb09c-279c-448b-a246-2b302b2771ed.png)

**Comment by wxywizard** [comment]
version
go 1.8.1
github.com/xuri/excelize/v2 v2.5.0

**Comment by xuri** [comment]
Thanks for your feedback. This issue has been fixed in the v2.6.0, please upgrade to the latest version.

**Comment by wxywizard** [comment]
> Thanks for your feedback. This issue has been fixed in the v2.6.0, please upgrade to the latest version.

3q，测试ok
