### ISSUE TITLE
Dynamically convert to Struct？

### ISSUE THREAD

**Issue by toddwyl** [qax-os/excelize#1208]
Is there any plan to dynamically convert each row within excel into a struct-like data type
We can use reflect to scan and convert dynamically, and define the types that need to be converted through configuration.

**Comment by xuri** [comment]
This issue duplicate with #619. Users can easily make this wrapper and even create their own complex nested structure. I didn't suggest introducing this feature to make the library core and easy.

**Comment by xuri** [comment]
I will close this issue. If you have any questions, please let me know.
