### ISSUE TITLE
Bug about GetCellRichText

### ISSUE THREAD

**Issue by CHANTXU64** [qax-os/excelize#1213]
**Description**

Create `test_rich_text.xlsx` in Excel，`Sheet1`:
|A|
|-|
|***rich***~~text~~|
|a|
|b|
|c|
|d|
|e|
|f|
|TRUE|
|FALSE|

Run: 

```go
func TestRichText (t *testing.T) {
  file, err := excelize.OpenFile("test_rich_text.xlsx")
  if err != nil {
    fmt.Println(err)
  }
  sheet := "Sheet1"
  for i := 0; i < 9; i++ {
    cell, _ := excelize.CoordinatesToCellName(1, i + 1)
    richtext, err := file.GetCellRichText(sheet, cell)
    if err != nil {
      fmt.Println(err)
    }
    fmt.Println(richtext)
  }
  file.Close()
}
```

**Describe the results you received:**

```text
[{<nil> TEST} {0x140005b5950 rich text}]
[]
[]
[]
[]
[]
[]
[]
[{<nil> TEST} {0x140005b59a0 rich text}]
```

**Describe the results you expected:**

```text
[{<nil> TEST} {0x140005b5950 rich text}]
[]
[]
[]
[]
[]
[]
[]
[]
```

**Output of `go version`:**

```text
go version go1.18.1 darwin/arm64
```

**Excelize version or commit ID:**

```text
version 2.6.0
```

**Environment details (OS, Microsoft Excel™ version, physical, etc.):**
macOS: Microsoft Excel

**Comment by xuri** [comment]
Thanks for your issue, I have fixed it. Please upgrade to the master branch code, and this patch will be released in the next version.
