### ISSUE TITLE
AddPicture autofit is very slow when cell Merged

### ISSUE THREAD

**Issue by wzhsh90** [qax-os/excelize#1216]
autofit  is very slow, only use x_scale and y_scale.

**Comment by xuri** [comment]
Which versiWhich version of Excelize are you using, how many images have been inserted in your spreadsheet, and how long does time cost? Here are some performance figures for your reference: [Performance Figures](https://github.com/xuri/excelize/wiki#performance-figures).

**Comment by xuri** [comment]
Which version of Excelize are you using, how many images have been inserted in your spreadsheet, and how long does time cost? Here are some performance figures for your reference: [Performance Figures](https://github.com/xuri/excelize/wiki#performance-figures).

**Comment by wzhsh90** [comment]
version: v2.6.0
total data: 1000
time: more then 10 minutes


total row num 7*1000=7000


merge 7 rows and add pic.






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "qax-os/excelize"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年4月30日(星期六) 中午1:05
***@***.***&gt;;
抄送:&nbsp;"@***@***.******@***.***&gt;;
主题:&nbsp;Re: [qax-os/excelize] AddPicture autofit is very slow when cell Merged (Issue #1216)





 
Which version of Excelize are you using, how many images have been inserted in your spreadsheet, and how long does time cost? Here are some performance figures for your reference: Performance Figures.

**Comment by xuri** [comment]
Can you show us a complete, standalone example program or reproducible demo?

**Comment by xuri** [comment]
It seems still not have enough info of code and attachments to reproduce this issue, so I'll close this issue, if you have any questions, please let me know to reopen this anytime.
