### ISSUE TITLE
After update CellHyperLink, GetCellHyperLink won't return the latest link

### ISSUE THREAD

**Issue by CHANTXU64** [qax-os/excelize#1217]
**Description**

After update CellHyperLink, GetCellHyperLink won't return the latest link.

**Steps to reproduce the issue:**

Run:

```go
func TestUpdateHL (t *testing.T) {
  file := excelize.NewFile()
  err := file.SetCellHyperLink("Sheet1", "A1", "https://github.com", "External")
  if err != nil {
    fmt.Println(err)
  }
  err = file.SetCellHyperLink("Sheet1", "A1", "https://baidu.com", "External")
  if err != nil {
    fmt.Println(err)
  }
  _, link, _ := file.GetCellHyperLink("Sheet1", "A1")
  assert.Equal(t, "https://baidu.com", link)
  file.Close()
}
```

**Describe the results you received:**

```text
FAIL
expected: "https://baidu.com"
actual  : "https://github.com"
```

**Output of `go version`:**

```text
go version go1.18.1 linux/amd64
```

**Excelize version or commit ID:**

commit [856ee57](https://github.com/qax-os/excelize/commit/856ee57c4019b4478da0f6cb3010ae636914a6be)

**Environment details (OS, Microsoft Excel™ version, physical, etc.):**
Linux

**Comment by xuri** [comment]
Thanks for your issue, I have fixed it. Please upgrade to the master branch code, and this patch will be released in the next version.
