### ISSUE TITLE
Cell values with underscore surrounded by numbers not able to be read (ex: 123_4567)

### ISSUE THREAD

**Issue by HunterWard** [qax-os/excelize#1219]
**Description**
I'm trying to read in data from an .xlsx and it seems like excelize has a problem reading in cell value data when the data in the cell is in the format of "[NUMBERS]_[NUMBERS]".  I've not been able to find a fix.

**Steps to reproduce the issue:**
The data I'm working with is sensitive so I made a dummy .xlsx which I also attached:
[sample2.xlsx](https://github.com/qax-os/excelize/files/8599936/sample2.xlsx) (A column has no special formatting)
![image](https://user-images.githubusercontent.com/8880686/166167871-54cdb3b6-1dfe-4641-aab9-34d7f819b963.png)
I made the A column show a few different examples of underscores in the cells.

Here is my code:
![image](https://user-images.githubusercontent.com/8880686/166168053-f871f9e9-4616-4a52-a78a-71ab28439f2f.png)

**Describe the results you received:**
![image](https://user-images.githubusercontent.com/8880686/166167941-08ad2b73-3dea-4823-b6f4-98ed8598f677.png)
You can see that it is detecting and reading in the A column just fine except for where there is an underscore surrounded by numbers in the second row (A2).  The results are the same when using GetCellValue().

In the debugger it is just an empty string "".  Here are second and third rows from debugger:
![image](https://user-images.githubusercontent.com/8880686/166168248-4c6cf053-d209-4290-bc4a-6ddf6f8b9c69.png)

**Describe the results you expected:**
I expect a cell with "[NUMBERS_NUMBERS]" (ex 1888_257) to be read into the []string that GetRows()/GetCellValue() returns.

**Output of `go version`:**

```text
go version go1.18.1 windows/amd64
```

**Excelize version or commit ID:**

```text
v2.6.0
```

**Environment details (OS, Microsoft Excel™ version, physical, etc.):**
I'm on windows working specifically with .xlsx format files.

**Comment by HunterWard** [comment]
**Small update:**

As a work around I was trying to use the `RawCellValue: true` option but for some reason that wasn't working either.  In the debugger it looks like the options I set are not being passed to the parsing functions.  Might be another bug?

This is how I'm passing options:
`f, err := excelize.OpenFile("sample2.xlsx", excelize.Options{RawCellValue: true})`

I replaced line 66 in cell.go from:
`val, err := c.getValueFrom(f, f.sharedStringsReader(), parseOptions(opts...).RawCellValue)`
to
`val, err := c.getValueFrom(f, f.sharedStringsReader(), f.options.RawCellValue)`

and line 132 in rows.go from:
`rows.rawCellValue, rows.sst = parseOptions(opts...).RawCellValue, rows.f.sharedStringsReader()`
to
`rows.rawCellValue, rows.sst = rows.f.options.RawCellValue, rows.f.sharedStringsReader()`

I don't know of any unintentional side effects of this change but it works for getting those underscore values to be read:
`[ 2016.1.1 6/16/16 Test Subject This is a sample description some notes John Doe Gift of So and So 2016.1 orig]`
to
`[1888_257 2016.1.1 6/16/16 Test Subject This is a sample description some notes John Doe Gift of So and So 2016.1 orig]`

I'm not familiar enough with the codebase yet to understand what may be going wrong with trying to parse the original values but I'll keep looking.

**Comment by HunterWard** [comment]
So it looks like textHandler() in numfmt.go is the last function where my cells value is present, then the function returns an empty string which ends up being the final value.  I put in a check at the end:
![image](https://user-images.githubusercontent.com/8880686/166181090-27c997cf-e696-4b48-87ec-abda5abd9594.png)
And now returns the correct value and my final output is correct.  Thoughts on this change?

**Comment by xuri** [comment]
Thanks for your issue, I have fixed it. Please upgrade to the master branch code, and this patch will be released in the next version.
