### ISSUE TITLE
使用过程中，部分func占用内存过高，能否优化一下？

### ISSUE THREAD

**Issue by ecioc** [qax-os/excelize#1220]
单个Excel就262个sheet，每个sheet差不多在300*300单元格。
`
(pprof) top
Showing nodes accounting for 998.92MB, 99.15% of 1007.43MB total
Dropped 74 nodes (cum <= 5.04MB)
Showing top 10 nodes out of 37
      flat  flat%   sum%        cum   cum%
  503.05MB 49.93% 49.93%      892MB 88.54%  github.com/xuri/excelize/v2.prepareSheetXML
  359.95MB 35.73% 85.66%   388.95MB 38.61%  github.com/xuri/excelize/v2.fillColumns
   39.03MB  3.87% 89.54%    39.03MB  3.87%  github.com/xuri/excelize/v2.(*File).saveFileList (inline)
   21.50MB  2.13% 91.67%    25.50MB  2.53%  encoding/xml.(*printer).marshalAttr
   18.50MB  1.84% 93.51%    18.50MB  1.84%  github.com/xuri/excelize/v2.ColumnNumberToName
   18.38MB  1.82% 95.33%    18.38MB  1.82%  golang.org/x/net/webdav.(*memFile).Write
      16MB  1.59% 96.92%   985.04MB 97.78%  xxxxxxxxxxxxx
   13.50MB  1.34% 98.26%       29MB  2.88%  github.com/xuri/excelize/v2.CoordinatesToCellName
       9MB  0.89% 99.15%        9MB  0.89%  strconv.formatBits
         0     0% 99.15%    25.50MB  2.53%  encoding/xml.(*Encoder).Encode

`

**Comment by xuri** [comment]
Thanks for your feedback. Please using provided streaming API to generating or reading data from a worksheet with huge amounts of data.

**Comment by xuri** [comment]
Which version of Excelize are you using? Can you show us a complete, standalone example program or reproducible demo? The library has been provided streaming API to generating or reading data from a worksheet with huge amounts of data, please using the stream API if you can, and here are some performance figures for your reference: [Performance Figures](https://github.com/xuri/excelize/wiki#performance-figures).

**Comment by xuri** [comment]
Thanks for your feedback. Which version of Excelize are you using? Can you show us a complete, standalone example program or reproducible demo? The library has been provided streaming API to generating or reading data from a worksheet with huge amounts of data, please using the stream API if you can, and here are some performance figures for your reference: [Performance Figures](https://github.com/xuri/excelize/wiki#performance-figures).

**Comment by xuri** [comment]
It seems still not have enough info of code and attachments to reproduce this issue, so I'll close this issue, if you have any questions, please let me know to reopen this anytime.

**Comment by lovepepsi** [comment]
@ecioc  你好，我们也遇上同样的问题，我们用的版本号是v2.1.0,你们呢？

**Comment by xuri** [comment]
Hi @lovepepsi, please upgrade to the master branch code and using the [rows iterator](https://xuri.me/excelize/zh-hans/sheet.html#Rows) read data as streaming.
