### ISSUE TITLE
function AddComment caused oom when upload a file contains comment 

### ISSUE THREAD

**Issue by cowboysbff** [qax-os/excelize#1222]
version:v2.4.1
some cells contains comment, i want to add comment on other cells, caused oom, the origin file only 70kb

**Comment by xuri** [comment]
Thanks for your feedback. Can you show us a complete, standalone example program or reproducible demo?

**Comment by xuri** [comment]
It seems still not have enough info of code and attachments to reproduce this issue, so I'll close this issue, if you have any questions, please let me know to reopen this anytime.
