### ISSUE TITLE
Set picture scale

### ISSUE THREAD

**Issue by CHANTXU64** [qax-os/excelize#1224]
**Description**

Incorrect picture scale.

**Steps to reproduce the issue:**
1. download https://git-scm.com/images/logo@2x.png to git.png
2. run:
```go
f := excelize.NewFile()
f.AddPicture("Sheet1", "A1", "git.png", `{"x_scale": 0.33, "y_scale": 0.33}`)
f.SaveAs("gitlogo.xlsx")
```

**Describe the results you received:**

in wps:  
scale height: 31%  
scale width: 36%

**Describe the results you expected:**

in wps:  
scale height: 33%  
scale width: 33%

**Output of `go version`:**

```text
go version go1.18.1 linux/amd64
```

**Excelize version or commit ID:**

```text
eed431e
```

**Environment details (OS, Microsoft Excel™ version, physical, etc.):**
Linux x86_64, wps-office-cn 11.1.0.10976-2

**Comment by xuri** [comment]
This issue is duplicate with #248 and #212.

**Comment by xuri** [comment]
I will close this issue and move discuss on #248.
