### ISSUE TITLE
SetColDefault() and SetRowDefault()

### ISSUE THREAD

**Issue by Chamberlia** [qax-os/excelize#1226]
**Description**
there will be more convenient for users to have function SetColDefault() and SetRowDefault().
please ,thanks !

**Steps to reproduce the issue:**
1.
2.
3.

**Describe the results you received:**

**Describe the results you expected:**

**Output of `go version`:**

```text
(paste your output here)
```

**Excelize version or commit ID:**

```text
(paste here)
```

**Environment details (OS, Microsoft Excel™ version, physical, etc.):**

**Comment by xuri** [comment]
Thanks for your issue. Due to the principle of minimum availability, I didn't suggest introducing this feature to keep the library core and easy. I'll close this issue. If you have any questions, please let me know.
