### ISSUE TITLE
style property "lang" with number format

### ISSUE THREAD

**Issue by tashaX** [qax-os/excelize#1227]
Is there a way, currently, to set a custom number format like "#.##0,00" (dots and commas reversed form the en-US style ) 
So With a style like: 
```
f := "#.##0,00"
style := excelize.Style{
    CustomNumFmt: &f,
    Lang: "hr-HR"	
}
```
the cell still gets formatted with the default locale instead of the specified one and also setting decimal places works only if I'm not trying to set a number format different than the default locale supports.

In anyway, great library, helped a lot. :)

I would just like to know if this is even supported or am I doing something wrong

**Comment by xuri** [comment]
Thanks for your issue. Thanks for your issue. There are four categories of number format related to language and region settings: Accounting, Date, Time, and Special, what's the number in your set, and what's your expected?

**Comment by tashaX** [comment]
Sorry, I forgot to specify, I meant for Accounting I think.
 I would expect that a number like 10000,00 in "en-US" locale would be formatted as 10,000.00 (which works great, that's a 4 number format if I am not mistaken), but I would also expect that in a "hr-HR" the number would be formatted as 10.000,00 (that is the format used in most of the European countries, decimal is separated by a comma instead of a dot)

**Comment by xuri** [comment]
Please try to using this custom number format code:

```go
fmtCode := `_-* #,##0.00\ _€_-;\-* #,##0.00\ _€_-;_-* "-"??\ _€_-;_-@_-`
style := excelize.Style{
    CustomNumFmt: &fmtCode,
}
```

**Comment by tashaX** [comment]
`_-* #,##0.00\ _€_-;\-* #,##0.00\ _€_-;_-* "-"??\ _€_-;_-@_-` is English euro format, what I need is something like this: 

```
fmtCode :=  `_-* #.##0,00_€_-;-* #.##0,00 _€_-;_-* "-"??_€_-;_-@_-`
```

so that "," is used instead of "." for decimal places, but this format does not work. I don't think the problem is in the number format but in the language option that stays the same as the default.

tnx anyway, I'll make something up

**Comment by xuri** [comment]
You also need to change operation system settings to the Europe regions, before opening the spreadsheet which generated with this format code.

**Comment by tashaX** [comment]
I am aware of that, but I thought that the Lang option inside Style can set language dynamically like: 

```
style := excelize.Style{
    Lang: "de-DE"	
}

```
or something similar, but really never mind, this will do :)
Thank you for answering, I will close this issue if you don't mind
