### ISSUE TITLE
ErrMaxFileNameLength is file path length?

### ISSUE THREAD

**Issue by sceneq** [qax-os/excelize#1229]
https://github.com/qax-os/excelize/blob/ecbc6e2fde1941cb5ac9e5f3bfce329e7bfa8825/file.go#L69-L71

Is the correct code like this?
```go
	if len(filepath.Base(name)) > MaxFileNameLength {
		return ErrMaxFileNameLength
	}
```

**Comment by xuri** [comment]
Thanks for the issue. It should be `ErrMaxFilePathLength`. We need rename exported constant `MaxFileNameLength` to `MaxFilePathLength `and update the error message, and also welcome to contribute to fixing these mistakes.

**Comment by sceneq** [comment]
@xuri

https://en.wikipedia.org/wiki/ISO_9660
>the maximum file name length to 207 characters
>the path length of any file must not exceed 255.

It seems that file name are limited to 207 characters and file path are limited to 255

**Comment by xuri** [comment]
The file name or file path are both limited to 207 characters in Windows Office, so I suggest select the shorter one as the limit.

**Comment by xuri** [comment]
The file name length is limited to 207 in Excel for Mac, and the file path is limited to 218 in Windows Excel, so I suggest using the shorter one as the limit.
