### ISSUE TITLE
Is SetCellValue in v2.6.0 slower than v2.5.0?

### ISSUE THREAD

**Issue by TawsifKarim** [qax-os/excelize#1231]
I have upgraded from v2.5.0 to v2.6.0 on one of my go (v1.17) application. 
for 150k row with around 35 column excel file writing like below,  it was taking around 9.5 sec avg. on my machine.

```
for i := 0; i < len(rows); i++ {
	pos := fmt.Sprintf("%v", i+2)
       f.SetCellValue("Sheet1", "A"+pos, rows[i].ID)
       ......
       ......
}
```
after upgrading to v2.6.0 exact same amount of rows, its taking around 8-9 min(!) 
So I downgraded to v2.5.0. 
Is there anything that should be taken care of?

**Comment by xuri** [comment]
Yes, according to the benchmark report of v2.6.0, a fix for #1129 (commit: [`156bf6d`](https://github.com/xuri/excelize/tree/156bf6d16ecbd5257d81e781138eaaaf357ffbec)) slows down the set sheet row and the merging cell about 400 times. I fixed the performance impact when resolving that issue on commit [`eed431e`](https://github.com/xuri/excelize/tree/eed431e0fc2f61b13e7745857a41cb47d9f7f810). Please try to upgrade to the master branch code, and this patch will be released in the next version.
