### ISSUE TITLE
无法打开excel文件，错误：[] decrypted file failed

### ISSUE THREAD

**Issue by serialt** [qax-os/excelize#1237]
同事从钉钉上导出的人员信息表，打开的时候显示：[] decrypted file failed，wps是可以正常打开的。试过了2.6.0和2.5.0都是一样的报错，用wsp新建一个表格，把数据复制进去，excelize打开这个新的是正常的。
```
package main

import (
	"fmt"

	"github.com/xuri/excelize/v2"
)

func main() {

	fmt.Println(PasreExcel("/Users/serialt/Downloads/20220513_exmail.xls"))
}

func PasreExcel(filepath string) (data [][]string, err error) {

	file, err := excelize.OpenFile(filepath)
	if err != nil {
		return
	}
	defer file.Close()

	rows, err := file.GetRows("Sheet1")
	if err != nil {
		return
	}

	data = rows
	return
}
```

[20220513_exmail.xls](https://github.com/qax-os/excelize/files/8790636/20220513_exmail.xls)

**Comment by xuri** [comment]
This issue duplicate with, #207, #821 and #881. Note that this library doesn't support the legacy XLS file format.
