### ISSUE TITLE
Overwrite Cell Values

### ISSUE THREAD

**Issue by Cheetah-whiteflash** [qax-os/excelize#1238]
**Description**

**Steps to reproduce the issue:**
1.
2.
3.

**Describe the results you received:**
SetCellValue cannot overwrite cells if already have values. Meanwhile, there is no clean cell content function.
**Describe the results you expected:**

**Output of `go version`:**

```text
(paste your output here)
```

**Excelize version or commit ID:**

```text
2.6.0
```

**Environment details (OS, Microsoft Excel™ version, physical, etc.):**

**Comment by xuri** [comment]
Thanks for your issue. Could you show us a complete, standalone example program or reproducible demo?  You can clean cell content by call SetCellValue with nil value.

**Comment by xuri** [comment]
It seems still not have enough info of code and attachments to reproduce this issue, so I'll close this issue, if you have any questions, please let me know to reopen this anytime.
