### ISSUE TITLE
Ability to save a file as .xls

### ISSUE THREAD

**Issue by clauderoy790** [qax-os/excelize#1239]
It would be awesome to have the ability to save a file as an .xls as well.
When I try to do so, I'm getting the following error: unsupported workbook extension

`	exportPath := "/Users/clauderoy/Desktop/test.xls"`
	`f = excelize.NewFile()`
	`if err := f.SaveAs(exportPath); err != nil {`
		`.   panic(fmt.Errorf("failed to write file: %w", err))`
	`}`
Go version 1.18.2jj
github.com/xuri/excelize/v2 v2.6.0
Mac OS Monterey 12.3.1

**Comment by xuri** [comment]
Thanks for your feedback. This issue duplicate with #44, #264 and #368.

**Comment by xuri** [comment]
I'll close this issue, if you have any questions, please let me know to reopen this anytime.
