### ISSUE TITLE
Is any function read excel row to key-value style(golang map or truct)?

### ISSUE THREAD

**Issue by neo502721** [qax-os/excelize#1241]
excel:
姓名 | 证件号码 | 联系电话
-- | -- | --
13 | 33333 | 3333
14 | 33334 | 3334

return value:
map[姓名:13 证件号码:3333 联系电话: 3333]
map[姓名:13 证件号码:3333 联系电话: 3333]

**Comment by xuri** [comment]
Thanks for your issue. You need to transform the 2D array returns of GetRows into any custom data structures by yourselves.

**Comment by neo502721** [comment]
Thanks for your help.
