### ISSUE TITLE
Position properties for AddShape to avoid re-sizing with cells

### ISSUE THREAD

**Issue by petestonefire** [qax-os/excelize#1242]
Hi,

I am missing (or can't find) how to set the property to disallow a shape (rect used as text box in particular) to re-size together with cell resizing. I found that there is such setting for a chart (Positioning: absolute), but seems to be missing for a shape.

Using:
go 1.18
github.com/xuri/excelize/v2 v2.6.0

Thanks for an awesome Excel library

**Comment by xuri** [comment]
I'll close this issue, if you have any questions, please let me know to reopen this anytime.
