### ISSUE TITLE
Hyperlink in the new sheet, not available in google drive

### ISSUE THREAD

**Issue by cvzm** [qax-os/excelize#1244]
**Description**
Creating a hyperlink in the default sheet1 and uploading it to google drive works normally, but the hyperlink of the new sheet cannot be used.

**Steps to reproduce the issue:**
``` golang
file := excelize.NewFile()
sheet = "Sheet2"
file.NewSheet(sheet)
file.SetCellValue(sheet, "A1", "test link")
file.SetCellHyperLink(sheet, "A1", "https://google.com", "External") 
file.SaveAs("test.xlsx")
```

**Describe the results you received:**
Hyperlinks in Sheet2, are not recognized in google.
But local can work normally

**Describe the results you expected:**
It is hoped that hyperlinks can be identified normally in google drive.

In addition, I found a solution in disguise, using CopySheet(). 
new sheet copied through sheet1 can work properly in google.

**Output of `go version`:**

```text
go version go1.16.6 darwin/amd64
```

**Excelize version or commit ID:**

```text
version 2.6.0
```

**Environment details (OS, Microsoft Excel™ version, physical, etc.):**
MacOS:  WPS, Google Drive

**Comment by xuri** [comment]
Thanks for your issue. Google Sheets currently have a compatibility issue currently with the XML namespace which contains relationships in markup compatibility ignorable: `mc:Ignorable="r"`.

**Comment by xuri** [comment]
Thanks for your issue. Google Sheets currently have a compatibility issue currently with the XML namespace which contains relationships in markup compatibility ignorable: `mc:Ignorable="r"`, it can be skip at the internal function [`addNameSpaces`](https://github.com/qax-os/excelize/blob/ecbc6e2fde1941cb5ac9e5f3bfce329e7bfa8825/lib.go#L650-L683), but I don't suggest made change for this currently for it maybe cause unstable compatibility impact.

**Comment by xuri** [comment]
This issue has been fixed, please upgrade to the master branch code, and this patch will be released in the next version.
