### ISSUE TITLE
SetCellFormula

### ISSUE THREAD

**Issue by Valeria1807** [qax-os/excelize#1246]
Hello I wanted to tell you that I'm having problems with the setCellFormula, where I pass as a formula the SUBTOTAL but it does not go

```
func main() {

	f := excelize.NewFile()

	f.SetCellValue("Sheet1", "A1", "ID")
	f.SetCellValue("Sheet1", "B1", "Nome")
	f.SetCellValue("Sheet1", "D1", "Cognome")
	f.SetCellValue("Sheet1", "C1", "Email")
	f.SetCellValue("Sheet1", "D1", "IDENTITY_CARD_EXPIRE_DATE")
	f.SetCellValue("Sheet1", "E1", "TOTAL")

	f.SetCellValue("Sheet1", "E2", "1")
	f.SetCellValue("Sheet1", "E3", "5")
	f.SetCellValue("Sheet1", "E4", "10")

	//formula
	f.SetCellFormula("Sheet1", "E6", `=SUBTOTAL(9,E2:E4)`)
	//f.SetCellFormula("Sheet1", "E6", `=SUM(E2:E4)`)

	f.SetColWidth("Sheet1", "A", "D", 30)
	if err := f.SaveAs("Prova.xlsx"); err != nil {
		log.Fatal(err)
	}
}


I pasted you a small piece of code just to try, maybe I'm wrong something 
Ps the library is wonderful compliments!
```

**Comment by xuri** [comment]
Thanks for your issue, please set the numeric instead of text on the E2:E4 range cells. For example, using `f.SetCellValue("Sheet1", "E2", 1)` instead of `f.SetCellValue("Sheet1", "E2", "1")`.

**Comment by Valeria1807** [comment]
thank you very much for responding right away. I wish you a good day
PS now it’s working!

Inviato da Posta<https://go.microsoft.com/fwlink/?LinkId=550986> per Windows

Da: ***@***.***>
Inviato: giovedì 9 giugno 2022 13:23
A: ***@***.***>
Cc: ***@***.***>; ***@***.***>
Oggetto: Re: [qax-os/excelize] SetCellFormula (Issue #1246)


Thanks for your issue, please set the numeric instead of text on the E2:E4 range cells. For example, using f.SetCellValue("Sheet1", "E2", 1) instead of f.SetCellValue("Sheet1", "E2", "1").
