### ISSUE TITLE
SetSheetCol feature

### ISSUE THREAD

**Issue by stanleyyzhu** [qax-os/excelize#1247]
**How about adding a new method "SetSheetCol"**

I do see "func (f *File) SetSheetRow(sheet, axis string, slice interface{}) error {}" in the latest release but I can't find the similar method for Col. 

Shall we add a method for setting up sheet col values? It could be really similar as "SetSheetRow"

```
func (f *File) SetSheetCol(sheet, axis string, slice interface{}) error {
	col, row, err := CellNameToCoordinates(axis)
	if err != nil {
		return err
	}

	// Make sure 'slice' is a Ptr to Slice
	v := reflect.ValueOf(slice)
	if v.Kind() != reflect.Ptr || v.Elem().Kind() != reflect.Slice {
		return errors.New("pointer to slice expected")
	}
	v = v.Elem()

	for i := 0; i < v.Len(); i++ {
		cell, err := CoordinatesToCellName(col, row+i)
		// Error should never happens here. But keep checking to early detect regresions
		// if it will be introduced in future.
		if err != nil {
			return err
		}
		if err := f.SetCellValue(sheet, cell, v.Index(i).Interface()); err != nil {
			return err
		}
	}
	return err
}
```

**Comment by xuri** [comment]
Thanks for your issue. To add this feature, we need to create the common function to check cell reference and value reflection for `SetSheetCol` and `SetSheetRow`, which can be made code simple and clean.

**Comment by stanleyyzhu** [comment]
Thank you xuri
