### ISSUE TITLE
Make OpenFile function also accept url address, instead of path only

### ISSUE THREAD

**Issue by ahah43** [qax-os/excelize#1249]
**Description**
Make OpenFile function also accept url address, instead of path only.

It is pretty simple, but yet very useful.
**OpenFile** is to check the **file name** and decide if it is a url or not. If it is a url, then the file is loaded using http/get, else, it would be a normal path.

**OpenFile function would be modified as follows:**

func OpenFile(filename string, opt ...Options) (*File, error) {
	////////////////////////////////////////////////////////////////// 
	var err error							
	var file io.ReadCloser						
	if isValidUrl(filename){					
		resp, err := http.Get(filename)				
		if err != nil {return nil, err}				
		file = resp.Body					
		} else{ 						
			file, err = os.Open(filepath.Clean(filename))	
            if err != nil {return nil, err}				
	    	}							
	//////////////////////////////////////////////////////////////////
	f, err := OpenReader(file, opt...)
	if err != nil {
		closeErr := file.Close()
		if closeErr == nil {
			return f, err
		}
		return f, closeErr
	}
	f.Path = filename
	return f, file.Close()
}

**isValidUrl function has to be added to the excelize.go**
Source of **isValidUrl** function is found at the following url: https://golangcode.com/how-to-check-if-a-string-is-a-url/

func isValidUrl(toTest string) bool {
	_, err := url.ParseRequestURI(toTest)
	if err != nil {return false}
	u, err := url.Parse(toTest)
	if err != nil || u.Scheme == "" || u.Host == "" {return false}
	return true
}

**Lastly, the following libraries must be imported:**
"net/url"     // to be used in the **isValidUrl** function
"net/http"  // **http.Get** is to be used in the modified **OpenFile** function

**Comment by xuri** [comment]
Thanks for your issue. As per the comments I left in #1248, The developer can fetch the file and open it by [`OpenReader`](https://xuri.me/excelize/en/workbook.html#OpenReader) function. Fetch, or receiving files from the network by HTTP or other protocols was not in the scope of this library. I'll close this issue. If you have questions please let me know and reopen this anytime.
