### ISSUE TITLE
Almost 2000 of empty rows in iterator parsing

### ISSUE THREAD

**Issue by renta** [qax-os/excelize#1251]
**Description**

**Steps to reproduce the issue:**
1. Run the code from the https://github.com/renta/excelize_empty_rows

**Describe the results you received:**
A row with a header information, 20 lines with content and 1980 empty lines.

**Describe the results you expected:**
Only header and filled rows.

**Output of `go version`:**

go version go1.17.11 linux/amd64

```text
I saw a strange behavior on parsing a file: with an iterator a got 21 line with content (header and rows)
and 1980 empty rows. There were no such troubles without the iterator  with `GetRows` method, 
but I do not want to use it because of unpredictable size of files that my service could get. 

My questions are:
 - what is a limit for empty content after which iterator will stop?
 - are there any workaround to reduce this limit in a client code (like "stop after the 3-rd empty line")?
 - why there are no such problems with `GetRows` method?
 
I understand that I can easily create this behavior by counting the empty rows and breaking the iteration 
after the second empty line (for ex.) but maybe there are Excelize way to do it?  
```

**Excelize version or commit ID:**

```text
v2.6.0
```

**Environment details (OS, Microsoft Excel™ version, physical, etc.):**
```text
Linux, Libre Office Version: 6.4.7.2
```

**Comment by xuri** [comment]
Thanks for your issue. The `Rows` function fetches the worksheet data as a stream and returns each row as is. If you want to skip empty rows in the tail of the worksheet, please use the `GetRows` function.

**Comment by renta** [comment]
@xuri The problem with `GetRows` and huge files that this method will put all the data in the memory which is very dangerous for unlimited size uploads. I suppose that the approach with counting empty rows and stopping the iterator on some limit will solve the problem.

**Comment by xuri** [comment]
Could you define a variable to flag the latest no-empty row's number, and check the length of the row before assigning it to this variable. After iteration of all of the rows in a worksheet, you will get it.

**Comment by xuri** [comment]
I have updated documentation of the [Columns](https://github.com/qax-os/excelize/blob/301f7bc21755cdf7c91c9acd50ddcdcf0285f779/rows.go#L125-L168) function and added a notice about this behavior. I'll close this issue, if you have any questions, please let me know to reopen this anytime.
