### ISSUE TITLE
SetColWidth report bug: panic: runtime error: invalid memory address or nil pointer dereference     

### ISSUE THREAD

**Issue by 20160920** [qax-os/excelize#1256]
**Description**
Hi, I suddenly encountered this bug today when using excelize.openFile.I didn't make any changes to the code, but all of a sudden this problem appears, which was normal a few days ago.

**Steps to reproduce the issue:**
1.     f, _ := excelize.OpenFile("data_output2.xlsx")
	defer f.Close()
	sheetName := "Sheet" + strconv.Itoa(times)
        sheetWords := []string{
		"A", "B", "C", "D", "E", "F", "G", "H", "I", "J",
	}
2.    f.SetColWidth(sheetName, "A", sheetWords[len(sheetWords)-1], 18)

**report:**

```text
panic: runtime error: invalid memory address or nil pointer dereference                
        panic: runtime error: invalid memory address or nil pointer dereference        
[signal 0xc0000005 code=0x0 addr=0xd0 pc=0xd87c5a]                                     
                                                                                       
goroutine 1 [running]:                                                                 
github.com/xuri/excelize/v2.(*File).Close(0x0?)                                        
        C:/Users/qihuang/go/pkg/mod/github.com/xuri/excelize/v2@v2.6.0/file.go:99 +0x1a
panic({0xe9ce20, 0x1a9f950})                                                           
        C:/Program Files/Go/src/runtime/panic.go:838 +0x207
github.com/xuri/excelize/v2.(*File).workSheetReader(0x0, {0xc00049be00, 0x6})
        C:/Users/qihuang/go/pkg/mod/github.com/xuri/excelize/v2@v2.6.0/excelize.go:224 +0x71
github.com/xuri/excelize/v2.(*File).SetColWidth(0x11b5f00?, {0xc00049be00, 0x6}, {0xfeee5d?, 0x1?}, {0xfeef64, 0x2}, 0x4032000000000000)

```

**Comment by xuri** [comment]
Thanks for your feedback, please show us a complete, standalone example program or reproducible demo, and provide your input file attachment without confidential info if you can.

**Comment by xuri** [comment]
Please receive and check the error returned by OpenFile at first, do not ignore errors, for make sure the `data_output2.xlsx` file is a valid spreadsheet.

**Comment by 20160920** [comment]
Thank you！After confirmation, the previous relative path is unavailable.Now we're done
