### ISSUE TITLE
Saving excel file makes it corrupt

### ISSUE THREAD

**Issue by admeen-vs** [qax-os/excelize#1257]
Description of task
Here is the task that I need to solve: open an excel document template that contains comments and formulas; insert the new values into the places where the comments are (function used to change the values: SetCellValue); save the excel document under a new path and new name

As result
After opening the saved file an error occurs that the file is corrupted

go version:
go version go1.18.1 windows/amd64

exelize version:
github.com/xuri/excelize/v2 v2.6.0

excel version
Microsoft® Excel® LTSC MSO (16.0.14332.20296) 64-bit 

win version
Windows 11 Pro 21H2 build 22000.675

excel template file in attachment
[Z.xlsx](https://github.com/qax-os/excelize/files/8942294/Z.xlsx)

**Comment by xuri** [comment]
Thanks for your issue. I have fixed it, please upgrade to the master branch code, and this patch will be released in the next version. Note that the source spreadsheet `Z.xlsx` can't open on Excel 2007.

**Comment by admeen-vs** [comment]
thank you very much

**Comment by AhmedX6** [comment]
@xuri I'm facing same issue.. opening an xlsx file and write on it some cell value then save makes it corrupt I'm on master branch up to date.. what's happening?

**Comment by xuri** [comment]
@AhmedX6 Thanks for your feedback. Could you provide your input file attachment without confidential info?

**Comment by AhmedX6** [comment]
[input.xlsx](https://github.com/qax-os/excelize/files/9705071/input.xlsx)

**Comment by xuri** [comment]
Hi @AhmedX6, I have tested based on the Excelize v2.6.1 and master branch code with your attachment, and it works well on Office 2007 and Excelize for Mac 16.65. Which Excel version are you using? Can you show us a complete, standalone example program or reproducible demo?

**Comment by AhmedX6** [comment]
I'm using : `Microsoft® Excel® for Microsoft 365 MSO (Version 2209 Build 16.0.15629.20152) 64-bit `
I think I'm on 2020+ or 2018+ but not less...

**Comment by xuri** [comment]
I have just test on Excel 2021 16.0.15629.20156 and it work well. Do you make sure using the master branch code? Can you show us a complete, standalone example program or reproducible demo?

**Comment by AhmedX6** [comment]
![image](https://user-images.githubusercontent.com/13573148/193876903-86854129-ee1a-4753-b966-5174a7f73c92.png)
I don't understand... It started to work now... when I retried.... omg
