### ISSUE TITLE
 file corrupt if multiple table in a Sheet

### ISSUE THREAD

**Issue by bunnycodego** [qax-os/excelize#1259]
**Description**

**Steps to reproduce the issue:**
1. 循环来处理2个excel文件, 每个excel文件里面的两个sheets,里面的数据需要增加table
2.在循环里调用AddTable方法,一共调用了两次,给两个不同的excel文件的sheets加tables
3. for _, eachExcel := range excels {
              ...
              if err := editExcel.AddTable(eachExcelStruct.SummaryFile, vCellCounts1, "Sheet1"); err != nil {
			log.Println(err)
		}
              ...
             if err := editExcel.AddTable(eachExcelStruct.SummaryFile, vCellCount2, "Sheet2"); err != nil {
			log.Println(err)
		}
6. }

**Describe the results you received:**
可以生成文件,golang没有报错
但是当打开生成的excel文件时会提示警告,请看附件照片

**Describe the results you expected:**
不报警告错误
**Output of `go version`:**
go version go1.18.3 darwin/amd64

![alert](https://user-images.githubusercontent.com/81451316/175401533-9495a199-0a5a-4b85-b89a-3c4722b1c307.png)

```text
没有报错
```

**Excelize version or commit ID:**
excelize/v2 v2.6.0
```text
(paste here)
```

**Environment details (OS, Microsoft Excel™ version, physical, etc.):**
Excel for Mac Version 16.63

**Comment by xuri** [comment]
Thanks for you issue. Can you show us a complete, standalone example program or reproducible demo?

**Comment by bunnycodego** [comment]
Hi Xuri,
It just occurred to me that on one of the sheets, there was a header cell named "Invoice Number" and another header cell also named "INVOICE NUMBER", but in all capitals. This is against the rule that header cells must be unique. I think the issue can probably be closed, thank you!
