### ISSUE TITLE
constant overflows int when compiling for linux

### ISSUE THREAD

**Issue by pancakestack-io** [qax-os/excelize#1260]
**Description**
When trying to compile a linux binary from my mac using the latest version of master branch. I get a an error with 2 sets of numbers:
../../pkg/mod/github.com/xuri/excelize/v2@v2.6.1-0.20220623170319-2e1b0efadc05/crypt.go:1229:22: constant 3759263696 overflows int
../../pkg/mod/github.com/xuri/excelize/v2@v2.6.1-0.20220623170319-2e1b0efadc05/crypt.go:1230:22: constant 3776623009 overflows int

when compiling for mac it is fine

**Steps to reproduce the issue:**
1. go get github.com/xuri/excelize/v2@master 
2.  GOOS=linux GOARCH=386 CGO_ENABLED=0 go build -o XXX
3.

**Describe the results you received:**
../../pkg/mod/github.com/xuri/excelize/v2@v2.6.1-0.20220623170319-2e1b0efadc05/crypt.go:1229:22: constant 3759263696 overflows int
../../pkg/mod/github.com/xuri/excelize/v2@v2.6.1-0.20220623170319-2e1b0efadc05/crypt.go:1230:22: constant 3776623009 overflows int

**Describe the results you expected:**
just to be compilied

**Output of `go version`:**

```text
go version go1.16.3 darwin/amd64

```

**Excelize version or commit ID:**

```text
v2.6.1-0.20220623170319-2e1b0efadc05
```

**Environment details (OS, Microsoft Excel™ version, physical, etc.):**
Mac OS Big Sur, M1 chip

**Comment by xuri** [comment]
Thanks for your issue. I have fixed it, please upgrade to the master branch code.

**Comment by pancakestack-io** [comment]
thanks so much for resolving the issue so quickly!
