### ISSUE TITLE
File Corrupt (Zero byte) when executing in Linux

### ISSUE THREAD

**Issue by pancakestack-io** [qax-os/excelize#1261]
**Description**
When running the code in Linux, the xlsx file which is created, has 0 bytes and when attempting to open in excel or google sheets gives:
_Excel cannot open the file ’Test.xlsx’ because the file format or file extension is not valid. Verify that the file has not been corrupted and that the file extension matches the format of the file._

if i run the same code in mac, the file comes out perfectly fine and works.

**Steps to reproduce the issue:**
1. GOOS=linux GOARCH=386 CGO_ENABLED=0 go build -o XXX
2. try and open the xlsx file, by scp'ing it back to Mac/Windows or opening on google sheets
3.

**Describe the results you received:**
The excel file was 0 bytes large and got an error message of corruption when trying to open

**Describe the results you expected:**
have data in the file and not be corrupt.

**Output of `go version`:**

```text
go version go1.16.3 darwin/amd64
```

**Excelize version or commit ID:**

```text
v2.6.1-0.20220627130059-301f7bc21755
```

**Environment details (OS, Microsoft Excel™ version, physical, etc.):**
Linux DISTRIB_DESCRIPTION="Ubuntu 18.04.6 LTS" for execution
Mac, Big Sur M1 for compiling

**Comment by xuri** [comment]
Thanks for your feedback, any error on your saving the file? Can you show us a complete, standalone example program or reproducible demo?

**Comment by pancakestack-io** [comment]
Hi @xuri 

I want to thank you for being so prompt and getting to all the issues very quickly. one of the best maintained repo's i have seen. so thank you.

this is where the embarrassing part comes from me. unfortunately my EC2 instance was out of disk space. which was causing the corrupted / 0 byte files.

once i expanded the drive, it all worked as expected.

Thanks!
