### ISSUE TITLE
 formula calc doesn't work if cell refers to another formula cell

### ISSUE THREAD

**Issue by devloppper** [qax-os/excelize#1262]
**Code**
```go
workBook := excelize.NewFile()
	_ = workBook.NewSheet("test")
	_ = workBook.SetCellValue("test", "G6", 2)
	_ = workBook.SetCellValue("test", "H6", 3)
	_ = workBook.SetCellValue("test", "K8", 2022)
	_ = workBook.SetCellFormula("test", "I7", "=LEFT(K8, 2)")
	_ = workBook.SetCellFormula("test", "I6", "=IFERROR(I7,H6)")
	_, _ = workBook.CalcCellValue("test", "I7")
	value, err := workBook.CalcCellValue("test", "I6")
	if err != nil {
		panic(err)
	}
```
the value will be 20 in excel but  it is an empty value

**Comment by xuri** [comment]
Thanks for your issue. This library doesn't support calculating formulas for dependence formulas currently. The feature of formula engine is working in progress.

**Comment by xuri** [comment]
Hi @devloppper, I have added support for dependence formulas calculation, please upgrade to the master branch code, and this feature will be released next version.
