### ISSUE TITLE
Value of a cell is changed to a floating point number if it contains only numerical values

### ISSUE THREAD

**Issue by qburst-salax** [qax-os/excelize#1275]
**Description**

**Steps to reproduce the issue:**
1. Create a excel file with a value "8_08_78_08_76" inside a cell.
2. Read the excel file with this package.
3. Print the cell value read by the package.

**Describe the results you received:**
"808780876"

**Describe the results you expected:**
"8_08_78_08_76"

**Output of `go version`:**
go 1.17

**Excelize version or commit ID:**
v2.5.0

**Environment details (OS, Microsoft Excel™ version, physical, etc.):**
Ubuntu 20.04.4 LTS

**Comment by xuri** [comment]
Thanks for your feedback. This issue has been fixed in [v2.6.0](https://xuri.me/excelize/en/releases/v2.6.0.html), please update to the lasted version or using the master branch code.

**Comment by xuri** [comment]
I have tested and it works well, could you provide the file attachment without confidential info?

**Comment by qburst-salax** [comment]
[/home/qbuser/Desktop/UploadPhotos_ABC1234 (1)/UploadPhotos_ABC1234/UploadPhotos_template.xlsx](url)

**Comment by xuri** [comment]
Thanks for your feedback, this issue was duplicate with #1219, I have fixed it, please upgrade to the master branch code, and this patch will be released in the next version.

**Comment by qburst-salax** [comment]
Ok, will do that. Thank You!
