### ISSUE TITLE
非常需要excel 转pdf 的功能，能不能增加一下？^_^

### ISSUE THREAD

**Issue by yhyf** [qax-os/excelize#1277]
**Description**

**Steps to reproduce the issue:**
1.
2.
3.

**Describe the results you received:**

**Describe the results you expected:**

**Output of `go version`:**

```text
(paste your output here)
```

**Excelize version or commit ID:**

```text
(paste here)
```

**Environment details (OS, Microsoft Excel™ version, physical, etc.):**

**Comment by xuri** [comment]
This feature was not in the scope of this library, so there is no plan to add PDF format support for this library.

**Comment by xuri** [comment]
Sorry, this feature was not in the scope of this library, so there is no plan to add PDF format support for this library.
