### ISSUE TITLE
tabColor: support options other than RGB

### ISSUE THREAD

**Issue by thomascharbonnel** [qax-os/excelize#1283]
**Description**

Related to #785. I've noticed the tab color feature only supports RGB (read and write) currently. Do you think it would be okay to add support for the other types of tab colors (eg. "theme", "indexed")? I should be able to pick up this task (and the other one we discussed earlier) in the coming few weeks.

**Comment by xuri** [comment]
Thanks for your issue. Contributions are welcome. I think we need to make following works for this feature:

- Add new options `TabColorIndexed`, `TabColorTheme`, `TabColorTint` for the `SheetPrOption`
- Implement setter and getter for these options
- Add unit test for this feature

**Comment by thomascharbonnel** [comment]
Thanks for the help!
I've written some code to support TabColorTheme first, does this change make sense? https://github.com/thomascharbonnel/excelize/commit/2e9ea923188bb71e226776a11e96d491fe0c7c81
I'm not sure what to do when `theme` is unset, as Golang's default int value of 0 is a valid theme value. I've chosen -1 to indicate that theme is unset. What do you think?

**Comment by xuri** [comment]
Okay, I agree with you.

**Comment by thomascharbonnel** [comment]
Thank you for the feedback, i'll keep working on this next week.
I think i'll make the theme an enum (list of possible values: https://docs.microsoft.com/en-us/dotnet/api/documentformat.openxml.drawing.colorscheme?view=openxml-2.8.1), this way `-1` will be a little bit cleaner rather than a magic number.
One strange thing is that Excel does not seem to follow the spec: https://stackoverflow.com/a/2761369

**Comment by xuri** [comment]
Okay, make the `TabColorTheme` accept theme enumeration, and returns the theme index as is. In Excel the first four theme color index was different with spec. We need to make a patch for it when getting the theme-based color. For example: [get the cell background color](https://xuri.me/excelize/en/utils.html#ThemeColor).
