### ISSUE TITLE
get empty string when the value is INF of field

### ISSUE THREAD

**Issue by LooJee** [qax-os/excelize#1287]
**Description**
If the value of the field is "INF", the program returns "" both when GetCellValue and GetRows.

debug info :
![image](https://user-images.githubusercontent.com/13059033/180959221-e40fb6af-4b2f-4d10-b771-dc37bfd2db47.png)

value in excel :
<img width="309" alt="image" src="https://user-images.githubusercontent.com/13059033/180960152-1c14cc26-c0de-456d-861f-12710af8eec7.png">

**Describe the results you received:**
empty string ""
**Describe the results you expected:**
as string : INF
**Output of `go version`:**

```text
go version go1.18.4 darwin/arm64
```

**Excelize version or commit ID:**

```text
github.com/xuri/excelize/v2 v2.6.0
```

**Comment by LooJee** [comment]
it's ok when i use `github.com/xuri/excelize/v2 v2.5.0`

**Comment by xuri** [comment]
Thanks for your issue. Could you provide your input file attachment without confidential info?

**Comment by LooJee** [comment]
[INF_example.xlsx](https://github.com/qax-os/excelize/files/9190090/INF_example.xlsx)

here is an example

```go
func ParseQuestions(data string)  error {
	xlsx, err := excelize.OpenReader(strings.NewReader(data))
	if err != nil {
		return errors.Wrap(err, "open xlsx failed")
	}

	rows, err := xlsx.GetRows(streamWriterName)
	if err != nil {
		return  errors.Wrap(err, "get xlsx rows failed")
	}

	fmt.Println(rows)

	return  nil
}
```

**Comment by xuri** [comment]
Thanks for your feedback, this issue was duplicate with #1275 and #1219, I have fixed it, please upgrade to the master branch code, and this patch will be released in the next version.
