### ISSUE TITLE
Can I make smoothing disable at line chart?

### ISSUE THREAD

**Issue by tetsuyanh** [qax-os/excelize#1290]
I want to do it.
Why is it enable by default?

**Comment by tetsuyanh** [comment]
I had read documentation, and know nothing like function or argument. 
If there is a way, please let me know.

**Comment by xuri** [comment]
Thanks for your issue. This library doesn't support specifying if using the smoothed line of the chart currently. We need to add a smooth field like this for the line chart in the internal [`drawChartSeries`](https://github.com/qax-os/excelize/blob/fd0eb2bcbf31eccfc2b853dc406e0cfd247f7fb2/drawing.go#L761) function:

```go
Smooth: &attrValBool{Val: boolPtr(false)},
```

I'll consider adding this support later.

**Comment by xuri** [comment]
Thanks for your issue. This library doesn't support specifying if using the smoothed line of the chart currently. We need to add a smooth field like this for the line chart in the internal [`drawChartSeries`](https://github.com/xuri/excelize/blob/fd0eb2bcbf31eccfc2b853dc406e0cfd247f7fb2/drawing.go#L761) function:

```go
Smooth: &attrValBool{Val: boolPtr(false)},
```

I'll consider adding this support later.

**Comment by tetsuyanh** [comment]
Thanks to quick reply.

**Comment by xuri** [comment]
I have add a new smooth field in chart format parameter, support specify if smooth line chart. Please upgrade to the master branch code, and this feature will be released in the next version.
