### ISSUE TITLE
Whether it can support the correspondence between struct tag and xlsx columns

### ISSUE THREAD

**Issue by moluzhui** [qax-os/excelize#1303]
**Description**

Is there a way to write `struct tag`, **export** the struct array to xlsx, and can **import** from xlsx to the structure array

Take xlsx **import** as an example, assuming the following data
| Name  | Description |
| ----- | ----------- |
| John  | John test   |
| Peter | Peter test  |

1. The struct is as follows, including the labels imported and exported by xlsx
```
type User struct{
	Name string    `json:"name" xlsx:"Name"`
	Age  string    `json:"age" xlsx:"Age"`
	Description string     `json:"description" xlsx:"Description"`
}
```
2.  Load function
```
xlsx, err := excelize.OpenReader(file)
uses := make([]User,0)
err := excelize.Load(xlsx, uses)
```
3.  Ability to automatically match fields of structs

Similarly, the structure array can be **exported** to xlsx
```
list := []User{
    {"a", "44", "test1"},
    {"b", "44", "test2"},
    {"c", "44", "test3"},
    {"d", "44", "test3"}
}
// create xlsx
f := WriteXlsx("Sheet1", list)
// save
if err := f.SaveAs("Book1.xlsx"); err != nil {
println(err.Error())
}
```

**Comment by xuri** [comment]
Thanks for your feedback. This is similar to issue #619, #1208 and #1302. Currently, you need to convert the input to the Excelize required data types by yourself.

**Comment by xuri** [comment]
I closed this issue. If you have any questions, please let me know to reopen this anytime.

**Comment by jtyoui** [comment]
please [click see](https://github.com/gounits/goexcel)
