### ISSUE TITLE
AddComment used too many memory ( more than 10GB for only 100 comments)

### ISSUE THREAD

**Issue by pqx0703** [qax-os/excelize#1310]
we added about 100 comments in 5 batch,  but it use too many memory, like more than 10GB.

code and files are in the attachment 

[test1.zip](https://github.com/qax-os/excelize/files/9288405/test1.zip)

**Comment by xuri** [comment]
Thanks for your issue. I have test with your attachment and get runtime memory usage by [`printBenchmarkInfo`](https://github.com/xuri/excelize-benchmark/blob/2f1b4a646dd36d3cc03febe275d0d7526cdfea5f/v2.5.0-master/utils.go#L26-L36) function, and it just cost about `11MB`, please make sure your code and real memory usage.

**Comment by pqx0703** [comment]
@xuri 你这个函数可能不太准，开个 top  看一下，处理100条就很慢，而且内存明显飙升 

我的操作系统是 centos 7.9 ， Go 版本 1.6 / 1.8/ 1.9 都试过，都有问题

**Comment by xuri** [comment]
The [`Getrusage`](https://pkg.go.dev/syscall#Getrusage) uses the low-level operating system primitives, which get the same resident memory usage as the top command. Version 2.6.0 of this library requires the Go language to be 1.15 later. If you're using 1.6, 1.8, or 1.9, you couldn't build successfully. Please check your code or service, and you can also diagnose logic and performance problems by [profiling tools](https://go.dev/doc/diagnostics).

**Comment by xuri** [comment]
I closed this issue. If you have any questions, please let me know to reopen this anytime.

**Comment by pqx0703** [comment]
@xuri  是   1.16 / 1.18/ 1.19 , 上面打错了

**Comment by pqx0703** [comment]
@xuri I think i've found what's wrong.  

https://github.com/qax-os/excelize/blob/master/comment.go#L236

It's ok when you create a new file, add some comments, and save it. But when you reopen that file, and append some comments, it loads the existing shapes from `xl/drawings/vmlDrawing1.vml`  everytime, and append it to the current vml. 

so, the ploblem is : The existing shapes should only load once ! 

Dont modify and just run this code: [test2.zip](https://github.com/qax-os/excelize/files/9292948/test2.zip) , then unzip the 20220808.xlsx file, you would get a 2GB vml file  !!!

![image](https://user-images.githubusercontent.com/59309931/183707916-ccc9c441-7e61-4022-8483-4c00b54906b0.png)

**Comment by pqx0703** [comment]
I've made a fix for this, tested locally and works fine

**Comment by xuri** [comment]
Thanks for your feedback, I've accepted pull request #1311, and this patch will be released in the next version.
