### ISSUE TITLE
numFmt cannot handle format 

### ISSUE THREAD

**Issue by aschereT** [qax-os/excelize#1312]
**Description**
numFmt does not handle format "000" correctly. In numfmt.go:340, only "0" is handled and not any other zero placeholders.

**Steps to reproduce the issue:**
1. Download [npf-test.zip](https://github.com/qax-os/excelize/files/9295107/npf-test.zip)
2. Extract to a temporary directory
3. Run `go run .`

**Describe the results you received:**
```
❯ go run .
0 123
```

**Describe the results you expected:**
```
❯ go run .
0 123
1 456
```

**Output of `go version`:**

```text
go version go1.19 darwin/amd64
```

**Excelize version or commit ID:**

```text
v2.6.0
```

**Environment details (OS, Microsoft Excel™ version, physical, etc.):**

**Comment by xuri** [comment]
Thanks for your feedback. This issue has been fixed, please upgrade to the master branch code, and this patch will be released in the next version.
