### ISSUE TITLE
numFmt cannot handle format "000"

### ISSUE THREAD

**Issue by aschereT** [qax-os/excelize#1313]
**Description**
numFmt does not handle format "000" correctly. In numfmt.go:340, only "0" is handled and not any other zero placeholders.

**Steps to reproduce the issue:**
1. Download [nfp-test.zip](https://github.com/qax-os/excelize/files/9295121/nfp-test.zip)
2. Extract to a temporary directory
3. Run `go run .`

**Describe the results you received:**
```
❯ go run .
0 123
```
The second cell just disappears.

**Describe the results you expected:**
```
❯ go run .
0 123
1 456
```

**Output of `go version`:**

```text
go version go1.19 darwin/amd64
```

**Excelize version or commit ID:**

```text
v2.6.0
```
I've bisected it to `4b64b26c52932a51ca97a2bb6bf372a07020e52b`

**Environment details (OS, Microsoft Excel™ version, physical, etc.):**
```
Darwin mac.local 21.6.0 Darwin Kernel Version 21.6.0: Sat Jun 18 17:07:25 PDT 2022; root:xnu-8020.140.41~1/RELEASE_X86_64 x86_64
```

**Comment by xuri** [comment]
This issue was duplicate with #1313, I have fixed it.

**Comment by aschereT** [comment]
I don't know why it was filed twice. But thanks a lot for the quick fix!
