### ISSUE TITLE
Can we extra cells with data as an image ?

### ISSUE THREAD

**Issue by ZhixingWang** [qax-os/excelize#1318]
Can we extra cells with data as an image by excelize lib? 
**Description**
I use excel to store data and edit it later. After that, I will paste it into word document as an image which is part of a report. Is that achievable?
And the image is like this: [the image type](https://camo.githubusercontent.com/a6df141c9ecc3efcd5534081dbb1ca8e97c68d9bc82d12236147d53890052089/68747470733a2f2f787572692e6d652f77702d636f6e74656e742f75706c6f6164732f323031362f30382f657863656c697a652d706572666f726d616e63652e7376673f743d3230323230353032)

**Comment by ZhixingWang** [comment]
For now, I past it into word document as image as follow steps:
1. use wps to open the xlxs file 
2. cope the cells and paste it into wechat 
3. cope the image and paste it into word document

**Comment by xuri** [comment]
Thanks for your issue. Sorry, this library is used for reading and writing files compliant with the ECMA-376 standard, not related to rendering, so it can't convert cell data to an image, this feature was not in the scope of this library.

**Comment by ZhixingWang** [comment]
Thanks for your reply. Any idea? I want to do that. Appreciate for any suggestion.

**Comment by xuri** [comment]
Please consider using [PowerShell script](https://www.powershellgallery.com/packages/ImportExcel/4.0.12/Content/ConvertExcelToImageFile.ps1) to convert Excel to image as your need.

**Comment by xuri** [comment]
I closed this issue. If you have any questions, please let me know to reopen this anytime.
