### ISSUE TITLE
Formula: -<function> format yields 0 instead of expected value

### ISSUE THREAD

**Issue by thomascharbonnel** [qax-os/excelize#1319]
**Description**

When creating formulas such as `-<function>`, the result always becomes 0 rather than `-1 * <function>`.
`-1 * <function>` works but Excel properly supports `-<function>` too.

**Steps to reproduce the issue:**
1. Create a formula in Excel such as `=-COS(0)`
2. Calculate the cell using Excelize

**Describe the results you received:**

0

**Describe the results you expected:**

-1

**Output of `go version`:**

```text
go version go1.18.3 linux/amd64
```

**Excelize version or commit ID:**

```text
master
```

**Environment details (OS, Microsoft Excel™ version, physical, etc.):**

Running Excelize on Linux.
Excel v. 2108 on Windows.

**Comment by xuri** [comment]
Thanks for your feedback, this issue was caused by commit [`0f7a0c8`](https://github.com/xuri/excelize/commit/0f7a0c8f3b5c9abd5858cab80902296d1639625f), and I have fixed it, please upgrade to the master branch code.

**Comment by thomascharbonnel** [comment]
Thank you for your help!
