### ISSUE TITLE
Read csv file data to excel is bad encoding （写入Excel乱码）

### ISSUE THREAD

**Issue by zhangwk02** [qax-os/excelize#1321]
**Description**

**Steps to reproduce the issue:**
1. Read csv file data
2. get data write to excel
3.

**Describe the results you received:**
 the data write excel is bad encoding
**Describe the results you expected:**
   don't bad encoding
**Output of `go version`:**
 go version go1.16.6 darwin/amd64
```text
写入到excel 中会乱码：
�������查看空�回收站

```

**Excelize version or commit ID:**

```text
(paste here)
```

**Environment details (OS, Microsoft Excel™ version, physical, etc.):**

**Comment by xuri** [comment]
Thanks for your feedback. Which version of Excelize are you using? Can you show us a complete, standalone example program or reproducible demo?

**Comment by zhangwk02** [comment]
> Thanks for your feedback. Which version of Excelize are you using? Can you show us a complete, standalone example program or reproducible demo?


i want to read csv file an wrtie to excle

excelize version: v2.6.0

src file (it's ok)：
[用例导出-20220805210859.csv](https://github.com/qax-os/excelize/files/9357139/-20220805210859.csv)

target file （it's bad encoding）：
[测试报告.xlsx](https://github.com/qax-os/excelize/files/9357142/default.xlsx)

**Comment by xuri** [comment]
Please trim non-printable characters by yourselves before write cell: 

```go
trimedCellValue := strings.TrimFunc(cellvalue, func(r rune) bool { return !unicode.IsGraphic(r) })
```

**Comment by xuri** [comment]
Please trim non-printable characters by yourselves before write cell, for example:

```go
trimedCellValue := strings.Map(func(r rune) rune {
	if unicode.IsPrint(r) {
		return r
	}
	return -1
}, cellvalue)
```

**Comment by zhangwk02** [comment]
> 
it's printable
<img width="828" alt="image" src="https://user-images.githubusercontent.com/38233062/185116036-85aad512-9ad0-437e-a7ff-0d4e29f09dab.png">

but write to excel is bad encoding
<img width="769" alt="image" src="https://user-images.githubusercontent.com/38233062/185116307-9cb8ee03-9279-4469-85d9-a48642e7c5fa.png">

src file 
[用例导出-20220805210859.csv](https://github.com/qax-os/excelize/files/9359389/-20220805210859.csv)

target file 
[测试报告.xlsx](https://github.com/qax-os/excelize/files/9359391/default.xlsx)

**Comment by xuri** [comment]
Can you follow the issue template, and show us a complete, standalone example program to reproducible this demo? You just trim the non-printable characters and printout in your code snippet screenshot, did you trim it before writing the cell value into excel?

**Comment by zhangwk02** [comment]
> Can you follow the issue template, and show us a complete, standalone example program to reproducible this demo? You just trim the non-printable characters and printout in your code snippet screenshot, did you trim it before writing the cell value into excel?

thanks!  the bad encoding  is resloved. But the format is destroied, newline disappears. 

1. read csv and  trim non-printable characters

```
func ReadCsv(filePath string) [][]string {
	f, err := os.Open(filePath)
	if err != nil {
		log.Fatalf("cant not open file")
	}

	defer f.Close()
	r := csv.NewReader(f)
	content, err := r.ReadAll()
	if err != nil {
		log.Fatalf("can not readall, err is %+v", err)
	}
	for i1, val := range content {
		for i2, s := range val {
			val[i2] = checkString(s)
		}
		content[i1] = val
	}
	return content

}

func checkString(cellvalue string) string {
	trimedCellValue := strings.Map(func(r rune) rune {
		if unicode.IsPrint(r) {
			return r
		}
		return -1
	}, cellvalue)
	return trimedCellValue
}
```

2. write to excel 
```
func Wexcel(cases [][]string) {

	xlsx := excelize.NewFile()
	sheetName := "测试报告"
	index := xlsx.NewSheet(sheetName)
	for key, _da := range cases {
		axis := fmt.Sprintf("A%d", key+1)
		xlsx.SetSheetRow(sheetName, axis, &_da)
	}
	xlsx.SetActiveSheet(index)
	err := xlsx.SaveAs("/Users/xxxxx/Downloads/测试报告.xlsx")
	if err != nil {
		log.Fatal(err)
	}

}
```
3. run main
```
func main() {
	data := ReadCsv("/Users/xxxxxx/Downloads/用例导出-20220805210859.csv")
	model.Wexcel(data)
```
**Describe the results you received:**
newline disappears like this 
<img width="912" alt="image" src="https://user-images.githubusercontent.com/38233062/185153614-2b18c20d-9437-4288-83ec-028f238e8c0e.png">

original data 
<img width="610" alt="image" src="https://user-images.githubusercontent.com/38233062/185153857-a8d052f6-1693-46c0-9e76-5fcd85c0ef38.png">


**Describe the results you expected:**
keep original format

**Comment by xuri** [comment]
The CSV means comma-separated values file, your received conversion result is correct as expected. If you want to change the cell value and style, you can set the cell value by specifying the cell address. This problem is not an issue of this library.

**Comment by zhangwk02** [comment]
get thanks

> The CSV means comma-separated values file, your received conversion result is correct as expected. If you want to change the cell value and style, you can set the cell value by specifying the cell address. This problem is not an issue of this library.

get thanks!

**Comment by imysm** [comment]
我的 Golang version 1.23 ,excelize  2.9.0 ，生成的 excel 也是包含 ����，同样的代码，使用 golang 1.22 编译就正常，这可能是啥原因呀

**Comment by xuri** [comment]
@imysm please show us a complete, standalone example program to reproducible this demo.

**Comment by xuri** [comment]
@imysm please show us a complete, standalone example program to reproducible this issue.

**Comment by imysm** [comment]
我找到问题了，是 database/sql 中 sql.RawBytes 的问题。
我是从数据库中读取数据，然后生成 excel。读取的数据返回的是 sql.RawBytes 类型，这个在 go 1.22 和 go 1.23是有差异的，我换成 sql.NullString 就没有乱码了。下面是在 go 1.23 中产生乱码的代码 
`	for i, row := range data {
		for j, colName := range columns {
			colLetter, _ := excelize.ColumnNumberToName(j + 1)
			cellCoord := fmt.Sprintf("%s%d", colLetter, i+2)
			f.SetCellStyle("Sheet1", cellCoord, cellCoord, borderOnlyStyleID)
			// Convert the value to a string if it is a []byte
			if b, ok := row[colName].(*sql.RawBytes); ok {
				f.SetCellValue("Sheet1", cellCoord, string(*b))
			} else {
				f.SetCellValue("Sheet1", cellCoord, row[colName])
			}
		}
	}`

当把数据库返回数据类型修改成 sql.NullString 后正常了 ，下面是正常的代码
`	for i, row := range data {
		for j, colName := range columns {
			colLetter, _ := excelize.ColumnNumberToName(j + 1)
			cellCoord := fmt.Sprintf("%s%d", colLetter, i+2)
			f.SetCellStyle("Sheet1", cellCoord, cellCoord, borderOnlyStyleID)
			// Convert the value to a string if it is a []byte
			if b, ok := row[colName].(*sql.NullString); ok {
				f.SetCellValue("Sheet1", cellCoord, (*b).String)
			} else {
				f.SetCellValue("Sheet1", cellCoord, row[colName])
			}
		}
	}`
