### ISSUE TITLE
Trigger formulas automatic calculation 填充数据后对应的公式需要手动处理

### ISSUE THREAD

**Issue by lee501** [qax-os/excelize#1322]
**Description**

**Steps to reproduce the issue:**
1. 使用excelize在隐藏的sheet添加cell数据，另一个sheet的cell实用=sheet!cell公式关联
2. saveAs后保需要在excel公式的cell手动enter一下， 数据才显示
3. 而在excel 直接填数据，关联的cell会自动显示

**Describe the results you received:**
<img width="421" alt="image" src="https://user-images.githubusercontent.com/22001475/185528115-229f500f-a2e7-477a-bde9-627c87bcbecd.png">
<img width="546" alt="image" src="https://user-images.githubusercontent.com/22001475/185528304-becf4c53-dd09-4753-9ff2-a976429997c6.png">

**Describe the results you expected:**
期望数据填上，公式会自动产生
**Output of `go version`:**

```text
(paste your output here)
```
<img width="277" alt="image" src="https://user-images.githubusercontent.com/22001475/185528423-f7eaa0f2-aa4f-48c7-840e-dea4684dff40.png">

**Excelize version or commit ID:**
```text
v2.6.0

```

**Environment details (OS, Microsoft Excel™ version, physical, etc.):**
os: mac m1
excel: Microsoft_Office_16.61

**Comment by xuri** [comment]
I think this issue is similar with #634 and #1195. Please use [`UpdateLinkedValue`](https://pkg.go.dev/github.com/xuri/excelize/v2#File.UpdateLinkedValue) to cleanup cell calculation cache value before saving the spreadsheet.

**Comment by xuri** [comment]
I closed this issue. If you have any questions, please let me know to reopen this anytime.
