### ISSUE TITLE
File corruption after re-saving

### ISSUE THREAD

**Issue by romanzh1** [qax-os/excelize#1323]
Hi👋. 

### Description
I have a small program that adds a comment to the file every run. On the **second run**, the file is corrupted. The bug works for the **Save** and **AsSave** functions. The comments may be different, but the problem is to re-add the comment to the same cell.

In addition, I noticed that adding a non-existing styleID to SetCellStyle func leads to file corruption.

### Program
```
package main
import (
	"fmt"

	"github.com/xuri/excelize/v2"
)

func main() {
	excel, _ := excelize.OpenFile("test.xlsx")

	if err := excel.AddComment("project", "A2", fmt.Sprintf(`{"author":"system: ","text":"Test: test"}`)); err != nil {
		fmt.Printf("comment: %w\n", err)
	}

	if err := excel.Save(); err != nil {
		fmt.Printf("\ncan't save error file: %w", err)
	}
}
```

### Result
After opening the re-saved file an error occurs that the file is corrupted

### Excelize version or commit ID
I used the version of the last commit on the master branch:
commit d1e76fc432ac5c9bde99591ec5e88e46b62d9c3d
import:
github.com/xuri/excelize/v2 v2.6.1-0.20220817025952-d1e76fc432ac

### Excel file
[https://www.dropbox.com/scl/fi/lvqws5itronua15tpridk/test.xlsx?dl=0&rlkey=b2053854zq6qwdnt1p8d5v3qb](url)

**Comment by xuri** [comment]
Thanks for your issue. There is only one comment allowed in a cell in the spreadsheet, so if you add the comment on the second run, the file will be corrupt. I've just merged pull request #1317, which introduced the new function `DeleteComment` to support deleting comments, please upgrade to the master branch code, and use it before adding a comment, and this feature will be released in the next version.

**Comment by romanzh1** [comment]
Thanks a lot. The release is very timely)
What about SetCellStyle? Adding a non-existing styleID also results in file corruption.

**Comment by xuri** [comment]
I have added checking for the style ID, an error will be returned when setting the not existing style ID. Please upgrade to the master branch code, and this feature will be released in the next version.
