### ISSUE TITLE
Number rounding issue

### ISSUE THREAD

**Issue by pramonow** [qax-os/excelize#1328]
**Description**
Float number is always rounded down

**Steps to reproduce the issue:**
Uploading excel with this value

<img width="891" alt="Screen Shot 2022-08-23 at 18 03 26" src="https://user-images.githubusercontent.com/28787057/186142921-ae99ad88-dbc2-4b84-a74a-de839b75298c.png">

notes the circled value, raw value is 463.614634146341
and the excel value is 464 (because of the rounding formatting)

Tried on some excel version and it's getting different behaviour (it's giving expected value in excel 2007 but not on 2020)

**Describe the results you received:**
Result from excelize `GetRows` method is returning 463 (rounded down)

**Describe the results you expected:**
Expected it to return 464

**Excelize version or commit ID:**

```text
github.com/xuri/excelize/v2 v2.6.0
```

**Environment details (OS, Microsoft Excel™ version, physical, etc.):**
Mac OS Monterey, Excel version 2020

**Comment by xuri** [comment]
Thanks for your feedback. Could you provides the workbook file as an attachment without confidential info?

**Comment by pramonow** [comment]
thanks for the reply
below i have attached the file 
[testing sampling v2 (6) (1).xlsx](https://github.com/qax-os/excelize/files/9402312/testing.sampling.v2.6.1.xlsx)

also the result when i printed out the rows are:
`
[ 310]
[ 1.85663157894737]
[ 463]
[ 1.92857142857143]
[ 518]
[ 491]
[ 530]
`
where i expected it to actually match the excel value (i.e: first one should be 311)

**Comment by xuri** [comment]
Thanks for your issue. I have fixed it, please upgrade to the master branch code, and this patch will be released in the next version.
