### ISSUE TITLE
Using array formula defined name for the dependent drop list 关于级联列表能否使用切片数据做为选项值

### ISSUE THREAD

**Issue by MoShQing** [qax-os/excelize#1337]
if err = f.SetDefinedName(&excelize.DefinedName{
        Name:     "Vegetables",
        RefersTo: "Sheet1!$B$2:$B$6",
        Scope:    "Sheet1",
    }); err != nil {
        fmt.Println(err)
        return
    }
示例代码中，使用B2-B6的值做为"Vegetables"对应的级联列表的选项，此处能否支持传入["a","b","c"]这种方式

**Comment by xuri** [comment]
You can define an array constant with array formula in defined name , but which can't be used for dependent drop list.

**Comment by xuri** [comment]
I closed this issue. If you have any questions, please let me know to reopen this anytime.
