### ISSUE TITLE
`GetRows()` method parses `12:20 PM` as `00:20 AM`, not consistent to `ExcelDateToTime()` method

### ISSUE THREAD

**Issue by limingjie** [qax-os/excelize#1338]
**Description**

The `excelize.File.GetRows` method parses `12:20 PM` as `00:20 AM`, usually 12:20 PM is treated as 20 minutes past noon, which is 12:20 in 24-hour format.

**Steps to reproduce the issue:**
1. In the Excel file, enter `1/2/23 12:20 PM` in a cell, the cell is in Date format.
2. Use `excelize.File.GetRows(sheetName)` method to get the data.

**Describe the results you received:**
`1/2/23 00:20 AM`

**Describe the results you expected:**
`1/2/23 12:20 PM`

**Workaround**
There is a workaround.
1. Get the data by `excelize.File.GetRows(sheetName, excelize.Options{RawCellValue: true})`
2. Convert the float value by `excelize.ExcelDateToTime(f, false)` method.

**Output of `go version`:**

```text
go version go1.18.3 darwin/arm64
```

**Excelize version or commit ID:**

```text
v2.6.0
```

**Environment details (OS, Microsoft Excel™ version, physical, etc.):**
macOS Monterey 12.5.1

**Comment by xuri** [comment]
Thanks for your feedback, could you provide your input file attachment without confidential info?

**Comment by xuri** [comment]
Thanks for your feedback. This issue has been fixed, please upgrade to the master branch code, and this patch will be released in the next version.

**Comment by limingjie** [comment]
Thank you @xuri for the quick turnaround!
