### ISSUE TITLE
SetCellValue() and  MergeCell()  are very slowly when populate 10,000 rows

### ISSUE THREAD

**Issue by xuzue** [qax-os/excelize#1349]
**Description**

SetCellValue() and  MergeCell()  are very slowly when populate a large number of cells if style value is bigger than 0

**Describe the results you received:**

when SetCellValue() or MergeCell() is called, the prepareCellStyle() method will loop all rows in sheet everytime. So when populate a large number of cells about 450,000 cells that there are 10,000 rows, the span time is very very long.

**Describe the results you expected:**

prepareCellStyle() need return the style value directly if parameter "style" is bigger than 0.

**Output of `go version`:**

```text
1.18.4
```

**Excelize version or commit ID:**

```text
v2.6.0
```

**Environment details (OS, Microsoft Excel™ version, physical, etc.):**

**Comment by xuri** [comment]
The `prepareCellStyle` function gets rows style by one-time addressing when it has been called. When setting the cell's value, we need to know if the cell's style should be inherited from a row or column's style.  Currently, which returns the style ID directly if given a specific style ID.

**Comment by elias506** [comment]
I propose a temporary but very effective solution to this problem.
Before you use `SetCellStr` or any other function to insert a value into a cell, use this call: `SetRowStyle("sheet_name", 1, 1, styleID)`. With this, the insert function will not go through every value of every line in the file. It is necessary to set the style specifically for the first line.
In this option, all subsequent cells will be filled with the provided style. If you need to change the style of subsequent inserted cells, simply call a new `SetRowStyle("sheet_name", 1, 1, newStyleID)` with the new style.

Note that you need to pass a non-zero styleID.

Remember that you can use the `SetCellStyle` function to overwrite the old style.

It is also worth noting that such a problem does not exist when using `StreamWriter`. If you have roughly 10000 lines or more it's always worth using `StreamWriter` I think. It gives too much of a performance boost.

**Comment by xuri** [comment]
Thanks for your feedback. Due to the problem has been resolved, I closed this issue.
