### ISSUE TITLE
Autofit cell width/height

### ISSUE THREAD

**Issue by gucio321** [qax-os/excelize#1351]
**Description**

In excel, it is possible to autofit cell (column/row) size by double-clicking on the cols/rows border. Is it possible to add such a feature in excelize?

**Output of `go version`:**

```console
go version go1.18.4 linux/amd64
```

**Environment details (OS, Microsoft Excel™ version, physical, etc.):**
OS: Fedora linux 36
*opening xlsx files via LibreOffice but I suppose it doesn't metter here*

**Comment by xuri** [comment]
This issue was duplicated with #92, #204, and #1209. I will close this issue and move on to discuss #92.
