### ISSUE TITLE
StreamWriter couldn't set row style by `RowOpt`

### ISSUE THREAD

**Issue by invzhi** [qax-os/excelize#1354]
**Description**

Stream Writer couldn't set row style by `RowOpt`.

**Steps to reproduce the issue:**
```go
f := excelize.NewFile()
w, _ := f.NewStreamWriter("Sheet1")

styleID, _ := f.NewStyle(&excelize.Style{
	Fill: excelize.Fill{Type: "pattern", Color: []string{"#FBBC04"}, Pattern: 1},
})

_ = w.SetRow("A1", []interface{}{"value1", "value2"}, excelize.RowOpts{StyleID: styleID})
_ = w.Flush()

_ = f.SaveAs("demo.xlsx")

```

**Describe the results you received:**

<img width="652" alt="image" src="https://user-images.githubusercontent.com/19483698/191160653-560797df-db95-480c-b5e1-074882f63ce8.png">

**Describe the results you expected:**

<img width="652" alt="image" src="https://user-images.githubusercontent.com/19483698/191161003-edee9dec-483e-4fa1-b442-570c398340cb.png">

**Output of `go version`:**

```text
go version go1.18.4 darwin/arm64
```

**Excelize version or commit ID:**

```text
v2.6.1
```

**Comment by xuri** [comment]
Thanks for your issue. The stream writer won't apply or overwrite the style of each cell when you specify the row style, please specify the style for each cell as you need like this:

```go
w.SetRow("A1", []interface{}{
    excelize.Cell{StyleID: styleID, Value: "value1"},
    excelize.Cell{StyleID: styleID, Value: "value1"},
})
```

**Comment by invzhi** [comment]
Thanks for your quick response. I would like to open a pull request to fix this issue.

I have a question about the expected behavior.

When I specify the style like this:
```go
w.SetRow("A1", []interface{}{excelize.Cell{StyleID: 0, Value: "value1"}}, excelize.RowOpts{StyleID: styleID})
```
The style id of A1 should be:
1. overridden by 0
2. still use `styleID` in `excelize.RowOpts`?

My understanding is that the first is the expected behavior, which the developers could unset the cell style.

**Comment by xuri** [comment]
Yep, the cell style should be overridden by 0 in this case, the cell style priority is hight than the rows.
