### ISSUE TITLE
Legacy version rows iterator cause high memory occupies 行迭代器把容器内存打满问题

### ISSUE THREAD

**Issue by huizhang001** [qax-os/excelize#1356]
描述：
我有一个20M的excel文件，本来想通过rows迭代器进行逐行处理，但发现rows方法会将整个文件的内容压入内存，导致容器OOM。

诉求：
- 希望提供逐行读取的能力，还是此项目具有此能力我没有发现？

https://github.com/szyhf/go-excel 
这个包是可以实现逐行读取的，但功能不成熟bug较多，还是希望此项目能提供此能力。

谢谢谢！！！

**Comment by xuri** [comment]
This issue was duplicated with #845 and #1096. Please use the [row's iterator](https://xuri.me/excelize/zh-hans/sheet.html#Rows) to read data as streaming.

**Comment by xuri** [comment]
Thanks for your feedback. Which version of Excelize are you using? Can you show us a complete, standalone example program or reproducible demo? This issue was duplicated with #845, #1096, and #1220. The [row's iterator](https://xuri.me/excelize/zh-hans/sheet.html#Rows) read data as streaming,  it will use lower memory than `GetRows`.

**Comment by huizhang001** [comment]
version：
github.com/360EntSecGroup-Skylar/excelize v1.4.1

code example：

`
       // File size is 20+ M
       targetFile := "xxx.xlsx"
	file, err := excelize.OpenFile(targetFile)
	if err != nil {
		return nil, "", err
	}

        // This line of code is very time-consuming
	rows, _ := file.Rows(file.GetSheetName(1))

	for rows.Next() {
		row := rows.Columns()
		fmt.Println(row)
	}
`


@xuri Check whether the information I provide is satisfied？

**Comment by xuri** [comment]
Thanks for the feedback. Please upgrade to the latest version. The performance of the streaming readers has a lot improved.

**Comment by huizhang001** [comment]
Thank you, I'll try！！！

**Comment by xuri** [comment]
Here is a [performance benchmark report](https://xuri.me/excelize/en/performance.html) for your information.

**Comment by huizhang001** [comment]
Thank you very much. What version did you start from? The performance has been greatly improved.

@xuri

**Comment by xuri** [comment]
I will close this issue. If you have any questions, please let me know.
