### ISSUE TITLE
Float string error

### ISSUE THREAD

**Issue by tomgitcode** [qax-os/excelize#1360]
excel is config is  0.0724
but read out use excelize  is "0.07239999999999999"
I use "require github.com/xuri/excelize/v2 v2.6.1"
how can i do?

**Comment by xuri** [comment]
Thanks for your feedback. I have tested and it works well, could you provide your input file attachment without confidential info?

**Comment by tomgitcode** [comment]
正常的填写浮点数是没有问题的也是能读出来是字符串，
我的这个0.0724是表格公式计算结果值。比如（C4-C5）*xxx==0.0724.

**Comment by xuri** [comment]
Thanks for your issue, I have fixed it. Please upgrade to the master branch code, and this patch will be released in the next version.
