### ISSUE TITLE
empty sheetname will cause damaged file

### ISSUE THREAD

**Issue by eaglexiang** [qax-os/excelize#1361]
**Description**

**Steps to reproduce the issue:**
1. Run this demo
2. You get one damaged file
3. MS Excel cannot open this file unless you fix sheetname of `workbook.xml` inner test.xlsx file.

```go
package main

import "github.com/xuri/excelize/v2"

func main() {
	f := excelize.NewFile()
	f.NewSheet("")
	err := f.SaveAs("test.xlsx")
	if err != nil {
		panic(err)
	}
}

```

**Describe the results you received:**

I got a damaged excel file.

**Describe the results you expected:**

Err returned by Method  `NewSheet` or other Export-class Methods.

**Output of `go version`:**

```text
go version go1.18.3 windows/amd64
```

**Excelize version or commit ID:**

```text
v2.6.1
```

**Environment details (OS, Microsoft Excel™ version, physical, etc.):**

Microsoft® Excel® 适用于 Microsoft 365MSO (版本 2208 Build 16.0.15601.20148) 64 位

**Comment by eaglexiang** [comment]
Adding err to `NewSheet` is simple but broken, Adding err to `Export-class` Methods like `SaveAs` and `WriteTo` may cause too many changes. So I gave up contributing this time. :)

**Comment by xuri** [comment]
Thanks for your issue, I have fixed it. Please upgrade to the master branch code, and this patch will be released in the next version.
