### ISSUE TITLE
Memory leak on Create Excel File

### ISSUE THREAD

**Issue by ridwankustanto** [qax-os/excelize#1364]
**Description**
Hi, I want to report a potential memory leak on creating file excel.

**Steps to reproduce the issue:**
1. NewFile()
2. NewSheet("Sheet1")
3. SetActiveSheet()
4. Looping the data and SetCellValue() --> the data around 8K rows
5. SaveAs()

**Describe the results you received:**
When I check the memory, it consumes like 200-ish M RAM on the server per run. And after several times, it still doesn't released the memory

**Describe the results you expected:**
The memory will release.

**Output of `go version`:**
```text
go version go1.17.12 darwin/arm64
```

**Excelize version or commit ID:**

```text
v2.6.1
```

**Environment details (OS, Microsoft Excel™ version, physical, etc.):**

**Comment by xuri** [comment]
As you know, the Go language supports automatic garbage collection, that maybe not free memory immediately, wait a moment. You can trace the garbage collection for your application by `GODEBUG=gctrace=1` environment, and you can manually initiate a garbage collection by putting a `runtime.GC()` statement in your code.

**Comment by ridwankustanto** [comment]
I see, in my case, before the memory is freed, the create excel function already gets hit, it makes the memory full and kills other containers. Do you think it's a common approach to put `runtime.GC() ` (released memory) manually?

**Comment by xuri** [comment]
Manually calling garbage collection is not common in the Go program, frequent GC will affect the performance of the program. Maybe you can consider using the streaming mode function to generate a mount of data to reduce memory usage.

**Comment by ridwankustanto** [comment]
Well, thanks for your advice, will do! And I will close this issue. Have a great day!
