### ISSUE TITLE
cell value is a timestamp 1651716000, but method GetRows return a string, content is "1651715999.9999998"

### ISSUE THREAD

**Issue by darjun** [qax-os/excelize#1367]
**Description**

the cell value is a timestamp 1651716000, but when I use GetRows to read it, it returns a string, in which the content is "1651715999.9999998", something like a float number. My cell format is general.

**Steps to reproduce the issue:**
1.use the excel at https://github.com/darjun/temp/blob/main/parameter2_info.xlsx
2.read the excel with GetRows

btw, I try to specify option "rawCellValue", but it doesn't work.

**Comment by xuri** [comment]
Thanks for your feedback. Which version of Excelize are you using? This issue was duplicated with #727, #1030, and #1328. This issue has been fixed, and I have tested it with your attachment and it works well. Please upgrade to the latest version or use the master branch code.

**Comment by darjun** [comment]
version: 2.6.0 not work
version: 2.6.1 works
thx
