### ISSUE TITLE
cell with percent format, when the content is not valid, etc 7_10000_1, GetRows will return 7100001%

### ISSUE THREAD

**Issue by darjun** [qax-os/excelize#1368]
**Description**

I have a cell with percent format.
When the content is not valid, etc 7_10000_1, GetRows will return 7100001%.
Libs from other languages will give me string "7_10000_1"

**Steps to reproduce the issue:**
1.clone https://github.com/darjun/temp/tree/main/excelize
2.cd excelize && go run main.go

go version: 1.19
excelize version: 2.6.1

**Comment by xuri** [comment]
Thanks for your issue, I have fixed it. Please upgrade to the master branch code, and this patch will be released in the next version.
