### ISSUE TITLE
Support for Print Area(s)

### ISSUE THREAD

**Issue by ondrejholecek** [qax-os/excelize#1371]
Hello, 

is it possible to set Print Area(s)? 

![image](https://user-images.githubusercontent.com/40828115/196251291-4ffec20e-4cba-4ff1-a30b-4a530a3a4cc2.png)

That is useful to signalize which columns are used so it looks nice (centered) when printing. Without it, Excel seems to use one more empty column on right side and page appears unaligned on the paper.

I haven't found any way to configure this, so can it be added please?

**Comment by xuri** [comment]
Please set print area by [`SetDefinedName`](https://xuri.me/excelize/en/workbook.html#SetDefinedName) function.

**Comment by ondrejholecek** [comment]
Awesome, that works! Thanks.
