### ISSUE TITLE
SetColVisible for high range column values seems not working ( exemple AI:AM )

### ISSUE THREAD

**Issue by hadiweslati** [qax-os/excelize#1372]
**Description**

**Steps to reproduce the issue:**
1. f.SetColVisible(sheetName,"AI:AM", false)
2. Or (f.SetColVisible(sheetName,"AI", false))
3.

**Describe the results you received:**
Columns from AI to AM continue being visible
Or ( Column AI always visible)
**Describe the results you expected:**
Columns from AI to AM being hidden
Or ( Column AI hidden)
**Output of `go version`:**

```text
1.18
```

**Excelize version or commit ID:**

```text
	github.com/xuri/excelize/v2 v2.6.1

```

**Environment details (OS, Microsoft Excel™ version, physical, etc.):**
macOs

**Comment by xuri** [comment]
Thanks for your feedback. I have tested it with the latest version and master branch code and it works well. Are there any error returns? Could you show us a complete, standalone example program or reproducible demo?

**Comment by hadiweslati** [comment]
Thanks for your fast response. I test the issue on a standalone exemple and it worked well as you said. I think that the problem is related to other issue in my code.

**Comment by hadiweslati** [comment]
In fact the issue appears when I did the merge for the columns I want to hide. Here's an exemple: 

	f := excelize.NewFile()
	// Create a new worksheet.
	index := f.NewSheet("Sheet2")
	// Set value of a cell.
	f.SetColVisible("Sheet1", "AI:AK", false)
	f.SetCellValue("Sheet1", "AI2", "Hello world.")
	f.SetCellValue("Sheet1", "AJ2", "Hello world.")
	f.SetCellValue("Sheet1", "AK2", "Hello world.")
	f.MergeCell("Sheet1", "AI2", "AK2")
	// Set the active worksheet of the workbook.
	f.SetActiveSheet(index)
	// Save the spreadsheet by the given path.
	if err := f.SaveAs("Book1.xlsx"); err != nil {
		fmt.Println(err)
	}

**Comment by xuri** [comment]
I have tested it with the latest version and master branch code, and it works well. Do you confirm that the columns unhidden were on the `Sheet1`?

**Comment by hadiweslati** [comment]
Yes. 
<img width="555" alt="image" src="https://user-images.githubusercontent.com/36129006/196437745-e3bc7e31-bb0c-4e37-8252-70c4a3481829.png">
The columns AI AJ and AK still visible in my Sheet1

**Comment by xuri** [comment]
It works on Microsoft Office Excel, OpenOffice, LibreOffice and Kingsoft WPS, etc. But not Apple Numbers, which doesn't support hiding a column with horizontal merge cells that involve that column.
