### ISSUE TITLE
GetCellValue () got a lost the value of the precision

### ISSUE THREAD

**Issue by zjfGH** [qax-os/excelize#1373]
[t.xlsx](https://github.com/qax-os/excelize/files/9816645/t.xlsx)

value, _ := file.GetCellValue("Sheet1", "A1")
fmt.Println(value)

expect  console
---------------------
88888666665555500000

actual  console
---------------------
-9223372036854775808

**Comment by xuri** [comment]
Thanks for your issue, I have fixed it. Please upgrade to the master branch code, and this patch will be released in the next version.
