### ISSUE TITLE
GetMergeCells() return 'parameter is invalid' err

### ISSUE THREAD

**Issue by zjfGH** [qax-os/excelize#1380]
The excel is generated through a third party program.
[merge.xls](https://github.com/qax-os/excelize/files/9865595/merge.xls)

GetMergeCells() got the 'parameter is invalid' err In the 'A1' axis when i use of the excelize to read.
Hope can be compatible with the situation, Thanks !!!

**Comment by xuri** [comment]
This library doesn't support the legacy XLS file format in your attachment.

**Comment by zjfGH** [comment]
Thanks for your answers

**Comment by xuri** [comment]
I think this problem is caused by a worksheet that contains one cell merged cell range. I will consider adding compatibility with that.
