### ISSUE TITLE
xlsx文件另存为xls格式文件，打开xls文件会报错：unsupported workbook file format

### ISSUE THREAD

**Issue by kay07** [qax-os/excelize#1381]
env： wps
xlsx：get xlsx file with excelize.NewFile() function
xls: use wps to save as xls file
open: use excelize.OpenFile() function open xls file
error: unsupported workbook file format

**Comment by xuri** [comment]
This issue similar with #44, #264, #368 and #572. This library doesn't support the legacy XLS format currently. I closed this and merged it into issue #44. Please let me know if you have any questions to reopen this anytime.
