### ISSUE TITLE
Get merged cells cost too much time than expected

### ISSUE THREAD

**Issue by evanscat** [qax-os/excelize#1382]
**Description**

**Steps to reproduce the issue:**
1. a excel documment has 10,000 merged cells
2. open the doc and call the GetMergeCells function
3. 

**Describe the results you received:**
it cost almost a minute
**Describe the results you expected:**
cost about 1 second 
**Output of `go version`:**

```text
go version go1.18.4 darwin/amd64
```

**Excelize version or commit ID:**

```text
v2.6.1
```

**Environment details (OS, Microsoft Excel™ version, physical, etc.):**
Darwin Kernel Version 22.1.0: Sun Oct
2 GHz 四核Intel Core i5 
16 GB 3733 MHz LPDDR4X

**Comment by xuri** [comment]
Thanks for your issue. The cell value of the merged cell would be returned when you get the merged cells if you needn't get this value, removing the [get cell value statements](https://github.com/xuri/excelize/blob/a410b22bdd50e9f212b0b454e5aed798e3476394/merge.go#L147) will speed up as your expected.

**Comment by xuri** [comment]
The issue #1448 was similar with this, the performance of the `GetMergeCells` function has been improvement by #1500, and this optimization has been released in the version 2.7.1. Please upgrade to the latest version. I've closed this issue, if you have any question, please let me know, and you can reopen this anytime.

**Comment by xuri** [comment]
The issues #1018 and #1448 was similar with this, the performance of the `GetMergeCells` function has been improvement by #1500, and this optimization has been released in the version 2.7.1. Please upgrade to the latest version. I've closed this issue, if you have any question, please let me know, and you can reopen this anytime.
