### ISSUE TITLE
The file size increases abnormally when saving

### ISSUE THREAD

**Issue by seanliang** [qax-os/excelize#1383]
The original file size is 8KB, and it contains nothing but only one empty row (row# 1048576), the file size will become 2.8MB when saving.
[origin.xlsx](https://github.com/qax-os/excelize/files/9915838/origin.xlsx)

Unzipped both files and you can find that the file size of sheet1.xml has increased from 1KB to 23MB.

```
package main

import (
	"log"
	"os"

	"github.com/xuri/excelize/v2"
)

func main() {
	fi, err := os.Stat("origin.xlsx")
	if err != nil {
		log.Fatal(err)
	}
	log.Printf("Origin file size: %v", fi.Size())
	file, _ := excelize.OpenFile("origin.xlsx")
	file.SetCellValue("Test", "A1", "test")
	file.SaveAs("copy.xlsx")
	fi, _ = os.Stat("copy.xlsx")
	log.Printf("Copy file size: %v", fi.Size())
}
```

The output is
```
Origin file size: 8382
Copy file size: 2759163
```

**Comment by xuri** [comment]
Thanks for your issue, I have fixed it. Please upgrade to the master branch code, and this patch will be released in the next version.

**Comment by seanliang** [comment]
Awesome! Thanks for your efforts!
