### ISSUE TITLE
How to lock the droplist input cell？

### ISSUE THREAD

**Issue by fengkai** [qax-os/excelize#1389]
I set a droplist, it works fine, like this:
```
dvRange1 := excelize.NewDataValidation(true)
dvRange1.Sqref = "D3:D100000"
dvRange1.SetDropList([]string{"1,", "2", "3"})
if err = f.AddDataValidation("Sheet1", dvRange1); err != nil {
        fmt.Println(err)
	return
}
```

How can i lock the cell to prevent user inputing number which not in 1/2/3 ?

**Comment by xuri** [comment]
Thanks for your issue. Here is [the documentation](https://xuri.me/excelize/zh-hans/data.html#AddDataValidation) for your information, you can set the error alert on the data validation range:

```go
dvRange1.SetError(excelize.DataValidationErrorStyleStop, "error title", "error body")
```

**Comment by xuri** [comment]
I will close this issue. If you have any questions, please let me know and reopen this anytime.
