### ISSUE TITLE
Issue with reading dates of format '*14/02/2012'

### ISSUE THREAD

**Issue by bvwells** [qax-os/excelize#139]
Hi,
Many thanks for the great tool! I'm currently having an issue reading dates from a spreadsheet when using the GetCellValue api.

When reading a date in almost every date format using GetCellValue it returns a double value which corresponds to the internal excel value of the date. However when I set the date format in Excel to be '*14/02/2012' (see image) I am returned a string of the form 'dd-mm-yy'. This makes the API quite hard to use in terms of consistency. Let me know if you require any further information.

![image](https://user-images.githubusercontent.com/22873967/32051178-8fef97b8-ba4b-11e7-80de-a2e5727d6c8a.png)

Thanks,
Ben

**Comment by xuri** [comment]
Excel application adds format tag to a .xlsx document when you format through the window settings. Function `GetCellValue()` only supports a limited cell format, for the date format if the function `GetCellValue()` doesn't support the value of the type that returns double data type value.

**Comment by bvwells** [comment]
Many thanks for your fast response. So is the expected behaviour that this API will return the date in the string format  'dd-mm-yy' if the cell format is supported?

**Comment by bvwells** [comment]
Many thanks for your fast response. So is the expected behaviour that this API will return the date in whatever format is specified in Excel?

I now understand that the internal excel value is only returned if the date format is not supported. Is there anyway to determine that this is an unsupported date format?

**Comment by xuri** [comment]
Sorry for mat late reply, this issue has been fixed since [v2.3.2](https://github.com/xuri/excelize/releases/tag/v2.3.2).
