### ISSUE TITLE
How does excel insert svg files

### ISSUE THREAD

**Issue by Lee-Zhang-997** [qax-os/excelize#1390]
How does excel insert svg files

**Comment by xuri** [comment]
I have added insert SVG format images support for the [`AddPicture`](https://pkg.go.dev/github.com/xuri/excelize/v2#File.AddPicture) function on commit [`db2d084`](https://github.com/xuri/excelize/commit/db2d084ada1a08a48967506b2f1852062168deec). Please upgrade to the master branch code. It would help if you used a custom image parser or third part SVG library to parse the image properties, for example:

```go
import (
    "image"

    "github.com/xuri/excelize/v2"
)
```

```go
f := excelize.NewFile()
decode := func(r io.Reader) (image.Image, error) { return nil, nil }
decodeConfig := func(r io.Reader) (image.Config, error) {
    return image.Config{Height: 100, Width: 90}, nil
}
image.RegisterFormat("svg", "", decode, decodeConfig)
err := f.AddPicture("Sheet1", "A1", "image.svg", `{"x_scale": 2.1}`)
```

This feature will be released in the next version. Note that Office Excel has supported SVG format images since version 2016 and later when you open the generated workbook which contains an SVG image, it will be displayed as a fallback placeholder or can not normally display in the previous version of Excel. There is the Chinese version [release note preview](https://xuri.me/excelize/zh-hans/releases/v2.7.0.html) of the next release version for your information.

**Comment by Lee-Zhang-997** [comment]
Use the above code to report an error ：unsupported image extension


> I have added insert SVG format images support for the [`AddPicture`](https://pkg.go.dev/github.com/xuri/excelize/v2#File.AddPicture) function on commit [`db2d084`](https://github.com/xuri/excelize/commit/db2d084ada1a08a48967506b2f1852062168deec). Please upgrade to the master branch code. It would help if you used a custom image parser or third part SVG library to parse the image properties, for example:
> 
> ```go
> import (
>     "image"
> 
>     "github.com/xuri/excelize/v2"
> )
> ```
> 
> ```go
> f := excelize.NewFile()
> decode := func(r io.Reader) (image.Image, error) { return nil, nil }
> decodeConfig := func(r io.Reader) (image.Config, error) {
>     return image.Config{Height: 100, Width: 90}, nil
> }
> image.RegisterFormat("svg", "", decode, decodeConfig)
> err := f.AddPicture("Sheet1", "A1", "image.svg", `{"x_scale": 2.1}`)
> ```
> 
> This feature will be released in the next version. Note that Office Excel has supported SVG format images since version 2016 and later when you open the generated workbook which contains an SVG image, it will be displayed as a fallback placeholder or can not normally display in the previous version of Excel. There is the Chinese version [release note preview](https://xuri.me/excelize/zh-hans/releases/v2.7.0.html) of the next release version for your information.


Use the above code to report an error ：unsupported image extension

**Comment by xuri** [comment]
Did you upgrade to the master branch code? You can upgrade to the master branch code by the following command:

```shell
go get -v github.com/xuri/excelize/v2@master
```

**Comment by Lee-Zhang-997** [comment]
> Did you upgrade to the master branch code? You can upgrade to the master branch code by the following command:
> 
> ```shell
> go get -v github.com/xuri/excelize/v2@master
> ```

Sorry, I forgot to use master, that's all right now, thank you very much

**Comment by Lee-Zhang-997** [comment]
go get github.com/xuri/excelize/v2@master
go get: upgraded github.com/xuri/excelize/v2 v2.6.0 => v2.6.2-0.20221111161623-bd5dd17673f7
go get: upgraded golang.org/x/sync v0.0.0-20210220032951-036812b2e83c => v0.0.0-20220722155255-886fb9371eb4
go get: upgraded golang.org/x/sys v0.1.0 => v0.2.0

**Comment by Lee-Zhang-997** [comment]
go get github.com/xuri/excelize/v2@master
go get: upgraded github.com/xuri/excelize/v2 v2.6.0 => v2.6.2-0.20221111161623-bd5dd17673f7
go get: upgraded golang.org/x/sync v0.0.0-20210220032951-036812b2e83c => v0.0.0-20220722155255-886fb9371eb4
go get: upgraded golang.org/x/sys v0.1.0 => v0.2.0

**Comment by Lee-Zhang-997** [comment]
go get github.com/xuri/excelize/v2@master

Go get: upgraded github.com/xuri/excelize/v2 v2.6.0 = > v2.6.2-0.20221111161623 - bd5dd17673f7

go get: upgraded golang.org/x/sync v0.0.0-20210220032951-036812b2e83c => v0.0.0-20220722155255-886fb9371eb4

go get: upgraded golang.org/x/sys v0.1.0 => v0.2.0



Golang.org/x/sys adopted go 1.7, but my version is 1.6, no unsafe. Slice this method, golang.org/x/sys@v0.2.0/unix/syscall.go:83:16: undefined: unsafe.Slice

**Comment by Lee-Zhang-997** [comment]
replace (
	golang.org/x/sys => golang.org/x/sys v0.0.0-20211216021012-1d35b9e2eb4e
)

You can replace it with this and fix the error，Thanks to the author
