### ISSUE TITLE
FORMULA ADDRESS has some error

### ISSUE THREAD

**Issue by devloppper** [qax-os/excelize#1396]
show the code
the func need col,row but address transmits col,col
![image](https://user-images.githubusercontent.com/76152313/203076879-f0017f36-d0af-4fc0-ae3b-e7c536496902.png)
![image](https://user-images.githubusercontent.com/76152313/203076927-a86b3b57-e82c-4de9-822c-f67b4fe88064.png)

**Comment by xuri** [comment]
Thanks for your feedback. Would you like to create a pull request to fix it? or I'll fix it recently.

**Comment by devloppper** [comment]
OK, I am willing to do that

**Comment by devloppper** [comment]
> 

OK, I am willing to do that
