### ISSUE TITLE
Generate Large file

### ISSUE THREAD

**Issue by Evgengrmit** [qax-os/excelize#1399]
Hi! We generate a large xlsx file that writes data to the workbook, and then send it to the ceph storage. However, we fall with the error out of memory. How do I fix this with StreamWriter ?

**Comment by xuri** [comment]
Thanks for your feedback. Which version of Excelize are you using, how many cells have been written in your spreadsheet, and how much memory usage? Here are some performance figures for your reference: [Performance Figures](https://xuri.me/excelize/ru/performance.html), please try using the last version, and here is documentation about [the stream writer](https://xuri.me/excelize/ru/stream.html#NewStreamWriter)

**Comment by Evgengrmit** [comment]
I am using the latest version github.com/xuri/excelize/v2 v2.6.1 from go.mod. Thanks for the detailed documentation. According to her, I did. And used StreamWriter. Please take a look at the implementation of the methods of the feedJobItemReportExcelize structure. Unfortunately, prof shows more memory usage than in the tealeg/xlsx library. 2 sheets of 4500 rows and 6 columns are generated. But this is just a simple option. There may be more lines

**Comment by Evgengrmit** [comment]
Xslx memory use
total: 37925992
mallocs: 451812
excelize memory use
total: 72764176
mallocs: 1103191

**Comment by xuri** [comment]
The stream writer holds cell data in memory when less or equal to 16MB, the cell data will be stored in temporary files if over this limit, which can save the memory usage for large-scale data generation.

**Comment by Evgengrmit** [comment]
That is, everything is fine in the program and I don't have to worry about increasing memory. Excelize itself will write to temporary files when the size becomes larger than 16 megabytes?

**Comment by xuri** [comment]
To be exact, the temporary files will be generated when the file size of each worksheet file is over 16MB. The total memory usage will be more than it, but that will be using much less memory than loading all sheet data in memory. Just give a test using the example codes in the documentation or benchmark scripts if you like.

**Comment by Evgengrmit** [comment]
Thank you
