### ISSUE TITLE
GetCellType returns numeric value.

### ISSUE THREAD

**Issue by VinceLewis** [qax-os/excelize#1400]
Hi, I'm using this code (below). Cell A1 in that sheet is a string containing the words "User ID".
When I run this code I get typ=5 and I am expecting typ="string"

package main
import (
//	"context"
	"log"
	"github.com/xuri/excelize/v2"
	)

func importExcel(xls string) {
f, err := excelize.OpenFile(xls)
if err != nil {
	log.Println("could not open file ",xls)
	log.Println(err.Error)
    return
}

defer f.Close()

// first off, check the file 
val,err:=f.GetCellValue("Data","A1")
log.Println("Data A1 is ",val)
typ,err:=f.GetCellType("Data","A1")
log.Println("typ A1 is ",typ)
}

**Comment by xuri** [comment]
The [`CellType`](https://github.com/xuri/excelize/blob/dde6b9c00135cefffdd9c64b7f22cfdc34c28e47/cell.go#L35) using `itoa` data type represents the cell data type enumeration, the value 5 means which is an inline string.

**Comment by xuri** [comment]
The [`CellType`](https://github.com/xuri/excelize/blob/dde6b9c00135cefffdd9c64b7f22cfdc34c28e47/cell.go#L35) using `itoa` data type represents the cell data type enumeration, the value 5 means which is an inline string.

**Comment by VinceLewis** [comment]
ah ok, it's just all the examples I saw online seemed to return a string result.
Many thanks for speedy reply.
