### ISSUE TITLE
How to read cells value in a custom way

### ISSUE THREAD

**Issue by endingman** [qax-os/excelize#1409]
![Screenshot 2022-12-01 173357](https://user-images.githubusercontent.com/16915802/205017653-55fe8a77-e892-4237-921d-e8ba533d42a1.png)
可以直接读取生成
[
  {
   'name': xxx2,
   'email': xxxx1@emal.com
   ...
  },
  {
   'name': xxx2,
   'email': xxxx2@emal.com
   ...
  },
...
]
这样的结构吗？

**Comment by xuri** [comment]
Here is the documentation for your information. You can read worksheet cells row by row with a [row iterator](https://xuri.me/excelize/en/sheet.html#Rows), or column by column with [column iterator](https://xuri.me/excelize/en/sheet.html#Cols) and also support can get all cells matrix by [`GetRows`](https://xuri.me/excelize/en/cell.html#GetRows), and then read them in any way as your need.

**Comment by xuri** [comment]
I closed this issue. Please let me know if you have any questions, and reopen this anytime.
