### ISSUE TITLE
Excel's celll format does not support numeric types

### ISSUE THREAD

**Issue by kkkilo** [qax-os/excelize#1411]
## Background
We need to use excel to display a large amount of data, including percentages, decimals, currency, time, and text.
## Problem
The “decimal” cannot control the number of digits and the format is not a decimal
(the below picture shows what I want)
<img width="440" alt="image" src="https://user-images.githubusercontent.com/47410712/205256701-a51a6eb3-05ee-4a86-9cb4-e3549d84e0eb.png">
but most of them(I mean all the numFmt ID I test) shows "custom"
I know use "customNumFmt" can control the number of digits but the format is "custom"!

Thanks!

**Comment by xuri** [comment]
Thanks for your feedback. But sorry, I don't understand what you exactly mean. This problem may be similar to issue #705, and you can use build-in number format ID 2 for the numeric data type values. You can find more built-in number format mapping details in the [documentation](https://xuri.me/excelize/en/style.html#number_format).

**Comment by kkkilo** [comment]
I am so sorry that my English is poor, the more detail is below:
 I used to use number format ID 2:
![image](https://user-images.githubusercontent.com/47410712/205320509-b3beb541-0b44-422a-9289-b2b1a3545190.png)

 At the same time, all the built-in numFmts can not control the digits's decimal places, it always 2 places!
 
 Thanks for answer!

**Comment by xuri** [comment]
Please use the custom number format for the Kingsoft WPS, but which will incompatible with Microsoft Excel for Mac:

```go
customNumFmt := "0.00_ "
styleID, err := f.NewStyle(&excelize.Style{CustomNumFmt: &customNumFmt})
if err != nil {
    fmt.Println(err)
    return
}
```

**Comment by kkkilo** [comment]
the code you pin seems don't work, it shows the format is "General". 
<img width="669" alt="image" src="https://user-images.githubusercontent.com/47410712/205478680-1a0cd578-f091-40d1-9e92-8bcd069749b0.png">
( the format "0.00_" seems invalid?)
<img width="637" alt="image" src="https://user-images.githubusercontent.com/47410712/205478851-e105ca3d-4287-48a8-aa74-9adb5ad36b85.png">

btw my wps is kingsoft.

**Comment by xuri** [comment]
Which version of Excelize library and Kingsoft WPS are you using?

**Comment by kkkilo** [comment]
exelize: 1.4.1
wps 4.4.2

**Comment by xuri** [comment]
It seems your provided Kingsoft WPS version is incorrect, version 4.4.2 was released in 2001, which does not support the spreadsheet in xlsx format, I have tested with version 11.1.0.12763, and it works well.

**Comment by kkkilo** [comment]
but I can't find any other version info in wps
<img width="312" alt="image" src="https://user-images.githubusercontent.com/47410712/205502997-af41c2ae-062f-4a15-9888-82c53a40711f.png">
（when I click the update button, it shows the wps is the newest version🥺）

**Comment by xuri** [comment]
Thanks for your feedback. Here is an example for you reference, and it works on WPS Office for Mac:

```go
package main

import (
    "fmt"

    "github.com/xuri/excelize/v2"
)

func main() {
    f := excelize.NewFile()
    defer func() {
        if err := f.Close(); err != nil {
            fmt.Println(err)
        }
    }()
    if err := f.SetCellValue("Sheet1", "A1", 23.455667); err != nil {
        fmt.Println(err)
        return
    }
    customNumFmt := "0.00_ "
    styleID, err := f.NewStyle(&excelize.Style{CustomNumFmt: &customNumFmt})
    if err != nil {
        fmt.Println(err)
        return
    }
    if err := f.SetCellStyle("Sheet1", "A1", "A1", styleID); err != nil {
        fmt.Println(err)
        return
    }
    if err := f.SaveAs("Book1.xlsx"); err != nil {
        fmt.Println(err)
    }
}
```

**Comment by xuri** [comment]
It seems still not have enough info or feedback for this issue, so I'll close this issue, if you have any questions, please let me know to reopen this anytime.

**Comment by kkkilo** [comment]
The question has been resolved. and the code did work!  Thanks a lot!!!  ❤️
