### ISSUE TITLE
How to set different styles for different string lines in a cell?

### ISSUE THREAD

**Issue by Shinefallen** [qax-os/excelize#1412]
For Example:
![image](https://user-images.githubusercontent.com/37903181/205438603-5d101c6e-083b-4f6a-9b4a-0f0fc17e1286.png)

I need to change the style from the left one to the right one. But i just find SetCellStyle to change the color for the whole cell.
Is there any way to do this? 
Thanks a lot.

**Comment by xuri** [comment]
This duplicate with issues #100, #172, and #242, please reference the documentation and use the [`SetCellRichText`](https://xuri.me/excelize/en/cell.html#SetCellRichText) function, and the set the wrap style for the rich text cell.

**Comment by xuri** [comment]
I closed this issue. Please let me know if you have any questions, and reopen this anytime.
