### ISSUE TITLE
StreamWriter should support OutlineLevel

### ISSUE THREAD

**Issue by Bayzet** [qax-os/excelize#1416]
Description

It's possible to set a worksheet's OutlineLevel using the regular API but not the streamwriter. This issue is meant to track this change.

**Comment by Bayzet** [comment]
I add changes that require editing in the documentation. How can i do this? I can’t find where to edit the documentation, if I understand correctly, then we are talking about the full documentation at the link https://xuri.me/excelize/en

**Comment by xuri** [comment]
Thanks for your issue. There is the contribution guide for your information, the documentation repository is open-source, and contributions are welcome. I'll certainly accept this feature patch if you did that, and the docs for this feature should be updated before the next version release.

**Comment by xuri** [comment]
Thanks for your issue. There is [the contribution guide](https://xuri.me/excelize/en/contribution.html) for your information, the documentation repository is open-source, and contributions are welcome. I'll certainly accept this feature patch if you did that, and the docs for this feature should be updated before the next version release.
