### ISSUE TITLE
AddPicture automatically change the ratio of picture without any format

### ISSUE THREAD

**Issue by Noah-Chiu** [qax-os/excelize#1419]
**Description**

**Steps to reproduce the issue:**
1.file.AddPicture("Sheet1", "F8", "image.jpg", ``)
2.Save and open the excel to check format of picture

It automatically change the ratio of my picture, that cause the x_scale and y_scale or other format are not work expectedly.

**Describe the results you received:**
![image](https://user-images.githubusercontent.com/48880952/206664359-06701e54-34c1-4ddd-b0e0-c2d9d49afd7f.png)

**Describe the results you expected:**
![image](https://user-images.githubusercontent.com/48880952/206664445-372a690f-13fa-4207-9bf3-ef7c9af3813a.png)

**Output of `go version`:**

```text
go 1.17
```

**Excelize version or commit ID:**

```text
v2.6.1
```

**Environment details (OS, Microsoft Excel™ version, physical, etc.):**

**Comment by xuri** [comment]
Thanks for your issue. This is related to #260 and #279. The actual image size may be inconsistent between different spreadsheet applications. For example, the image scale shows 100% in Microsoft Excel 2007 and 2010 but not in Microsoft Excel 2016. The reason for that was columns width and row height depend on the display device resolution, so please adjust the image scale manually to fit your priority environments. I think this issue can be closed, and merged into #260 to continue to discuss this problem.

**Comment by xuri** [comment]
I closed this issue. Please let me know if you have any questions, and reopen this anytime.
