### ISSUE TITLE
GetCellValue error (formatting problem?)

### ISSUE THREAD

**Issue by j0hnsmith** [qax-os/excelize#1420]
`GetCellValue()` is returning an incorrect value, due to a formatting problem I think.

**Steps to reproduce the issue:**
[get_cell_value.xlsx](https://github.com/qax-os/excelize/files/10194277/get_cell_value.xlsx)

`B3` has the value `62630346.9173956`, formatted as number with 0 decimal places and commas
`C3` has the formula `=B3`, formatted as number with 0 decimal places and commas
Excel shows `62,347,347`

<img width="250" alt="Screenshot 2022-12-09 at 11 28 47" src="https://user-images.githubusercontent.com/118963/206692816-616db204-906a-4688-b660-76e8d94ecb2e.png">

```
v, err := ef.GetCellValue("Sheet1", "C3") // no error is returned, omitting check for brevity
fmt.Println(v) // 62630346 s/be 62630347
```
**Describe the results you received:**
`"62630346"`

**Describe the results you expected:**
`"62,630,347"` (with commas as I can see in excel) or even `"62630347"`

I get the same result with `ef.GetCellValue("Sheet1", "B3")`

**Output of `go version`:**

```text
go version go1.19.3 darwin/arm64
```

**Excelize version or commit ID:**

```text
github.com/xuri/excelize/v2 v2.6.1
```

**Comment by j0hnsmith** [comment]
I started to debug, was going to add details of where the problem is then realised this has been fixed in master... @xuri please push a new release 😄

**Comment by xuri** [comment]
Thanks for your issue. The next stable [version of Excelize](https://github.com/xuri/excelize/projects?type=classic&query=) v2.7.0 will be released on January 9, 2023. This is the [release note preview](https://xuri.me/excelize/en/releases/v2.7.0.html). The content of it will be kept updated before the release. Welcome to upgrade to the master branch code to participate in testing and feedback issues.
