### ISSUE TITLE
MS Excel can not open when using 'AddComment' func

### ISSUE THREAD

**Issue by fengkai** [qax-os/excelize#1423]
When using 
`f.AddComment("Sheet","A2", {"author":"","text":"xxx"})`

It works fine in WPS, but i can not open it in MS Excel, it shows: 

"发现"xxx.xlsx”中的部分内容有问题。是否让我们尽量尝试恢复? 如果您信任此工作簿的源，请单击“是”。"

What should i do to solve this?

**Comment by xuri** [comment]
This issue was duplicated with #1204.

**Comment by xuri** [comment]
I closed this issue. Please let me know if you have any questions, and reopen this anytime.
