### ISSUE TITLE
When setting sheetName, trimSheetName is used by default to remove invalid characters; this always feels unreasonable

### ISSUE THREAD

**Issue by guoweikuang** [qax-os/excelize#1425]
If the user sets a sheetName that includes invalid characters, a clear error message should be given instead of silently removing invalid characters (trimSheetName function), which is prone to errors and confuses users. And trimSheetName has no comment content yet

Similar to wps will give a clear prompt, and the setting is unsuccessful:
<img width="806" alt="image" src="https://user-images.githubusercontent.com/12684035/208647733-0941ef00-91db-4e21-814e-9c406d56ae1e.png">

**Comment by xuri** [comment]
Thanks for your suggestion. I agree with you, and I will consider making some changes to this, and contributions are welcome.
