### ISSUE TITLE
picture insert style error

### ISSUE THREAD

**Issue by zhujunjie-c** [qax-os/excelize#1427]
**Description**
when i try to insert more than three pictures in a cell, there is a style mixed in the cell, the third picture will fill the whole cell and the other left picture which are more than 3 their width would be 0

**Steps to reproduce the issue:**
1.
2.
3.

**Describe the results you received:**

**Describe the results you expected:**

**Output of `go version`:**

```text
(paste your output here)
```

**Excelize version or commit ID:**

```text
(paste here)
```

**Environment details (OS, Microsoft Excel™ version, physical, etc.):**

**Comment by zhujunjie-c** [comment]
![image](https://user-images.githubusercontent.com/32892505/208945191-8a8aa0da-ba61-4d03-a582-7c4f2fd24875.png)
and i user the code 
```
format := fmt.Sprintf(`{"x_offset":%d,"y_scale": %f,"x_scale": %f}`, int(count), rateHeight, rateHeight)
					err = f.AddPictureFromBytes(consts.DefaultSheetName, cell, format, fileName, ".jpeg", recordInfo.Value)
```

**Comment by xuri** [comment]
Which version of Excelize library are you using? What's the value of variables `count`, `rateHeight`, `recordInfo` and etc. in your code? Can you show us a **complete**, standalone example program or reproducible demo or detail the issue by the **issue template**?

**Comment by xuri** [comment]
It seems still not have enough info of code and attachments to reproduce this issue, so I'll close this issue, if you have any questions, please let me know to reopen this anytime.
