### ISSUE TITLE
StreamWriter to S3 or any other object storage.

### ISSUE THREAD

**Issue by dgkrivenko** [qax-os/excelize#1429]
Is it impossible to create StreamWriter for streaming to object storage like s3 in the latest version? Is it difficult to implement?

**Comment by xuri** [comment]
Thanks for your issue. The stream writer is used to generate a worksheet with the amount of data, which is not used for writing data to `io.Writer`, please use the [`Write`](https://pkg.go.dev/github.com/xuri/excelize/v2@v2.6.1#File.Write) or [`WriteTo`](https://pkg.go.dev/github.com/xuri/excelize/v2@v2.6.1#File.WriteTo) function.

**Comment by dgkrivenko** [comment]
I need to generate a worksheet with the amount of data but i don't want to save file on disk (even temporary). Is it possible to send file in batches to external storage during generation and don't load it into RAM entirely? As I understand, the function [Write](https://pkg.go.dev/github.com/xuri/excelize/v2@v2.6.1#File.Write) load full file in memory and i can't send file send file partially

**Comment by xuri** [comment]
Sorry, that's no possible. I think this issue was similar with issue #753 and #1052.

**Comment by dgkrivenko** [comment]
Thank you!
