### ISSUE TITLE
Can support v tag in formula cell 

### ISSUE THREAD

**Issue by RickyJian** [qax-os/excelize#1430]
## Description

When I read formula value from file which generated from excelize, we should use `CalcCellValue` function to read value. 

But read file from google, we can directly read value when row iterate.

I find a different from our file and google exported. The `<v>` tag helps us directly read cell value.

Can support `<v>` tag for formula cell when save file?

below xml from library

```xml
<row r="6">
  <c r="A6">
    <f>SUM(A1:A5)</f>
  </c>
</row>
```

below xml from google

```xml
<row r="6">
  <c r="A6" s="1">
    <f>SUM(A1:A5)</f>
    <v>5</v>
  </c>
</row>
```

### full code

```go
package main

import (
	"fmt"
	"log"

	"github.com/xuri/excelize/v2"
)

func main() {
	readLibraryFile()
	readGoogleFile()
}

const (
	sheetName       = "Sheet1"
	formulaCellName = "A6"
)

func readLibraryFile() {
	f, err := excelize.OpenFile("library.xlsx")
	if err != nil {
		log.Fatalf("read file error: %v", err)
	}

	rows, err := f.GetRows(sheetName)
	if err != nil {
		log.Fatalf("read row error: %v", err)
	}

	for rowIdx, row := range rows {
		for cellIdx, cell := range row {
			cellname, err := excelize.CoordinatesToCellName(cellIdx+1, rowIdx+1)
			if err != nil {
				log.Fatalf("get cell name error: %v", err)
			}
			// when we generate from library and cell is formula,
			// we need to use `CalcCellValue` to get cell value
			if cellname == formulaCellName {
				formula, err := f.GetCellFormula(sheetName, cellname)
				if err != nil {
					log.Fatalf("get cell formula err: %v", err)
				}
				fmt.Printf("get data from read rows, formula: %s, value: %s\n", formula, cell) // cell is empty
				value, err := f.CalcCellValue(sheetName, cellname)
				if err != nil {
					log.Fatalf("calculate formula error: %v", err)
				}
				fmt.Printf("get data from calc cell value, formula: %s, value: %s\n", formula, value)
			}
		}
	}
}

func readGoogleFile() {
	f, err := excelize.OpenFile("google.xlsx")
	if err != nil {
		log.Fatalf("read file error: %v", err)
	}

	rows, err := f.GetRows(sheetName)
	if err != nil {
		log.Fatalf("read row error: %v", err)
	}

	for rowIdx, row := range rows {
		for cellIdx, cell := range row {
			cellname, err := excelize.CoordinatesToCellName(cellIdx+1, rowIdx+1)
			if err != nil {
				log.Fatalf("get cell name error: %v", err)
			}
			// when we export from google and cell is formula, we can directly get cell value
			if cellname == formulaCellName {
				formula, err := f.GetCellFormula(sheetName, cellname)
				if err != nil {
					log.Fatalf("get cell formula err: %v", err)
				}
				fmt.Printf("get data from read rows, formula: %s, value: %s\n", formula, cell) // cell is empty
			}
		}
	}
}
```
-------
## Test Files

* generate from library: [library.xlsx](https://github.com/qax-os/excelize/files/10301588/library.xlsx)

* export from google: [google.xlsx](https://github.com/qax-os/excelize/files/10301589/google.xlsx)

**Comment by xuri** [comment]
Thanks for your issue. The value of element `<v>` in the formula cell was the calculation result cache, which is an optional value. The formula result will be calculated automatically when Excel and other spreadsheet applications open the workbook generated by this library, the calculation engine of this library is still working in progress, and the feature of saving calculation result cache may be implemented after the calculation engine working finished. Currently, please get the cell type before reading the cell value, if you got a formula cell, then use the `CalcCellValue` function to calculate the cell's value.

**Comment by RickyJian** [comment]
Thanks for your replying. I don't have any questions.
