### ISSUE TITLE
Add new feature: Column Wrap Text

### ISSUE THREAD

**Issue by kpikamlesh** [qax-os/excelize#1434]
I am looking to set wrap text column property.  I have columns that may be long over 200+ characters.   I want to wrap text if any column is over 100 characters.  I did not find an way to set this property and therefore assume that this feature does not exist.

**Comment by xuri** [comment]
Thanks for your issue. Please create a wrap text style by the NewStyle function to get a style ID, and then set the style of the columns with that. For example:

```go
package main

import (
    "fmt"

    "github.com/xuri/excelize/v2"
)

func main() {
    f := excelize.NewFile()
    defer func() {
        if err := f.Close(); err != nil {
            fmt.Println(err)
        }
    }()
    styleID, err := f.NewStyle(&excelize.Style{
        Alignment: &excelize.Alignment{
            WrapText: true,
        },
    })
    if err != nil {
        fmt.Println(err)
        return
    }
    if err := f.SetColStyle("Sheet1", "A:E", styleID); err != nil {
        fmt.Println(err)
        return
    }
    if err := f.SaveAs("Book1.xlsx"); err != nil {
        fmt.Println(err)
    }
}
```

**Comment by kpikamlesh** [comment]
Thank you

**Comment by xuri** [comment]
I closed this issue, if you have any questions, please let me know to reopen this anytime.

**Comment by paustint** [comment]
Would it be possible to add this property to the docs? `Alignment` in the docs does not mention `WrapText` so I was not aware the feature existed and found this issue.

Thank you.

**Comment by xuri** [comment]
Thanks for your advice, I will update documentation website.
