### ISSUE TITLE
CalcCellValue doesn't support function TEXT

### ISSUE THREAD

**Issue by alexvr8282** [qax-os/excelize#1436]
**Description**

**Steps to reproduce the issue:**
1. in cell A1 input the value 0.05
2. in cell A2 define the following formula =TEXT(A1, "0,0%")

**Describe the results you received:**
unsupported TEXT function

**Output of `go version`:**

```text
go version go1.19.1 windows/amd64
```

**Excelize version or commit ID:**

```text
b39626fae9c2aaa648259d412a67b67e7768ad17
```

**Environment details (OS, Microsoft Excel™ version, physical, etc.):**
Windows, Excel

**Comment by xuri** [comment]
Thanks for your issue. This issue was a part of issue #65, the `TEXT` formula function doesn't implement yet, the formula engine still working in progress, and the supported formula functions were listed in the documentation of the `CalcCellValue` function.

**Comment by xuri** [comment]
I have just added the TEXT formula function support on the master branch. Please try to upgrade the master branch code, and this feature will be released in the next version.
