### ISSUE TITLE
CalcCellValue - don't evalutate correct value with Formula IF with other formula inside

### ISSUE THREAD

**Issue by alexvr8282** [qax-os/excelize#1438]
**Description**

**Steps to reproduce the issue:**
1. in cell D142 value 2, in cell D143 value 1, in cell D144 value 1, in cell D145 value 2
2. in cell E142 define formula =AVERAGE(D142:D145)/5
3. in cell F142 define formula =IF(E142 > 0,4;"major";"minor")

**Describe the results you received:**
major
**Describe the results you expected:**
minor because the value in E142 is 0,3
**Output of `go version`:**

```text
go version go1.19.1 windows/amd64
```

**Excelize version or commit ID:**

```text
b39626fae9c2aaa648259d412a67b67e7768ad17
```

**Environment details (OS, Microsoft Excel™ version, physical, etc.):**
Windows, Excel

**Comment by xuri** [comment]
Thanks for your issue, I have fixed it. Please upgrade to the master branch code, and this patch will be released in the next version.
