### ISSUE TITLE
Some issues about Write() and SetPanes() in v2.7.0

### ISSUE THREAD

**Issue by HC-miss** [qax-os/excelize#1442]
**Description**
The following problems appeared in the v2.7 version, maybe I did not operate properly.

- In version 2.7, doing a Write type operation after calling Close() will result in file corruption.
- Using defer to call streamWriter.Flush() will also cause file corruption.
- Calling streamWriter.SetPane() to freeze the window will also cause file exceptions.

```golang
func TestExcelSave(t *testing.T) {
	file := excelize.NewFile()

	defer func() {
		if err := file.Close(); err != nil {
			fmt.Println(err)
		}
	}()

	_ = file.SetDefaultFont(DefaultFont) // 等线

	_ = file.SetSheetName("Sheet1", "Test")

	streamWriter, err := file.NewStreamWriter("Test")
	if err != nil {
		fmt.Println(err)
	}

	//defer func() {
	//	fmt.Println("终止流式写入")
	//	if err := streamWriter.Flush(); err != nil {
	//		fmt.Println(err)
	//	}
	//}()

	// 冻结首行 冻结不起作用 会在v2.7.0版本中增加流式写入的冻结功能 必须在SetRow之前调用
	//err = streamWriter.SetPanes(&excelize.Panes{
	//	Freeze: true,
	//	Split:  false,
	//	XSplit: 0,
	//	YSplit: 2,
	//})
	//
	//if err != nil {
	//	fmt.Println(err)
	//	return
	//}

	style, _ := file.NewStyle(&excelize.Style{
		Border: []excelize.Border{
			{
				Type:  "top",
				Color: "FF0000",
				Style: 1,
			},
			{
				Type:  "bottom",
				Color: "FF0000",
				Style: 1,
			},
		},
		Alignment: &excelize.Alignment{
			Horizontal: "center",
			Vertical:   "center",
			WrapText:   true,
		},
	})

	if err := streamWriter.SetRow("A1",
		[]interface{}{"RowA", "RowB", "RowC", "RowD", "RowE", "RowF", "RowG", "RowH", "RowI"},
		excelize.RowOpts{Height: 25, StyleID: style}); err != nil {
		fmt.Println(err)
	}

	rowStyle, _ := file.NewStyle(&excelize.Style{
		Font: &excelize.Font{
			Family: DefaultFont,
			Size:   11,
		},
		Alignment: &excelize.Alignment{
			Horizontal: "center",
			Vertical:   "center",
			WrapText:   true,
		},
	})

	for rowID := 2; rowID <= 24; rowID++ {
		row := make([]interface{}, 9)
		for colID := 0; colID < 9; colID++ {
			row[colID] = rand.Intn(640000)
		}
		cell, _ := excelize.CoordinatesToCellName(1, rowID)
		if err := streamWriter.SetRow(cell, row, excelize.RowOpts{Height: 25, StyleID: rowStyle}); err != nil {
			fmt.Println(err)
		}
	}

	// defer Flush 导致文件异常
	if err := streamWriter.Flush(); err != nil {
		fmt.Println(err)
	}

	// 提前Close会导致文件异常
	//file.Close()

	if err := file.SaveAs("Book1.xlsx"); err != nil {
		fmt.Println(err)
	}
}
```

**Steps to reproduce the issue:**

**Describe the results you received:**
![Snipaste_2023-01-10_11-38-42](https://user-images.githubusercontent.com/40908362/211456821-c9ef697c-8a92-467a-b89a-3c92724aa2b7.png)

**Describe the results you expected:**
normal file

**Output of `go version`:**

```text
go version go1.18 windows/amd64
```

**Excelize version or commit ID:**

```text
v2.7.0
```

**Environment details (OS, Microsoft Excel™ version, physical, etc.):**
win11. excel2019

**Comment by xuri** [comment]
Thanks for your issue. About the first 2 problems, because the order of function call should be `Flush` -> `Save` -> `Close`, you need to put the save function after the flush function in defer. The third problem about panes, as the documentation says, you must call the `SetPanes` function before the `SetRow` function, and don't forget to specify the `TopLeftCell` of the panes. Finally, the work's code is like this:

```go
func TestExcelSave(t *testing.T) {
    file := excelize.NewFile()

    defer func() {
        if err := file.Close(); err != nil {
            fmt.Println(err)
        }
    }()

    _ = file.SetDefaultFont(DefaultFont) // 等线

    _ = file.SetSheetName("Sheet1", "Test")

    streamWriter, err := file.NewStreamWriter("Test")
    if err != nil {
        fmt.Println(err)
    }

    defer func() {
        fmt.Println("终止流式写入")
        if err := streamWriter.Flush(); err != nil {
            fmt.Println(err)
        }
        if err := file.SaveAs("Book1.xlsx"); err != nil {
            fmt.Println(err)
        }
    }()

    if err = streamWriter.SetPanes(&excelize.Panes{
        Freeze:      true,
        Split:       false,
        XSplit:      0,
        YSplit:      1,
        TopLeftCell: "A2",
    }); err != nil {
        fmt.Println(err)
        return
    }

    style, _ := file.NewStyle(&excelize.Style{
        Border: []excelize.Border{
            {
                Type:  "top",
                Color: "FF0000",
                Style: 1,
            },
            {
                Type:  "bottom",
                Color: "FF0000",
                Style: 1,
            },
        },
        Alignment: &excelize.Alignment{
            Horizontal: "center",
            Vertical:   "center",
            WrapText:   true,
        },
    })

    if err := streamWriter.SetRow("A1",
        []interface{}{"RowA", "RowB", "RowC", "RowD", "RowE", "RowF", "RowG", "RowH", "RowI"},
        excelize.RowOpts{Height: 25, StyleID: style}); err != nil {
        fmt.Println(err)
    }

    rowStyle, _ := file.NewStyle(&excelize.Style{
        Font: &excelize.Font{
            Family: DefaultFont,
            Size:   11,
        },
        Alignment: &excelize.Alignment{
            Horizontal: "center",
            Vertical:   "center",
            WrapText:   true,
        },
    })

    for rowID := 2; rowID <= 24; rowID++ {
        row := make([]interface{}, 9)
        for colID := 0; colID < 9; colID++ {
            row[colID] = rand.Intn(640000)
        }
        cell, _ := excelize.CoordinatesToCellName(1, rowID)
        if err := streamWriter.SetRow(cell, row, excelize.RowOpts{Height: 25, StyleID: rowStyle}); err != nil {
            fmt.Println(err)
        }
    }
}
```

**Comment by HC-miss** [comment]
> Thanks for your issue. About the first 2 problems, because the order of function call should be `Flush` -> `Save` -> `Close`, you need to put the save function after the flush function in defer. The third problem about panes, as the documentation says, you must call the `SetPanes` function before the `SetRow` function, and don't forget to specify the `TopLeftCell` of the panes. Finally, the work's code is like this:
> 
> ```go
> func TestExcelSave(t *testing.T) {
>     file := excelize.NewFile()
> 
>     defer func() {
>         if err := file.Close(); err != nil {
>             fmt.Println(err)
>         }
>     }()
> 
>     _ = file.SetDefaultFont(DefaultFont) // 等线
> 
>     _ = file.SetSheetName("Sheet1", "Test")
> 
>     streamWriter, err := file.NewStreamWriter("Test")
>     if err != nil {
>         fmt.Println(err)
>     }
> 
>     defer func() {
>         fmt.Println("终止流式写入")
>         if err := streamWriter.Flush(); err != nil {
>             fmt.Println(err)
>         }
>         if err := file.SaveAs("Book1.xlsx"); err != nil {
>             fmt.Println(err)
>         }
>     }()
> 
>     if err = streamWriter.SetPanes(&excelize.Panes{
>         Freeze:      true,
>         Split:       false,
>         XSplit:      0,
>         YSplit:      1,
>         TopLeftCell: "A2",
>     }); err != nil {
>         fmt.Println(err)
>         return
>     }
> 
>     style, _ := file.NewStyle(&excelize.Style{
>         Border: []excelize.Border{
>             {
>                 Type:  "top",
>                 Color: "FF0000",
>                 Style: 1,
>             },
>             {
>                 Type:  "bottom",
>                 Color: "FF0000",
>                 Style: 1,
>             },
>         },
>         Alignment: &excelize.Alignment{
>             Horizontal: "center",
>             Vertical:   "center",
>             WrapText:   true,
>         },
>     })
> 
>     if err := streamWriter.SetRow("A1",
>         []interface{}{"RowA", "RowB", "RowC", "RowD", "RowE", "RowF", "RowG", "RowH", "RowI"},
>         excelize.RowOpts{Height: 25, StyleID: style}); err != nil {
>         fmt.Println(err)
>     }
> 
>     rowStyle, _ := file.NewStyle(&excelize.Style{
>         Font: &excelize.Font{
>             Family: DefaultFont,
>             Size:   11,
>         },
>         Alignment: &excelize.Alignment{
>             Horizontal: "center",
>             Vertical:   "center",
>             WrapText:   true,
>         },
>     })
> 
>     for rowID := 2; rowID <= 24; rowID++ {
>         row := make([]interface{}, 9)
>         for colID := 0; colID < 9; colID++ {
>             row[colID] = rand.Intn(640000)
>         }
>         cell, _ := excelize.CoordinatesToCellName(1, rowID)
>         if err := streamWriter.SetRow(cell, row, excelize.RowOpts{Height: 25, StyleID: rowStyle}); err != nil {
>             fmt.Println(err)
>         }
>     }
> }
> ```

Thanks a bunch
