### ISSUE TITLE
Latest release and my code issue

### ISSUE THREAD

**Issue by kpikamlesh** [qax-os/excelize#1444]
Hi,
I noticed you have made some significant changes.  I am not an expert Go programmer.  Only consider myself casual programmer as I don't code full time.  I use Golang for integration and audits.
Much of my code will require rewrite with your latest release.  I am sure there is a way for me to point to working Excelize module.  The module that was before you latest release.

Can you help me or point me to how I would point my code to use the prior Excelize modules?  I am on Windows platform.

Thank you
Kamlesh

**Comment by xuri** [comment]
Thanks for your issue. If your Go language version is 1.11 and later, you can lock a specific version of Excelize by [Go Module](https://go.dev/blog/using-go-modules). For example, install v2.6.1:

```bash
go install github.com/xuri/excelize/v2@v2.6.1
```

**Comment by atc0005** [comment]
@xuri Recommendation: When the API is changed (e.g., function signatures, function names, exported/unexported visibility) consider releasing the next version as a new major version.

The expectation is that a minor version bump (e.g., v2.6.1 to v2.7.0) will not break existing client code, but a major version bump communicates that client code will need to be adjusted to use the new version.

**Comment by xuri** [comment]
Thanks for your advice, sorry for bringing you confusion. I will follow the semantic version in the future versions released. I closed this issue, if you have any questions, please let me know to reopen this anytime.
