### ISSUE TITLE
expected element <theme> in name space

### ISSUE THREAD

**Issue by bourne-3** [qax-os/excelize#1447]
**Description**
Hi. I use the package to read a excel and encounter the err report like this
```
expected element <theme> in name space http://schemas.openxmlformats.org/drawingml/2006/main but have http://purl.oclc.org/ooxml/drawingml/main
```
The file i use is a xlsx format file which i save as from a csv file.

code below:
```
	f, err := excelize.OpenFile("inventory.xlsx")
	if err != nil {
		fmt.Println(err)
		return
	}
	defer func() {
		if err := f.Close(); err != nil {
			fmt.Println(err)
		}
	}()

	// 获取 Sheet1 上所有单元格
	rows, err := f.GetRows("sheet1")
	if err != nil {
		fmt.Println(err)
		return
	}
	for _, row := range rows {
		for _, colCell := range row {
			fmt.Print(colCell, "\t")
		}
		fmt.Println()
	}

```
any suggestion?

**Comment by xuri** [comment]
Thanks for your feedback. Please provide your input file attachment without confidential info if you can.

**Comment by bourne-3** [comment]
[sample_origin.csv](https://github.com/qax-os/excelize/files/10398131/sample_origin.csv)
[sample_save_as_xlsx.xlsx](https://github.com/qax-os/excelize/files/10398133/sample_save_as_xlsx.xlsx)

The files i use are shown above. Please check

**Comment by bourne-3** [comment]
> Thanks for your feedback. Please provide your input file attachment without confidential info if you can.

[sample_origin.csv](https://github.com/qax-os/excel
[sample_save_as_xlsx_format.xlsx](https://github.com/qax-os/excelize/files/10398142/sample_save_as_xlsx_format.xlsx)
ize/files/10398141/sample_origin.csv)

The files i use shown above, please check

**Comment by bourne-3** [comment]
[sample_origin.csv](https://github.com/qax-os/excelize/files/10398148/sample_origin.csv)
[sample_save_as_xlsx_format.xlsx](https://github.com/qax-os/excelize/files/10398149/sample_save_as_xlsx_format.xlsx)


The files i use shown above, please check

**Comment by xuri** [comment]
Thanks for your issue, I have fixed it. Please upgrade to the master branch code, and this patch will be released in the next version.
