### ISSUE TITLE
末尾填充问题

### ISSUE THREAD

**Issue by zuozhehao** [qax-os/excelize#1452]
![企业微信截图_16738631011750](https://user-images.githubusercontent.com/4464252/212650868-7371add8-44a7-49f1-be7b-a2763f47cd5a.png)

末尾的可以填充空值，这在循环的时候就不需要多一个判断。

**Comment by xuri** [comment]
Thanks for your feedback. This issue is duplicated with #1135, and #1245, I have already explained the reason for this design in issue #1245. I closed this issue, if you have any questions, please let me know to reopen this anytime.
