### ISSUE TITLE
Provide access to table definitions like DefinedNames

### ISSUE THREAD

**Issue by chiefgeek157** [qax-os/excelize#1454]
**Description**

It is possible to obtain the list of DefinedNames today, and that works well. In Excel (M365), Name Manager also lists defined Tables as named ranges.

In excelize, there are functions to add tables (AddTable()), but not to retrieve existing tables. Some of the private functions, such as countTables(), appear to be able to access the proper information about tables.

Ideally, existing tables should either be returned in DefinedNames() or in a new function such as Tables().

Tables are a very common structure in many Excel files, and I happen to use them extensively because of their power in providing structured references for use in formula functions such as XLOOKUP.

If this ability is already present, then I apologize for having missed it.

**Describe the results you expected:**

File.Tables() would return a list of tables defined in the workbook similar to File.DefinedNames(). The returned structure should include at least the name or the table and the reference to be useful, and ideally all the data that could be used in AddTable().

**Output of `go version`:**

```text
go version go1.19.5 Darwin/amd64
```

**Excelize version or commit ID:**

```text
require github.com/xuri/excelize/v2 v2.7.0
```

**Environment details (OS, Microsoft Excel™ version, physical, etc.):**

MacOS 12.6.2, Excel M365 current as of today

**Comment by xuri** [comment]
Thanks for your issue. The library doesn't support listing table names and ranges currently. I will consider adding this feature.

**Comment by chiefgeek157** [comment]
That would be great. I took a look and am not sure I can easily figure out the changes to add this feature, but it looks like the code already examines the tables refs in XML, so I guessing it is very close.

**Comment by taomin597715379** [comment]
The new functions GetTables. Now, we can get table name, range, style name, etc., please try to upgrade the master branch code. This feature will be released in the next version.

**Comment by taomin597715379** [comment]
The new functions `GetTables` has been added. Now, we can get table name, range, style name, etc., please try to upgrade the master branch code. This feature will be released in the next version.
