### ISSUE TITLE
High memory usage in localMonthNamesXhosa

### ISSUE THREAD

**Issue by nathj07** [qax-os/excelize#1455]
**Description**

Whilst reading XLSX files I've noticed large amounts of memory being consumed.
![pprof003](https://user-images.githubusercontent.com/3279761/214006832-e068ee59-fec2-4c58-bb86-ca857ecf631e.svg)
![pprof004](https://user-images.githubusercontent.com/3279761/214006834-4cab0242-1633-401c-b7c0-45c1c4d2f44d.svg)
![pprof007](https://user-images.githubusercontent.com/3279761/214006835-280e43c5-a1c9-4479-b5ff-d59fc411de3e.svg)
![pprof001](https://user-images.githubusercontent.com/3279761/214006827-45790017-6d3b-4285-bbc3-32472467ede3.svg)
![pprof002](https://user-images.githubusercontent.com/3279761/214006829-5e94a4f2-2d5a-4f24-ba81-942f706158fa.svg)

These pprof SVGs show where the issue appears to be - `localMonthsNameXhosa`. I have seen it for other local months names too, but Xhosa is the biggest. Sadly I do not have an XLSX file available that will reproduce this issue for you, but hopefully knowing where the high memory usage is ocurring will aid in finding a resolution.

**Output of `go version`:**

```text
go version go1.19.4 darwin/amd64
```

**Excelize version or commit ID:**

```text
github.com/xuri/excelize/v2 v2.7.0

```

**Environment details (OS, Microsoft Excel™ version, physical, etc.):**
This occurs when running in a Docker Container based on RockyLinux: 8.6 with 8G memory and 4vCPU on a K8s cluster

**Comment by dankinder** [comment]
Notably, `localMonthsNameXhosa` is one of the ones that creates new strings via concatenation, where e.g. English doesn't https://github.com/qax-os/excelize/blob/b39626fae9c2aaa648259d412a67b67e7768ad17/numfmt.go#L385

It would be quite straightforward to refactor these functions to pre-generate the abbreviation variations instead of allocating new strings. It would be good to know if the authors would welcome a PR that does that.

**Comment by xuri** [comment]
Thanks for your issue. Contributions are welcome. I'll certainly accept this patch if anybody did that.

**Comment by nathj07** [comment]
Let me know if this is not the way you want to go, can totally close this and go a different way. Or I can add to this if there are other funcs that need this treatment.
