### ISSUE TITLE
checkRow memory usage

### ISSUE THREAD

**Issue by nathj07** [qax-os/excelize#1460]
**Description**
I'm seeing large memory consumption with `rows.checkRow`. Sadly, I am unable to share the exact file we were processing.

**Describe the results you received:**

The following pprof outputs show the issue we were seeing:
![pprof001](https://user-images.githubusercontent.com/3279761/215515929-b5a948bb-6fcf-4dc2-8329-2550af7c9c7b.svg)
![pprof002](https://user-images.githubusercontent.com/3279761/215515937-43523ec6-0290-406a-98bc-fbde87bcc9d1.svg)

**Describe the results you expected:**
Ideally less ,emory used. I admit I've taken a look at the function indicated and there are no obvious improvements. So I guess I'm filing this issue in case anyone else sees a change to make.

**Output of `go version`:**

```text
go version go1.17.2 linux/amd64
```

**Excelize version or commit ID:**

```text
	github.com/xuri/excelize/v2 v2.7.1-0.20230126023513-be36b09c8a17
```

**Environment details (OS, Microsoft Excel™ version, physical, etc.):**
Running in K8s on EC@. Each pod has 8G of memory and is running one container.

**Comment by xuri** [comment]
Thanks for your issue. If you need to handle a file with an amount of data, please also consider using the stream mode functions (Row iterator for read-only, stream writer for write-only).

**Comment by xuri** [comment]
I've closed this issue, if you have any questions, please let me know to reopen this anytime.
