### ISSUE TITLE
Is there any way to set custom style on DataBar Conditional Formatting

### ISSUE THREAD

**Issue by coolseven** [qax-os/excelize#1462]
I'm trying to set custom style on a conditional formatting `data_bar`

I'm using the code like below:
```go
// my custom style
solidFillStyle, _ := f.NewConditionalStyle(&excelize.Style{Fill: excelize.Fill{Color: []string{"#A9D08E"}, Type: "pattern", Pattern: 1}})

_ = f.SetConditionalFormat(sheetAlias, someRangeRef, []excelize.ConditionalFormatOptions{{Type: "data_bar", BarColor: "#A9D08E", Format: solidFillStyle, Criteria: "=", MinType: "min", MaxType: "max"}})
```

I'm expecting the data_bar to be filled with solid color , as defined in `solidFillStyle` , 

But what I get is a gradient-filled data_bar 

Seems that it will use an internal style for data_bar, which uses gradient fill, and any custom style will just be ignored

Am I doing something wrong here ? thank you.

---
go version I'm using
```
go version go1.17.2 linux/amd64
```

lib version:
```
github.com/xuri/excelize/v2 v2.7.0
```

**Comment by xuri** [comment]
Thanks for your issue. Currently, the library doesn't support creating a conditional format with a solid color data bar style. I will consider adding this feature support in the future.

**Comment by xuri** [comment]
I have added support for creating a conditional format with a solid color data bar style. Please try to upgrade to the master branch code, and this patch will be released in the next version. Now you can specify solid color by `BarSolid` like this:

```diff
err := f.SetConditionalFormat(sheetAlias, someRangeRef,
    []excelize.ConditionalFormatOptions{
        {
            Type:     "data_bar",
            BarColor: "#A9D08E",
            Format:   solidFillStyle,
            Criteria: "=",
            MinType:  "min",
            MaxType:  "max",
+           BarSolid: true,
        },
    },
)
```

**Comment by coolseven** [comment]
Thanks a lot!

**Comment by ShowerBandV** [comment]
can i get `gradient` attr from data_bar ?
