### ISSUE TITLE
Ability to remove or set Sheet Dimension <dimension> element

### ISSUE THREAD

**Issue by Josh-Weston** [qax-os/excelize#1463]
- Excel automatically adds and updates a `<dimension ref="A1:C4"></dimension>` when saving a workbook
- Excelize does not update the `<dimension>` element (which is fine); however,
- The `<dimension>` element will become incorrect as you make changes using Excelize
- This becomes problematic because some software (e.g., Power BI) uses the `<dimension>` element (if present) to determine the `UsedRange` of the sheet when importing rows.

I suggest adding a new method to allow the user to:

1. remove the `<dimension>` element entirely if not needed
2. set the `<dimension>` element if needed

Example:

 `func (f *File) SetSheetDimension(dimension string) error`

- if `dimension` is an empty string, then remove the `<dimension>` element entirely
- if `dimension` is not an empty string then set the `<dimension>` element
- returning an error is only required if the function will perform validation checks on the dimension argument; otherwise, it can be omitted from the function signature

References to `<dimension>` element in this package and others:

- #817 
- https://github.com/awalker89/openxlsx/issues/192
- https://learn.microsoft.com/en-us/dotnet/api/documentformat.openxml.spreadsheet.sheetdimension?view=openxml-2.8.1
- https://bz.apache.org/bugzilla/show_bug.cgi?id=53611

**Comment by xuri** [comment]
Thanks for your issue. I will adding this feature support in the future.

**Comment by Josh-Weston** [comment]
Excellent. Do you want me to work on a pull request?

**Comment by xuri** [comment]
Contributions are welcome. I'll certainly accept the pull request if anybody did that.
