### ISSUE TITLE
excel打开弹出警告部分内容有问题

### ISSUE THREAD

**Issue by hjy846** [qax-os/excelize#1466]
**Description**

**Steps to reproduce the issue:**
1. excelizeImp.File.SetPanes("Sheet1", &excelize.Panes{Freeze: true, Split: false, XSplit: 1, YSplit: 1, TopLeftCell: "B1"})

**Describe the results you received:**
excel打开弹出告警
<img width="228" alt="image" src="https://user-images.githubusercontent.com/7923144/217462532-79eb9e1f-8ed7-4bac-969d-9d348974f311.png">

**Describe the results you expected:**
不告警

**Output of `go version`:**
```text
1.19
```

**Excelize version or commit ID:**

```text
2.7.0
```

**Environment details (OS, Microsoft Excel™ version, physical, etc.):**
max os, excel for mac 16.69.1

**Comment by xuri** [comment]
According to the documentation, the value of `topRight` should be a cell in the right and left regions, for example:


```diff
-excelizeImp.File.SetPanes("Sheet1", &excelize.Panes{Freeze: true, Split: false, XSplit: 1, YSplit: 1, TopLeftCell: "B1"})
+excelizeImp.File.SetPanes("Sheet1", &excelize.Panes{Freeze: true, Split: false, XSplit: 1, YSplit: 1, TopLeftCell: "C2"})
```

I closed this issue, if you have any questions, please let me know to reopen this anytime.
