### ISSUE TITLE
AddTables creates invalid files if the tables name has spaces

### ISSUE THREAD

**Issue by wlbr** [qax-os/excelize#1468]
Hi,

AddTables creates corrupt files if the name attribute is using spaces.

Either it should be more resilient and replace the spaces with _ (what Excel will do anyway),
or this should be documented and an error should be thrown.

So this will work, but it took me quite a while to figure  out the reason for the corruption:
```
err := f.AddTable(sheetname, fmt.Sprintf("B%d:J%d", datastart, len(issues)+datastart), &excelize.TableOptions{
		Name:              strings.ReplaceAll("Issues "+sheetname, " ", "_"),
		StyleName:         "TableStyleMedium2",
		ShowFirstColumn:   false,
		ShowLastColumn:    false,
		ShowRowStripes:    &disable,
		ShowColumnStripes: false,
	})
```

Regards,
Michael

**Comment by xuri** [comment]
Thanks for your issue. I have added checks for the table name, please upgrade to the master branch code, and this patch will be released in the next version.

**Comment by wlbr** [comment]
Wow, now that' a quick response!
Thanks a lot!
