### ISSUE TITLE
User defined series colors in colStacked chart

### ISSUE THREAD

**Issue by jerrychen113** [qax-os/excelize#1474]
**Description**
Hello. We have series line color property work fine. But when I try combo with chart type "colStacked" with multi series, these colors seems too messy.

**Steps to reproduce the issue:**

	var chartSeriesC []excelize.ChartSeries = []excelize.ChartSeries{
		{
			Name:        "Sheet1!$B$38",
			Categories: "Sheet1!$C$37:$Z$37",
			Values:     "Sheet1!$C$38:$Z$38",
			Line: excelize.ChartLine{
				Color: "FFFF00",
			},
		},
		{
			Name:       "Sheet1!$B$39",
			Categories: "Sheet1!$C$37:$Z$37",
			Values:     "Sheet1!$C$39:$Z$39",
		},
		{
			Name:       "Sheet1!$B$40",
			Categories: "Sheet1!$C$37:$Z$37",
			Values:     "Sheet1!$C$40:$Z$40",
		},
		{
			Name:       "Sheet1!$B$41",
			Categories: "Sheet1!$C$37:$Z$37",
			Values:     "Sheet1!$C$41:$Z$41",
		},
		{
			Name:       "Sheet1!$B$42",
			Categories: "Sheet1!$C$37:$Z$37",
			Values:     "Sheet1!$C$42:$Z$42",
		},
		{
			Name:       "Sheet1!$B$43",
			Categories: "Sheet1!$C$37:$Z$37",
			Values:     "Sheet1!$C$43:$Z$43",
		},
		{
			Name:       "Sheet1!$B$44",
			Categories: "Sheet1!$C$37:$Z$37",
			Values:     "Sheet1!$C$44:$Z$44",
		},
	}
	var chartSeriesL []excelize.ChartSeries = []excelize.ChartSeries{
		{
			Name:       "Sheet1!$B$45",
			Categories: "Sheet1!$C$37:$Z$37",
			Values:     "Sheet1!$C$45:$Z$45",
			Line: excelize.ChartLine{
				Color: "FF0000",
			},
			Marker: excelize.ChartMarker{
				Symbol: "none",
			},
		},
		{
			Name:       "Sheet1!$B$46",
			Categories: "Sheet1!$C$37:$Z$37",
			Values:     "Sheet1!$C$46:$Z$46",
			Marker: excelize.ChartMarker{
				Symbol: "none",
			},
		},
		{
			Name:       "Sheet1!$B$47",
			Categories: "Sheet1!$C$37:$Z$37",
			Values:     "Sheet1!$C$47:$Z$47",
			Marker: excelize.ChartMarker{
				Symbol: "none",
			},
		},
	}

	excel.AddChart("Sheet1", "K2", &excelize.Chart{
		Type:   "colStacked",
		Series: chartSeriesC,
	}, &excelize.Chart{
		Type:   "line",
		Series: chartSeriesL,
	})

**Describe the results you received:**
    ![image](https://user-images.githubusercontent.com/24427963/219594879-854f1c20-9c42-4edd-980c-1af2b5445e28.png)
    
    The colStacked in the chart has the default color.

**Describe the results you expected:**

    Defined color by user.

**Similar issue:**

   #1345

**Excelize version or commit ID:**

```text
(2.7.0)
```

**Comment by xuri** [comment]
Thanks for your issue. I have add support for set the format for the data series fill. Now you can set the custom solid fill format like this:

```diff
var chartSeriesC []excelize.ChartSeries = []excelize.ChartSeries{
    {
        Name:        "Sheet1!$B$38",
        Categories: "Sheet1!$C$37:$Z$37",
        Values:     "Sheet1!$C$38:$Z$38",
+        Fill:   Fill{Type: "pattern", Color: []string{"FFFF00"}, Pattern: 1},
-        Line: excelize.ChartLine{
-            Color: "FFFF00",
-        },
    },
```

Note that, the `Color` field in the `ChartLine` structure has been removed. This feature will be released in the next version.
