### ISSUE TITLE
I wanted to use SetCellStyle() to style excel A33, but it always changed to A34. It didn't have this problem in v2.4.0, and it has had this problem in every version tested since

### ISSUE THREAD

**Issue by hertzzhang** [qax-os/excelize#1479]
代码中设置的A33
![image](https://user-images.githubusercontent.com/61894856/220583149-2a518817-e699-4b62-be08-54e9926d99b4.png)

In excel, the style is A34
<img width="191" alt="image" src="https://user-images.githubusercontent.com/61894856/220583611-47103805-99c2-4eb1-af1b-5d5ac00b6907.png">

**Comment by xuri** [comment]
Thanks for your feedback. Could you provide a reproducible demo and your input file attachment without confidential info?

**Comment by hertzzhang** [comment]
> 

Sorry, I can't provide the code and attachment, I can only provide the above information, because it does involve confidential issues, but I can ensure the existence of this problem, because I found the problem together with another engineer in the team.

**Comment by xuri** [comment]
I have tested your code snippets with each stable version from 2.4.1 to 2.7.0 and the master branch code, and it works well. Sorry, if not have enough info on code and attachments to reproduce this issue, I'll close this issue, if you have any questions, please let me know to reopen this anytime.
