### ISSUE TITLE
CalcCellValue - don't evalutate correct value with Formula

### ISSUE THREAD

**Issue by alexvr8282** [qax-os/excelize#1484]
**Description**

**Steps to reproduce the issue:**
1. in cell B2 value: 5
2. in cell B2 value: 10
3. in cell B2 value: 15
4.  in cell B2 value: 25
5.  in cell B2 value: 30
6.  in cell B2 value: 60

**Describe the results you received:**
12.5

**Describe the results you expected:**
18.7

**Output of `go version`:**
```text
go version go1.19.1 windows/amd64
```

**Excelize version or commit ID:**
```text
5429f13 
```

**Environment details (OS, Microsoft Excel™ version, physical, etc.):**
Windows, Excel

[testing_function_AVG_saved.xlsx](https://github.com/qax-os/excelize/files/10847565/testing_function_AVG_saved.xlsx)

**Comment by xuri** [comment]
Thanks for your issue. This issue has been fixed. Please try to upgrade to the master branch code, and this patch will be released in the next version.
