### ISSUE TITLE
How to change the height for the comment box? 如何设置【批注】的高度？

### ISSUE THREAD

**Issue by bianxiankui** [qax-os/excelize#1487]
**Description**
使用方法：func (f *File) AddComment(sheet string, comment Comment) error

给单元格添加【注解】之后，鼠标首次悬浮时，注解的高度适中。鼠标选中底下的单元格之后再将鼠标悬浮在单元格上显示【注解】时，注解会变得很高

**Steps to reproduce the issue:**
1. 鼠标悬浮在含有【注解】的单元格上，显示注解，这时注解的高度正常
2. 让鼠标选中下面的单元格
3. 再将鼠标放在第一步的单元格上显示注解，注解的高度会变得很高：会一直延伸到屏幕的底部

**Describe the results you received:**

**Describe the results you expected:**
希望能设置注解的高度

**Output of `go version`:**
 Go Version:  go version go1.18.8 windows/amd64
```text
(paste your output here)
```

**Excelize version or commit ID:**
Excelize : v2.7.0

```text
(paste here)
```

**Environment details (OS, Microsoft Excel™ version, physical, etc.):**

**Comment by xuri** [comment]
Thanks for your feedback. I've tested and it seems to work well. Which version of the spreadsheet application are you using? Please follow by issue template to provide environment details, code, and steps to reproduce the issue, and a translation in English would be welcome too.

**Comment by xuri** [comment]
It seems still not have enough info of code and attachments to reproduce this issue, so I'll close this issue, if you have any questions, please let me know to reopen this anytime.
