### ISSUE TITLE
Set state of Row/Col Outlines

### ISSUE THREAD

**Issue by sasloz** [qax-os/excelize#1491]
Hi!

Is there already a possibility to set the status of a grouping aka "Row/Col Outline"? So that this is "closed" instead of "open" as of now.

**Comment by xuri** [comment]
Thanks for your issue. We can set the visible for the columns or rows to control the group collapsed state. For example:

```go
package main

import (
    "fmt"

    "github.com/xuri/excelize/v2"
)

func main() {
    f := excelize.NewFile()
    defer func() {
        if err := f.Close(); err != nil {
            fmt.Println(err)
        }
    }()
    for row := 5; row < 10; row++ {
        if err := f.SetRowOutlineLevel("Sheet1", row, 1); err != nil {
            fmt.Println(err)
        }
        if err := f.SetRowVisible("Sheet1", row, false); err != nil {
            fmt.Println(err)
        }
    }
    if err := f.SaveAs("Book1.xlsx"); err != nil {
        fmt.Println(err)
    }
}
```

**Comment by sasloz** [comment]
Exactly that! Ah, I see. SetRowVisible, okay. **Thank you so much for your support!** 

Perhaps it would be a good idea to link to an example on your website using SetRowOutlineLevel with SetRowVisible (maybe a link). I hadn't "seen" the two functions together.
