### ISSUE TITLE
Creating data bars MinValue and/or MaxValue not set correctly in EXCEL

### ISSUE THREAD

**Issue by usuallyvexed** [qax-os/excelize#1492]
**Description**

I am trying to use the conditional formatting feature and create some data bars, this partially works.
However, whenever I try to specify min and or max values, excelize does not appear to be converting the numeric values correctly.

**Steps to reproduce the issue:**
1. Create a column if increasing numbers, 1-100.
2. Use the following code to conditionally format the cells:
err = ss.Excelize.SetConditionalFormat(sheetName, fmt.Sprintf("$AL$%d:$AL$%d", startRow, nodeRow-1),
		[]excelize.ConditionalFormatOptions{
			{
				Type:     "data_bar",
				Criteria: "=",
				MinType:  "num",
				MinValue: "0",
				MaxType:  "num",
				MaxValue: "100",
				BarColor: "#FF0000,
			},
		},
	)
3. Go into EXCEL, select the range and then the HOME tab, Conditional Formatting, Manage Rules, then edit rule. 

**Describe the results you received:**

For me the max value shows up as zero.

**Describe the results you expected:**

I was expecting the max value to be 100.

If I tried using a cell reference, the formatting of the cell reference in EXCEL was wrong as well, it would contain extraneous quotation marks(").

**Output of `go version`:**
go version go1.20.2 windows/amd64

```text
(paste your output here)
```

**Excelize version or commit ID:**

github.com/xuri/excelize/v2 v2.7.0 // indirect

**Environment details (OS, Microsoft Excel™ version, physical, etc.):**

Windows 10
EXCEL 2013 part of the Microsoft Office 2013 bundle

![databar-issue-reported-20230313](https://user-images.githubusercontent.com/68232208/224721348-9e42cfc9-3cad-48f3-b08d-0a479b2a8074.png)

**Comment by xuri** [comment]
Thanks for your issue. I have fixed it, please upgrade to the master branch code, and this patch will be released in the next version.
