### ISSUE TITLE
zip: not a valid zip file

### ISSUE THREAD

**Issue by 1070523402** [qax-os/excelize#1496]
上传csv文件报错 zip: not a valid zip file

**Comment by xuri** [comment]
This was a duplicate with issues #821 and #881, so I closed this. Kind notice, please follow the issue templates to describe the results you expected when creating an issue.

**Comment by 1070523402** [comment]
The csv file type cannot be opened??

**Comment by xuri** [comment]
Please using the Go's [encoding/csv](https://pkg.go.dev/encoding/csv) library for CSV format files.

**Comment by quanxiangsheng** [comment]
> 对于 CSV 格式文件，请使用 Go 的[编码/csv库。](https://pkg.go.dev/encoding/csv)

Therefore, the library does not support reading csv files and writing them to excel
?

**Comment by xuri** [comment]
> > 对于 CSV 格式文件，请使用 Go 的[编码/csv库。](https://pkg.go.dev/encoding/csv)
> 
> Therefore, the library does not support reading csv files and writing them to excel ?

You can made encoding/csv package and this library working with together. There a tutorial video on the [documentation website](https://xuri.me/excelize/) about this:

[2.3 Converting CSV to XLSX, Row Height, Column Width, and Rich Text Settings](https://youtu.be/4yjrdMUlckc) (in English)
[2.3 基本操作 - CSV 转 XLSX、行高列宽和富文本设置](https://www.bilibili.com/video/BV1US4y1R7t3) (in Chinese)
