### ISSUE TITLE
Infinite loop issue of the GetRows function? GetRows 获取所有行时候 会出现无限 循环

### ISSUE THREAD

**Issue by ahKevinXy** [qax-os/excelize#1498]
可以添加一个指定多少行后返回这样机制吗

**Comment by xuri** [comment]
Thanks for your feedback. Could you follow the issue template, and show us a complete, standalone example program or reproducible demo?

**Comment by ahKevinXy** [comment]
可以加个获取指定行数的函数吗，例如 GetRowsLimit(1000) 获取前 1000 行数据

**Comment by xuri** [comment]
This issue similar with issue #865.
