### ISSUE TITLE
How to hide percent in pie chart that are 0%

### ISSUE THREAD

**Issue by DarkMatterV** [qax-os/excelize#1499]
i want generate a pie chart about task statistic，whtn "任务1“ percent is 100%, others percent is 0%, how to hide 

![image](https://user-images.githubusercontent.com/90494331/225844659-c493ea86-cf20-4164-875a-31805df7d934.png)

**Comment by xuri** [comment]
I have added support to set custom number format for chart data labels and axis. Please upgrade to the master branch code,  now you can specify custom number format in `PlotArea`'s `Labels` fields like this:

```go
PlotArea: excelize.ChartPlotArea{
    Labels: excelize.ChartLabel{CustomNumFmt: "0.00%;0;;"},
}
```

This feature will be released in the next version.

**Comment by xuri** [comment]
I have added support to set custom number format for chart data labels and axis. Please upgrade to the master branch code,  now you can specify custom number format in `PlotArea`'s `Labels` fields like this:

```go
PlotArea: excelize.ChartPlotArea{
    NumFmt: excelize.ChartNumFmt{CustomNumFmt: "0.00%;0;;"},
}
```

This feature will be released in the next version.

**Comment by xuri** [comment]
I have added support to set custom number format for chart data labels and axis. Please upgrade to the master branch code,  now you can specify custom number format in `PlotArea`'s `NumFmt` fields like this:

```go
PlotArea: excelize.ChartPlotArea{
    NumFmt: excelize.ChartNumFmt{CustomNumFmt: "0.00%;0;;"},
}
```

This feature will be released in the next version.
