### ISSUE TITLE
Set the date range limitation in the data validation

### ISSUE THREAD

**Issue by firomoo** [qax-os/excelize#1502]
在使用NewDataValidation的DataValidationTypeDate的时候，开始日期和结束日期设置完后，在excel中查看，会多出一个“=”，使得该条数据验证直接无法起作用。
组件版本：v2.7.0
实例代码：
`
	// 数据校验
	dv := excelize.NewDataValidation(true)
	dv.SetSqref("E3:E102")
	dv.SetRange(-3.0, 3.0, excelize.DataValidationTypeWhole, excelize.DataValidationOperatorBetween)
	dv.SetError(excelize.DataValidationErrorStyleStop, "差异值", "亲, 该列只能输入数字喔~")
	f.AddDataValidation(sheetName, dv)

	dv2 := excelize.NewDataValidation(true)
	dv2.SetSqref("A3:A102")
	dv2.SetRange(`1980-01`, `2100-01`, excelize.DataValidationTypeDate, excelize.DataValidationOperatorBetween)
	dv2.SetError(excelize.DataValidationErrorStyleStop, "月份", "亲, 该列只能年-月喔~")
	f.AddDataValidation(sheetName, dv2)

	// 解锁输入区域
	cellUnLocked, _ := f.NewStyle(&excelize.Style{Protection: &excelize.Protection{Locked: false}})
	lastCell, _ := excelize.CoordinatesToCellName(8, 101)
	fmt.Println("last", lastCell)
	_ = f.SetCellStyle(sheetName, "A3", lastCell, cellUnLocked)

	exp := "yyyy-mm"
	dateStyle, _ := f.NewStyle(&excelize.Style{Protection: &excelize.Protection{Locked: false}, CustomNumFmt: &exp})
	_ = f.SetCellStyle(sheetName, "A3", "A103", dateStyle)
`
响应结果：
![20230321211834253](https://user-images.githubusercontent.com/78334773/226617993-3dcc1606-f633-45f2-9dbe-58dba8060fa8.png)

这应该是个bug吧？

**Comment by xuri** [comment]
I've closed this issue, if you have any questions, please let me know to reopen this anytime.

**Comment by firomoo** [comment]
谢谢大佬~

**Comment by firomoo** [comment]
感谢大佬，改成这个(+ dv2.SetRange(`29221`, `73051`, excelize.DataValidationTypeDate, excelize.DataValidationOperatorBetween))确实生效了。

**Comment by xuri** [comment]
The DATEVALUE formula function converts a date into a date serial. You can also using this in the rules:

```diff
- dv2.SetRange(`1980-01`, `2100-01`, excelize.DataValidationTypeDate, excelize.DataValidationOperatorBetween)
+ dv2.SetRange(`=DATEVALUE("1980-01")`, `=DATEVALUE("2100-01")`, excelize.DataValidationTypeDate, excelize.DataValidationOperatorBetween)
```
