### ISSUE TITLE
Clear formats in file

### ISSUE THREAD

**Issue by Krevedos** [qax-os/excelize#1508]
I have a problem with the file, it parse incorrectly, but if I open the file manual in excel and press the CLEAR FORMATS button and save the file, the problem disappears. Is there a way to clear formats programmatically? Thx for all ! 
[test.xlsx](https://github.com/qax-os/excelize/files/11063057/test.xlsx)

**Comment by Krevedos** [comment]
I have made some test with file, and i think that the problem is in the first line, where the names are written in Cyrillic, if i rename them, then the file is perfectly parsed. Maybe there are some special characters? Can you analyze my file? (test.xlsx)

**Comment by xuri** [comment]
Sorry, I didn't understand what's means "parse incorrectly" as your say. Which version of this library were your using? Did you get any errors? Please **follow the issue templates** to provide more details about this.

**Comment by Krevedos** [comment]
Ok, for example,  the first line is displayed perfectly, as in the excel file, but line 100000 already looks different from the file, I am attaching screenshots...

<img width="1512" alt="1" src="https://user-images.githubusercontent.com/26144119/227728125-a72e0fac-5db6-4a94-acc2-0b082f547222.png">
<img width="1124" alt="2" src="https://user-images.githubusercontent.com/26144119/227728137-c5ae284a-e2a5-46ef-9dfc-cce118af71a2.png">
<img width="1512" alt="3" src="https://user-images.githubusercontent.com/26144119/227728142-9b3aa8e9-4c77-4b5c-9528-674fa44823d9.png">

**Comment by xuri** [comment]
It seems you set the numeric cell value as a text string. Please convert it to numeric data types before setting the cell value. Could you **follow the issue template**, and show us a complete, standalone example program or reproducible demo?

**Comment by Krevedos** [comment]
This excel file i am get from mail, I don’t install anything in it, I have the task of parsing it and then inserting rows into the database. But the problem is that some kind of bugs occurs during parsing, I have attached screenshots where you can see that the first line is the same as in the original file, but line 100000 no longer matches the source file.

**Comment by Krevedos** [comment]
My code is very simple
`
		f, err := excelize.OpenFile("test.xlsx")
		if err != nil {
			fmt.Println(err)
			return err
		}
		defer func() {
			if err := f.Close(); err != nil {
				fmt.Println(err)
			}
		}()

		sheets1 := f.GetSheetList()

		rows, err := f.GetRows(sheets1[0])
		if err != nil {
			fmt.Println(err)
			return err
		}
		for i, row := range rows {
			if i == 1 || i == 100000 {
				fmt.Println(row)
			}
		}`

**Comment by xuri** [comment]
This issue caused by shared string table index shich contains blank characters, we need to trim these before covert it into integer, for example made some change based on the commit [`60b9d02`](https://github.com/xuri/excelize/commit/60b9d029a672634299fdab880423ba48a165507b) whould you like to create a pull request to fix it? Or I'll fixed it later.


This issue is caused by the shared string table index which contains blank characters, we need to trim these blank characters before converting them into integers, for example, made some changes based on the commit [`60b9d02`](https://github.com/xuri/excelize/commit/60b9d029a672634299fdab880423ba48a165507b). Would you like to create a pull request to fix it? Or I'll fix it later.

```diff
diff --git a/cell.go b/cell.go
index 5ebcefe..5fcadce 100644
--- a/cell.go
+++ b/cell.go
@@ -564,7 +564,7 @@ func (c *xlsxC) getValueFrom(f *File, d *xlsxSST, raw bool) (string, error) {
    case "s":
        if c.V != "" {
            xlsxSI := 0
-           xlsxSI, _ = strconv.Atoi(c.V)
+           xlsxSI, _ = strconv.Atoi(strings.TrimSpace(c.V))
            if _, ok := f.tempFiles.Load(defaultXMLPathSharedStrings); ok {
                return f.formattedValue(c.S, f.getFromStringItem(xlsxSI), raw)
            }
diff --git a/cell_test.go b/cell_test.go
index 58a4bee..565c1c9 100644
--- a/cell_test.go
+++ b/cell_test.go
@@ -432,6 +432,11 @@ func TestGetValueFrom(t *testing.T) {
    value, err := c.getValueFrom(f, sst, false)
    assert.NoError(t, err)
    assert.Equal(t, "", value)
+
+   c = xlsxC{T: "s", V: " 1 "}
+   value, err = c.getValueFrom(f, &xlsxSST{Count: 1, SI: []xlsxSI{{}, {T: &xlsxT{Val: "s"}}}}, false)
+   assert.NoError(t, err)
+   assert.Equal(t, "s", value)
 }
 
 func TestGetCellFormula(t *testing.T) {
```

**Comment by xuri** [comment]
This issue is caused by the shared string table index which contains blank characters, we need to trim these blank characters before converting them into integers, for example, made some changes based on the commit [`60b9d02`](https://github.com/xuri/excelize/commit/60b9d029a672634299fdab880423ba48a165507b). Would you like to create a pull request to fix it? Or I'll fix it later.

```diff
diff --git a/cell.go b/cell.go
index 5ebcefe..5fcadce 100644
--- a/cell.go
+++ b/cell.go
@@ -564,7 +564,7 @@ func (c *xlsxC) getValueFrom(f *File, d *xlsxSST, raw bool) (string, error) {
    case "s":
        if c.V != "" {
            xlsxSI := 0
-           xlsxSI, _ = strconv.Atoi(c.V)
+           xlsxSI, _ = strconv.Atoi(strings.TrimSpace(c.V))
            if _, ok := f.tempFiles.Load(defaultXMLPathSharedStrings); ok {
                return f.formattedValue(c.S, f.getFromStringItem(xlsxSI), raw)
            }
diff --git a/cell_test.go b/cell_test.go
index 58a4bee..565c1c9 100644
--- a/cell_test.go
+++ b/cell_test.go
@@ -432,6 +432,11 @@ func TestGetValueFrom(t *testing.T) {
    value, err := c.getValueFrom(f, sst, false)
    assert.NoError(t, err)
    assert.Equal(t, "", value)
+
+   c = xlsxC{T: "s", V: " 1 "}
+   value, err = c.getValueFrom(f, &xlsxSST{Count: 1, SI: []xlsxSI{{}, {T: &xlsxT{Val: "s"}}}}, false)
+   assert.NoError(t, err)
+   assert.Equal(t, "s", value)
 }
 
 func TestGetCellFormula(t *testing.T) {
```

**Comment by Krevedos** [comment]
Thx. I am wait for your fix.
