### ISSUE TITLE
Empty cell data

### ISSUE THREAD

**Issue by ceearrashee** [qax-os/excelize#1510]
**Description**
Hello!
I ran into a problem with one document. I have an Excel template that I export the data to the "Answers" sheet. But cell A2 is empty. I checked the export data - everything is correct. I unpacked the document and checked that the data in the document cell had value, but when I opened the document, the column was empty.

**Steps to reproduce the issue:**
I attached the document to analyse. All data set to document using function life `SetCellValue("Answers","A2", time.Now.Truncate(24 * time.Hour))`

**Output of `go version`:**

```text
1.20.1
```

**Excelize version or commit ID:**

```text
v2.7.0
```

**Environment details (OS, Microsoft Excel™ version, physical, etc.):**
Linux/Windows LibraOffice/MSOffice/MSOffice online
[Survey result (14).xlsx](https://github.com/qax-os/excelize/files/11068905/Survey.result.14.xlsx)

**Comment by xuri** [comment]
Thanks for your feedback. This issue seems like #1464, and I have fixed that issue. Please try to upgrade to the master branch code. If still doesn't work, please provide the template file as an attachment for details. Note that the code in your example has a syntax error, correct it like this:

```diff
- time.Now.Truncate(24 * time.Hour)
+ time.Now().Truncate(24 * time.Hour)
```

**Comment by xuri** [comment]
It seems still not have enough info of code and attachments to reproduce this issue, so I'll close this issue, if you have any questions, please let me know to reopen this anytime.
