### ISSUE TITLE
how to set some cell unlock

### ISSUE THREAD

**Issue by cooper-car** [qax-os/excelize#1511]
**Question:**
method `ProtectSheet` can lock sheet, but how to set some cell unlock?

**Excelize version:**
2.6.1

**Comment by xuri** [comment]
Thanks for your issue. Please create an unlocked style first, and then set the cell with this style you want to unlock. For example, the following code unlocks the `D6` cell on the protected worksheet `Sheet1`:

```go
style, err := f.NewStyle(&excelize.Style{
    Protection: &excelize.Protection{
        Locked: false,
    },
})
if err != nil {
    fmt.Println(err)
    return
}
if err := f.SetCellStyle("Sheet1", "D6", "D6", style); err != nil {
    fmt.Println(err)
}
```

I've closed this issue, if you have any questions, please let me know to reopen this anytime.

**Comment by cooper-car** [comment]
It works! Thanks for your help.
