### ISSUE TITLE
merged cell

### ISSUE THREAD

**Issue by Jerry-yz** [qax-os/excelize#1514]
when merged cell, the cell bord disappear,how to reserve cell bord

**Comment by xuri** [comment]
Thanks for your issue. Please set the new border styles for the merged cells after merging cells.

**Comment by xuri** [comment]
Thanks for your issue. Please set the new border styles for the merged cells by the `NewStyle` and `SetCellStyle` functions after merging cells.

**Comment by xuri** [comment]
Thanks for your issue. Please set the new border styles for the merged cells by the `NewStyle` and `SetCellStyle` functions after merging cells. I've closed this issue, if you have any questions, please let me know to reopen this anytime.
