### ISSUE TITLE
Red highlighting negative number and specify decimal places 关于数字自定义格式的NumFmt索引不包含“红色负值”以及其小数位数无法自定义设置位数的问题

### ISSUE THREAD

**Issue by firomoo** [qax-os/excelize#1515]
问题如下：
**本人现在有个需求，导出的列若为数字的，需要自行添加千位分隔符，有的列会是小数，小数位数不定。
如下图，有的数字小数位是4位。**
<img width="916" alt="image" src="https://user-images.githubusercontent.com/78334773/230747538-37e4c5ec-416e-493a-8a96-888cdd358c2b.png">

**但是文档中的索引常量中，好像并没有包含到红色负值？** 
![image](https://user-images.githubusercontent.com/78334773/230747578-7478e947-fe8b-4b6f-9666-e342734272d2.png)
![image](https://user-images.githubusercontent.com/78334773/230747590-63319804-6a9a-44a4-bd65-a20d0f9ce1e4.png)

**然后还需要请教下，怎么自定义小数的小数位数呢？定义“DecimalPlaces”参数没有生效。**
```go
// CellNumericTypeCustom | 数字格式定义
func CellNumericTypeCustom(f *excelize.File, sheetName string, col int, formats ...int) error {
	colName, _ := excelize.ColumnNumberToName(col)
	format := 40
	if len(formats) > 0 {
		format = formats[0]
	}
	dateStyle, err := f.NewStyle(&excelize.Style{
		Protection: &excelize.Protection{Locked: false},
		NumFmt:     format,
		DecimalPlaces: 4,
	})
	if err != nil {
		return err
	}
	return f.SetColStyle(sheetName, colName, dateStyle)
}

```
**lib version: v2.7.0**

希望大佬有时间能抽空帮我看下～
谢谢🙏～

**Comment by xuri** [comment]
Thanks for your issue. This duplicate with the issue #969, please specified custom number format like this:


```go
numfmt := `#,##0.0000;[Red]#,##0.0000`
styleID, err := f.NewStyle(&excelize.Style{CustomNumFmt: &numfmt})
```

I've closed this issue, if you have any questions, please let me know to reopen this anytime.

**Comment by firomoo** [comment]
谢谢～🙏
实测有效。 不过要变成带“-”格式的红色负值需要在正则中加上
```go
numfmt := `#,##0.0000;[Red]"-"#,##0.0000`
styleID, err := f.NewStyle(&excelize.Style{CustomNumFmt: &numfmt})
```
因为有的列精度要求不一样，所以在设置表结构的时候，如上这种正则配置就会显得和臃肿。
比如要么选择通过入参设置用循环配置0.00……这里小数点后的0点个数，要么选择每种精度配置一个正则表达式。
所以想问下，后续会考虑加一个字段能真正用来配置DecimalPlaces吗？
