### ISSUE TITLE
Individual Style Component Modification

### ISSUE THREAD

**Issue by usuallyvexed** [qax-os/excelize#1520]
Would it be possible to have style related routines that change only a single aspect of a style for a cell, row, column?
For example:

SetCellFill(sheetName, startCell, endCell, fill-info)
SetCellFont(sheetName, startCell, endCell, font-info)
SetCellAlignment(sheetName, startCell, endCell, alignment-info)
SetCellBorders(sheetName, startCell, endCell, border-info)
etc.

Having the routines to alter individual components of an objects style saves a lot of work of having to create many different styles when you want to preserve all other components of the style save the one you want to change.

Thanks.

**Comment by xuri** [comment]
Thanks for your issue. The library has a plan to add support to get style definitions in the next released version (issue #314). After that the user can get existing cell style details by style index, and re-set style after modifying partial of styles to achieve merge or modify style this way.

**Comment by xuri** [comment]
The new function `GetStyle` has been added. Now, we can get style index at first, get the style definition with that, modify style definition and then re-set the style. Please try to upgrade the master branch code. This feature will be released in the next version.

**Comment by usuallyvexed** [comment]
A big thank you!


Sent from Yahoo Mail for iPhone


On Thursday, August 24, 2023, 20:06, xuri ***@***.***> wrote:




The new function GetStyle has been added. Now, we can get style index at first, get the style definition with that, modify style definition and then re-set the style. Please try to upgrade the master branch code. This feature will be released in the next version.
