### ISSUE TITLE
The SetCellValue method has a bug

### ISSUE THREAD

**Issue by heliangrui** [qax-os/excelize#1528]
The official documentation says that the secondary method is thread-safe, but multithreading starts with an error:
go f.SetCellValue(e.sheetName, s, nowValue)
errors: panic: runtime error: index out of range [4] with length 1

**Comment by heliangrui** [comment]
Of course.You can see the sample: github.com/heliangrui/excel; Run the test-main method to execute the test case. You can execute the test case without modifying it. Modify the exportData method in excel/ Excel. go and add the go flag to 179,183

**Comment by xuri** [comment]
I have tested with the repository you mention, and it works well. I don't understand what means you said: "Modify the exportData method in excel/ Excel. go and add the go flag to 179,183". Could you follow the issue template, provide a reproducible demo with simplified codes, and provide what's the results you expected?

**Comment by heliangrui** [comment]
![image](https://user-images.githubusercontent.com/130044339/233815332-05e57f36-b1b8-414c-ae04-104ad7dfac41.png)
excel/excel.go file

**Comment by xuri** [comment]
Thanks for your feedback. The statements already exists same with you want to changes. Could you follow the issue template, provide a reproducible demo with simplified codes, and provide what's the results you expected?  That will be helpful quick understand and resove this issues.

**Comment by xuri** [comment]
Thanks for your feedback. The statements already exist same with you want to change them. Could you follow the issue template, provide a reproducible demo with simplified codes, and provide what're the results you expected? That will be helpful in quickly understanding and resolving this problem.

**Comment by heliangrui** [comment]
![image](https://user-images.githubusercontent.com/130044339/233816587-43587761-7124-42da-aa0d-7a2a9fef73e8.png)
I have submitted this error, repull:
https://github.com/heliangrui/excel
Run the test/main.go file under the main method

errorMessage:
panic: runtime error: index out of range [4] with length 2

goroutine 81895 [running]:
github.com/xuri/excelize/v2.(*File).prepareCell(0xc000160160?, 0xc00091a1c0, {0xc01a4836f0?, 0xc01a60beb0?})
        E:/project/pkg/mod/github.com/xuri/excelize/v2@v2.7.1/cell.go:1266 +0x25e
github.com/xuri/excelize/v2.(*File).SetCellStr(0xc01a60bf78?, {0xfb3150, 0x9}, {0xc01a4836f0, 0x6}, {0x0, 0x0})
        E:/project/pkg/mod/github.com/xuri/excelize/v2@v2.7.1/cell.go:383 +0xab
github.com/xuri/excelize/v2.(*File).SetCellValue(0x0?, {0xfb3150, 0x9}, {0xc01a4836f0, 0x6}, {0xfa8520?, 0xc01a477b90?})
        E:/project/pkg/mod/github.com/xuri/excelize/v2@v2.7.1/cell.go:153 +0x43d
created by github.com/heliangrui/excel.(*Export[...]).exportData
        E:/project/excel/excel.go:179 +0x3ab

**Comment by xuri** [comment]
Thank you for your issue. I have fixed race condition issues, please upgrade to the master branch code, and this patch will be released in the next version. In addition, you need to wait for all the goroutines launched here to finish in your code `excel.go`:

```diff
diff --git a/excel.go b/excel.go
index f1371b5..15ebb92 100644
--- a/excel.go
+++ b/excel.go
@@ -165,7 +166,6 @@ func (e *Export[T]) setHeadStyle(style *excelize.Style) *Export[T] {
 
 func (e *Export[T]) exportData(object []T, start int) *Export[T] {
 	obLen := len(object)
-	e.wg.Add(1)
 	e.setRowHeight(start, obLen)
 	for i := 0; i < obLen; i++ {
 		mod := object[i]
@@ -175,16 +175,20 @@ func (e *Export[T]) exportData(object []T, start int) *Export[T] {
 			nowValue := value.FieldByName(fieldName)
 			name, _ := excelize.ColumnNumberToName(r + 1)
 			s := name + strconv.Itoa(i+start+e.headRowHeight)
-			if m.toExcelFormat == "" {
-				go e.f.SetCellValue(e.sheetName, s, nowValue)
-			} else {
-				toExcelFun := value.MethodByName(m.toExcelFormat)
-				call := toExcelFun.Call(nil)
-				go e.f.SetCellValue(e.sheetName, s, call[0])
-			}
+			e.wg.Add(1)
+			go func() {
+				defer e.wg.Done()
+				if m.toExcelFormat == "" {
+					e.f.SetCellValue(e.sheetName, s, nowValue)
+				} else {
+					toExcelFun := value.MethodByName(m.toExcelFormat)
+					call := toExcelFun.Call(nil)
+					e.f.SetCellValue(e.sheetName, s, call[0])
+				}
+			}()
 		}
 	}
-	e.wg.Done()
+	e.wg.Wait()
 	return e
 }
```

**Comment by heliangrui** [comment]
Thanks♪(･ω･)ﾉ
