### ISSUE TITLE
number format code support switchArguments;

### ISSUE THREAD

**Issue by fudali113** [qax-os/excelize#1531]
number format code support switchArguments;

such as:
* [DBNum1][$-804]General
* [DBNum1][$-804]m"月"d"日";@

features:

- [ ] DBNUM1
- [ ] DBNUM2

etc.

**Comment by xuri** [comment]
Thanks for your issue. This issue has been resolved by commit [`bbdb83ab`](https://github.com/xuri/excelize/commit/bbdb83abf0a182f7203d434d44dd04a761648d73), I'll closed this. Please upgrade to the master branch, and this feature will be released in the next version.
