### ISSUE TITLE
Use the NewStreamWriter function on no-blank worksheets (NewStreamWriter 覆盖了原来的sheet)

### ISSUE THREAD

**Issue by 943885179** [qax-os/excelize#1537]
现在的NewStreamWriter 会把原来当前的sheet清空，有没有办法只是覆盖内容，我想通过流写入大量数据，但是内存不够，所以只能分批查询分配插入

**Comment by xuri** [comment]
Thanks for your issue. As the documentation says, the stream writer used to generate the new worksheet doesn't support appending data to the existing worksheet, so please use it for a new worksheet just created. Please create a new worksheet by NewSheet function first, and then write data by stream writer into it.
