### ISSUE TITLE
GetCellType causes panic:runtime error: index out of range

### ISSUE THREAD

**Issue by eqinox76** [qax-os/excelize#1538]
**Description**
Calling `GetCellType` on an empty cell causes a `index out of range` panic. Due to the file being confidential i sadly cannot share the file itself but at least the debugger state.

**Steps to reproduce the issue:**
We have a normal looking Excel Workbook with one Sheet `Allokationsdaten`. Calling `GetCellType` panics on Cell E5. The Cell looks normal as you can see in the following screenshot
![image](https://github.com/qax-os/excelize/assets/5861557/e5ccd4ec-c334-4b8f-a4ed-c5b49611fd18)

**Describe the results you received:**
```
runtime panic:runtime error: index out of range [0] with length 0
 goroutine 97 [running]:
runtime/debug.Stack()
	/usr/lib/go-1.20/src/runtime/debug/stack.go:24 +0x7a
panic({0x2016e80, 0xc00528e018})
	/usr/lib/go-1.20/src/runtime/panic.go:890 +0x262
github.com/xuri/excelize/v2.checkSheet(0xc000748380)
	/home/go/pkg/mod/github.com/xuri/excelize/v2@v2.7.1/excelize.go:318 +0x80a
github.com/xuri/excelize/v2.(*File).workSheetReader(0xc0003a9e40, {0xc0035212a0, 0x10})
	/home/go/pkg/mod/github.com/xuri/excelize/v2@v2.7.1/excelize.go:275 +0xa05
github.com/xuri/excelize/v2.(*File).getCellStringFunc(0xc0003a9e40, {0xc0035212a0, 0x10}, {0xc002e6f2de, 0x2}, 0x2202e90)
	/home/go/pkg/mod/github.com/xuri/excelize/v2@v2.7.1/cell.go:1273 +0x9d
github.com/xuri/excelize/v2.(*File).GetCellType(0xc0003a9e40, {0xc0035212a0, 0x10}, {0xc002e6f2de, 0x2})
	/home/go/pkg/mod/github.com/xuri/excelize/v2@v2.7.1/cell.go:87 +0xb0
```
Debugger state:
![image](https://github.com/qax-os/excelize/assets/5861557/042c0124-a814-4cfa-93be-6f4fa95506b5)

**Describe the results you expected:**
No Panic.

**Output of `go version`:**
```text
go version go1.20.3 linux/amd64
```

**Excelize version or commit ID:**

```text
	github.com/xuri/excelize/v2 v2.7.1
```

**Environment details (OS, Microsoft Excel™ version, physical, etc.):**
Our go executable runs on Ubuntu 22.04
The Excel screenshot is done with Microsoft 365 (Version 2304)

A fix or hints on how to debug this further would be highly appreciated.

**Comment by xuri** [comment]
Thanks for your feedback. Could you provide a reproducible demo mock as your input file attachment without confidential info?

**Comment by eqinox76** [comment]
The excel file seems to be pretty interestingly broken. When i open and save it its working fine again. I was not able to reduce the file and save it in a way so that its still causing the panic.
Any data structure that could cause this issue? I could try to extract it via the debugger.

**Comment by xuri** [comment]
If you can provide a file that can be reproduced, that would be very helpful for analytics to make sure of any special data structure internal workbook, to quickly resolve this issue.

**Comment by eqinox76** [comment]
Sorry i can neither share the existing file nor remove the confidential information as saving it again fixes the file. I will reopen this if we spot a file that exhibits the same behaviour and is shareable.

Thanks for the library and your support!
