### ISSUE TITLE
Want to request some help with test document

### ISSUE THREAD

**Issue by tiansuo114** [qax-os/excelize#1542]
**Description**

Hello, I am a student who wants to participate in the part of our project released in the Open Source Summer project, and I find that part of the project I want to apply for requires a complete incremental test

If I could, I would like to see some examples of past community test specs or documentation

This is my email address, if you can, I would like to connect with you, thank you very much
Email address: zhaoyi_114@outlook.com

**Comment by xuri** [comment]
Thanks for your issue. Contributions are welcome! [This post](https://go.dev/testing/coverage/) shows how to use Go to collect coverage profiles for larger programs. You can use it locally, and this library also tracks the code coverage by CodeCov for [each commit](https://app.codecov.io/gh/qax-os/excelize/pulls). I'll close this issue, if you have any questions, please let me know to reopen this anytime.
