### ISSUE TITLE
Set cell on merged cells by the SetSheetRow function 

### ISSUE THREAD

**Issue by firomoo** [qax-os/excelize#1543]
现在遇到个问题，比如使用merge合并单元格 “A1:A3",然后使用SetSheetRow(sheet,cell,value)赋值的时候

值为:
    value:=&[]interface{}{"test1","test2"}

输出文件发现，A4的位置并没有把 test2 赋值进去

疑问： A1:A3合并单元格之后，进行行赋值时，A1,A2,A3也是要进行赋值吗？
eg: 
  value:=&[]interface{}{"test1",nil,nil,"test2"}

**Comment by xuri** [comment]
Exactly right. As the documentation says: merging cells only keeps the upper-left cell value, and discards the other values. So please use nil value as a placeholder when your write cells for a row.

**Comment by xuri** [comment]
Thanks for your issue. Exactly right. As the documentation says: merging cells only keeps the upper-left cell value, and discards the other values. So please use nil value as a placeholder when your write cells for a row. I will close this issue. If you have any questions, please let me know, and reopen this anytime.
