### ISSUE TITLE
getPicture can get only one picture in a cell

### ISSUE THREAD

**Issue by yicixin** [qax-os/excelize#1548]
**Description**
I tried the feature of getting multiple images in a cell introduced in 2.7.1, but after testing I could only get one of them.
I think the problem is with this line.

https://github.com/qax-os/excelize/blob/76cd0992b038ceaad87a471f81cbde503423cc85/picture.go#LL675C6-L675C12

**Comment by xuri** [comment]
Thanks for your issue. Would you like create a pull request to help us to fix this issue by remove return statements?
