### ISSUE TITLE
Can't save to stream (backwards breaking change)

### ISSUE THREAD

**Issue by tommed** [qax-os/excelize#1550]
**Description**

"github.com/xuri/excelize/v2" is versioned, so you woudln't expect backwards breaking changes. Previously `excelize.File` had a method with the signature `Write(w io.Writer) error` - this allowed us to save the spreadsheet to a `http.ResponseWriter` out to the user without needing the local file directory (which we want to avoid as this is a cloud service chargeable by I/O used and some spreadsheets are hundreds of MBs/GBs).

A recent update has removed this method and the only ones left are prefixed `Save` and require a local file path.

**Describe the results you received:**

Our build has started failing with this:

```
cannot use f (variable of type *excelize.File) as ParseResults value in return statement: *excelize.File does not implement ParseResults (wrong type for method Write)
```

Because we cast `excelize.File` to our interface:

```go
type ParseResults interface {
	Write(w io.Writer) error
}
```

**Describe the results you expected:**

We need to get this function back as saving to a stream is the method we've always used in V2 and wish to continue using. Equally, going forwards any backwards-breaking changes to the library should be versioned (e.g., V3) so we can avoid breaking our system when design changes are made.

**Output of `go version`:**

```text
go version go1.20.3 darwin/amd64
```

**Excelize version or commit ID:**

```text
github.com/xuri/excelize/v2 v2.7.1
```

**Environment details (OS, Microsoft Excel™ version, physical, etc.):**

macOS

**Comment by xuri** [comment]
Thanks for your issue. The `Write` function not has been removed in v2. I just change the signature for it in the commit [`fb1aab7`](https://github.com/xuri/excelize/commit/fb1aab7add52808c96c9cc10570fe73ce797b7f4#diff-33f8fbc61d6878200e61e69725cd724475a0c9dbb73bc63fcfc913a5651764feR104) for options support. Please also reference issue [#744](https://github.com/xuri/excelize/issues/744#issuecomment-1378684558).

**Comment by xuri** [comment]
I've closed this issue, if you have any questions, please let me know to reopen this anytime.
