### ISSUE TITLE
Whether it is supported to reference another sheet as a drop-down list

### ISSUE THREAD

**Issue by ZQHcode** [qax-os/excelize#1552]
like SetDropList, excel that instead of having a hard coded list, a reference to a part of the file is accepted and the list is automatically taken from there.

**Comment by yicixin** [comment]
If you want to reference a range as the droplist data source, you can use the `SetSqrefDropList` method.

**Comment by ZQHcode** [comment]
> ```go
> SetSqrefDropList
> ```

When the referenced sheet name is test##test，for example: dv.SetSqrefDropList("test##test!$A$1:$A$7")，the generated excel is problematic, how to solve it?

**Comment by xuri** [comment]
Please add single quote for the worksheet name in the cell reference: `='test##test'!$A$1:$A$3`, just like set source of data validation in the spreadsheet application.

**Comment by xuri** [comment]
Please add single quote for the worksheet name in the cell reference, just like set source of data validation in the spreadsheet application:

```go
dv.SetSqrefDropList("'test##test'!$A$1:$A$3")
```
