### ISSUE TITLE
How to modify the same row repeatedly when using NewStreamWriter

### ISSUE THREAD

**Issue by ZQHcode** [qax-os/excelize#1554]
When using NewStreamWriter,  I change the value of cell A1 and manipulate the next row of data, how can I come back to modify the value of cell C1?

**Comment by xuri** [comment]
Thanks for your issue. As the documentation of the `StreamWriter` function says,  you need to ensure that the order of row numbers is ascending. The stream write function is used to generate a new worksheet with a mound of data, and it doesn't support modifying rows which already been written. Please prepare all cells in a row before writing them into the worksheet.

**Comment by xuri** [comment]
I've closed this issue, if you have any questions, please let me know to reopen this anytime.
