### ISSUE TITLE
func (*Rows) Columns  API  Empty rows at the end of the worksheet are skipped.

### ISSUE THREAD

**Issue by ambiguous-pointer** [qax-os/excelize#1557]
**Description**

**Steps to reproduce the issue:**
I ran the code and found that it did not meet my expected results
``` go
r, _ := f.Rows(f.GetSheetList()[0])
	cur := 0
	for r.Next() {
		cur++
		row, err := r.Columns() //By querying the document, we can see that this will not skip the trailing blank lines
		if err != nil {
			break
		}
		fmt.Println(len(row)) //Print the length of each row in excel here
		if cur == 13 {
			break
		}
	}
```
**This is my excel data**
![O`FA9(EM67M2F_`AXFSL1Y](https://github.com/qax-os/excelize/assets/119987662/3d846788-c119-465c-9652-9512d7dc1636)

**Describe the results you received:**

The output of the program is
``` go
30
30
30
32
32
32
32
30
30
30
30
18
```

**Describe the results you expected:**
From the above picture, we can know that the total length of each row of my excel data (including empty and continuous empty at the end) is 32, but when the 13th row is read, it is continuously empty from the 18th cell, so the length is the same It is 18, but the `r.Columns()` API does not return or does not operate? Or is there something wrong with my understanding?

`r.Columns()` API  Shouldn't the obtained lengths be 32 each?
Because its docs say so
` and will not skip empty rows in the tail of the worksheet.`

**Output of `go version`:**

```go version go1.20.2 windows/amd64```

**Excelize version or commit ID:**

```text
The version I am using is  github.com/xuri/excelize/v2 v2.7.1
```

**Personally, the reason is**
1. I misunderstood the usage of this `func (*Rows) Columns` API  [API doc](https://pkg.go.dev/github.com/xuri/excelize/v2#Rows.Columns)

**Hope to get a reply**
1. I want to get a standard two-dimensional table in excel, the length of each row is the same, because my subsequent code will do the mapping operation, and the inconsistent length will cause me to be unable to map to the structure well.
2. I hope to tell me to get an API that will not skip an array with consecutive empty tails
3. If you can, please explain the specific implementation of `func (*Rows) Columns` api. I tried to look at it myself and found that I didn’t understand it.

> I have not been learning Go for a long time, and I may not be very clear about the description of this problem. If you need other information from me, please point it out directly. Thank you very much

**Environment details (OS, Microsoft Excel™ version, physical, etc.):**
```
My OS: Windows11 22621.1702
My  Microsoft Excel™:  Microsoft Office Home and Student 2019
```

**Comment by xuri** [comment]
Thanks for your issue. This was duplicated with issue #1135, #1245, and #1452. Please check the length of each cell before getting the element in the slice. I have made a figure in issue #1245 to explain what kind of cells will be skipped for your reference, and I closed this issue. If you have any questions, please let me know to reopen this anytime.
