### ISSUE TITLE
AddPicture's OffsetY Method will cause the image to be displayed incorrectly

### ISSUE THREAD

**Issue by jacobLiou1225** [qax-os/excelize#1560]
**Description**
(想知道為何OffsetY一旦>=20就會使圖片跑版，謝謝)
I want to place two pictures in a cell using the  `AddPicture` Method, but when my `OffsetY` is greater than 20, the position of the pictures becomes incorrect.

**Describe the results you received:**

**This is the result when OffsetY is 19.**
![image](https://github.com/qax-os/excelize/assets/109709595/81e75286-0af9-4c19-aa95-b28af268fc54)

**This is the result when OffsetY is 20.**
![image](https://github.com/qax-os/excelize/assets/109709595/5dec17b5-db96-4eae-a05d-a08c8b3c0bf8)

The image that was supposed to be in cell A1 has shifted to A2.
I have also tried using  `AutoFit: true` but it didn't solve my problem.

Here's my code:

```
package main

import (
	_ "image/jpeg"
	_ "image/png"

	"github.com/xuri/excelize/v2"
)

func main() {
	f, _ := excelize.OpenFile("cat.xlsx")
	f.AddPicture("cat", "A1", "cat.png",
		&excelize.GraphicOptions{
			AutoFit:     true,
			ScaleX:      1,
			ScaleY:      1,
			OffsetX:     10,
			OffsetY:     20,
			Positioning: "absolute",
		},
	)
	f.SaveAs("output.xlsx")
}
```
here's the repository
https://github.com/jacobLiou1225/API-AddPicture-Question.git

**Excelize version or commit ID: 2.7.1**
**golang version  1.19**
**Environment details : windows 10 21H2**

Any help on this issue would be greatly appreciated. Thank you!

**Comment by xuri** [comment]
Thanks for your issue. Your provided repository was not found, could you provide a workbook and image as attachments without confidential info?

**Comment by jacobLiou1225** [comment]
@xuri Thank you for responding so quickly! Here is the correct URL without confidential info:
[https://github.com/jacobLiou1225/API-AddPicture-Question.git](url)

**Comment by xuri** [comment]
Thanks for your feedback. I have fixed this issue, please try to upgrade the master branch code, and this patch will be released in the next version.

**Comment by jacobLiou1225** [comment]
Thank you very much for your response. This project has been extremely helpful to me!
