### ISSUE TITLE
SetCellHyperLink: Missing Display

### ISSUE THREAD

**Issue by AndreasBuc** [qax-os/excelize#1563]
Hello Xuri,
first of all, thanks for this package :)

**Description**
The hyperlink is missing the display text in the cell. 
The tooltip is there, the link is there, but the cell seems empty, since there is no display text

**Steps to reproduce the issue:**
Take the code from the docs:

    display, tooltip := "https://github.com/xuri/excelize", "Excelize on GitHub"
    if err := f.SetCellHyperLink("Sheet1", "A3",
    "https://github.com/xuri/excelize", "External", excelize.HyperlinkOpts{
	    Display: &display,
	    Tooltip: &tooltip,
    }); err != nil {
        fmt.Println(err)
    }
    
    style, err := f.NewStyle(&excelize.Style{
    Font: &excelize.Font{Color: "1265BE", Underline: "single"},
    })
    if err != nil {
    fmt.Println(err)
    }
    err = f.SetCellStyle("Sheet1", "A3", "A3", style)
    if err := f.SaveAs("Book1.xlsx"); err != nil {
		fmt.Println(err)
    }

**Describe the results you received:**
The hyperlink is set in the excel file correctly, but the display text is missing, so the cell seems empty.

**Describe the results you expected:**
I expected that the cell displays "https://github.com/xuri/excelize"

**Output of `go version`:**
```text
go1.20.5 windows/amd64
```

**Excelize version or commit ID:**

```text
github.com/xuri/efp v0.0.0-20220603152613-6918739fd470 // indirect
github.com/xuri/excelize/v2 v2.7.1 // indirect
github.com/xuri/nfp v0.0.0-20220409054826-5e722a1d9e22 // indirect
```

**Environment details (OS, Microsoft Excel™ version, physical, etc.):**
```text
windows 11
excel: Version 2305 (Build 16501.20196)

cpu: AMD Ryzen 9 3900X 12 Core 3,8 GHz
memory: 64GB
```

Thanks for your time :)
Andreas

**Comment by xuri** [comment]
Thanks for your issue. As the documentation of the [`SetCellHyperLink`](https://xuri.me/excelize/en/cell.html#SetCellHyperLink) function says: the `SetCellHyperLink` function is only used to set the hyperlink of the cell and doesn't affect the value of the cells. So, this result was in expected. If you want to change the cell value, please set the cell value with the `SetCellValue` function:

```go
err := f.SetCellValue("Sheet1", "A3", "https://github.com/xuri/excelize")
```

**Comment by AndreasBuc** [comment]
Hello Xuri, 
wow, thanks for that quick response and help.
I am sorry I misunderstood the documentation. 

Have a nice saturday.
Andreas

**Comment by xuri** [comment]
Have a nice saturday. I've closed this, if you have any question please let me know, and you can reopen this anytime.

**Comment by feketegy** [comment]
I think this should be documented better.
