### ISSUE TITLE
Connection reset by peer when trying to download library

### ISSUE THREAD

**Issue by aphsa** [qax-os/excelize#1568]
**Description**
When try to run go mod tidy or go get, getting a connection reset by peer 

**Steps to reproduce the issue:**
```
go mod tidy 
(and)
go get github.com/xuri/excelize/v2
```

**Describe the results you received:**
github.com/xuri/excelize/v2: github.com/xuri/excelize/v2@v2.7.1: read "https:/proxy.golang.org/@v/v2.7.1.zip": read tcp <redacted>
:46292->142.250.189.209:443: read: connection reset by peer

nslookup 142.250.189.209
209.189.250.142.in-addr.arpa    name = sfo03s25-in-f17.1e100.net.

**Describe the results you expected:**
Successful download of excelize package just like other go packages from github.

**Output of `go version`:**

```text
go version go1.20.5 linux/amd64
```

**Excelize version or commit ID:**

```text
github.com/xuri/excelize/v2@v2.7.1
```

**Environment details (OS, Microsoft Excel™ version, physical, etc.):**
RHEL 7 running go 1.20.5 downloaded from https://go.dev

**Comment by aphsa** [comment]
I tried to modify the GOPROXY using 

```sh
go env -w GOPROXY=direct
```
and 

```sh
go get  github.com/xuri/excelize/v2
```
```
go: github.com/xuri/excelize/v2@v2.7.1 requires
        golang.org/x/image@v0.5.0 requires
        golang.org/x/text@v0.7.0 requires
        golang.org/x/tools@v0.1.12 requires
        golang.org/x/sync@v0.0.0-20220722155255-886fb9371eb4: invalid version: git fetch --unshallow -f origin in /root/go/pkg/mod/cache/vcs/d7307bee4c4ea6392fc96a77e51c2a492fb1cac611e6d73d5197c5d523473656: exit status 128:
        fatal: git fetch-pack: expected shallow list
```

**Comment by xuri** [comment]
Thanks for your issue. Please check your network or try to use another goproxy service, and you can also [download the project template](https://xuri.me/excelize/vendor/v2.7.1.zip) from here in vendor mode and use it offline:

```sh
go run -mod=vendor main.go
```

**Comment by xuri** [comment]
I've closed this issue. If you have any questions, please let me know, and reopen this anytime.
