### ISSUE TITLE
The Concat function can't support concatenation of multiple cell values

### ISSUE THREAD

**Issue by podmask** [qax-os/excelize#1569]
func TestMyConcat(t *testing.T) {
	t.Log("Start testing ....")
	f, err := excelize.OpenFile("test.xlsx")
	if err != nil {
		t.Error(err)
		return
	}
	defer f.Close()

	f.SetCellValue("Mytest", "A1", "1")
	f.SetCellValue("Mytest", "A2", "2")
	f.SetCellValue("Mytest", "A3", "3")
	f.SetCellValue("Mytest", "A4", "4")
	f.SetCellValue("Mytest", "A5", "5")

	f.SetCellFormula("Mytest", "C5", "CONCAT(A1:A5)")

	value, err := f.CalcCellValue("Mytest", "C5")
	if err != nil {
		t.Error(err)
		return
	}
	t.Logf("The value of Mytest C5 is : %s", value)
}

=========
 go test -v -run ^TestMyConcat$ excelizer/testing
=== RUN   TestMyConcat
    excelize_test.go:54: Start testing ....
    excelize_test.go:73: CONCAT requires arguments to be strings
--- FAIL: TestMyConcat (0.01s)
FAIL
FAIL    excelizer/testing       0.590s
FAIL

**Environment details (Windows, Microsoft Excel™ 365, physical, etc.):**

**Comment by xuri** [comment]
Thanks for your issue. I have fixed this issue, please try to upgrade the master branch code, and this patch will be released in the next version.
