### ISSUE TITLE
A Bug was found when using the "CONCAT" function across sheets.

### ISSUE THREAD

**Issue by podmask** [qax-os/excelize#1570]
**A Bug was found when using the "CONCAT" function across sheets.**
```
func TestMyTest(t *testing.T) {
	f, err := excelize.OpenFile("../test.xlsx")
	if err != nil {
		fmt.Println(err)
		return
	}
	defer f.Close()

	f.SetCellValue("sheet1", "A1", "1")
	f.SetCellValue("sheet1", "B1", "2")
	f.SetCellValue("sheet1", "C1", "3")
	f.SetCellValue("sheet1", "D1", "4")

	f.SetCellFormula("sheet2", "B2", "CONCAT(sheet1!A1:sheet1!D1)")

	value, err := f.CalcCellValue("sheet2", "B2")
	if err != nil {
		fmt.Println(err)
		return
	}
	t.Log(value)
}
```
The code outputing is：
```text

go.exe test -timeout 30s -run ^TestMyTest$ excelizer/testing -v

=== RUN   TestMyTest
    d:\DEV\go-dev\excelizer\testing\excel_test.go:104: 4
--- PASS: TestMyTest (0.00s)
PASS
ok  	excelizer/testing	1.689s
```
**Expecting is:  1234**
 

**Environment details (Windows, Microsoft Excel™ 365, physical, etc.):**

**Comment by xuri** [comment]
Thanks for your feedback. Which version of Excelize was your using? I have tested it with the master branch code ([`fb72e56`](https://github.com/xuri/excelize/tree/fb72e56667c7d88d52757e39145ff9e190184523)) and it works well. Please try to upgrade with the master branch code, if still doesn't work, please provide a workbook without confidential info as an attachment.

**Comment by podmask** [comment]
Thank you very much for your answer. I switched the version from v2.7.1 to v2.7.2-0.20230706104949 fb72e56667c7 according to your prompt, and the issue has been resolved. Thank you again for contributing such a powerful tool.

**Comment by xuri** [comment]
Okay, I've closed this issue.
