### ISSUE TITLE
Setting currency cell style to 0 decimal places shows as 2 decimal places

### ISSUE THREAD

**Issue by gdotgordon** [qax-os/excelize#1572]
**Description**

I am trying to display US Dollars, English (United States) in a cell with 0 decimal places, using the documented NumFmt 165 with this style declaration: `&excelize.Style{NumFmt: 165, DecimalPlaces: 0}`. However, debugging in the Excelize code in _styles.go_, if the number of decimal places is 0, it is reset to 2, and as a result, the dollar amount is shown in the spreadsheet with two decimal places.

I have worked around this for now in my code by using the custom format: `"[$$-409]#,##0"`, but given Excelize already supports this encoding and currency, it is much better to use built-in support rather than creating a non-intuitive custom format.

**Steps to reproduce the issue:**
1. Unzip the attached file currency.zip containing the test program.
2. cd to directory "currency".
3. invoke `go run .`
4. The code will create an output file "test.xlsx".
5.  Open "test.xlsx" with Excel and observe that cell A1 shows the value as "$35.27" instead of "$35".

[currency.zip](https://github.com/qax-os/excelize/files/11984992/currency.zip)

**Describe the results you received:**
On running the test code and opening the created Excel file, we note that the cell value for A1 is shown as "$35.27". Further, right mousing on the cell and selecting "Format Cells...", we see the proper currency encoding, but the number of decimal places is 2.

**Describe the results you expected:**
The value displayed is "$35" and "Format Cells..." shows the number of decimal places as 0.

**Output of `go version`:**
```
go version go1.20.5 darwin/amd64
```

**Excelize version or commit ID:**
```
github.com/xuri/excelize/v2 v2.7.1
```

**Environment details (OS, Microsoft Excel™ version, physical, etc.):**
```
MacOS Ventura 13.4.1, Microsoft Excel™ Version 16.74
```

**Additional debugging details:**
I see two places in the Excelize code that would contribute to the observed result:

1. styles.go, function NewStyle(style \*Style), approx line 2004:

```
if fs.DecimalPlaces == 0 {
		fs.DecimalPlaces = 2
}
```

I have declared that I want 0 decimal places, but the code resets it to 2. Should this possibly be `if fs.DecimalPlaces < 0` as it is in the code in `newNumFmt()` below?

But even if that is fixed, there is another issue in the flow:

2. styles.go newNumFmt(styleSheet *xlsxStyleSheet, style *Style), approx line 2310:

```
dp := "0."
numFmtID := 164 // Default custom number format code from 164.
if style.DecimalPlaces < 0 || style.DecimalPlaces > 30 {
	style.DecimalPlaces = 2
}
for i := 0; i < style.DecimalPlaces; i++ {
	dp += "0"
}
```

Here the issue is that if DecimalPlaces correctly had the value 0, the final value of dp would be "0." (the loop has 0 iterations), leaving an extra dot at the end of the desired format (it should be "0"). And so later in the code, the final format is: `"[$$-409]#,##0."`, whereas it should be `"[$$-409]#,##0"`.

**Comment by xuri** [comment]
Thanks for your issue. I have changed the data type for the `DecimalPlaces` to pointer of integer to resolve this issue. Please try to upgrade to the master branch code, and this breaking changes will be released in the next version.

**Comment by cristaloleg** [comment]
Oof, but that's a not backward compatible change :\
