### ISSUE TITLE
ChartLegend type is missing the "None" field

### ISSUE THREAD

**Issue by timohahaa** [qax-os/excelize#1575]
**Description**
When adding a new chart, you cant specify a "None" option in a chartLegend struct, so the chart legend will be always shown and there is no way to disable it. It seems, that the field should be there, because it is specified in the docs: https://xuri.me/excelize/en/chart.html#AddChart 
"Set properties of the chart legend. The options that can be set are: 

Parameter           | Type  | Explanation
None                   | bool   | Specify if show the legend without overlapping the chart. The default value is false  <== HERE
Position               | string | The position of the chart legend
ShowLegendKey | bool   | Set the legend keys shall be shown in data labels"

the option in a struct is completely missing :(

**Steps to reproduce the issue:**
1. Create a new chart
2. specify the "Legend" parametr using excelize.ChartLegend type
3. realize, that the "None" field is missing and you cant disable the legend

**Describe the results you received:**

**Describe the results you expected:**

**Output of `go 1.20.1`:**

**Excelize version or commit ID:**
excelize/v2, latest version
```text
(paste here)
```

**Environment details (OS, Microsoft Excel™ version, physical, etc.):**
Linux, LibreOffice calc to view the resulting xlsx files

**Comment by xuri** [comment]
Thanks for your issue. I have updated the documentation website. If you want to disable the legend for the chart, please specify the `Position` field value as `none` like this:

```go
err := f.AddChart("Sheet1", "E1", &excelize.Chart{
    // ...
    Legend: excelize.ChartLegend{
        Position: "none",
    },
})
```
