### ISSUE TITLE
Set data validation of a whole column/row

### ISSUE THREAD

**Issue by Tony642** [qax-os/excelize#1576]
**Description**

I've noticed microsoft excel allows you to set in-cell dropdown for a whole column/row via these steps:

1, select a cell with in-cell dropdown and press ctrl+c
2, press the header of a row(1/2/3/4....) or column(A/B/C/D...) to select whole row/column
3, press ctrl+v on selected area.

I really want you developers allows me to do the same thing in this library.

**Excelize version or commit ID:**
v2.7.1

**Comment by xuri** [comment]
Thanks for your issue. As the documentation says, you can set the data validation range by the [`Sqref`](https://xuri.me/excelize/en/data.html#AddDataValidation) field. You can set all cells in column A with maximum rows constants ([`excelize.TotalRows`](https://xuri.me/excelize/en/constants.html?h=TotalRows)) reference`A1:A1048576` (columns A and B `A1:B1048576`), and you can also set all cells for the first row with maximum columns name ([`excelize.MaxColumns`](https://xuri.me/excelize/en/constants.html?h=MaxColumns)) by reference `A1:XFD1`, etc., For example:

```go
package main

import (
    "fmt"

    "github.com/xuri/excelize/v2"
)

func main() {
    f := excelize.NewFile()
    defer func() {
        if err := f.Close(); err != nil {
            fmt.Println(err)
        }
    }()
    dv := excelize.NewDataValidation(true)
    dv.Sqref = "A1:A1048576" // Column A
    dv.SetDropList([]string{"1", "2", "3"})
    if err := f.AddDataValidation("Sheet1", dv); err != nil {
        fmt.Println(err)
        return
    }
    // Save spreadsheet by the given path.
    if err := f.SaveAs("Book1.xlsx"); err != nil {
        fmt.Println(err)
    } 
}
```
