### ISSUE TITLE
i have some pictures in the excel, but  when I use the GetPictures() method to get them,some of resulet is  null,why?

### ISSUE THREAD

**Issue by zhanqixuan** [qax-os/excelize#1585]
**Description**

**Steps to reproduce the issue:**
i have some pictures in the excel, but  when I use the GetPictures() method to get them,some of resulet is  null
**Describe the results you received:**
some of the pics is null
**Describe the results you expected:**
all of them should not be null
**Output of `go version`:**

```text
1.20.6
```

**Excelize version or commit ID:**

```text
v2.7.1
```

**Environment details (OS, Microsoft Excel™ version, physical, etc.):**
WINDOWS

**Comment by xuri** [comment]
Thanks for your feedback. Could you show us a complete, standalone example program or reproducible demo?

**Comment by xuri** [comment]
It seems still not have enough info of code and attachments to reproduce this issue, so I'll close this issue, if you have any questions, please let me know to reopen this anytime.

**Comment by ihater** [comment]
I also have a similar problem, I don't know where is the problem：

I don't know if it's a problem with the excel format or a problem with the code

**go version：**

1.17.13

**Excelize version ID：**

v2.7.1

demo:
```
	reader, err := excelize.OpenReader(file)
	rows, err := reader.GetRows("sheet1")
	picCellCos := []string{"F", "G", "H"}

	for index, row := range rows {
		if index == 0 {
			continue
		}

		// the text in the cell
		id := row[0]

		for _, cos := range picCellCos {
			// but some pics is nil 
			pics, picerr := reader.GetPictures("sheet1", cos+conv.ToString(index+1))
			if picerr == nil {
				for _, pic := range pics {
					picByte := bytes.NewReader(pic.File)
				
					// do something
	
				}
			}
		}
	}
```


Please tell me where I did wrong, thank you ～～


Here is my test data
[testupload.xlsx](https://github.com/qax-os/excelize/files/12284660/testupload.xlsx)

**Comment by xuri** [comment]
Hi @ihater, thanks for your feedback. I have fixed this issue, please try to upgrade the master branch code, and this patch will be released in the next version.
