### ISSUE TITLE
Update nfp library and release new version

### ISSUE THREAD

**Issue by martinmr** [qax-os/excelize#1586]
Hi,

Just opening an issue to track adding a version of the nfp library with this [fix](https://github.com/xuri/nfp/pull/2) into excelize and release a new version we can use in our internal services.

EDIT: I see that the library was already updated, so I'll use the latest commit for now. Still, a new release tag would be nice.

**Comment by xuri** [comment]
Thanks for your contribution. This library usually releases a stable version [every 3 or 4 months](https://github.com/xuri/excelize/projects). These changes will be released in the next version. Please use the Go module to lock the version before the new version is released.
