### ISSUE TITLE
time value is incorrect

### ISSUE THREAD

**Issue by hefju** [qax-os/excelize#1587]
value in excel is 14:37:30 ,  why GetRows and Print it is 15:37:30?

**Comment by xuri** [comment]
Thanks for your issue. Which version of the Excelize library are you using? Could you follow the issue template, and show us a complete, standalone example program or reproducible demo? Could you provide your input file attachment without confidential info?

**Comment by hefju** [comment]
[testxlsx.xlsx](https://github.com/qax-os/excelize/files/12170443/testxlsx.xlsx)
I found  problem  cell format is [HH]:mm:ss
