### ISSUE TITLE
Custom format for the chart title 支持修改图表title的字体吗？

### ISSUE THREAD

**Issue by lifenglsf** [qax-os/excelize#1588]
目前发现创建的图表的title都是灰色的，想把图表title更改字体颜色，不知道是否支持。
通过ChartTitle设置的图表title，看到charttitle只有name这一个属性

**Comment by xuri** [comment]
Thanks for your issue, I have made a breaking changes for the `AddChart` function, now it supports formatting and setting rich text titles for the chart. Please try to upgrade the master branch code, and this feature will be released in the next version. For example, you can set title for chart with blue color and custom formats like this:

```go
err := f.AddChart("Sheet1", "E1", &excelize.Chart{
    // ...
    Title: []excelize.RichTextRun{
        {
            Text: "Chart Title",
            Font: &excelize.Font{
                Bold:   true,
                Italic: true,
                Family: "Times New Roman",
                Size:   16,
                Color:  "2354e8",
            },
        },
    },
});
```
