### ISSUE TITLE
excelize skip pages

### ISSUE THREAD

**Issue by togemura** [qax-os/excelize#1591]
Please replace in lib.go :
string 56 ( https://github.com/qax-os/excelize/blob/2e9c2904f2965fc45ad0fa1d5e2bfc7c0632a7cc/lib.go#L56 )
```
strings.HasPrefix(fileName, "xl/worksheets/sheet")
```
to
```
strings.HasPrefix(strings.ToLower(fileName), "xl/worksheets/sheet")
```

We have excel files with fileName like "xl/worksheets/Sheet" - and sheets just skip because of upper case

**Comment by xuri** [comment]
Thanks for your issue. I have made a changes for this, please try to upgrade the master branch code, and this patch will be released in the next version.

**Comment by togemura** [comment]
Thanks a lot!
