### ISSUE TITLE
Download excel from url and parse it, there is an error, it looks like the file is garbled

### ISSUE THREAD

**Issue by zhaozeyu89** [qax-os/excelize#1592]

**Comment by zhaozeyu89** [comment]
Is there any documentation or examples for reference?

**Comment by xuri** [comment]
Thanks for your feedback. Could you follow the issue template, and show us a complete, standalone example program or reproducible demo?

**Comment by xuri** [comment]
It seems still not have enough info of code and attachments to reproduce this issue, so I'll close this issue, if you have any questions, please let me know to reopen this anytime. Please also reference the example in the [documentation](https://xuri.me/excelize/en/workbook.html#OpenReader) about read data stream from `io.Reader` and return a populated spreadsheet file.
