### ISSUE TITLE
Apply style for cells in merged range based on the master cell 合并单元格时，如何把前面单元格的样式应用到被合并的单元格

### ISSUE THREAD

**Issue by ZQHcode** [qax-os/excelize#1593]
合并单元格时，如何把前面单元格的样式应用到被合并的单元格，如：A1 合并 B1，单元格A1的四个边框是灰色，B1没有设置边框样式，这个时候合并完，还是只有A1的单元格边框是灰色

**Comment by xuri** [comment]
Thanks for your issue. Please get the style index of cell A1 first, and then apply this style for the cells in the merged range like this:

```go
package main

import (
    "fmt"

    "github.com/xuri/excelize/v2"
)

func main() {
    f, err := excelize.OpenFile("Book1.xlsx")
    if err != nil {
        fmt.Println(err)
        return
    }
    defer func() {
        if err := f.Close(); err != nil {
            fmt.Println(err)
        }
    }()
    styleIdx, err := f.GetCellStyle("Sheet1", "A1")
    if err != nil {
        fmt.Println(err)
        return
    }
    if err = f.MergeCell("Sheet1", "A1", "B1"); err != nil {
        fmt.Println(err)
        return
    }
    if err = f.SetCellStyle("Sheet1", "A1", "B1", styleIdx); err != nil {
        fmt.Println(err)
        return
    }
    if err := f.SaveAs("Book2.xlsx"); err != nil {
        fmt.Println(err)
    }
}
```

**Comment by ZQHcode** [comment]
> Thanks for your issue. Please get the style index of cell A1 first, and then apply this style for the cells in the merged range like this:
> 
> ```go
> package main
> 
> import (
>     "fmt"
> 
>     "github.com/xuri/excelize/v2"
> )
> 
> func main() {
>     f, err := excelize.OpenFile("Book1.xlsx")
>     if err != nil {
>         fmt.Println(err)
>         return
>     }
>     defer func() {
>         if err := f.Close(); err != nil {
>             fmt.Println(err)
>         }
>     }()
>     styleIdx, err := f.GetCellStyle("Sheet1", "A1")
>     if err != nil {
>         fmt.Println(err)
>         return
>     }
>     if err = f.MergeCell("Sheet1", "A1", "B1"); err != nil {
>         fmt.Println(err)
>         return
>     }
>     if err = f.SetCellStyle("Sheet1", "A1", "B1", styleIdx); err != nil {
>         fmt.Println(err)
>         return
>     }
>     if err := f.SaveAs("Book2.xlsx"); err != nil {
>         fmt.Println(err)
>     }
> }
> ```

谢谢回复，但是我使用的是StreamWriter进行单元格合并，并没有上面的方法可以设置样式，我该如何处理呢

**Comment by xuri** [comment]
Since the stream writer is used for writing cells for an existing empty worksheet, so you can create style by the `NewStyle` function at first, and then bind the style ID for each cell in the merge cells range by stream writing. For example:

```go
package main

import (
    "fmt"

    "github.com/xuri/excelize/v2"
)

func main() {
    f := excelize.NewFile()
    defer func() {
        if err := f.Close(); err != nil {
            fmt.Println(err)
        }
    }()
    style, err := f.NewStyle(&excelize.Style{
        Border: []excelize.Border{
            {Type: "left", Color: "0000FF", Style: 2},
            {Type: "top", Color: "0000FF", Style: 2},
            {Type: "bottom", Color: "0000FF", Style: 2},
            {Type: "right", Color: "0000FF", Style: 2},
        },
    })
    if err != nil {
        fmt.Println(err)
        return
    }
    sw, err := f.NewStreamWriter("Sheet1")
    if err != nil {
        fmt.Println(err)
        return
    }
    if err := sw.SetRow("A1", []interface{}{excelize.Cell{StyleID: style}, excelize.Cell{StyleID: style}}); err != nil {
        fmt.Println(err)
        return
    }
    if err := sw.MergeCell("A1", "B1"); err != nil {
        fmt.Println(err)
        return
    }
    if err := sw.Flush(); err != nil {
        fmt.Println(err)
        return
    }
    if err := f.SaveAs("Book1.xlsx"); err != nil {
        fmt.Println(err)
    }
}
```

**Comment by ZQHcode** [comment]
如果是在同一行的话通过上面的方式是可以的；现在还有一种场景是在同一列进行合并，如果按照上述方法操作，执行完合并操作后，由于StreamWriter只能一行一行顺序写，会影响到后面行数据的写入；请问有没有不通过设置excelize.Cell的方式，就可以设置它的样式呢，谢谢

**Comment by xuri** [comment]
You need to set the style for each cell in the merged cells range before merging cells with the stream writer, and the style and cell value should be prepared before merging cells and written with the stream writer at once. If you need to modify cell values or styles after writing, you need to use the normal mode functions instead of stream writer.
