### ISSUE TITLE
Unable to work in golang1.21

### ISSUE THREAD

**Issue by yushengji** [qax-os/excelize#1595]
No error was reported when exporting the Excel file

**Comment by xuri** [comment]
Thanks for your feedback. This issue is duplicated with #1465, I have feedback with the Go team, and this issue is still being addressed in progress. I closed this and merged it to the issue #1456 to discuss this problem.

**Comment by xuri** [comment]
This was duplicated with issues #1465, #1595, #1603, #1608, #1614, #1619 and #1620. There are some incompatible changes in the Go 1.21.0 encoding/xml library. I have given feedback to the Go team and created a patch for it (golang/go#61881), and still waiting for a reply. The Go team has added golang/go#62051 to the Go 1.21.1 milestone. I suggest using the Go 1.20.7 and previous Go released version or waiting for the next Go minor releases.

**Comment by xuri** [comment]
This was duplicated with issues #1465, #1603, #1608, #1614, #1619, #1620 and #1621. There are some incompatible changes in the Go 1.21.0 encoding/xml library. I have given feedback to the Go team and created a patch for it (golang/go#61881), and still waiting for a reply. The Go team has added golang/go#62051 to the Go 1.21.1 milestone. I suggest using the Go 1.20.7 and previous Go released version or waiting for the next Go minor releases.
