### ISSUE TITLE
Use the NewStreamWriter function on no-blank worksheets 对于一个已存在数据的sheet，如何使用StreamWriter往它的后面继续写入数据

### ISSUE THREAD

**Issue by ZQHcode** [qax-os/excelize#1598]
对于一个已存在数据的sheet，第一行第二行已经有数据了；这个时候打开这个excel文件，如何使用StreamWriter往第三行继续写入数据；ps: 在实际使用过程中，发现原excel的前两行数据会不见

**Comment by xuri** [comment]
This issue was duplicated with issues #1445 and #1537.
