### ISSUE TITLE
Is there a way to set the default style for a sheet

### ISSUE THREAD

**Issue by hkhere** [qax-os/excelize#1600]
For example, if one wants to make a sheet borderless. Currently one may be able to  achieve this by using the  `sheet.SetRowStyle` with the `TotalRows` as the `end` argument. But that is a big loop, the`TotalRows` is 1048576.

**Comment by xuri** [comment]
Thanks for your issue. You can use the `SetColStyle` function to set styles for all cells in a worksheet, for example:

```go
err := f.SetColStyle("Sheet1", "A:XFD", 0)
```

If you want to hide the gride line for a worksheet, please use the `SetSheetView` function like this:

```go
disable := false
err := f.SetSheetView("Sheet1", -1, &excelize.ViewOptions{
    ShowGridLines: &disable,
})
```

**Comment by hkhere** [comment]
very much appreciated!
