### ISSUE TITLE
Copy images to another cell 单元格里的数据是图片，如何复制到另一个excel的单元格中

### ISSUE THREAD

**Issue by ZQHcode** [qax-os/excelize#1605]
单元格里的数据是图片，如何复制到另一个excel的单元格中

**Comment by xuri** [comment]
This issue similar to #41, #134, #472, #532, #574, #629, #640, #712 #818. Currently, this library doesn't support copy images to another workbook, but you can read picture properties and binary data by the [`GetPictures`](https://pkg.go.dev/github.com/xuri/excelize/v2#File.GetPictures) function at first, and then insert the image to another worksheet with [`AddPictureFromBytes`](https://pkg.go.dev/github.com/xuri/excelize/v2#File.AddPictureFromBytes). I closed this and merged it into issue #41 is still discussing this feature.

**Comment by xuri** [comment]
This issue similar to #41, #134, #472, #532, #574, #629, #640, #712 and #818. Currently, this library doesn't support copy images to another workbook, but you can read picture properties and binary data by the [`GetPictures`](https://pkg.go.dev/github.com/xuri/excelize/v2#File.GetPictures) function at first, and then insert the image to another worksheet with [`AddPictureFromBytes`](https://pkg.go.dev/github.com/xuri/excelize/v2#File.AddPictureFromBytes). I closed this and merged it into issue #41 is still discussing this feature.
