### ISSUE TITLE
Apply style for cells in merged range based on the master cell 合并单元格时，如何把前面单元格的样式应用到被合并的单元格

### ISSUE THREAD

**Issue by ZQHcode** [qax-os/excelize#1606]
你好，已经回复了上次的issue，由于无法进行reopen，重新提问下 https://github.com/qax-os/excelize/issues/1593

**Comment by xuri** [comment]
Please don't create duplicate issue.

**Comment by ZQHcode** [comment]
好的，已经关闭，麻烦在上一个issue中解答下，谢谢
