### ISSUE TITLE
xlsx文件无法用Excel打开

### ISSUE THREAD

**Issue by yyMlv** [qax-os/excelize#1608]
**Description**
使用Create spreadsheet示例生成的xlsx文件在Excel中报错，测试后发现 /Book1.xlsx/xl/worksheets/sheet1.xml 中 <sheetData xmlns="">导致Excel打开失败。

package main

import (
    "fmt"

    "github.com/xuri/excelize/v2"
)

func main() {
    f := excelize.NewFile()
    defer func() {
        if err := f.Close(); err != nil {
            fmt.Println(err)
        }
    }()
    // Create a new sheet.
    index, err := f.NewSheet("Sheet2")
    if err != nil {
        fmt.Println(err)
        return
    }
    // Set value of a cell.
    f.SetCellValue("Sheet2", "A2", "Hello world.")
    f.SetCellValue("Sheet1", "B2", 100)
    // Set active sheet of the workbook.
    f.SetActiveSheet(index)
    // Save spreadsheet by the given path.
    if err := f.SaveAs("Book1.xlsx"); err != nil {
        fmt.Println(err)
    }
}
![截屏2023-08-14 17 08 38](https://github.com/qax-os/excelize/assets/3760761/3e7aa607-67c6-4441-984b-9a126d89ba96)

**Output of `go version`:**

```text
go version go1.21.0 darwin/amd64
```

**Excelize version or commit ID:**

```text
v2.7.1
```

**Environment details (OS, Microsoft Excel™ version, physical, etc.):**
MacOS 13.5 (22G74)
Microsoft Excel for Mac 16.75.2(23071901)

**Comment by xuri** [comment]
This issue is duplicated with #1465, #1595 and #1603. Also reference golang/go#61881.
