### ISSUE TITLE
Consistency between CalcCellValue results and Excel calculations?

### ISSUE THREAD

**Issue by KAMIENDER** [qax-os/excelize#1611]
I would like to know if the results of CalcCellValue are exactly the same as those calculated by Excel. Is there any detailed documentation or data available that explains and substantiates this?

**Comment by xuri** [comment]
Currently, not all formula functions have been supported, and the supported formula functions were listed in the documentation of the [`CalcCellValue`](https://xuri.me/excelize/en/cell.html#CalcCellValue) function. The aims for calculation function implementation are the same with Excel, but we can't exactly substantiate this. The library test each formula function, and the result of each formula are the same as those calculated by Excel. If you find any consistency issues, welcome to feedback.

**Comment by xuri** [comment]
Currently, not all formula functions have been supported, the formula engine still working in progress, and the supported formula functions were listed in the documentation of the [`CalcCellValue`](https://xuri.me/excelize/en/cell.html#CalcCellValue) function. The aims for calculation function implementation are the same with Excel, but we can't exactly substantiate this. The library test each formula function, and the result of each formula are the same as those calculated by Excel. If you find any consistency issues, welcome to feedback.

**Comment by xuri** [comment]
I closed this issue, and merged this into #65 to continue to discuss this. If you have any question, please let me know, and reopen this anytime.
