### ISSUE TITLE
go 1.21 无法生成正确的excel

### ISSUE THREAD

**Issue by 645775992** [qax-os/excelize#1614]
![image](https://github.com/qax-os/excelize/assets/52311460/f8cc243c-0451-470f-a633-1e552c9e87d2)

希望能尽快解决

**Comment by 645775992** [comment]
完全按照demo书写的

**Comment by xuri** [comment]
Please don't create a duplicate issue, I've closed this. This was duplicated with issue #1465, #1595 and #1603. There are some incompatible changes in the Go 1.21.0 encoding/xml library. I have given feedback to the Go team and created a patch for it (golang/go#61881). I suggest waiting for the next minor releases or using the Go 1.20.7 or previous version, and you can also vendoring the Go encoding/xml package by yourself if you need to, or apply the patchsets in the CL https://go.dev/cl/466295 if you can.
