### ISSUE TITLE
Formula referencess not updated after InsertCols

### ISSUE THREAD

**Issue by CSHornby** [qax-os/excelize#1615]
**Description**
Formula references are not updated after using InsertCols. 

**Steps to reproduce the issue:**
1. Create a formula in cell F5 that references  C5 + D5 + I5
2. InsertCols at column C or D or G

**Describe the results you received:**
Formula references are not updated, so formula still reads C5 + D5 + I5

**Describe the results you expected:**
Formula references should be updated to: 
D5 + E5 + J5 for insert at C
C5 + E5 + J5 for insert at D
C5 + D5 + J5 for insert at G

**Output of `go version`:**
```
go version go1.20.5 linux/amd64
```

**Excelize version or commit ID:**

```text
v2.7.2-0.20230703160637-e2c74162925c
```

**Environment details (OS, Microsoft Excel™ version, physical, etc.):**
Ubuntu Linux on laptop

**Comment by xuri** [comment]
Thanks for your issue. As the documentation of the `InsertCols` function says: "which will affect changes in references such as formulas, charts, and so on. If there is any referenced value of the worksheet, it will cause a file error when you open it. The excelize only partially updates these references currently". I'll consider adding support for this in the future.

**Comment by xuri** [comment]
This library now support this feature, please upgrade to the master branch code, and this feature will be released in the next version.
