### ISSUE TITLE
get wrong row columns

### ISSUE THREAD

**Issue by xiaogu-space** [qax-os/excelize#1616]
`rows, err := f.GetRows(list[0])`

the xlsx like this
![image](https://github.com/qax-os/excelize/assets/8435230/b7b8bf05-c493-49c3-a3da-b09f5371d2db)
but the row great than 1 the row length is 9，not 10
![image](https://github.com/qax-os/excelize/assets/8435230/97cfda95-6fc5-43cb-afc8-7fda6a30bb77)

**Comment by xuri** [comment]
Thanks for your issue. This was duplicated with issue #721, #1016, #1135, #1245, #1452, #1557 and #1597. Please check the length of each cell before getting the element in the slice. I have made a figure in issue #1245 to explain what kind of cells will be skipped for your reference, and I closed this issue. If you have any questions, please let me know to reopen this anytime.
