### ISSUE TITLE
Cells with quotes

### ISSUE THREAD

**Issue by tredoe** [qax-os/excelize#1618]
**Description**

If there is a cell with quotes into a column and in the next row also have quotes, then it's got the error : 

`extraneous or missing " in quoted-field`

**Describe the results you received:**

ERROR: parse error on line 1172, column 42: extraneous or missing " in quoted-field

**Output of `go version`:**

```text
go version go1.21.0 linux/amd64
```

**Excelize version or commit ID:**

```text
v2.7.1
```

**Environment details (OS, Microsoft Excel™ version, physical, etc.):**

Description:	Ubuntu 22.04.3 LTS
LibreOffice 7.3.7.2
[error-quotes.xlsx](https://github.com/qax-os/excelize/files/12383536/error-quotes.xlsx)

**Comment by xuri** [comment]
Thanks for your feedback. I have tested open your workbook with LibreOffice 7.3.7.2, Ubuntu 22.04.1 LTS, and it works well. Could you provide more details for this or standalone example program or reproducible demo? I noticed that you're using the Go 1.21.0, also reference issues #1465, #1595, #1603, and #1616. There are some incompatible changes in the Go 1.21.0 encoding/xml library. Please try using the Go 1.20.7 or the previous version if you can.

**Comment by tredoe** [comment]
I have tested on `go version
go version go1.20.7 linux/amd64` and it got the same error: `ERROR: parse error on line 9, column 39: extraneous or missing " in quoted-field
exit status 1
`

**Comment by xuri** [comment]
Thanks for your feedback. Could you show us a screenshot and complete, standalone example program or reproducible demo?

**Comment by tredoe** [comment]
By the way, I got the same error with an XLS file:

https://github.com/extrame/xls/issues/90

**Comment by tredoe** [comment]
@xuri Sorry! I got the issue and it is not by Excelize. Sorry!

**Comment by xuri** [comment]
Thanks for the feedback. I've closed this issue.
