### ISSUE TITLE
Excel Cannot Open Generated File

### ISSUE THREAD

**Issue by teschste-reyrey** [qax-os/excelize#1620]
**Description**
Anytime I generate a new xlsx file, Excel is not able to open it.  I am using Go Modules version github.com/xuri/excelize/v2.
I did some digging and the generated sheet1.xml file file has xmlns="" added to the dimension, sheetViews, sheetFormatPr, and sheetData tags.  Through experimentation I was able to determine that if I remove the xmlns="" property from the sheetData tag (or all tags), the workbook will open normally.

**Steps to reproduce the issue:**
1. var xlsx = excelize.NewFile()
2. xlsx.SaveAs([filepath_and_name])
3. Attempt to open the generated file with Excel and it will report "We found a problem with some content in [filename].  Do you want us to try to recover as much as we can?"

**Describe the results you received:**
Attempting to open a generated file with Excel produces the message: "We found a problem with some content in [filename].  Do you want us to try to recover as much as we can?"

**Describe the results you expected:**
The file to open correctly.

**Output of `go version`:**

```text
go version go1.21.0 windows/amd64
```

**Excelize version or commit ID:**

```text
v2@2.7.1
```

**Environment details (OS, Microsoft Excel™ version, physical, etc.):**
Windows 10, Excel 2016
[sheet1.txt](https://github.com/qax-os/excelize/files/12397711/sheet1.txt)

**Comment by xuri** [comment]
This was duplicated with issue #1465, #1595, #1603 and #1619. I suggest using the previous Go version or waiting for the next minor releases.
