### ISSUE TITLE
Strange bug: gened file broken while using go1.21.0 but works fine in older versions

### ISSUE THREAD

**Issue by anotherGoogleFan** [qax-os/excelize#1621]
The code is very simple:
```
package main

import "github.com/xuri/excelize/v2"

func main() {
	f := excelize.NewFile()
	sheetName := "Sheet1"
	_, _ = f.NewSheet(sheetName)
	_ = f.SaveAs("temp.xlsx")
}
```
When I gened the ```temp.xlsx``` using go 1.20  ```go version go1.20.7 darwin/amd64``` or older version, all things goes well; 
when I used go 1.21 ```go version go1.21.0 darwin/amd64``` the gened file cannot be opened by microsoft excel. It's said broken file.

**Comment by xuri** [comment]
This was duplicated with issue #1465, #1595, #1603, #1608, #1614, #1619 and #1620. I suggest using the previous Go version or waiting for the next minor releases. There are some incompatible changes in the Go 1.21 encoding/xml library. I have given feedback to the Go team and created a patch for it (golang/go#61881), and still waiting for a reply. The Go team has added golang/go#62051 to the Go1.21.1 milestone. I suggest using the previous Go version or waiting for the next Go minor releases.

**Comment by xuri** [comment]
If you are reporting a new issue, make sure that we do not have any duplicates
already open. This was duplicated with issue #1465, #1595, #1603, #1608, #1614, #1619 and #1620. There are some incompatible changes in the Go 1.21 encoding/xml library. I have given feedback to the Go team and created a patch for it (golang/go#61881), and still waiting for a reply. The Go team has added golang/go#62051 to the Go1.21.1 milestone. I suggest using the previous Go version or waiting for the next Go minor releases.

**Comment by xuri** [comment]
If you are reporting a new issue, make sure that we do not have any duplicates already open. This was duplicated with issue #1465, #1595, #1603, #1608, #1614, #1619 and #1620. There are some incompatible changes in the Go 1.21 encoding/xml library. I have given feedback to the Go team and created a patch for it (golang/go#61881), and still waiting for a reply. The Go team has added golang/go#62051 to the Go1.21.1 milestone. I suggest using the previous Go version or waiting for the next Go minor releases.

**Comment by xuri** [comment]
If you are reporting a new issue, make sure that we do not have any duplicates already open. This was duplicated with issue #1465, #1595, #1603, #1608, #1614, #1619 and #1620. There are some incompatible changes in the Go 1.21.0 encoding/xml library. I have given feedback to the Go team and created a patch for it (golang/go#61881), and still waiting for a reply. The Go team has added golang/go#62051 to the Go 1.21.1 milestone. I suggest using the Go 1.20.7 and previous Go released version or waiting for the next Go minor releases.

**Comment by xuri** [comment]
If you are reporting a new issue, make sure that we do not have any duplicates already open. This was duplicated with issues #1465, #1595, #1603, #1608, #1614, #1619 and #1620. There are some incompatible changes in the Go 1.21.0 encoding/xml library. I have given feedback to the Go team and created a patch for it (golang/go#61881), and still waiting for a reply. The Go team has added golang/go#62051 to the Go 1.21.1 milestone. I suggest using the Go 1.20.7 and previous Go released version or waiting for the next Go minor releases.
