### ISSUE TITLE
Not able to view data on xlsx file

### ISSUE THREAD

**Issue by nikhilbhavsar121** [qax-os/excelize#1622]
When we open the Excel file, there is no data present. However, when we attempt to parse the file programmatically, the data becomes available within the file.

Could you please assist in identifying the issue?

File are created properly previously in production and staging server.

**Comment by xuri** [comment]
Which version of the Go language are you using? Note that there are some incompatible changes in the Go 1.21.0 encoding/xml library. Please try using the Go 1.20.7 or the previous version if you can. Also reference issues issues #1465, #1595, #1603, #1608, #1614, #1619 and #1620. If you still have problems, follow by issue template to provide environment details, code, and steps to reproduce the issue.

**Comment by AndreasBuc** [comment]
Hello, I guess I have the same issue. 
If I create the excel file, it cannot be opend by excel. Excel tells me it can try to repair the file, but it will fail.
It started just recently. This is my excel version: (Version 2307 Build 16.0.16626.20170) 64 Bit 

I have following files:
main.go, go.mod, Dockerfile and docker-compose.yaml:
### main.go
```
package main

import (
	"fmt"

	"github.com/xuri/excelize/v2"
)

func main() {
	f := excelize.NewFile()
	defer func() {
		if err := f.Close(); err != nil {
			fmt.Println(err)
		}
	}()
	// Create a new sheet.
	index, err := f.NewSheet("Sheet2")
	if err != nil {
		fmt.Println(err)
		return
	}
	// Set value of a cell.
	f.SetCellValue("Sheet2", "A2", "Hello world.")
	f.SetCellValue("Sheet1", "B2", 100)
	// Set active sheet of the workbook.
	f.SetActiveSheet(index)
	// Save spreadsheet by the given path.
	if err := f.SaveAs("Book1.xlsx"); err != nil {
		fmt.Println(err)
	}
}
```
### go.mod
```
module ExcelTest

go 1.20.5

require (
	github.com/mohae/deepcopy v0.0.0-20170929034955-c48cc78d4826 // indirect
	github.com/richardlehane/mscfb v1.0.4 // indirect
	github.com/richardlehane/msoleps v1.0.3 // indirect
	github.com/xuri/efp v0.0.0-20220603152613-6918739fd470 // indirect
	github.com/xuri/excelize/v2 v2.7.1 // indirect
	github.com/xuri/nfp v0.0.0-20220409054826-5e722a1d9e22 // indirect
	golang.org/x/crypto v0.8.0 // indirect
	golang.org/x/net v0.9.0 // indirect
	golang.org/x/text v0.9.0 // indirect
)
```

### Dockerfile

```
FROM golang:1.20.5-alpine
COPY . /app
WORKDIR /app
EXPOSE 5000
CMD ["go", "run", "main.go"]

```

### docker-compose.yaml
```
version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile

    volumes:
      - ./:/app
```

writing 

```
docker-compose up
```
will create the excel file

Thank you very much for working on this project. 
I really appreciate it.
Andreas

**Comment by xuri** [comment]
It seems still not have enough info of code and attachments to reproduce this issue, so I'll close this issue, if you have any questions, please let me know to reopen this anytime.

**Comment by nikhilbhavsar121** [comment]
Thanks, 
It's working after degrading to 1.20.7 version.

**Comment by xuri** [comment]
The [Go 1.21.1](https://go.dev/doc/devel/release#go1.21.1) is released, this issue has been fixed.
