### ISSUE TITLE
getPicture decode WsDr and search picture twice.

### ISSUE THREAD

**Issue by yicixin** [qax-os/excelize#1624]
**Description**
I'm trying to get all the pictures in a xlsx file. At present, I can only traverse the cells one by one to get pictures. I found multiple decoding operations in the loop affect the performance.

![2a5b2bce2cca4264ad57e74fde45ebc0](https://github.com/qax-os/excelize/assets/45734708/36d1e0bd-fd54-4630-97de-3fc4f8621793)

**Comment by xuri** [comment]
Did you have any problems?  What's the result you expected, what's the result you expected? Please follow the issue template, and briefly describe the problem you are having in a few paragraphs.

**Comment by xuri** [comment]
Did you got any problems?  What's the result you expected, what's the result you expected? Please follow the issue template, and briefly describe the problem you are having in a few paragraphs.

**Comment by yicixin** [comment]
Maybe what I need is a function to directly get all the pictures in the xlsx file, for example, get a picture map indexed by rows and columns. This will avoid decoding WsDr in the loop.
