### ISSUE TITLE
How to get a style object based on a styleId

### ISSUE THREAD

**Issue by zsy619** [qax-os/excelize#1631]
**Description**

**Steps to reproduce the issue:**
如何根据styleId获取到style对象

**Describe the results you received:**

**Describe the results you expected:**

**Output of `go version`:**

```text
go version go1.21.0 darwin/amd64
```

**Excelize version or commit ID:**

```text
github.com/xuri/excelize/v2 v2.7.1
```

**Environment details (OS, Microsoft Excel™ version, physical, etc.):**

**Comment by xuri** [comment]
This issue was duplicated with #314.
