### ISSUE TITLE
为什么DataValidation的SetDropList方法设置的下拉长度限制0-255，如何能够解除这个限制呢

### ISSUE THREAD

**Issue by ZQHcode** [qax-os/excelize#1632]
为什么DataValidation的SetDropList方法设置的下拉长度限制0-255，请问如何能够解除这个限制呢

**Comment by xuri** [comment]
There are limits to the number of items that will show in a data validation drop down list: The list can show up to show 32,767 items from a list on the worksheet. If you type the items into the data validation dialog box (a delimited list), the limit is 256 characters, including the separators. If your data validation list source formula is over the maximum length limit, please set the allowed values in the worksheet cells, and use the `SetSqrefDropList` function to set the reference for their cells. For example, set data validation on Sheet1!B1 with validation criteria settings, and create an in-cell dropdown by allowing list sources 1 to 300:

```go
package main

import (
    "fmt"

    "github.com/xuri/excelize/v2"
)

func main() {
    f := excelize.NewFile()
    defer func() {
        if err := f.Close(); err != nil {
            fmt.Println(err)
            return
        }
    }()

    for r := 1; r <= 300; r++ {
        cell, err := excelize.CoordinatesToCellName(1, r)
        if err != nil {
            fmt.Println(err)
            return
        }
        if err = f.SetCellValue("Sheet1", cell, r); err != nil {
            fmt.Println(err)
            return
        }
    }
    dv := excelize.NewDataValidation(true)
    dv.SetSqref("B1")
    dv.SetSqrefDropList("A1:A300")
    if err := f.AddDataValidation("Sheet1", dv); err != nil {
        fmt.Println(err)
        return
    }
    if err := f.SaveAs("Book1.xlsx"); err != nil {
        fmt.Println(err)
    }
}
```

**Comment by ZQHcode** [comment]
目前不希望下拉选项的全部数据出现在excel的一列中；请问是出于什么考虑，SetDropList方法设置的下拉长度限制0-255？

**Comment by xuri** [comment]
That's the limit of the Excel, please also reference:
https://answers.microsoft.com/en-us/msoffice/forum/all/data-validation-is-there-a-work-around-to-the-256/d3b4ea7f-9c32-461a-97fd-16dcd21f6ec0
https://support.microsoft.com/en-us/office/excel-specifications-and-limits-1672b34d-7043-467e-8e27-269d656771c3
