### ISSUE TITLE
Excel Files generated with Excelize cannot be read anymore

### ISSUE THREAD

**Issue by Emanolo786** [qax-os/excelize#1633]
**Description**

I've been using Excelize with Golang without problem for 2 years.
Recently, although I did not change anything, the excel files generated by my golang module could not be read with Excel for Mac.
The strange item: I did not change anything in my module, which worked perfectly before. It seems that some XML items are not supported any more.
It must be related to the new release of Excel 16.76 on August 15th:
[https://learn.microsoft.com/en-us/officeupdates/release-notes-office-for-mac](url)

**Steps to reproduce the issue:**
1. Run Go Module
2. Open Excel File
3. Get Error message

**Describe the results you received:**
Here is the message provided when I try to open the file with Excel:

Repair Result to Excel Test0.xml
Errors were detected in file ’pathtofile’

Repaired Part: /xl/worksheets/sheet2.xml part with XML error.  HRESULT 0x8000ffff

Microsoft Words for Mac
Version: 16.76 (23081101)

Message:
We found a problem with some content in ’Excel Test.xlsx’. Do you want us to try to recover as much as we can? If you trust the source of this workbook, click Yes.

Excel was able to open the file by repairing or removing the unreadable content.

**Describe the results you expected:**

**Output of `go version`:**

```text
(paste your output here)
```

**Excelize version or commit ID:**
v2.7.1

```text
(paste here)
```

**Environment details (OS, Microsoft Excel™ version, physical, etc.):**
Go module running with Ubuntu Linux
Excel for Mac 16.76 running with MacOS Ventura 13.4.1

**Comment by RobM83** [comment]
I got the same problem, when I locally build the binary it all works fine, this is with version `1.20.6 (darwin/arm64)`.
When it is build by the gitlab runner, which uses the `golang:latest` which is currently at `1.21.0` the saving of excel files fails.  Both produce executable binaries.

**Comment by RobM83** [comment]
Did some additional testing;

- Upgrade Excelize from v2.7.1 to v2.8.0 made no difference.
- Tried using the `golang:1.20.6` container for the gitlab-runner (same version as on mine local system) - without succes.
- Tried using the `golang:1.20.7` container for the gitlab-runner  with succes (thanks @jintaokoong )

**Comment by Emanolo786** [comment]
@RobM83 && jintaokong: Thanks a lot for the feedbacks.
If I understand it correctly, we have to compile on Golang 1.20.7 and it will work ?
If it does not work with Golang 1.21.0, is this a regression ?

**Comment by RobM83** [comment]
> @RobM83 && jintaokong: Thanks a lot for the feedbacks. If I understand it correctly, we have to compile on Golang 1.20.7 and it will work ? If it does not work with Golang 1.21.0, is this a regression ?

Yes, it will probably work with 1.20.7 (at least it did for me :-) ).
No idea if this is a regression.

**Comment by xuri** [comment]
If it does not work with Go 1.21.0, please reference the issues #1465, #1595, #1603, #1608, #1614, #1619, #1620, and #1621. There are some incompatible changes in the Go 1.21.0 encoding/xml library. I have given feedback to the Go team and created a patch for it (golang/go#61881), and the Go team has added golang/go#62051 to the Go 1.21.1 milestone. I suggest using the Go 1.20.7 and previous Go released version or waiting for the next Go minor releases.

**Comment by xuri** [comment]
I have added notice on the [README](https://github.com/xuri/excelize/blob/master/README.md#introduction) and [documentation website](https://xuri.me/excelize/en/base/installation.html#install) for this, and I've closed this. If you have any questions, please let me know, and reopen this anytime.

**Comment by Emanolo786** [comment]
I did downgrade to 1.20.7 and it did work for me.
Thank you so much to everyone for your help and support.
