### ISSUE TITLE
Support go structure tag mapping

### ISSUE THREAD

**Issue by quanxiangsheng** [qax-os/excelize#1636]
I don't know if I haven't found the documentation or a workaround, but if not, I'd like to ask if excelize supports or releases excel's read/write struct mapping capabilities, like gocarina/gocsv, gorm, go-redis, and many other libraries support tag mapping. thank you...

**Comment by xuri** [comment]
Thanks for your issue. This issue was similar with #619, #992, #1208, #1302, #1303, #1357 and #1540, so I've closed this. Users can easily make this wrapper and even create their own complex nested structure. I didn't suggest introducing this feature to make the library core and easy.
