### ISSUE TITLE
版本兼容

### ISSUE THREAD

**Issue by Xiaomajohn** [qax-os/excelize#1637]
**不兼容go 1.21.0,使用该版本后，新创建的excel文件，打开时提示损坏。更新本库到最新版本仍然出现了问题，go版本回溯到go1.20.2，没有出现问题，其他版本没有出现“

**Comment by xuri** [comment]
If you are reporting a new issue, make sure that we do not have any duplicates already exist. If it does not work with Go 1.21.0, please reference the issues #1465, #1595, #1603, #1608, #1614, #1619, #1620, #1621, #1623 and #1633. There are some incompatible changes in the Go 1.21.0 encoding/xml library. I have given feedback to the Go team and created a patch for it (golang/go#61881), and the Go team has added golang/go#62051 to the Go 1.21.1 milestone. I suggest using the Go 1.20.7 and previous Go released version or waiting for the next Go minor releases. I have added notice on the [README](https://github.com/xuri/excelize/blob/master/README.md#introduction) and [documentation website](https://xuri.me/excelize/en/base/installation.html#install) for this, and I've closed this. If you have any questions, please let me know, and reopen this anytime.
