### ISSUE TITLE
File showing Corrupted

### ISSUE THREAD

**Issue by deb151292** [qax-os/excelize#1640]
When we are not using "streamWriter" its showing corrupted file . "streamWriter" does not support the HyperLink Feature so how can we do that . 2 years our application running suddenly the new update causing problem . its only happening in alpine docker that we are using as our server but its working in our local code .

**Comment by deb151292** [comment]
Go version 
1.17.7

**Comment by deb151292** [comment]
No Docker Go version is not 1.21.0

**Comment by xuri** [comment]
@mpietrowicz, please reference the issue in above reply. Please using the Go 1.20.7 and previous Go released version or waiting for the next Go minor releases. The Go 1.21.1 will be released in the September 6, 2023.

**Comment by xuri** [comment]
@deb151292, there are many reasons can be caused workbook corrupted, still not have enough info of code and attachments to reproduce this issue, so I'll close this issue, if you have any questions, please let me know to reopen this anytime.
