### ISSUE TITLE
getCellDate獲取值時類型是否寫錯了

### ISSUE THREAD

**Issue by suifengsanjin** [qax-os/excelize#1643]
https://github.com/qax-os/excelize/blob/3b2b8ca8d6130723f494b773e462b03cfa011140/cell.go#L568C9-L568C9
568行 
return f.formattedValue(c, raw, CellTypeBool)
這裡單元格類型應該是不是應該設置為CellTypeDate

**Comment by xuri** [comment]
Thanks for your issue. The cell type should be `CellTypeDate`, but this statement is just used to read raw cell value, the result of the cell value is correct even for any cell type. If you like to create a pull request for this, that would be great.

**Comment by xuri** [comment]
Thanks for your issue. I have fixed this issue, please try to upgrade the master branch code, and this patch will be released in the next version.
