### ISSUE TITLE
SetHeaderFooter setting ScaleWithDoc & AlignWithMargins do not appear to work

### ISSUE THREAD

**Issue by fnickels** [qax-os/excelize#1645]
**Description**

When calling SetHeaderFooter() with either or both ScaleWithDoc & AlignWithMargins these settings do not appear to change when opening the resulting Excel document.

**Steps to reproduce the issue:**
1. Use code similar to that shown below
2. Write Excel file
3. Open the file with Excel
4. Navigate to Page Layout -> Page Setup -> Header/Footer
5. Both check boxes are still checked

```
	if err := tp.excelFile.SetHeaderFooter("Sheet1", &excelize.HeaderFooterOptions{
		OddHeader:        "&R&D &T",
		OddFooter:        "&L&F&C&A&RPage: &P/&N",
		ScaleWithDoc:     false,
		AlignWithMargins: false,
	}); err != nil {
		return err
	}
```

**Describe the results you received:**

![image](https://github.com/qax-os/excelize/assets/8341596/2986786d-f128-4998-98e4-064f378f7b16)

**Describe the results you expected:**

Expected both check boxes to be unchecked.

**Output of `go version`:**

```text
go version go1.20.7 linux/amd64
```

**Excelize version or commit ID:**

```text
	github.com/xuri/excelize/v2 v2.7.1
```

**Environment details (OS, Microsoft Excel™ version, physical, etc.):**

WSL2 under Windows, Ubuntu 22.04

**Comment by xuri** [comment]
Thanks for your issue. I have changed the data type for the `AlignWithMargins` and `ScaleWithDoc` fields to fix this. Please try to upgrade the master branch code, and this patch will be released in the next version. You can set `AlignWithMargins` and `ScaleWithDoc` like this:

```diff
+disable := false
 if err := tp.excelFile.SetHeaderFooter("Sheet1", &excelize.HeaderFooterOptions{
     OddHeader:        "&R&D &T",
     OddFooter:        "&L&F&C&A&RPage: &P/&N",
-    ScaleWithDoc:     false,
-    AlignWithMargins: false,
+    ScaleWithDoc:     &disable,
+    AlignWithMargins: &disable,
 }); err != nil {
     return err
 }
```
