### ISSUE TITLE
FitToWidth does not take focus in Excel Page Setup dialog box when used

### ISSUE THREAD

**Issue by fnickels** [qax-os/excelize#1646]
**Description**

Not sure if this is a bug, but would love to have the 'Fit to:' scaling option fall into focus when specifying Fit To Scaling options.  The documentation seems to suggest it should be.

See: https://github.com/qax-os/excelize/blob/master/xmlWorksheet.go#L999-L1006

**Steps to reproduce the issue:**
1. Use code similar to that shown below
2. Write Excel file
3. Open the file with Excel
4. Navigate to Page Layout -> Page Setup -> Page
5. 'Adjust to:' radion button is the selected choice, was hoping to see 'Fit to:' as the active selection

```
f := excelize.NewFile()
var (
    size                 = 1
    orientation          = "landscape"
    firstPageNumber uint = 1
    fitToHeight          = 2
    fitToWidth           = 2
    blackAndWhite        = false
)
if err := f.SetPageLayout("Sheet1", &excelize.PageLayoutOptions{
    Size:            &size,
    Orientation:     &orientation,
    FirstPageNumber: &firstPageNumber,
    FitToHeight:     &fitToHeight,
    FitToWidth:      &fitToWidth,
    BlackAndWhite:   &blackAndWhite,
}); err != nil {
    fmt.Println(err)
}
```

**Describe the results you received:**

![image](https://github.com/qax-os/excelize/assets/8341596/aff61f3b-763d-4cc2-98e2-3897da2cc44d)

**Describe the results you expected:**

Was hoping to see the 'Fit to:' radio button selected.

**Output of `go version`:**

```text
go version go1.20.7 linux/amd64
```

**Excelize version or commit ID:**

```text
	github.com/xuri/excelize/v2 v2.7.1
```

**Environment details (OS, Microsoft Excel™ version, physical, etc.):**

WSL2 under Windows, Ubuntu 22.04

**Comment by xuri** [comment]
Thanks for your issue. Please also set the sheet property to enable fit-to-page settings:

```diff
f := excelize.NewFile()
var (
    size                 = 1
    orientation          = "landscape"
    firstPageNumber uint = 1
    fitToHeight          = 2
    fitToWidth           = 2
    blackAndWhite        = false
+   enable               = true
)
+if err := f.SetSheetProps("Sheet1", &excelize.SheetPropsOptions{
+    FitToPage: &enable,
+ }); err != nil {
+   fmt.Println(err)
+   return
+}
if err := f.SetPageLayout("Sheet1", &excelize.PageLayoutOptions{
    Size:            &size,
    Orientation:     &orientation,
    FirstPageNumber: &firstPageNumber,
    FitToHeight:     &fitToHeight,
    FitToWidth:      &fitToWidth,
    BlackAndWhite:   &blackAndWhite,
}); err != nil {
    fmt.Println(err)
}
```

**Comment by xuri** [comment]
I've closed this, if you have any question, please let me know, and reopen this anytime.
