### ISSUE TITLE
i am input data,but can not show sheet value

### ISSUE THREAD

**Issue by dingyuanhong** [qax-os/excelize#1652]
i am use the same code to export file but in same linux the file exported can not show the data my export,only can read by code use this library。
in go 1.21 is error.
in go 1.18 is ok.
[main.go.txt](https://github.com/qax-os/excelize/files/12539621/main.go.txt)

**Comment by xuri** [comment]
Thanks for your issue. If you are reporting a new issue, make sure that we do not have any duplicates already exist. If it does not work with Go 1.21.0, please reference the (pinned) issues #1465, #1595, #1603, #1608, #1614, #1619, #1620, #1621, #1623, #1633, #1637, #1641, #1642, #1648 and #1651. There are some incompatible changes in the Go 1.21.0 encoding/xml library. I have given feedback to the Go team and created a patch for it (golang/go#61881), and the Go team has added golang/go#62051 to the Go 1.21.1 milestone, and it will be released on [Wednesday, September 6](https://groups.google.com/g/golang-announce/c/UXJQvKffcao). I suggest using the Go 1.20.7 and previous Go released version or waiting for the Go 1.21.1 releases. I have added notice on the [README](https://github.com/xuri/excelize#introduction) and [documentation website](https://xuri.me/excelize/en/base/installation.html#install) for this, and I've closed this. If you have any questions, please let me know, and reopen this anytime.

谢谢你的反馈，在您创建新的问题之前，请确保不存在任何重复的问题。请参考（置顶）问题 #1465，#1595，#1603，#1603，#1614，#1619，#1620，#1621，#1623，#1633，#1637，#1641，#1642，#1648 和 #1651。Go 1.21.0 对 encoding/xml 标准库做了不兼容的更改，我已将该问题反馈至 Go 团队，并提交了修复补丁 golang/go#61881，将在下一个版本 Go 1.21.1 中修复。目前建议使用 Go 1.20.7 以及更早版本，或等待 [2023年9月6日](https://groups.google.com/g/golang-announce/c/UXJQvKffcao/m/3yTGjzoQAAAJ) Go 语言 1.21.1 版本发布。我已经为此在[自述文档](https://github.com/xuri/excelize/blob/master/README_zh.md#简介)和[文档网站](https://xuri.me/excelize/zh-hans/base/installation.html#install)上添加了通知，因此我将关闭此问题。如果您有任何问题，请告诉我，并可随时重新打开。

**Comment by xuri** [comment]
The [Go 1.21.1](https://go.dev/doc/devel/release#go1.21.1) is released, this issue has been fixed.
