### ISSUE TITLE
Excel Files generated with Excelize cannot be read correctly

### ISSUE THREAD

**Issue by mediawall** [qax-os/excelize#1653]
reproduce the issue under go 1.21.1 and excelize 2.8.0

[test.xlsx](https://github.com/qax-os/excelize/files/12545260/test.xlsx)

```go
package main

import "github.com/xuri/excelize/v2"

func main() {
	f, err := excelize.OpenFile("test.xlsx")
	if err != nil {
		panic(err)
	}
	defer f.Close()

	if err := f.SaveAs("test1.xlsx"); err != nil {
		panic(err)
	}
}
```
test.xlsx can open correctly but test1.xlsx can't
![Screenshot from 2023-09-07 14-13-21](https://github.com/qax-os/excelize/assets/109123576/82946781-e64c-4a4d-bdd8-f45f86b91a15)

**Comment by gyf19** [comment]
+1  go 1.21 版本出问题了

**Comment by Achillesxu** [comment]
+1 go 1.21 版本出问题了

**Comment by xuri** [comment]
@gyf19 @Achillesxu If it does not work with Go 1.21.0, please reference the issues #1465, #1595, #1603, #1608, #1614, #1619, #1620, #1621, #1623, #1633, #1637, #1641, #1642, #1648, #1651, and #1652. There are some incompatible changes in the Go 1.21.0 encoding/xml library. I have given feedback to the Go team and created a patch for it (golang/go#61881), and [Go 1.21.1](https://go.dev/doc/devel/release#go1.21.1) is released on wednesday, september 6, this issue has been fixed. Please using the Go 1.20.7 and previous Go released version or upgrade to the Go 1.21.1. I have added notice on the [README](https://github.com/xuri/excelize#introduction) and [documentation website](https://xuri.me/excelize/en/base/installation.html#install) for this, but the Go version was 1.21.1 in @mediawall report, so I need to investigation for this. 

@gyf19 @Achillesxu， 如果你正在使用 Go 1.21.0，请参考问题 #1465，#1595，#1603，#1603，#1614，#1619，#1620，#1621，#1623，#1633，#1637，#1641，#1642，#1648，#1651 和 #1652。Go 1.21.0 对 encoding/xml 标准库做了不兼容的更改，我已将该问题反馈至 Go 团队，并提交了修复补丁 golang/go#61881，已在2023年9月6日发布的 Go 语言 1.21.1 版本中修复。我为此在[自述文档](https://github.com/xuri/excelize/blob/master/README_zh.md#简介)和[文档网站](https://xuri.me/excelize/zh-hans/base/installation.html#install)上添加了通知，因此请使用 Go 1.20.7 以及更早版本，或升级至 Go1.21.1，但在 @mediawall 的报告中，使用的 Go 版本为 1.21.1，因此该问题有待进一步调查。

**Comment by xuri** [comment]
Hi @mediawall, thanks for your issue. I have fixed this issue, please try to upgrade the master branch code, and this patch will be released in the next version.

**Comment by mediawall** [comment]
Hi @xuri , thanks for the fix. :+1:

**Comment by Achillesxu** [comment]
Hi @xuri , thanks for the fix. 👍

**Comment by ffh-zhang** [comment]
Hi @xuri, I use the go 1.20.7, and I had the same problem. MS Excel can not open correctly using excelize 2.8.0, but it works when using excelize 2.3.1

**Comment by ffh-zhang** [comment]
> Hi @ffh-zhang, thanks for your feedback. Please try to upgrade the master branch code at first, if it still doesn't works, please show us a standalone example program or reproducible demo.

[test.xlsx](https://github.com/qax-os/excelize/files/13499285/test.xlsx)
[testResult.xlsx](https://github.com/qax-os/excelize/files/13499287/testResult.xlsx)

**Comment by ffh-zhang** [comment]
> Hi @ffh-zhang, thanks for your feedback. Please try to upgrade the master branch code at first, if it still doesn't works, please show us a standalone example program or reproducible demo.

`package main

import (
	"fmt"
	"github.com/xuri/excelize/v2"
)

func main() {
	file, err := excelize.OpenFile("./test.xlsx")
	if err != nil {
		fmt.Printf("OpenFile error")
	}

	file.SaveAs("testResult.xlsx")
}`

**Comment by xuri** [comment]
Could you provide the file attachment without confidential info?

**Comment by LofannyWD1010** [comment]
I got same issue like that, I already update excelize xuri from master branch and still get error like that. I use go version 1.21 @xuri

**Comment by ffh-zhang** [comment]
> Could you provide the file attachment without confidential info?

Sorry, I can only reproduce this issue through this type of file with charts. When I use a regular blank file, this problem will not occur. The newly provided file "test.xlsx" only includes some hypothetical example data. I want to know if it is suitable.

[test.xlsx](https://github.com/qax-os/excelize/files/13595937/test.xlsx)
