### ISSUE TITLE
file.AutoFilter() can sometimes error out with a "nil pointer dereference".

### ISSUE THREAD

**Issue by blakepatteson** [qax-os/excelize#1655]
**Description**

file.AutoFilter can sometimes error out with a "nil pointer dereference". 

I think it's just due to this one bad file and on most files, "file.AutoFilter()" works fine, but it did happen with this file and I couldn't figure out why at first.

**Steps to reproduce the issue:**
Use this test repo I made with the bad file : 

1. ```git clone "https://github.com/blakepatteson/autofilterIssueTest"```
2. cd autofilterIssueTest
3. go run .

**Describe the results you received:**

Got a nil pointer dereference panic. 

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x0 pc=0x56c480]

goroutine 1 [running]:
github.com/xuri/excelize/v2.(*File).AutoFilter(0x5fce49?, {0x5f9bf4, 0x4}, {0xc000353f37?, 0x2?}, {0x0, 0x0, 0x0})
        C:/Users/bpatt/go/pkg/mod/github.com/xuri/excelize/v2@v2.8.0/table.go:454 +0x4c0
main.main()
        C:/zzz/repos/autofilterIssueTest/main.go:17 +0x105
exit status 2
```

The issue seems to be with this part being possibly nil :
````*definedName.LocalSheetID == sheetID````

So I think the fix would be just to add a check for this being nil?

Pretty sure the issue is with the "definedNames" part of this specific "test-autofilter-issue.xlsx" workbook : 
```
<definedNames>
    <definedName name="_xlnm._FilterDatabase" localSheetId="0" hidden="1">test!#REF!</definedName>
    <definedName name="_xlnm._FilterDatabase" hidden="1">'[1]Error Sheet'!$A$1:$I$1</definedName>
    <definedName name="Arial">#REF!</definedName>
</definedNames>
``` 
    
**Describe the results you expected:**

Expected Excelize to put a filter on the "test" worksheet with the provided parameters :
```
err = errWkbk.AutoFilter(sheetNm, fmt.Sprintf("A1:%v%v", "E", 5), nil)
```

**Output of `go version`:**

```text
go version go1.21.1 windows/amd64
```

**Excelize version or commit ID:**

```text
github.com/xuri/excelize/v2 v2.8.0
```

**Environment details (OS, Microsoft Excel™ version, physical, etc.):**

Here's the output of "go env" : 

```
set GO111MODULE=
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\bpatt\AppData\Local\go-build
set GOENV=C:\Users\bpatt\AppData\Roaming\go\env
set GOEXE=.exe
set GOEXPERIMENT=
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GOMODCACHE=C:\Users\bpatt\go\pkg\mod
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=C:\Users\bpatt\go
set GOPRIVATE=
set GOPROXY=https://proxy.golang.org,direct
set GOROOT=C:\Program Files\Go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLCHAIN=auto
set GOTOOLDIR=C:\Program Files\Go\pkg\tool\windows_amd64
set GOVCS=
set GOVERSION=go1.21.1
set GCCGO=gccgo
set GOAMD64=v1
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=0
set GOMOD=C:\zzz\repos\autofilterIssueTest\go.mod
set GOWORK=
set CGO_CFLAGS=-O2 -g
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-O2 -g
set CGO_FFLAGS=-O2 -g
set CGO_LDFLAGS=-O2 -g
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -fno-caret-diagnostics -Qunused-arguments -Wl,--no-gc-sections -fmessage-length=0 -ffile-prefix-map=C:\Users\bpatt\AppData\Local\Temp\go-build164768209=/tmp/go-build -gno-record-gcc-switches
```

**Comment by xuri** [comment]
Thanks for your issue. I have fixed this issue, please try to upgrade the master branch code, and this patch will be released in the next version.

**Comment by blakepatteson** [comment]
Awesome - thanks so much!
