### ISSUE TITLE
Cant be written  to Excel on MAC(m2 clips)

### ISSUE THREAD

**Issue by JohnChancfz** [qax-os/excelize#1657]
hi,all
I cant be wrriten any type to Excel ,my os is Mac os 13.5.2 (22G91) (Apple M2 Max)

**Comment by xuri** [comment]
Thanks for your issue. Which version of the Go language and Excelize library are you using? Could you follow the issue template and provides more details about this?

**Comment by JohnChancfz** [comment]
golang 1.21.0
excelize v2.8.0 / v2.6.1

**Comment by xuri** [comment]
If you are reporting a new issue, make sure that we do not have any duplicates already exist. If it does not work with Go 1.21.0, please reference the issues #1465, #1595, #1603, #1608, #1614, #1619, #1620, #1621, #1623, #1633, #1637, #1641, #1642, #1648, #1651, #1652 and #1656. I have added notice on the [README](https://github.com/xuri/excelize#introduction) and [documentation website](https://xuri.me/excelize/en/base/installation.html#install) for this.
