### ISSUE TITLE
Generated excel file corrupted when using mostly any currency NumFmt

### ISSUE THREAD

**Issue by nmfzone** [qax-os/excelize#1659]
**Description**

The generated excel file corrupted when using mostly any `NumFmt` that listed in `currencyNumFmt`. Here I'm using 359. I've tried using 350, 356, 361, etc and it's still the same. But I've tried using 313, it's working fine (I think only 313 that working, at least for me).

Here's the code
```
f := excelize.NewFile()
sheetName := "Sheet1"

f.SetCellValue(sheetName, "A1", "No")
f.SetColWidth(sheetName, "A", "A", 8)

f.SetCellValue(sheetName, "B1", "Value")
f.SetColWidth(sheetName, "B", "B", 20)

f.SetCellValue(sheetName, "A2", 1)
f.SetCellValue(sheetName, "B2", 0)
f.SetCellValue(sheetName, "A3", 2)
f.SetCellValue(sheetName, "B3", 99000)
f.SetCellValue(sheetName, "A4", 3)
f.SetCellValue(sheetName, "B4", 5919573)

currencyCols := []string{"B"}
currencyStyle, _ := f.NewStyle(&excelize.Style{
    Alignment:    &excelize.Alignment{Horizontal: "left", Vertical: "center"},
    NumFmt: 359,
})
for _, c := range currencyCols {
    f.SetColStyle(sheetName, c, currencyStyle)
}
```

When open the generated file, it gives me
![Screen Shot 2023-09-13 at 20 49 26](https://github.com/qax-os/excelize/assets/10361906/a7ff623d-0e06-40ec-849b-a41c1af0b822)
although after I'm clicking Yes, it's working fine, hmmm

**Output of `go version`:**

```text
go version go1.19.12 darwin/amd64
```

**Excelize version or commit ID:**

```text
v2.8.1-0.20230909055100-49706c9018fc
```

**Environment details (OS, Microsoft Excel™ version, physical, etc.):**
MacOs 10.14, Excel for Mac 16.45

**Comment by nmfzone** [comment]
Here's the file [file.xlsx](https://github.com/qax-os/excelize/files/12598481/ac5b0af4-a6a8-4c83-88e1-f82ab6b8f489.xlsx)

**Comment by nmfzone** [comment]
Hmmm, tried downgrade to version 2.7.0, and working fine.

**Comment by xuri** [comment]
Thanks for your issue. I have tested `v2.8.1-0.20230909055100-49706c9018fc` with your code and it works well. It also works with other currency number codes 350, 356, 361, etc, There is not enough info on the code and attachments to reproduce this issue, could you provide more details about this, such as how you saved the workbook at last?

**Comment by xuri** [comment]
Thanks for your feedback. I've tested with gin v1.9.1, excelize v2.8.0 or master branch by following code, and send request with cURL: `curl --location --request GET 'http://127.0.0.1:8080/export' -O`. It works well. Could you show us a complete, standalone example program or reproducible demo?

```go
package main

import (
    "github.com/gin-gonic/gin"
    "github.com/xuri/excelize/v2"
)

func main() {
    r := gin.Default()
    r.GET("/export", func(c *gin.Context) {
        c.Header("Content-Type", "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet")
        c.Header("Content-Disposition", "attachment; filename=file.xlsx")
        f := excelize.NewFile()
        sheetName := "Sheet1"

        f.SetCellValue(sheetName, "A1", "No")
        f.SetColWidth(sheetName, "A", "A", 8)

        f.SetCellValue(sheetName, "B1", "Value")
        f.SetColWidth(sheetName, "B", "B", 20)

        f.SetCellValue(sheetName, "A2", 1)
        f.SetCellValue(sheetName, "B2", 0)
        f.SetCellValue(sheetName, "A3", 2)
        f.SetCellValue(sheetName, "B3", 99000)
        f.SetCellValue(sheetName, "A4", 3)
        f.SetCellValue(sheetName, "B4", 5919573)

        currencyCols := []string{"B"}
        currencyStyle, _ := f.NewStyle(&excelize.Style{
            Alignment: &excelize.Alignment{Horizontal: "left", Vertical: "center"},
            NumFmt:    359,
        })
        for _, c := range currencyCols {
            f.SetColStyle(sheetName, c, currencyStyle)
        }
        f.Write(c.Writer)
    })
    r.Run()
}
```

**Comment by thomaspeugeot** [comment]
I have met the same issue with v2.8.0 and v2.7.1 and v2.7.0.

The code to generate the corrupted file is simple

```go
	f := excelize.NewFile()

	var tab ExcelizeTabulator
	tab.SetExcelizeFile(f)
	{
		f.DeleteSheet("Sheet1")
		if err := f.SaveAs(filename); err != nil {
			fmt.Println("cannot write xl file : ", err)
		}
	}
```

**Comment by xuri** [comment]
It seems still not have enough info of code and attachments to reproduce this issue, so I'll close this issue, if you have any questions, please let me know to reopen this anytime.
