### ISSUE TITLE
time formulated Values are not coming correctly

### ISSUE THREAD

**Issue by deanx3** [qax-os/excelize#1661]
[Excel](https://docs.google.com/spreadsheets/d/e/2PACX-1vQmMhnShjhjP5qwRjdA-1sWf2JE_iyph8j0kbM1QS_-WpYlzvAOBbZ79YLy0k3VzckREx70ntXTTRSP/pubhtml)

i am using GO 1.81, github.com/xuri/excelize/v2 v2.8.1-0.20230914145628-5a039f304529 and windows. using getRows function to import data from excel sheet

I'm taking information from Excel sheets. There are three columns: A and B show time in hours and minutes (like 01:30), and C should display the total time from A and B. When I use the "getRows" function to read the sheet, columns A and B are correct, but in column C, the hours are correct, but the minutes are always showing as 12.
**Steps to reproduce the issue:**
1. read excel sheet using getRows 
2. print the value in consol log, to see the result
3.

**Describe the results you received:**
if A=12:00, B=2:00 and C would be sum of A+B from the formula. C=14:00, but when i am reading it is  as 14:12
**Describe the results you expected:**
if A=12:00, B=2:00 and C would be sum of A+B from the formula. C=14:00, but when i am reading it is  as 14:12
**Output of `go version`:**

go version go1.19.5 windows/amd64

**Excelize version or commit ID:**

github.com/xuri/excelize/v2 v2.8.1-0.20230914145628-5a039f304529

**Comment by xuri** [comment]
Thanks for your issue. Your provided link is a webpage, could you provide a workbook as attachments without confidential info?

**Comment by deanx3** [comment]
[example.xlsx](https://github.com/qax-os/excelize/files/12641584/example.xlsx)
A and B, is coming correct, but C is the months are coming incorrectly

**Comment by xuri** [comment]
Thanks for your feedback. I have fixed it, please try to upgrade the master branch code, and this patch will be released in the next version.
