### ISSUE TITLE
Text in error is not grammatically correct and likely should not be thrown

### ISSUE THREAD

**Issue by fnickels** [qax-os/excelize#1662]
**Description**

**Steps to reproduce the issue:**
1.

```
		if err := f.SetDefinedName(&excelize.DefinedName{
			Name:     "_xlnm.Print_Area",
			RefersTo: "'" + currentSheetName + "'!" + cell1 + ":" + cell2,
			Scope:    currentSheetName,
		}); err != nil {
			return err
		}
```
2.
3.

**Describe the results you received:**

Error: invalid name "_xlnm.Print_Area", the name should be starts with a letter or underscore, can not include a space or character, and can not conflict with an existing name in the workbook

**Describe the results you expected:**

Should it say "the name should start with a letter or underscore" instead of "the name should be starts with a letter or underscore"?

Also, the name does start with an underscore, so why it the error being thrown?

**Output of `go version`:**

```text
go version go1.21.1 linux/amd64
```

**Excelize version or commit ID:**

```text
v2.8.0
```

**Environment details (OS, Microsoft Excel™ version, physical, etc.):**

**Comment by xuri** [comment]
Thanks for your issue. I have fixed this, please try to upgrade the master branch code, and this patch will be released in the next version.

**Comment by xuri** [comment]
I've closed this issue, if you have any questions please let me know, and reopen this any time.
