### ISSUE TITLE
生成的excel无法打开

### ISSUE THREAD

**Issue by xugnail** [qax-os/excelize#1663]
示例代码如下：
```
f := excelize.NewFile()

defer func() {
  if err := f.Close(); err != nil {
	  fmt.Println(err)
  }
}()

f.SetCellValue("Sheet1", "B2", 100)

if err := f.SaveAs("Book1.xlsx"); err != nil {
          fmt.Println(err)
}
```

问题如下：
![image](https://github.com/qax-os/excelize/assets/6836017/214d8632-f82a-4cbb-8d2e-8de32b22ae5e)

tag: 2.4.1、2.7.1、2.8.0 都有这个问题。

本地 go 版本有1.21.0，导出的excel如图无法打开

版本退回 go 1.18.10 问题解决

**Comment by xuri** [comment]
Thanks for your issue. If you are reporting a new issue, make sure that we do not have any duplicates already exist. If it does not work with Go 1.21.0, please reference the issues#1465, #1595, #1603, #1608, #1614, #1619, #1620, #1621, #1623, #1633, #1637, #1641, #1642, #1648, #1651, #1652, #1656, #1657 and #1660. There are some incompatible changes in the Go 1.21.0 encoding/xml library. I have given feedback to the Go team and created a patch for it (golang/go#61881), and it has been fixed on Go 1.21.1. Please using the Go 1.20.7 and previous Go released version or upgrade to Go 1.21.1 and later. I have added notice on the [README](https://github.com/xuri/excelize#introduction) and [documentation website](https://xuri.me/excelize/en/base/installation.html#install) for this, and I've closed this. If you have any questions, please let me know, and reopen this anytime.

谢谢您的提问，在您创建新的问题之前，请确保不存在任何重复的问题。这与已有问题重复，请参考 #1465, #1595, #1603, #1608, #1614, #1619, #1620, #1621, #1623, #1633, #1637, #1641, #1642, #1648, #1651, #1652, #1656, #1657 和 #1660。Go 1.21.0 对 encoding/xml 标准库做了不兼容的更改，我已将该问题反馈至 Go 团队，并提交了修复补丁 golang/go#61881，已在 Go 1.21.1 中修复。请使用 Go 1.20.7 以及更早版本，或升级 1.21.1 及以上版本。我已经为此在[自述文档](https://github.com/xuri/excelize/blob/master/README_zh.md#简介)和[文档网站](https://xuri.me/excelize/zh-hans/base/installation.html#install)上添加了通知，因此我将关闭此问题。如果您有任何问题，请告诉我，并可随时重新打开。
