### ISSUE TITLE
call SetRow multiple times. Break ms.excel. But not in google sheet, numbers and wps.

### ISSUE THREAD

**Issue by mosleim** [qax-os/excelize#1664]
**Description**
I have 2 function(and more) process single sheet . All function is use streamwriter. Everythings working well until the functions process in same row.

**Steps to reproduce the issue:**
1. run this code
2. open in google sheet or numbers or wps the output as expected
3. but, when open with ms.excel, will break.

sample codes:
```go
func TestExcel(t *testing.T) {
	ex := excelize.NewFile()
	sheet1 := "Sheet1"
	sw, _ := ex.NewStreamWriter(sheet1)
	sw.SetRow("A1", []interface{}{
		"Hello",
		"World",
	})

	sw.SetRow("A2", []interface{}{
		"Hello",
		"World",
	})

	sw.SetRow("C1", []interface{}{
		"Hello",
		"World",
	})
	sw.Flush()
	ex.SaveAs("test/sw.xlsx")
}
```

**Describe the results you received:**
in number:
![image](https://github.com/qax-os/excelize/assets/3499544/e0d510ea-a05f-4173-b7b0-7512c7651ed1)
in ms.excel:
![image](https://github.com/qax-os/excelize/assets/3499544/68912cb9-d132-4c93-83c5-f904cccf8141)

**Describe the results you expected:**
in ms.excell look like in number. 
**Output of `go version`:**

```text
go version go1.20.7 darwin/arm64
```

**Excelize version or commit ID:**

```text
v2.6.0
```

**Environment details (Macos, Microsoft Excel™ 360.):**

**Comment by mosleim** [comment]
I try to rewrite some code to partially not using streamwriter. but, this solution is not working.

```go
func TestExcel(t *testing.T) {
	ex := excelize.NewFile()
	sheet1 := "Sheet1"
	sw, _ := ex.NewStreamWriter(sheet1)
	sw.SetRow("A1", []interface{}{
		"Hello",
		"World",
	})
	sw.Flush()
	
	// this is not work
	ex.SetCellValue(sheet1, "F1", "Hello again")
	ex.SaveAs("test/sw.xlsx")
}
```

**Comment by xuri** [comment]
Thanks for your issue. Please don't ignore errors returned by any function. If you handle the error returns from the function, you will get the error details: "row 1 has already been written". As [the stream writer documentation](https://xuri.me/excelize/en/stream.html#NewStreamWriter) says: "ensure that the order of row numbers is ascending when set rows", so you need to write all cells in the first at once:

```go
package main

import (
    "fmt"

    "github.com/xuri/excelize/v2"
)

func main() {
    ex := excelize.NewFile()
    sheet1 := "Sheet1"
    sw, err := ex.NewStreamWriter(sheet1)
    if err != nil {
        fmt.Println(err)
        return
    }
    if err := sw.SetRow("A1", []interface{}{
        "Hello",
        "World",
        "Hello",
        "World",
    }); err != nil {
        fmt.Println(err)
        return
    }

    if err := sw.SetRow("A2", []interface{}{
        "Hello",
        "World",
    }); err != nil {
        fmt.Println(err)
        return
    }

    if err := sw.Flush(); err != nil {
        fmt.Println(err)
        return
    }
    if err := ex.SaveAs("sw.xlsx"); err != nil {
        fmt.Println(err)
        return
    }
}
```

I've closed this issue. If you have any questions, please me know and reopen this anytime.

**Comment by mosleim** [comment]
The documentation says flush is ending the streaming writing process. Is still not possible to SetCellValue after calling Flush?

**Comment by xuri** [comment]
There are two kinds of functions in the excelize library: normal mode functions and stream mode functions. The SetCellValue function is a normal mode function, and the NewStreamWriter is a stream mode function. These two kinds of functions can not be used mixed. The stream mode function is used to generate a worksheet with the amount of data in lower resource usage. Don't use the normal mode function on the same worksheet after flushing the worksheet with the stream writer. If you need to modify any cell just written, please use the normal mode function SetRow instead of the stream mode function.
