### ISSUE TITLE
GetRows  returns incorrect cell content which uses formula TEXT(C4,"YYYYMMDD")  

### ISSUE THREAD

**Issue by LixinSy** [qax-os/excelize#1665]
![image](https://github.com/qax-os/excelize/assets/29853388/43309bb9-c12e-4fde-b7d2-36fed344ca41)

![image](https://github.com/qax-os/excelize/assets/29853388/9db691ba-46f0-46bd-9fa8-16a36f1ee92b)

**Comment by xuri** [comment]
Thanks for your issue. Could you follow the issue template, and show us a complete, standalone example program or reproducible demo?

**Comment by LixinSy** [comment]
> Thanks for your issue. Could you follow the issue template, and show us a complete, standalone example program or reproducible demo?

![image](https://github.com/qax-os/excelize/assets/29853388/303f0d36-7791-4165-86e5-0fed8d50912a)

**Comment by xuri** [comment]
Thanks for your feedback. Which version of the Go language and Excelize library are you using? Could you **follow the issue template**, provide a workbook as attachments without confidential info?

**Comment by LixinSy** [comment]
golang version
`go version go1.17.3 windows/amd64`

go.mod file
```
module excel2json

go 1.17

require github.com/xuri/excelize/v2 v2.8.0

require (
	github.com/mohae/deepcopy v0.0.0-20170929034955-c48cc78d4826 // indirect
	github.com/richardlehane/mscfb v1.0.4 // indirect
	github.com/richardlehane/msoleps v1.0.3 // indirect
	github.com/xuri/efp v0.0.0-20230802181842-ad255f2331ca // indirect
	github.com/xuri/nfp v0.0.0-20230819163627-dc951e3ffe1a // indirect
	golang.org/x/crypto v0.12.0 // indirect
	golang.org/x/net v0.14.0 // indirect
	golang.org/x/text v0.12.0 // indirect
)
```
here is excel file
[data.xlsx](https://github.com/qax-os/excelize/files/12657463/data.xlsx)

**Comment by LixinSy** [comment]
> Thanks for your feedback. Which version of the Go language and Excelize library are you using? Could you **follow the issue template**, provide a workbook as attachments without confidential info?

golang version
`go version go1.17.3 windows/amd64`

go.mod file
```
module excel2json

go 1.17

require github.com/xuri/excelize/v2 v2.8.0

require (
	github.com/mohae/deepcopy v0.0.0-20170929034955-c48cc78d4826 // indirect
	github.com/richardlehane/mscfb v1.0.4 // indirect
	github.com/richardlehane/msoleps v1.0.3 // indirect
	github.com/xuri/efp v0.0.0-20230802181842-ad255f2331ca // indirect
	github.com/xuri/nfp v0.0.0-20230819163627-dc951e3ffe1a // indirect
	golang.org/x/crypto v0.12.0 // indirect
	golang.org/x/net v0.14.0 // indirect
	golang.org/x/text v0.12.0 // indirect
)
```
here is excel file
[data.xlsx](https://github.com/qax-os/excelize/files/12657463/data.xlsx)

**Comment by xuri** [comment]
Thanks for your issue. I have fixed this issue, please try to upgrade the master branch code, and this patch will be released in the next version.
