### ISSUE TITLE
Able to open the .xlsx file in vscode excel viewer but not able to open it in local Microsoft Excel 

### ISSUE THREAD

**Issue by philipleong97** [qax-os/excelize#1670]
**Description**

**Steps to reproduce the issue:**
1.  create a new go project 
2. Copy the code from https://github.com/qax-os/excelize#create-spreadsheet
3. Run the go project
4. Corrupted Excel file is produced
[Book1.xlsx](https://github.com/qax-os/excelize/files/12701227/Book1.xlsx)

**Describe the results you received:**
it generate the Book1.xlsx as expected and i am able to use ExcelViewer extension from vscode to view it. However when I try to open it with local Microsoft Excel , the file seems corrupted and it is empty when i proceed to view it.

**Describe the results you expected:**
I am able to view the content in Microsoft Excel
**Output of `go version`:**

```text
go version go1.21.0 darwin/arm64
```
<img width="853" alt="image" src="https://github.com/qax-os/excelize/assets/145777207/cdbbeb2d-2108-47a3-ade3-968aaebb0a41">

**Excelize version or commit ID:**

```text
v2.8.0
```

**Environment details (OS, Microsoft Excel™ version, physical, etc.):**
MacOs Ventura 13.4, Microsoft Excel™ version 16.76 (My license not activated due to this is newly bought computer. However , my friend with license is not able to view the file properly too. )

**Comment by xuri** [comment]
Thanks for your issue. If you are reporting a new issue, make sure that we do not have any duplicates already exist. If it does not work with Go 1.21.0, please reference the issues#1465, #1595, #1603, #1608, #1614, #1619, #1620, #1621, #1623, #1633, #1637, #1641, #1642, #1648, #1651, #1652, #1656, #1657, #1660 and #1663. There are some incompatible changes in the Go 1.21.0 encoding/xml library. I have given feedback to the Go team and created a patch for it (golang/go#61881), and it has been fixed on Go 1.21.1. Please using the Go 1.20.7 and previous Go released version or upgrade to Go 1.21.1 and later. I have added notice on the [README](https://github.com/xuri/excelize#introduction) and [documentation website](https://xuri.me/excelize/en/base/installation.html#install) for this, and I've closed this. If you have any questions, please let me know, and reopen this anytime.
