### ISSUE TITLE
Preserve existing style and format

### ISSUE THREAD

**Issue by speix** [qax-os/excelize#1672]
It would be nice to support opening and preserving the styles and formatting of a xlsx file, that is already formatted.
**Example use-case:** existing xlsx file, already formatted, and just want to fill it with values.

When I do that now, by simply using OpenFile/Save, my style is not preserved (pictures, titles, indentation and so on).
I get the error below:
"We found a problem with some content in ’test.xlsx’. Do you want us to try to recover as much as we can? If you trust the source of this workbook, click Yes."

Please, let me know if this is supported and I've missed it in the documentation.

**Comment by xuri** [comment]
Thanks for your issue. Which version of the Go language and Excelize library are you using? Could you follow the issue template and show us a complete, standalone example program or reproducible demo?

**Comment by speix** [comment]
Go version: **1.20.4 darwin/amd64 but I'm also targeting arm.**
Excelize Lib: **v2.8.0**

Samples xlsx below, nothing fancy:
[sample.xlsx](https://github.com/qax-os/excelize/files/12708663/sample.xlsx)

Code below (just a simple SaveAs a different name):
```
report, err := excelize.OpenFile("sample.xlsx")
	if err != nil {
		log.Fatal(err)
		return
	}
	defer func() {
		if err := report.Close(); err != nil {
			fmt.Println(err)
		}
	}()

if err := report.SaveAs("test.xlsx"); err != nil {
		log.Fatal(err)
	}
```

Trying to open the tests.xlsx gives me an excel spreadsheet with no styling and the warning message: "We found a problem with some content in ’test.xlsx’. Do you want us to try to recover as much as we can? If you trust the source of this workbook, click Yes."

**Comment by xuri** [comment]
Thanks for your feedback. This problem has been fixed, please upgrade to the master branch code, and this patch will be release in the next version.
