### ISSUE TITLE
Excel removes formulas with error when opening the file

### ISSUE THREAD

**Issue by BjarneAndersson** [qax-os/excelize#1674]
**Description**

I use `SetCellFormula` to insert the formula `VLOOKUP` into a cell. The reference cells are not filled in yet. When I try to open the Excel file, Excel reports an interpretation error. This causes Excel to remove the formulas completely.

Here's what I do:
```golang
Document.SetCellFormula("Sheet1", "D2","=VLOOKUP(A2;'Sheet2'!A:D;4;False)")
```
The `Sheet2` is filled in by the user after the file is set up. Therefore, the formula has unfilled reference cells.

If you insert the formula manually after opening the recovered file, Excel accepts the formula. 
However, since the reference cells are missing, the error value "#N/A" is returned.

**Describe the results you received:**
1. Excel error described in Excel log file:
```Removed Records: Formula from /xl/worksheets/sheet1.xml part```
3. Missing formula in expected cell.

**Describe the results you expected:**
I expect the cell to contain the formula. It should return the error "#N/A" because there is no data for the search.

**Output of `go version`:**

```text
go version go1.20.5 windows/amd64
```

**Excelize version or commit ID:**

```text
v2 v2.8.0 Vd4Qy809fupgp1v7X+nCS/MioeQmYVVzi495UCTqB7U
```

**Environment details (OS, Microsoft Excel™ version, physical, etc.):**
Windows 11, Microsoft 365 Excel Version 2308 (Build 16.0.16731.20182)

**Comment by xuri** [comment]
Thanks for your issue. Excel formula using a comma (,) to separate arguments within a function, so please using the comma instead of semicolon in your formula function: `=VLOOKUP(A2,'Sheet2'!A:D,4,FALSE)`.

**Comment by BjarneAndersson** [comment]
Thank you for your quick reply and solution!

Now everything works as expected. I was used to the German Excel formulas …
