### ISSUE TITLE
Value empty for cell with data

### ISSUE THREAD

**Issue by Coronon** [qax-os/excelize#1678]
**Description**

I have an Excel document where trying to read a value from cells will return an empty string even though the cell has data.

**Steps to reproduce the issue:**
1. Use this [Excel file](https://github.com/qax-os/excelize/files/12778250/Public.xlsx)

2. Attempt to read cell "A4"

```go
package main

import (
	"fmt"

	"github.com/xuri/excelize/v2"
)

func main() {
	f, err := excelize.OpenFile("Public.xlsx")
	if err != nil {
		fmt.Println(err)
		return
	}
	defer func() {
		// Close the spreadsheet.
		if err := f.Close(); err != nil {
			fmt.Println(err)
		}
	}()
	
        val, _ := f.GetCellValue("Sheet1", "A4")
        fmt.Println(val)
}
```

**Describe the results you received:**
`"", nil`

**Describe the results you expected:**
`"8337", nil`

**Output of `go version`:**

```text
go version go1.21.1 windows/amd64
```

**Excelize version or commit ID:**

```text
github.com/xuri/excelize/v2 v2.8.0
```

**Environment details (OS, Microsoft Excel™ version, physical, etc.):**
```text
OS: Microsoft Windows 10 (64bit)
Microsoft Excel: Microsoft® Excel® for Microsoft 365 MSO (Version 2308 Build 16.0.16731.20182) 64-bit
Physical machine: Yes
```

**Comment by xuri** [comment]
Thanks for your issue. This issue has been fixed, please try to upgrade the master branch code, and this patch will be released in the next version.

**Comment by Coronon** [comment]
My issue is indeed fixed - thank you very much for the extremly fast resolution!

Cheers :)
