### ISSUE TITLE
setCellIntFunc Data type conversion error

### ISSUE THREAD

**Issue by ppwator** [qax-os/excelize#1681]
**Description**
1. in cell.go setCellIntFunc have error for Data type conversion

case uint64:
		err = f.SetCellInt(sheet, axis, int(v))

**Steps to reproduce the issue:**
all

**Excelize version or commit ID:**
all

![Snipaste_2023-10-04_14-29-18](https://github.com/qax-os/excelize/assets/142149423/89957c96-f861-439a-b71e-2063d9f5e190)

**Comment by xuri** [comment]
Thanks for your issue. Which version of the Go language and Excelize library are you using? what results you received? and what results you expected? Could you follow the issue template and show us a complete, standalone example program or reproducible demo?

**Comment by xuri** [comment]
Thanks for your issue. This issue has been fixed, please try to upgrade the master branch code, and this patch will be released in the next version.
