### ISSUE TITLE
Delete Table not working

### ISSUE THREAD

**Issue by Abdelaziz-Ouhammou** [qax-os/excelize#1682]
Go: 1.21.1
Excelize: master

Updating a table's range by removing it and creating it again doesn't work.

```go
func main() {
	f, err := excelize.OpenFile("template.xlsx")
	if err != nil {
		panic(err)
	}

	err = f.SetSheetRow("Data", "A7", &[]any{"2023-10-06", 140})
	if err != nil {
		panic(err)
	}
	err = f.DeleteTable("Table1")
	if err != nil {
		panic(err)
	}
	err = f.AddTable("Data", &excelize.Table{
		Name:  "Table1",
		Range: "A1:B7",
	})
	if err != nil {
		panic(err)
	}
	err = f.SaveAs("output.xlsx")
	if err != nil {
		panic(err)
	}



}

//panic: the same name table already exists
```
[Excelize.zip](https://github.com/qax-os/excelize/files/12816532/Excelize.zip)
Also Is there a way to refresh the range of a chart ? or make the chart react to a table new row ?

**Comment by xuri** [comment]
Thanks for your issue. This issue has been fixed, please try to upgrade the master branch code, and this patch will be released in the next version. This library does not support change the data range of the chart currently, but you can delete the chart and create a new chart instead of that.

**Comment by Abdelaziz-Ouhammou** [comment]
@xuri I can confirm the issue is fixed. However DeleteTable deletes the table header ? is this the intended behavior ?

Also Add table doesn't specify a way to specify a header for the table.

If i have the header as 

``` csv
Date, Values
2023-10-05, 10

// After Delete Header
2023-10-05, 10

// After AddTable
Column1, Column2
2023-10-05, 10

```

is there a way to do this without losing the table header ?

**Comment by xuri** [comment]
Yes, I think we need to keep all cells value in the table range when deleting table, [these section code](https://github.com/xuri/excelize/blob/95fc35f46cbf1948198d114fc857f1e66b642ab4/table.go#L199-L210) is not required, would you like to create a pull request for that?

**Comment by Abdelaziz-Ouhammou** [comment]
Yes I will by the end of today.
