### ISSUE TITLE
CalcCellValue returns `""` for MATCH when value is greater than largest value in array

### ISSUE THREAD

**Issue by udapamup** [qax-os/excelize#1683]
**Description**

My sheet has several formula that use `MATCH(<ref_value>, <ref_array>, 1)`. `file.CalcCellValue` returns `""` when the `ref_value` is greater than the largest value in the array, whereas Excel gives the index of the greatest value in the array.

**Steps to reproduce the issue:**
1. In excel create two arrays with values
2. Have a cell with the formula `MATCH(<ref_value>, <ref_array>, 1)`. `<ref_value>` should be greater than the maximum value in the `ref_array` 
<img width="330" alt="image" src="https://github.com/qax-os/excelize/assets/140762167/0a316518-6038-4b4f-a321-ddfede6048e6">

3. Attempt to calculate the field using Excelize, e.g. `val, err := file.CalcCellValue("Sheet1", "C8")`
```go
val, err := file.CalcCellValue("Sheet1", "C8")
assert.NoError(t, err)
assert.Equal(t, "7", v)
```

**Describe the results you received:**
```
                Error:          Not equal:
                                expected: "7"
                                actual  : ""

                                Diff:
                                --- Expected
                                +++ Actual
                                @@ -1 +1 @@
                                -7
                                +
```

**Describe the results you expected:**
Expected `"7"`.

**Output of `go version`:**

```text
go version go1.21.1 darwin/arm64
```

**Excelize version or commit ID:**

```text
github.com/xuri/excelize/v2 v2.8.0
```

**Environment details (OS, Microsoft Excel™ version, physical, etc.):**
MacOS 13.6, Excel 16.77.1 (23091703), M1

**Comment by xuri** [comment]
Thanks for your issue. This issue has been fixed, please try to upgrade the master branch code, and this patch will be released in the next version.
