### ISSUE TITLE
Set size for the comment box 生成批注无法自适应大小

### ISSUE THREAD

**Issue by z-hua** [qax-os/excelize#1688]
**Description**

使用 AddComment 函数生成批注时，显示批注的 tips 无法显示全所有的批注，要手动编辑批注修改其宽高才能显示完全。我使用的是 WPS 。

**Output of `go version`:**

```text
go version go1.21.1 windows/amd64
```

**Excelize version or commit ID:**

```text
2.8.0
```

**Environment details (OS, Microsoft Excel™ version, physical, etc.):**

WPS

**Comment by xuri** [comment]
Thanks for your issue. I have added support for set the height and width for the comments box, please try to upgrade the master branch code, and this feature will be released in the next version. Now you can change the comments box size like this:

```diff
err := f.AddComment("Sheet1", excelize.Comment{
    Cell:   "A5",
    Author: "Excelize",
    Paragraph: []excelize.RichTextRun{
        {Text: "Excelize: ", Font: &excelize.Font{Bold: true}},
        {Text: "This is a comment."},
    },
+   Height: 40,
+   Width:  180,
})
```
