### ISSUE TITLE
GetConditionalStyle

### ISSUE THREAD

**Issue by franissirkovic** [qax-os/excelize#1690]
**Description**
I am very satisfied with excelize lib. As far as I can see all functions come in get/set pairs, for example NewStyle()/GetStyle(). But I have found one exception: there is only NewConditionalStyle() function. There are no GetConditionalStyle() function. So, it makes conditional styles something like write only memory (register). And, of course, I need GetConditionalStyle() function. I can't find style for conditionally highlighted cells.

I would appreciate if you can add it.
In the meantime I have found ugly workaround, I am accessing file.Styles.Dxfs.Dxfs directly.

Best wishes, Franis Sirkovic.

**Comment by xuri** [comment]
Thanks for your issue. I have just added support for getting the conditional format style definition, please upgrade to the master branch code, and this feature will be released in the next version.

**Comment by franissirkovic** [comment]
Dear Xuri,

thanks for fast reply. I have tested new lib and it works as my first
workaround. Problem is that field PatternFill.PatternType is an empty
string, and there is no mapping for it in styleFillPatterns. As a result I
got in the Style.Fill structure Pattern -1 and Color null. But in excel I
can see that the color is defined (it is background of the cell). So. I
didn't know better so I added additional check for empty string (in my
workaround) and assigned Pattern=1 in that case.
You certainly have better knowledge of excel file format, so maybe you can
prepare better solution.

Best wishes and many thanks, Franis Sirkovic.

**Comment by xuri** [comment]
Thanks for your feedback. I have tested this with unit tests, and it works well. Are you opening an existing workbook that contains a conditional format style or creating a conditional format style on a new workbook with this library? Could you provide a file attachment without confidential info and a standalone demo to reproduce this?

**Comment by franissirkovic** [comment]
Dear Xuri,

here is linux executable and xlsx file. Utility is simple xlsx to json
converter. If you prefer I can send you a sources or windows exe.

Best wishes, Franis Sirkovic.

P.S. Just my curiosity, it seems to me that we are not in the same time
zone. I am from Croatia.

**Comment by xuri** [comment]
I can't find your attachments in your reply, you can upload attachment to this issue, and show us a standalone reproducible source code demo.

**Comment by franissirkovic** [comment]
Dear Xuri,

here is windows version of utility.
Password for .7z file is win.
e2j.bin should be renamed to e2j.exe

Best wishes, Franis Sirkovic

**Comment by xuri** [comment]
I still can't find your attachments in your reply, could you upload it by webpage instead of reply by email? In addition, please show us a standalone reproducible source code demo instead of binary files.

**Comment by franissirkovic** [comment]
Here is xlsx file and source files of utility.
[demo.tar.gz](https://github.com/qax-os/excelize/files/12999345/demo.tar.gz)

**Comment by franissirkovic** [comment]
I have used webpage to send you xlsx file and sources.

**Comment by xuri** [comment]
I have made some changes to resolve this issue, please try to upgrade the master branch code. This change will be released in the next version.

**Comment by franissirkovic** [comment]
It works perfectly for my case. Thanks for help.

Best wishes, Franis Sirkovic.
