### ISSUE TITLE
Please start respecting semver

### ISSUE THREAD

**Issue by scripturial** [qax-os/excelize#1691]
The golang versioning/numbering scheme is intended to work like this:

https://semver.org

So for example v2.3.4 means vMAJOR.MINOR.PATCH:

- MAJOR version when you make incompatible API changes
- MINOR version when you add functionality in a backward compatible manner
- PATCH version when you make backward compatible bug fixes

However with this project you sometimes make changes to the code that break the API but only the minor version number. 

So when a project does a `go get -u` changes come in from your project that break everything that depends on your project. So for example, in a project we depend on, that project depends on excelize, and we are seeing:

```
/Users/myproject/go/pkg/mod/gitlab.com/myrepo/security@v0.139.1/page_accounts_export.go:371:3: unknown field Panes in struct literal of type excelize.Panes
/Users/myproject/go/pkg/mod/gitlab.com/myrepo/security@v0.139.1/page_accounts_export.go:371:21: undefined: excelize.PaneOptions

```

I know how annoying it is to have to do a major version bump, but it would be helpful if you could restrict API breaking changes to major version updates.  If this is not possible I understand, your project is awesome and all your work is much appreciated.

**Comment by xuri** [comment]
Thanks for your kind notice. This related with issues #231, #1079 and #1516. I will follow that in the future release.
