### ISSUE TITLE
Bump version from 2.6.1 to 2.8.0 the file generated by 2.8.0 show empty when preview with wechat on Android

### ISSUE THREAD

**Issue by lilien1010** [qax-os/excelize#1694]
I revently tried this lib for test, but found a issue when generated with 2.8.0 ,when the preview the file on wechat Android, the excel show blank (which I found the text is able to copy, but the text is invisible)
  
  Generate with 2.6.1 (visible on Android wechat)
[2023-10-18_156638320231018185239.xlsx](https://github.com/qax-os/excelize/files/13023551/2023-10-18_156638320231018185239.xlsx)

Generate with 2.8.0 (text is invisible on Android wechat)
[2023-10-18_156638320231018200449.xlsx](https://github.com/qax-os/excelize/files/13024012/2023-10-18_156638320231018200449.xlsx)

**Comment by xuri** [comment]
I have tested with Tencent WeChat 8.0.42 for Android, and the preview of 2023-10-18_156638320231018200449.xlsx works well, and the cell is displayed as blank in 2023-10-18_156638320231018185239.xlsx. This behavior was contrary to what you mentioned.

**Comment by lilien1010** [comment]
Oh, sorry I might name the file incorrect. actually it's not blank, it's just the text show in color white, and you can even copy the text from the invisible cell, so I was thinking might impacted by some default StyleID that introduced from 2.7.0?

**Comment by lilien1010** [comment]
Just another quick question, is there any way that I can set a default StyleID for the global *excelize.File object?

**Comment by xuri** [comment]
The default style ID hasn't changed in the recently released version. I think this is caused by the viewer bugs, which not compatible with internal theme parts generated by this library. Thanks for your sponsor, I'll try to investigate this recently.

**Comment by lilien1010** [comment]
Thank you, I just revert our service back to 2.6.1 for production. but still hope can bump to latest version which also support Wechat Android preview.

**Comment by xuri** [comment]
I have improved compatibility with the viewer which doesn't support the default theme part namespace to resolve this issue, please try to upgrade the master branch code. This change will be released in the next version.

**Comment by lilien1010** [comment]
confirmed that this have been fixed when change to
github.com/xuri/excelize/v2 v2.8.1-0.20231023160552-a8cbcfa39b7c

I think this should also fix https://github.com/qax-os/excelize/issues/1700

**Comment by xuri** [comment]
Thanks for your feedback. The workbook generated was corrupted in issue #1700. I think maybe another reason caused that. There is still not enough info to reproduce that. I need more details about this from the author of that issue.
