### ISSUE TITLE
When if I use  SetSheetName Method , and the value is not "Sheet1" ,  data can not be exported

### ISSUE THREAD

**Issue by falcondeng** [qax-os/excelize#1696]
**Description**

**Steps to reproduce the issue:**
1. Mac (10.15.7) + vscode
2. SetNewSheet("Sheet1","财务")
3. SaveAs(filepath)

**Describe the results you received:**
Nothing exported but title.  If I set sheet name "Sheet1" , no problem.
**Describe the results you expected:**
I set my custom sheet name , and all data can be exported!
**Output of `go version`:**

```text
(paste your output here)
```

**Excelize version or commit ID:**

```text
(paste here)
```

**Environment details (OS, Microsoft Excel™ version, physical, etc.):**

**Comment by xuri** [comment]
Thanks for your issue. Which version of the Go language and Excelize library are you using? There no `SetNewSheet` function in this library. Could you follow the issue template and show us a complete, standalone example program or reproducible demo?

**Comment by falcondeng** [comment]
Ok, I got a lot work going. &nbsp;Touch you later.&nbsp;




DJ
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "qax-os/excelize"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年10月23日(星期一) 下午4:07
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [qax-os/excelize] When if I use  SetSheetName Method , and the value is not "Sheet1" ,  data can not be exported (Issue #1696)





 
Hi @falcondeng, there are still not have enough info of code and attachments to reproduce this issue, so I'll close this issue, if you have any questions, please let me know to reopen this anytime.
