### ISSUE TITLE
SetCellDefault adds "unwanted" apostrophe.

### ISSUE THREAD

**Issue by jtcaraball** [qax-os/excelize#1697]
**Description**
Setting a cell's raw value with `SetCellDefault` adds an apostrophe at the beginning of it.
If this is the intended functionality is there a way to set a value as given?
Thanks in advance.

**Steps to reproduce the issue:**
1. Call `f.SetCellDefault(sheet, cell, "(123,456,789)")`.

**Describe the results you received:**
In the resulting file the corresponding cell has the value `'(123,456,789)`.

**Describe the results you expected:**
Have the value of the cell be `(123,456,789)`.

**Output of `go version`:**

```text
go version go1.21.1 linux/amd64
```

**Excelize version or commit ID:**

```text
v2.8.1-0.20231002165931-0861faf2f2f0
```

**Comment by xuri** [comment]
Thanks for your issue. There is no apostrophe symbol in the result if you get the cell value, You set the cell value with a string, which represents the cell value as a text, so this behavior is in expected. If you need to set a number for a cell, please set the cell value as numeric data type, and create a number format style with the built-in number format code or custom number format code by the [`NewStyle`](https://pkg.go.dev/github.com/xuri/excelize/v2#File.NewStyle) function to get the style index, then set the cell with style index by [`SetCellStyle`](https://pkg.go.dev/github.com/xuri/excelize/v2#File.SetCellStyle). For example:

```go
package main

import (
    "fmt"

    "github.com/xuri/excelize/v2"
)

func main() {
    f := excelize.NewFile()
    defer func() {
        if err := f.Close(); err != nil {
            fmt.Println(err)
        }
    }()
    styleID, err := f.NewStyle(&excelize.Style{
        NumFmt: 37,
    })
    if err != nil {
        fmt.Println(err)
        return
    }
    if err := f.SetCellValue("Sheet1", "B2", -123456789); err != nil {
        fmt.Println(err)
        return
    }
    if err := f.SetCellStyle("Sheet1", "B2", "B2", styleID); err != nil {
        fmt.Println(err)
        return
    }
    if err := f.SetColWidth("Sheet1", "B", "B", 14); err != nil {
        fmt.Println(err)
        return
    }
    if err := f.SaveAs("Book1.xlsx"); err != nil {
        fmt.Println(err)
    }
}
```

**Comment by jtcaraball** [comment]
Thank you so much for the quick response. I understand. I'm currently getting the value from another workbook's cell but I guess getting the raw value, convert it to an int and then setting the style as you mention would be an appropriate solution.
I'll mark this as closed. Thank you again for the help!
