### ISSUE TITLE
Ability to remove outline for charts

### ISSUE THREAD

**Issue by Abdelaziz-Ouhammou** [qax-os/excelize#1706]
When creating a chart, by default, it will have a border around it. This can be removed from excel by selecting "no outline". Any Chance this feature can be added to Excelize ? Much appreciated.

**Comment by xuri** [comment]
Thanks for your issue. I have added new `Border` field in the `Chart` type to set the chart area border, please try to upgrade the master branch code, and this feature will be released in the next version. Now, you can remove chart area border like this:

```diff
err := f.AddChart("Sheet1", "E1", &excelize.Chart{
    // ...
+   Border: excelize.ChartLine{
+       Type: excelize.ChartLineNone,
+   },
})
```
