### ISSUE TITLE
When copying styles, they sometimes become bottom-aligned.

### ISSUE THREAD

**Issue by yuki2006** [qax-os/excelize#1708]
**Description**

**Steps to reproduce the issue:**
1.  use [Book1.xlsx](https://github.com/qax-os/excelize/files/13227626/Book1.xlsx)
2.   execute the code below.
3. Open the outputted file.
[Book2.xlsx](https://github.com/qax-os/excelize/files/13227656/Book2.xlsx)

![image](https://github.com/qax-os/excelize/assets/1004620/98a541b6-8585-4950-8267-6bf141ddf38b)
![image](https://github.com/qax-os/excelize/assets/1004620/57e8530a-dad4-42c4-accb-5df79e1c2641)

```go

func copyStyle(f *excelize.File, src, dst string) error {
	styleID, err := f.GetCellStyle("Sheet1", src)
	if err != nil {
		return err
	}
	style, err := f.GetStyle(styleID)
	if err != nil {
		return err
	}
	if style.Font == nil {
		style.Font = &excelize.Font{}
	}
	style.Font.Strike = true
	newStyleID, err := f.NewStyle(style)
	if err != nil {
		return err
	}
	err = f.SetCellValue("Sheet1", dst, "Hello world.")
	if err != nil {
		return err
	}
	err = f.SetCellStyle("Sheet1", dst, dst, newStyleID)
	if err != nil {
		return err
	}
	return nil
}

func main() {

	f, err := excelize.OpenFile("Book1.xlsx")
	if err != nil {
		panic(err)
	}

	err = copyStyle(f, "A1", "B1")
	if err != nil {
		panic(err)
	}
	err = copyStyle(f, "A2", "B2")
	if err != nil {
		panic(err)
	}

	err = f.SaveAs("Book2.xlsx")
	if err != nil {
		panic(err)
	}
}
```

**Describe the results you received:**

![image](https://github.com/qax-os/excelize/assets/1004620/847b679d-9655-48d4-ab34-1e6d2ca6b2a8)

**Describe the results you expected:**

I want both to remain in their original style without becoming bottom-aligned.

**Output of `go version`:**

```text
go version go1.21.3 darwin/arm64
```

**Excelize version or commit ID:**

```text
	github.com/xuri/excelize/v2 v2.8.0
```

**Environment details (OS, Microsoft Excel™ version, physical, etc.):**

![image](https://github.com/qax-os/excelize/assets/1004620/985c67fd-f48c-4efe-9388-138f2b465b4a)

**Comment by xuri** [comment]
Thanks for your issue. This issue has been fixed, please try to upgrade the master branch code, and this patch will be released in the next version.
