### ISSUE TITLE
I want to retrieve all the images in an Excel file at once. How can I do that?

### ISSUE THREAD

**Issue by ahhoujiquan** [qax-os/excelize#1711]
**Description**

**Steps to reproduce the issue:**
1.
2.
3.

**Describe the results you received:**

**Describe the results you expected:**

**Output of `go version`:**

```text
(paste your output here)
```

**Excelize version or commit ID:**

```text
(paste here)
```

**Environment details (OS, Microsoft Excel™ version, physical, etc.):**

**Comment by xuri** [comment]
Thanks for your issue. If you are reporting a new issue, make sure that we do not have any duplicates already exist. This was duplicated with #1218. We have introduced the `GetPictureCells` function in #1634, please try to upgrade the master branch code, and this feature will be released in the next version. I closed this issue, if you have any questions, please let me know, and you can reopen this anytime.
