### ISSUE TITLE
StreamWriter  clear all formats of template files

### ISSUE THREAD

**Issue by Shawn-fung** [qax-os/excelize#1716]
流式写入器会清空原模板文件的所有格式，普通写入却没有问题。
StreamWriter will clear all formats of template files，but there is no problem with regular writing

**Comment by xuri** [comment]
Yep, as the documentation of the stream writer says, which used for writing data on a new existing empty worksheet with large amounts of data.

**Comment by xuri** [comment]
I closed this issue. If you have any question, please let me know, and you can reopen this anytime.
