### ISSUE TITLE
panic: runtime error: index out of range [0] with length 0

### ISSUE THREAD

**Issue by tumbleweedd** [qax-os/excelize#1723]
### Subject of the issue
I get the following panic when using the library `github.com/xuri/excelize/v2`: `panic: runtime error: index out of range [0] with length 0`

### Your environment
* usee golang 1.19
* use excelize/v2@v2.7.0

### Steps to reproduce
the client had a panic. for what reason is unclear
the code is approximately as follows
```
package main

import (
  "fmt"
  "github.com/xuri/excelize/v2"
  "log"
  "os"
)

type axisCounter struct {
  Row    int64
  Column []rune
}

func newAxisCounter() *axisCounter {
  axis := new(axisCounter)
  axis.Row = 1
  axis.Column = append(axis.Column, 'A')
  return axis
}

func (axis *axisCounter) getAxis() string {
  return fmt.Sprintf("%s%d", string(axis.Column), axis.Row)
}

func main() {
  file, err := os.Open("panic_import_ob (1).xlsx")
  if err != nil {
    log.Fatal(err)
  }
  defer file.Close()

  fileXlsx, err := excelize.OpenReader(file)
  if err != nil {
    log.Fatal(err)
  }
  defer fileXlsx.Close()

  sheet := fileXlsx.GetSheetName(0)

  rows, err := fileXlsx.Rows(sheet)
  if err != nil {
    log.Fatal(err)
  }
  defer rows.Close()

  var (
    axis = newAxisCounter()
  )

  for rows.Next() {
    row, err := rows.Columns()
    if err != nil {
      log.Fatal(err)
    }

    for _, cell := range row {
      cellType, err := fileXlsx.GetCellType(sheet, axis.getAxis())
      if err != nil {
        continue
      }

      if cellType == excelize.CellTypeDate {
        cell, err = changeDateFormat(fileXlsx, sheet, axis.getAxis())
        if err != nil {
          log.Fatal(err)
        }
      }
      fmt.Println(cell)
    }
  }

}

var xlsxNumberFormat = "yyyy-mm-dd"

func changeDateFormat(fileXlsx *excelize.File, sheet, axis string) (cell string, err error) {
  style, err := fileXlsx.NewStyle(&excelize.Style{CustomNumFmt: &xlsxNumberFormat})
  if err != nil {
    log.Fatal(err)

  }
  err = fileXlsx.SetCellStyle(sheet, axis, axis, style)
  if err != nil {
    log.Fatal(err)

  }
  cell, err = fileXlsx.GetCellValue(sheet, axis)
  if err != nil {
    log.Fatal(err)

  }

  return cell, nil
}
```

### Actual behaviour
panic occurs when the `getCellType` method is called in the `cellType, err := fileXlsx.GetCellType(sheet, axis.getAxis())`

### Expected behaviour
there should obviously be no panic. it is unclear for what reason it appears, since there is no way to view the problematic client file. maybe it's the version? has anyone encountered such behavior? unfortunately, there is no way to check whether it is the version or not, since (as I said) there is no way to repeat the panic due to lack of access to the client file

### Log
```
panic: runtime error: index out of range [0] with length 0

goroutine 2773676 [running]:
github.com/xuri/excelize/v2.checkSheet(0xc00bcff880)
  /root/go/pkg/mod/github.com/xuri/excelize/v2@v2.7.0/excelize.go:311 +0x490
github.com/xuri/excelize/v2.(*File).workSheetReader(0xc0097fcd00, {0xc002eaec48, 0x8})
  /root/go/pkg/mod/github.com/xuri/excelize/v2@v2.7.0/excelize.go:268 +0x714
github.com/xuri/excelize/v2.(*File).getCellStringFunc(0xc009bbe000?, {0xc002eaec48?, 0xc00983df80?}, {0xc002eaf8ac, 0x2}, 0x31aaa18)
  /root/go/pkg/mod/github.com/xuri/excelize/v2@v2.7.0/cell.go:1272 +0x79
github.com/xuri/excelize/v2.(*File).GetCellType(0x30532d0?, {0xc002eaec48?, 0xc00983df80?}, {0xc002eaf8ac?, 0x2?})
  /root/go/pkg/mod/github.com/xuri/excelize/v2@v2.7.0/cell.go:87 +0x2a

```
here is the file that was provided to me, but it does not cause panic, but perhaps reflects the structure of the client's file: [panic_import_ob (1).xlsx](https://github.com/boncey/Flickr4Java/files/13376157/panic_import_ob.1.xlsx)

based on the function in which the panic occurred, I can't understand why this happened
![image](https://github.com/qax-os/excelize/assets/62465285/a5ea4d04-95cd-45ca-9ac2-efe470bf7db5)

**Comment by xuri** [comment]
Thanks for your issue. I have tested your code with the attachment in v2.7.0, and it works well. We need more details info or reproduce demo for this.

**Comment by xuri** [comment]
Thanks for your issue. I have tested your code with the attachment in v2.7.0, and it works well. We need more details info or a reproducation demo for this. May be the pull request #1692 resolve the same problems with this.

**Comment by xuri** [comment]
I have merged the pull request #1692 to resolve this issue. This patch will be released in the next version.

**Comment by xuri** [comment]
According to [the benchmark report](https://github.com/xuri/excelize/wiki#performance-figures) of v2.8.1, the fix for this (commit: [`6220a79`](https://github.com/xuri/excelize/tree/6220a798fd79231bf4b3d7ef587bb2b79d276710)) slows down the get rows about 3 times, and memory using about 17 times. We need to fixed the performance impact later.

**Comment by 444307289** [comment]
Hello, I am currently using version 2.9.1 of GitHub/xuri/Excel/v2 and have encountered this issue. Has this problem been fixed yet?

**Comment by xuri** [comment]
This issue already has been fixed and released on v2.8.1. If you get any issue, try to upgrade the lasted version or using the master branch code at first, if that can't resolve, please provide a sample code to reproduce this issue, or provide the file attachment without confidential info.

**Comment by 444307289** [comment]
> This issue already has been fixed and released on v2.8.1. If you get any issue, try to upgrade the lasted version or using the master branch code at first, if that can't resolve, please provide a sample code to reproduce this issue, or provide the file attachment without confidential info.

I am using version 2.9.1 and it will panic. I will send you the file later so you can try it out. Also, I would like to ask if this library takes up a lot of memory when reading and merging cells. I have noticed that some Excel files often experience memory overflow when reading and merging cells. Is there any way to solve this problem.

**Comment by xuri** [comment]
For your second question, how many merged cells are in your worksheet? and how many memory usages? Here is [performance benchmark](https://xuri.me/excelize/en/performance.html) for your reference, the time cost and memory usage should be similar as benchmark report in similar number of merged cells. Note that, we added optional parameter `withoutValues` for the `GetMergeCells` function in PR #2184 for improve getting merged cells performance, the feature will be released on next version.

**Comment by 444307289** [comment]
> For your second question, how many merged cells are in your worksheet? and how many memory usages? Here is [performance benchmark](https://xuri.me/excelize/en/performance.html) for your reference, the time cost and memory usage should be similar as benchmark report in similar number of merged cells. Note that, we added optional parameter `withoutValues` for the `GetMergeCells` function in PR [#2184](https://github.com/qax-os/excelize/pull/2184) for improve getting merged cells performance, the feature will be released on next version.

Okay, thanks. I'll look into how to resolve this issue and get back to you if there are any problems.
