### ISSUE TITLE
about removeCol method

### ISSUE THREAD

**Issue by XieChengYi** [qax-os/excelize#1726]
**Description**
when i use removeCol method to remove a col in my excel sheet,i have this scence that i need to remove "M","N","O" cols,so my code like this:
```
colIndex := []string{"M", "N", "O"}
    for _, index := range colIndex {
        if err = file.RemoveCol(sheetName, index); err != nil {
              // some logic
        }
    }
```
beyond my expectation that i didn't remove the three's cols which i want ,i think while the for loop fisrt run the RemoveCol method，the cols behind the "M" will go head to "M"  cols,so i had to change my code like this:
``
for i := 0; i < 3; i++ {
    if err = file.RemoveCol(sheetName, "M"); err != nil {
	return 0, err
    }
}
```
<!--
Briefly describe the problem you are having in a few paragraphs.
-->

**Steps to reproduce the issue:**
1.prepare a excel file 
2. use RemoveCol method to remove thre  cols you want
3.you will find that you have to use same col that you can remove  three continuous col

**Describe the results you received:**

**Describe the results you expected:** remove  three continuous col

**Output of `go version`:**
1.18
```text
(paste your output here)
```
Does this situation meet your expectations，if not i think it's a bug and i want to fix it.
Thanks for your view!!
**Excelize version or commit ID:**
v2.6.1
```text
(paste here)
```

**Environment details (OS, Microsoft Excel™ version, physical, etc.):**

**Comment by xuri** [comment]
Thanks for your issue. This behavior is expected, just like with your delete column in the spreadsheet application, the cells in column N will be moving into column M after deleting column M. Not like InsertCols, this library doesn't support removing multiple columns at once. So you need to remove the column one by one. This issue needn't be fixed. I closed this, if you have any questions, please let me know, and we can reopen this anytime.

**Comment by XieChengYi** [comment]
Okay，thank you for your question and answers.May i have another question: i set colWidth for cols first,then  i used RemoveCol method to remove some cols and i found that the colWidth i had set is not remove. Is it possible that while we use  RemoveCol method,the corresponding col with can also be deleted?

**Comment by xuri** [comment]
Which version of the Excelize library are you using? Could you show us a complete, standalone example program or reproducible demo?

**Comment by XieChengYi** [comment]
> Which version of the Excelize library are you using? Could you show us a complete, standalone example program or reproducible demo?

It seems that the issue doesn't exist in version 2.8.0. We are currently using version 2.6.3 in our company, so you must have already fixed this issue. Thank you again for your guidance！！！
