### ISSUE TITLE
expected element <workbook> in name space http://schemas.openxmlformats.org/spreadsheetml/2006/main but have no name space

### ISSUE THREAD

**Issue by HollischenBiber** [qax-os/excelize#1727]
Hello. 

I'm trying to process a file that I got from another service (meaning I can't change it anyway but in my code using your lib), anyway I can't get a cell value from it, i got a panic. If I save it with file.SaveAs() and try to open a new file - i got an issue from the title.  If i open the file in Excel then save it - I can process it using your library without any problems. File with problems is attached.
[TestExcel2311.xlsx](https://github.com/qax-os/excelize/files/13453550/TestExcel2311.xlsx)

Thanks in advance for your help

**Comment by xuri** [comment]
Thanks for your issue. Which version of the Excelize library are you using? Could you show us a complete, standalone example program or reproducible demo?

**Comment by xuri** [comment]
Thanks for your issue. I have tested your attachment workbook with lasted version and it works well. Which version of the Excelize library are you using? Could you show us a complete, standalone example program or reproducible demo? There are some incompatible changes in the Go 1.21.0, the Excelize library can not working with that version normally, if you are using the Go 1.21.x, please upgrade to the Go 1.21.1 and later version.

**Comment by xuri** [comment]
Thanks for your issue. I have tested your attachment workbook with lasted version and it works well. Which version of the Excelize library are you using? Could you show us a complete, standalone example program or reproducible demo? Note that, there are some incompatible changes in the Go 1.21.0, the Excelize library can not working with that version normally, if you are using the Go 1.21.x, please upgrade to the Go 1.21.1 and later version.

**Comment by HollischenBiber** [comment]
Thanks for you answer. I updated everything but it doesnn't work

[TestExcelReading.zip](https://github.com/qax-os/excelize/files/13455829/TestExcelReading.zip)
[TestExcel2311.xlsx](https://github.com/qax-os/excelize/files/13455830/TestExcel2311.xlsx)
![image](https://github.com/qax-os/excelize/assets/54780262/674092b1-fe80-4bb2-9ebb-ca9ce6ad42c0)
![image](https://github.com/qax-os/excelize/assets/54780262/18b83e02-76ef-474b-ad14-a84c4d52009a)

**Comment by xuri** [comment]
Thanks for your feedback. This issue similar with #1723, and has been fixed in #1692. Please upgrade to the master branch code. This patch will be released in the next version.

**Comment by xuri** [comment]
I've closed this issue. If you have any questions, please let me know, and you can reopen this anytime.
