### ISSUE TITLE
There's no get default sheetname for file

### ISSUE THREAD

**Issue by yasarluo** [qax-os/excelize#1741]
there's many funtions with param 'sheet name', but if we want to get active sheet name, we'll use two steps.

`
activeSheetIdx := f.GetActiveSheetIndex()
`
`
activeSheetName := f.GetSheetName(activeSheetIdx)
`

So, we hope there's only one step that can easily to do this, just like: 

`
activeSheetName := f.GetActiveSheetName()
`

**Comment by xuri** [comment]
Thanks for your issue and pull request. I've left some comments for your pull request.
