### ISSUE TITLE
GetPictures func has a error

### ISSUE THREAD

**Issue by pihc** [qax-os/excelize#1743]
**Description**
GetPictures func has a error, runtime error: invalid memory address or nil pointer dereference

**Steps to reproduce the issue:**
1. upload excel with picture 
2. then get an error
3. please help me

**Describe the results you received:**

**Describe the results you expected:**

**Output of `go version`:**

```text
GOVERSION="go1.17.13"
```

**Excelize version or commit ID:**

```text
v2.8.0
```

**Environment details (OS, Microsoft Excel™ version, physical, etc.):**
mac 13.0.1 (22A400)
wps 6.3.0

[Uploading test.xlsx…]()

![image](https://github.com/qax-os/excelize/assets/17465928/17f62764-97b0-4cb0-8673-ad29fcc4b99a)

**Comment by xuri** [comment]
Thanks for your issue. Note that, your attachment workbook is not available. This problem probably has been fixed by #1721. Please try to upgrade the master branch code by `go get -u github.com/xuri/excelize/v2@master`, if it still doesn't work, please let me know and provide workbook attachments.

**Comment by xuri** [comment]
It seems still not have enough info of code and attachments to reproduce this issue, so I'll close this issue, if you have any questions, please let me know to reopen this anytime.
