### ISSUE TITLE
When I do not set the conditional formatting style, I will get an nil error

### ISSUE THREAD

**Issue by ShowerBandV** [qax-os/excelize#1748]
**Description**
Reading a file with conditional formatting as cell values, but without formatting, GetConditionalFormats() will return a nil error. It was found that the issue was caused by DxfID being nil. We hope to fix this issue

```golang
package main

import (
	"fmt"
	"log"
	"strings"

	"github.com/xuri/excelize/v2"
)

func main() {
	file, err := excelize.OpenFile("bbb.xlsx")
	if err != nil {
		fmt.Printf("open file failed:%s", err.Error())
		return
	}
	formats, err := file.GetConditionalFormats("Sheet1")
	if err != nil {
		fmt.Printf("get conditionformats failed:%s", err.Error())
		return
	}
}
```
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x0 pc=0x10bef2b]

goroutine 1 [running]:
github.com/xuri/excelize/v2.extractCondFmtCellIs(_, _)
        D:/Users/xx/go/pkg/mod/github.com/xuri/excelize/v2@v2.8.1-0.20231202040309-18a160c5be82/styles.go:2764 +0xcb 
github.com/xuri/excelize/v2.(*File).GetConditionalFormats(0x11625d7?, {0x115eb16, 0x6})
        D:/Users/xx/go/pkg/mod/github.com/xuri/excelize/v2@v2.8.1-0.20231202040309-18a160c5be82/styles.go:2996 +0x2a5
main.main()
        E:/projects/excelizeDemo/main.go:17 +0x65
```

And I have found that errors can also occur if the conditional format type is null and not formatted. I hope you can handle similar unformatted scenarios.

**Comment by xuri** [comment]
Thanks for your issue. This issue already has been fixed by commit [866f308](https://github.com/xuri/excelize/commit/866f3086cd6714ab9114331fb8a73b1b4a1df0a1). Please upgrade to the master branch code, and this patch will be released in the next version. I've closed this, if it still not work, please let me know, and you can reopen this anytime.

**Comment by ShowerBandV** [comment]
I found something wrong in this commit, if there is a condition A with style ,the unstyled condition will be applied with A's style.
 ```golang
func (f *File) extractCondFmtCellIs(c *xlsxCfRule, extLst *xlsxExtLst) ConditionalFormatOptions {
	format := ConditionalFormatOptions{StopIfTrue: c.StopIfTrue, Type: "cell", Criteria: operatorType[c.Operator]}
	if c.DxfID != nil {
		format.Format = *c.DxfID
	}
	if len(c.Formula) == 2 {
		format.MinValue, format.MaxValue = c.Formula[0], c.Formula[1]
		return format
	}
	format.Value = c.Formula[0]
	return format
}
```
because the condition A's DxfID is 0,that is to say c.DxfID is 0 , and the unstyled condition's DxfID is nil, format default is 0,so after extract,they all will be 0,we can't distinguish who is unstyled

**Comment by xuri** [comment]
> @xuri I found something wrong in this commit, if there is a condition A with style ,the unstyled condition will be applied with A's style.
> 
> ```go
> func (f *File) extractCondFmtCellIs(c *xlsxCfRule, extLst *xlsxExtLst) ConditionalFormatOptions {
>    format := ConditionalFormatOptions{StopIfTrue: c.StopIfTrue, Type: "cell", Criteria: operatorType[c.Operator]}
>    if c.DxfID != nil {
>    	format.Format = *c.DxfID
>    }
>    if len(c.Formula) == 2 {
>    	format.MinValue, format.MaxValue = c.Formula[0], c.Formula[1]
>    	return format
>    }
>    format.Value = c.Formula[0]
>    return format
> }
> ```
> 
> because the condition A's DxfID is 0,that is to say c.DxfID is 0 , and the unstyled condition's DxfID is nil, format default is 0,so after extract,they all will be 0,we can't distinguish who is unstyled

Thanks for the feedback. This same as issue #1867. I've fixed it. Please upgrade to the master branch code, and this breaking change will be released in the next version.
