### ISSUE TITLE
Error: the same name table already exists, when first deleting and then adding the table with the same name back.

### ISSUE THREAD

**Issue by keqin404** [qax-os/excelize#1751]
**Description**

I meet Error: the same name table already exists, when first deleting and then adding the table with the same name back.

**Steps to reproduce the issue:**
1. create a template excel file named Book1.xlsx with Sheet1 and Table1
2. run sample code

**Describe the results you received:**

the same name table already exists

**Describe the results you expected:**

the table should be added.

**Output of `go version`:**

```text
go version go1.20.5 darwin/amd64
```

**Excelize version or commit ID:**

```text
github.com/xuri/excelize/v2 v2.8.0
```

**Environment details (OS, Microsoft Excel™ version, physical, etc.):**

MacOS

**Sample code:**
``` go
package main

import (
	"fmt"

	"github.com/xuri/excelize/v2"
)

func main() {
	f, err := excelize.OpenFile("Book1.xlsx")
	if err != nil {
		fmt.Println(err)
		return
	}
	defer func() {
		// Close the spreadsheet.
		if err := f.Close(); err != nil {
			fmt.Println(err)
		}
	}()
	fmt.Println("before delete:")
	fmt.Println(f.GetTables("Sheet1"))
	f.DeleteTable("Table1")
	fmt.Println("after delete:")
	fmt.Println(f.GetTables("Sheet1"))
	err = f.AddTable("Sheet1", &excelize.Table{Range: "A1:B3", Name: "Table1"})
	if err != nil {
		fmt.Println(err)
		return
	}
}
```

**Comment by xuri** [comment]
Thanks for your issue. This issue duplicates with #1682, and it has been fixed. Please upgrade to the master branch code, and this patch will be released in the next version. If it still not work, please let me know.

**Comment by xuri** [comment]
I'll close this issue, if you have any questions, please let me know to reopen this anytime.
