### ISSUE TITLE
在go1.21版本中，导出的excel是空的

### ISSUE THREAD

**Issue by xl9612** [qax-os/excelize#1752]
**Description**

**Steps to reproduce the issue:**
1.
2.
3.

**Describe the results you received:**

**Describe the results you expected:**

**Output of `go version`:**

```text
(paste your output here)
```

**Excelize version or commit ID:**

```text
(paste here)
```

**Environment details (OS, Microsoft Excel™ version, physical, etc.):**

**Comment by xuri** [comment]
Thanks for your issue. If you are reporting a new issue, make sure that we do not have any duplicates already exist. If it does not work with Go 1.21.0, please reference the issues #1465, #1595, #1603, #1608, #1614, #1619, #1620, #1621, #1623, #1633, #1637, #1641, #1642, #1648, #1651, #1652, #1656, #1657, #1660, #1663, #1670, #1686 and #1734. There are some incompatible changes in the Go 1.21.0 encoding/xml library. I have given feedback to the Go team and created a patch for it (golang/go#61881), and it has been fixed on Go 1.21.1. Please using the Go 1.20.7 and previous Go released version or upgrade to Go 1.21.1 and later. I have added notice on the [README](https://github.com/xuri/excelize#introduction) and [documentation website](https://xuri.me/excelize/en/base/installation.html#install) for this, and I've closed this. If you have any questions, please let me know, and reopen this anytime.

谢谢您的提问，在您创建新的问题之前，请确保不存在任何重复的问题。这与已有问题重复，请参考 #1465, #1595, #1603, #1608, #1614, #1619, #1620, #1621, #1623, #1633, #1637, #1641, #1642, #1648, #1651, #1652, #1656, #1657, #1660, #1663, #1670, #1686 和 #1734。Go 1.21.0 对 encoding/xml 标准库做了不兼容的更改，我已将该问题反馈至 Go 团队，并提交了修复补丁 golang/go#61881，已在 Go 1.21.1 中修复。请使用 Go 1.20.7 以及更早版本，或升级 1.21.1 及以上版本。我已经为此在[自述文档](https://github.com/xuri/excelize/blob/master/README_zh.md#简介)和[文档网站](https://xuri.me/excelize/zh-hans/base/installation.html#install)上添加了通知，因此我将关闭此问题。如果您有任何问题，请告诉我，并可随时重新打开。

**Comment by xuri** [comment]
Thanks for your issue. If you are reporting a new issue, make sure that we do not have any duplicates already exist. If it does not work with Go 1.21.0, please reference the issues #1465, #1595, #1603, #1608, #1614, #1619, #1620, #1621, #1623, #1633, #1637, #1641, #1642, #1648, #1651, #1652, #1656, #1657, #1660, #1663, #1670, #1686 and #1734. There are some incompatible changes in the Go 1.21.0 encoding/xml library. I have given feedback to the Go team and created a patch for it (golang/go#61881), and it has been fixed on Go 1.21.1. Please using the Go 1.20.12 and previous Go released version or upgrade to Go 1.21.1 and later. I have added notice on the [README](https://github.com/xuri/excelize#introduction) and [documentation website](https://xuri.me/excelize/en/base/installation.html#install) for this, and I've closed this. If you have any questions, please let me know, and reopen this anytime.

谢谢您的提问，在您创建新的问题之前，请确保不存在任何重复的问题。这与已有问题重复，请参考 #1465, #1595, #1603, #1608, #1614, #1619, #1620, #1621, #1623, #1633, #1637, #1641, #1642, #1648, #1651, #1652, #1656, #1657, #1660, #1663, #1670, #1686 和 #1734。Go 1.21.0 对 encoding/xml 标准库做了不兼容的更改，我已将该问题反馈至 Go 团队，并提交了修复补丁 golang/go#61881，已在 Go 1.21.1 中修复。请使用 Go 1.20.12 以及更早版本，或升级 1.21.1 及以上版本。我已经为此在[自述文档](https://github.com/xuri/excelize/blob/master/README_zh.md#简介)和[文档网站](https://xuri.me/excelize/zh-hans/base/installation.html#install)上添加了通知，因此我将关闭此问题。如果您有任何问题，请告诉我，并可随时重新打开。
