### ISSUE TITLE
v2 Fails to read 3rd column

### ISSUE THREAD

**Issue by elbek** [qax-os/excelize#1756]
**Description**

Attaching an excel file and I can see that library fails to read unit column values, instead just omits it entirely and shifts next columns to its value

**Steps to reproduce the issue:**
1. Try to parse the [kmg_excel.xlsx](https://github.com/qax-os/excelize/files/13677167/kmg_excel.xlsx)
2.
3.

**Describe the results you received:** Unit column is omitted

**Describe the results you expected:** Unit column on row 34 and 35 should be parsed properly

**Output of `go version`:** 
```text
go version go1.20 linux/amd64
```

**Excelize version or commit ID:**

```text
v2.6.1
```

**Environment details (OS, Microsoft Excel™ version, physical, etc.):**
Ubunut Linux 64bit

**Comment by xuri** [comment]
Thanks for your issue. This problem already has been fixed in v2.8.0, please upgrade to the lasted version or use the master branch code.

**Comment by xuri** [comment]
There is no feedback for this issue, so I've closed this, if you have a question, please let me know, and you can reopen this anytime.
