### ISSUE TITLE
Failed to open execl, TabRatio may be of float type

### ISSUE THREAD

**Issue by lujin1** [qax-os/excelize#1767]
**Description**
Failed to open execl, TabRatio may be of float type
strconv.ParseInt: parsing \"757.6136724960263\": invalid syntax

**Steps to reproduce the issue:**
1. workbook.xml
![image](https://github.com/qax-os/excelize/assets/33309882/498b2533-179b-4d03-a248-015b4f03725b)
2. log
strconv.ParseInt: parsing \"757.6136724960263\": invalid syntax

xmlWorkbook.go
![image](https://github.com/qax-os/excelize/assets/33309882/6ba6d900-4a5d-4f06-8038-c6e07925af8d)

https://learn.microsoft.com/en-us/office/vba/api/excel.window.tabratio
![image](https://github.com/qax-os/excelize/assets/33309882/c5e17ce0-f09e-4be8-8aaf-1b246012da3e)

**Comment by xuri** [comment]
Thanks for your issue. It seems the workbook generated by Excel did not follow [the data type defined in OOXML specifications](https://github.com/sc34wg4/OOXMLSchemas/blob/master/Part1/OfficeOpenXML-XMLSchema-Strict/sml.xsd#L4121C12-L4121C12). I'll change the field data type in the structure for better compatibility.

**Comment by xuri** [comment]
This issue has been fixed, please upgrade to the master branch code, and this patch will be released in the next version.
