### ISSUE TITLE
GetConditionalFormats need get databar gradient

### ISSUE THREAD

**Issue by ShowerBandV** [qax-os/excelize#1769]
**Description**
When I tried to use GetConditionFormats to obtain the conditional format of a data bar, I didn't know if the data bar was gradient filled. I looked at the XML and found that if it wasn't gradient filled, there would be an attr with gradient="0". If it was gradient filled, there wouldn't be this attr. I hope excelize can support the function of obtaining whether the data bar is gradient filled

```xml
<x14:cfRule type="dataBar" id="{259B75A4-6F18-4B61-83F0-580C0D906035}">
<x14:dataBar minLength="0" maxLength="100" gradient="0">
<x14:cfvo type="autoMin"/>
<x14:cfvo type="autoMax"/>
<x14:negativeFillColor rgb="FFFF0000"/>
<x14:axisColor rgb="FF000000"/>
</x14:dataBar>
</x14:cfRule>
```
[test (2).xlsx](https://github.com/qax-os/excelize/files/13775133/test.2.xlsx)

**Comment by xuri** [comment]
Thanks for your issue. I have fixed this. Please upgrade to the master branch code, and this patch will be released in the next version. Please determine the gradient data bar with the `BarSolid` field, for example:

```go
package main

import (
    "fmt"

    "github.com/xuri/excelize/v2"
)

func main() {
    f, err := excelize.OpenFile("test.2.xlsx")
    if err != nil {
        fmt.Println(err)
        return
    }
    defer func() {
        if err := f.Close(); err != nil {
            fmt.Println(err)
        }
    }()
    cfs, err := f.GetConditionalFormats("Sheet1")
    if err != nil {
        fmt.Println(err)
        return
    }
    for _, cf := range cfs {
        for _, rule := range cf {
            fmt.Println("is gradient:", !rule.BarSolid)
        }
    }
}
```
