### ISSUE TITLE
Unable to write cell data values

### ISSUE THREAD

**Issue by z0125** [qax-os/excelize#1774]
**Description**

**Steps to reproduce the issue:**
1. Unable to write cell data values. Data can be written to other operating systems (Mac, Linux).
2.
![image](https://github.com/qax-os/excelize/assets/20272855/066297a0-5980-419e-b759-78794ec14277)
3.
![image](https://github.com/qax-os/excelize/assets/20272855/54a8a742-aa92-4ba7-adec-cb211a2eea95)

**Describe the results you received:**

**Describe the results you expected:**

**Output of `go version`:**

```text
1.21.0
```

**Excelize version or commit ID:**

```text
v2.6.0
```

**Environment details (OS, Microsoft Excel™ version, physical, etc.):**
```text
windows 11，WPS
```

**Comment by xuri** [comment]
Thanks for your issue. If you are reporting a new issue, make sure that we do not have any duplicates already exist. If it does not work with Go 1.21.0, please reference the issues #1465, #1595, #1603, #1608, #1614, #1619, #1620, #1621, #1623, #1633, #1637, #1641, #1642, #1648, #1651, #1652, #1656, #1657, #1660, #1663, #1670, #1686, #1734, #1752, #1764 and #1768. There are some incompatible changes in the Go 1.21.0 encoding/xml library. I have given feedback to the Go team and created a patch for it (golang/go#61881), and it has been fixed on Go 1.21.1. Please using the Go 1.20.12 and previous Go released version or upgrade to Go 1.21.1 and later. I have added notice on the README and documentation website for this, and I've closed this. If you have any questions, please let me know, and reopen this anytime.

谢谢您的议题，在您创建新的议题之前，请确保不存在任何重复的议题。这与已有议题重复，请参考 #1465, #1595, #1603, #1608, #1614, #1619, #1620, #1621, #1623, #1633, #1637, #1641, #1642, #1648, #1651, #1652, #1656, #1657, #1660, #1663, #1670, #1686, #1734, #1752, #1764 和 #1768。Go 1.21.0 对 encoding/xml 标准库做了不兼容的更改，我已将该问题反馈至 Go 团队，并提交了修复补丁 golang/go#61881，已在 Go 1.21.1 中修复。请使用 Go 1.20.12 以及更早版本，或升级 1.21.1 及以上版本。我已经为此在自述文档和文档网站上添加了通知，因此我将关闭此议题。如果您有任何问题，请告诉我，并可随时重新打开。
