### ISSUE TITLE
GetSheetDimension not working for newly created excelize XLSX file

### ISSUE THREAD

**Issue by waverunner** [qax-os/excelize#1776]
Create of new XLSX file with excelize improperly saves/updates the used range

I used trivial examples to create new small spreadsheet using excelize. Followed this with programmatic small sheet updates. I need to read the used dimension to find the last used row so I can append new rows to bottom. Any use of GetSheetDimension on a newly created file only returns the value of "A1" where as it should return a colon separate pair like "A1:D5"

**Steps to reproduce the issue:**
Example source code is included here:

package main

import (
        "fmt"
        "github.com/xuri/excelize/v2"
)

func main() {

        var f *excelize.File
        var dim string = ""
        var err error

        f, err = excelize.OpenFile("bug.xlsx")
        if err != nil {
                f = excelize.NewFile() // new file creates sheet "Sheet1"
                f.SetCellValue("Sheet1", "A1", "Data")
                f.SetCellValue("Sheet1", "D5", "5")
                // So the used range should be "A1:D5"
                dim, _ = f.GetSheetDimension("Sheet1")
                fmt.Println("dimension:", dim)
                f.SaveAs("bug.xlsx")
                f.Close()

                f, err = excelize.OpenFile("bug.xlsx")
                dim = ""
        }

        dim, _ = f.GetSheetDimension("Sheet1")
        fmt.Println("dimension:", dim)

        f.Close()
}

Steps to reproduce issue:
1. Run the example code in empty directory. A new file "bug.xlsx" will be created. Note that the 2 instances of GetSheetDimension both return the same value of "A1". Running the program again (with the excelize created file present) will only report "A1"
2. Open the bug.xlsx file in excel and save this file again, close excel
3. re-run the example program again. Note that after opening the file and saving from excel, the reported dimension is "A1:D5"

**Describe the results you received:**
It appears that a newly created or saved file does not set the used dimension properly. Only "A1" is returned

**Describe the results you expected:**
Expecting a colon separate cell range which represents the actual used range.

Using a file created by excel seems to work as expected.  Opening the excelize file in excel and saving it again fixes the file and subsequent run report the used range.

First run within empty directory:
$ ./bug
dimension: A1
dimension: A1

Subsequent run:
$ ./bug
dimension: A1

Subsequent run after opening and re-saving the created file with excel:
$ ./bug
dimension: A1:D5

**Output of `go version`:**
```
$ go version
go version go1.21.5 darwin/amd64
```

**Excelize version or commit ID:**

```
go 1.21.5

require github.com/xuri/excelize/v2 v2.8.0
```

**Environment details (OS, Microsoft Excel™ version, physical, etc.):**
Developing under MacOS 14.0 at command line. Excel version 16.80

**Comment by waverunner** [comment]
I could work around this by iterating over the rows I have, but it would be much more efficient to get this from GetSheetDimension and then work from there.

**Comment by waverunner** [comment]
I'm just poking through the code to see if I can learn where the issue is. I see in sheet_test.go there is a test on GetSheetDimension on a newly created sheet. This is not the problem but the test assert looks for a single entry of "A1".

My opinion here, but I think the output of GetSheetDimension should a colon separated value for any invocation. Even on a completely new sheet, the return of this function should be "A1:A1"

**Comment by waverunner** [comment]
I verified that SetSheetDimension() does set this value correctly.  However, subsequent writes to the file by excelize do not update the sheet dimension. Opening and saving this via excel updates the dimension.

**Comment by xuri** [comment]
Thanks for your issue. This library doesn't handle and update worksheet dimensions automatically when saving the spreadsheet currently, so please update the worksheet dimensions by `SetSheetDimension` function before you save the workbook. Please also reference issues #1200 and #1402.

**Comment by xuri** [comment]
I've closed this. If you have any question, please let me know, and reopen this anytime.

**Comment by waverunner** [comment]
No, but thanks for the pointers. Ideally the framework should track and update it all, but poking through the code I can see the complexity. Maybe it makes sense to put somewhere in the docs that it's the Excelize API user's responsibility to update the used space.
My particular use case is around automating lots of small spreadsheets, so the data sizes as small and predictable enough that I can just scan for the last row manually and use that for further processing.

Thanks
