### ISSUE TITLE
GetStyle does not return DecimalPlaces

### ISSUE THREAD

**Issue by mlorenz-tug** [qax-os/excelize#1777]
**Description**

Currently getting a style using `GetStyle` does not return the previously set `DecimalPlaces` property. If this setting is retained in the Excel file this should also be read in the `GetStyle` method.

**Steps to reproduce the issue:**
1. 

```golang
style1 := &excelize.Style{
  Font: &excelize.Font{
    Bold: true,
  },
}
x := 2
style2 := &excelize.Style{
  DecimalPlaces: &x,
  NumFmt:        2,
}

f := excelize.NewFile()

s1, _ := f.NewStyle(style1)
s2, _ := f.NewStyle(style2)

ss1, _ := f.GetStyle(s1)
ss2, _ := f.GetStyle(s2)

fmt.Printf("%+v\n", ss1)
fmt.Printf("%+v\n", ss2)
```

**Describe the results you received:**

```
&{Border:[] Fill:{Type: Pattern:0 Color:[] Shading:0} Font:0xc00027eb60 Alignment:<nil> Protection:<nil> NumFmt:0 DecimalPlaces:<nil> CustomNumFmt:<nil> NegRed:false}
&{Border:[] Fill:{Type: Pattern:0 Color:[] Shading:0} Font:<nil> Alignment:<nil> Protection:<nil> NumFmt:2 DecimalPlaces:<nil> CustomNumFmt:<nil> NegRed:false}
```

`DecimalPlaces` is `nil` in both outputs. It makes sense in the first style, since no decimal places were set there.

**Describe the results you expected:**

 In the second output one would expect `DecimalPlaces` to be set to `2` (pointer to variable set to `2` to be specific).

**Output of `go version`:**

```text
go version go1.21.5 linux/amd64
```

**Excelize version or commit ID:**

```text
github.com/xuri/excelize/v2 v2.8.0
```

**Environment details (OS, Microsoft Excel™ version, physical, etc.):**

**Comment by xuri** [comment]
Thanks for your issue. This already has been fixed by commit [`4e936da`](https://github.com/xuri/excelize/commit/4e936dafdd6d89edbe80b508b5fcf4402ab8da4c), please try to upgrade the master branch code, and this patch will be released in the next version.
