### ISSUE TITLE
When using file.SetCellValue()，it shows a warning that the number is in text format, which could lead to calculation errors.

### ISSUE THREAD

**Issue by moyu-yangl** [qax-os/excelize#1778]
I'm currently facing an issue with excelize. When using file.SetCellValue(), I input the value "$1231". However, when I download the xlsx file, it shows a warning that the number is in text format, which could lead to calculation errors. I want to input a string like "$1231" because it clearly should not be directly converted to a number based on the requirements, but I would like to convert it to a number in the final step before downloading.
![image](https://github.com/qax-os/excelize/assets/87761443/5ea0723d-be08-4ec6-9a6d-37080a54f199)
I'm not sure if there is a suitable function or approach to solve this problem.

**Comment by xuri** [comment]
Thanks for your issue. As the documentation of the [`SetCellValue`](https://pkg.go.dev/github.com/xuri/excelize/v2#File.SetCellValue) function says, it supports multiple data types. Please set the cell value by Go's numeric data type, then set the [currency number formats](https://pkg.go.dev/github.com/xuri/excelize/v2#File.NewStyle) for the cells. For example:

```go
package main

import (
    "fmt"

    "github.com/xuri/excelize/v2"
)

func main() {
    f := excelize.NewFile()
    defer func() {
        if err := f.Close(); err != nil {
            fmt.Println(err)
        }
    }()
    // Set cell value
    if err := f.SetCellValue("Sheet1", "A1", 1231); err != nil {
        fmt.Println(err)
        return
    }
    // Create new style with built-in currency formats
    styleID, err := f.NewStyle(&excelize.Style{
        NumFmt: 165,
    })
    if err != nil {
        fmt.Println(err)
        return
    }
    // Set number format for the cells
    if err := f.SetCellStyle("Sheet1", "A1", "A1", styleID); err != nil {
        fmt.Println(err)
        return
    }
    if err := f.SaveAs("Book1.xlsx"); err != nil {
        fmt.Println(err)
        return
    }
}
```
