### ISSUE TITLE
Reading and saving a file corrupts it

### ISSUE THREAD

**Issue by nlassaux** [qax-os/excelize#1779]
**Description**

Opening the file linked below and saving it directly corrupts it. Opening it in Excel then removes all styles

**Steps to reproduce the issue:**
1. Read the file and save it as a new one
2. The new file is broken

```
package main

import (
	"github.com/xuri/excelize/v2"
)

// in the main, we just open a file and save it
// to see if it corrupts it

func main() {
	f, err := excelize.OpenFile("WorkingFile.xlsx")
	if err != nil {
		panic(err)
	}
	if err := f.SaveAs("BreakingFile.xlsx"); err != nil {
		panic(err)
	}
}
```

[WorkingFile.xlsx](https://github.com/qax-os/excelize/files/13886082/WorkingFile.xlsx)
[BreakingFile.xlsx](https://github.com/qax-os/excelize/files/13886083/BreakingFile.xlsx)

**Describe the results you received:**
Excel must repair the file, removing all styles. From the error message the error is on `/xl/styles.xml (HRESULT 0x8000ffff Line 2, Col 0)`

**Describe the results you expected:**
The same document, +- some size differences due to different XML formatting.

**Output of `go version`:**

```text
go version go1.21.3 darwin/amd64
```

**Excelize version or commit ID:**

```text
github.com/xuri/excelize/v2 v2.8.0
```

**Environment details (OS, Microsoft Excel™ version, physical, etc.):**
On a Macbook Pro Intel. Using Excel Online for my tests but apparently the same with Excel running on Windows.

**Comment by xuri** [comment]
Thanks for your issue. This issue similar with #1653 and #1693, and already has been fixed, please upgrade to the master branch by `go get -u github.com/xuri/excelize/v2@master`, and this patch will be released in the next version.

**Comment by nlassaux** [comment]
It worked well, thanks!
