### ISSUE TITLE
file.WriteToBuffer方法占用过高内存

### ISSUE THREAD

**Issue by TopOneTop** [qax-os/excelize#1782]
**Description**

**Steps to reproduce the issue:**
1.当数据量大时，虽然已使用stream准备好了file数据，但此时将文件上传对象存储需要file.WriteToBuffer方法，底层实现是直接将file所有的内容压缩写到一个buf，此时是两倍内存占用。
2.是否可以提供一个方法，使用者传入指定容量的buf和分片位置index，遍历将file内容写入缓冲，让使用方可以实现追加上传对象存储，且不占用过高的内存呢。
3.

**Describe the results you received:**

**Describe the results you expected:**

**Output of `go version`:**

```text
(paste your output here)
```

**Excelize version or commit ID:**

```text
(paste here)
```

**Environment details (OS, Microsoft Excel™ version, physical, etc.):**

**Comment by xuri** [comment]
Thanks for your issue. If you are reporting a new issue, make sure that we do not have any duplicates already exist. This was duplicated with issues #753, #1052, #1429 and #1739.

**Comment by xiaozhiliaoo** [comment]
@TopOneTop Top 请问这个问题占用内存过高解决了没有呀，有没有好的办法呀，
