### ISSUE TITLE
When a condition style splited into multi part,it should be the same rule style

### ISSUE THREAD

**Issue by ShowerBandV** [qax-os/excelize#1783]
**Description**
I got a condition range like "$H$1:$H$4,$H$8:$H$10,$H$13:$H$15", SetConditionalFormat() will return "invalid column name "H4,H",I read the func code,I found excelize parse range should be like this 
```golang
func rangeRefToCoordinates(ref string) ([]int, error) {
	rng := strings.Split(strings.ReplaceAll(ref, "$", ""), ",")
	for i := 0; i < len(rng); i++ {
		rng2 := strings.Split(rng[i], ":")
		if len(rng) < 2 {
			return nil, ErrParameterInvalid
		}
		coordinates,err:=cellRefsToCoordinates(rng2[0], rng2[1])
                ...........
	}
        ......
}
```

**Comment by xuri** [comment]
Thanks for your issue. This issue has been fixed, please try to upgrade the master branch code, and this patch will be released in the next version.
