### ISSUE TITLE
DeleteComment is no deletion marker

### ISSUE THREAD

**Issue by baichachaa** [qax-os/excelize#1789]
After I deleted the comment, there was still the comment.
As you can see the code:

```
f.SetCellValue("Sheet1", "A2", 100)
f.AddComment("Sheet1", excelize.Comment{Cell: "A2", Text: "aaa"})
f.DeleteComment("Sheet1", "A2")
```
![Snipaste_2024-01-23_21-04-31](https://github.com/qax-os/excelize/assets/76542068/323ef998-82a7-43cd-a902-d8e84d649f18)

go version： go1.21.3 windows/amd64
excelize version： 2.8.0

**Comment by baichachaa** [comment]
I used your code and it's still the same as I described.
Maybe it's an issue with WPS Office.
WPS Office Version:  12.1.0.16120

**Comment by xuri** [comment]
Thanks for your feedback. This issue has been fixed, please try to upgrade the master branch code, and this patch will be released in the next version.
