### ISSUE TITLE
Auto Filter disappears when renaming sheet

### ISSUE THREAD

**Issue by jpmeijers** [qax-os/excelize#1792]
**Description**

Similar to https://github.com/qax-os/excelize/issues/324. When a sheet is renamed, a filter added before the rename is lost.

**Steps to reproduce the issue:**
1. Add a filter with `f.AutoFilter("Sheet1", "A2:T18", []excelize.AutoFilterOptions{})`
2. Rename the sheet `f.SetSheetName("Sheet1", "Test Sheet")`
3. Open in Excel/LibreOffice and the filter is not there

**Describe the results you received:**
The filter is dropped when the sheet is renamed

**Describe the results you expected:**
A filter should survive a sheet rename

**Output of `go version`:**

```text
go version go1.19.3 linux/amd64
```

**Excelize version or commit ID:**

```text
github.com/xuri/excelize/v2 v2.7.1
```

**Environment details (OS, Microsoft Excel™ version, physical, etc.):**
Ubuntu 23.10

Version: 7.6.4.1 (X86_64) / LibreOffice Community
Build ID: 60(Build:1)
CPU threads: 8; OS: Linux 6.5; UI render: default; VCL: gtk3
Locale: en-US (en_ZA.UTF-8); UI: en-US
Ubuntu package version: 4:7.6.4-0ubuntu0.23.10.1
Calc: threaded

**Comment by xuri** [comment]
Thanks for your issue. This bug has been fixed, please upgrade to the master branch code by `go get -u github.com/xuri/excelize@master`, and this patch will be released in the next version. Note that, as the documentation of this function says, it only changes the name of the sheet and will not update the sheet name in the formula or reference associated with the cell. So there still may be problem formula error or cell reference missing after this is fixed.
