### ISSUE TITLE
Retain Cell Formatting (date, custom format, percentage, etc..) when reading excel file and assigning new value to the cell like (SetCellValue)

### ISSUE THREAD

**Issue by edwardmatutino** [qax-os/excelize#1793]
**Description**

We are using excelize to read excel file and manipulate/update its values then saving it back again. And excelize works like a charm with that. However, I noticed that we're loosing the format (date, custom format, percentage, number, etc...) of the cells when saving the changes made. I'm not sure when, maybe it's not retaining the formatting when reading the excel file or maybe it's loosing the formatting when setting a new value to the cell. But with that said, is there a way to retain the formatting of the cell even when you set a new cell value (SetCellValue) or save the file?

**Steps to reproduce the issue:**
1. Read excel file with formatting like percentage or custom formats columns.
2. Update the cell value
3. Save the file

**Describe the results you received: the result looses the formatting**

**Describe the results you expected: does not loose formatting even when cell value is updated**

**Output of `go version`: latest**

```text
Not Needed
```

**Excelize version or commit ID: latest**

```text
Not Needed
```

**Environment details (OS, Microsoft Excel™ version, physical, etc.):**

**Comment by xuri** [comment]
Thanks for your issue. Which version of the Excelize library are you using? Could you show us a complete, standalone example program or reproducible demo, and a workbook attachment without confidential info?

**Comment by edwardmatutino** [comment]
We're using Excelize v2.8.0... right now I can't send you the program I'm using a clients data. But can you confirm, does Excelize retain cell formatting like Custom Format, Percentage, Numbers, etc...? From what I'm seeing after reading an excel file and saving it looses its formatting. I dont mean the format but the Data Format like Cutom Format, Numbers, Percentage, and others.

**Comment by xuri** [comment]
Excelize will retain cell formatting when you modify the cell values, I have fixed some style related issues in v2.8.0, please try to upgrade the master branch code, and if it still doesn't work, please provide a reproducible attachment and code.

**Comment by edwardmatutino** [comment]
How do I do that in go module to point to master? like go get ?

**Comment by edwardmatutino** [comment]
Works now. Perfect. I noticed another issue though. Like for example I have this formula cell [=SUM(A1:A10)] and by default the value is 0%. Now after reading the excel and updated 1 or more cell value from A1 to A10 cell. The formula cell remains at 0% when I open the saved excel. Now when I open the saved excel and just click on the Formula cell, that's the only time it computes for the real value. Not sure if you already considered this kind of scenario.

**Comment by xuri** [comment]
Sorry, I don't understand what you mean, did you want to trigger the formula's automatic calculation when opening the workbook by Excel application? If so, please reference issues #634, #1195, and #1322, and use the [`UpdateLinkedValue`](https://pkg.go.dev/github.com/xuri/excelize/v2#File.UpdateLinkedValue) to clean up the cell calculation cache value before saving the spreadsheet.

**Comment by edwardmatutino** [comment]
Correct, I need to trigger the formulas automatically. And the one you mentioned [UpdateLinkedValue](https://pkg.go.dev/github.com/xuri/excelize/v2#File.UpdateLinkedValue) saves me. Works Perfectly now. Much thanks for the quickest support ever.

**Comment by xuri** [comment]
You're welcome. Please close the issue if this problem has been resolved.

**Comment by edwardmatutino** [comment]
I will. Thanks much. You're a life saver.
