### ISSUE TITLE
"GetCellRichText" and "GetStyle" method do not set font color when white

### ISSUE THREAD

**Issue by Fujita-Naoyuki** [qax-os/excelize#1794]
**Description**
"GetCellRichText" and "GetStyle" method do not set font color when white

**Steps to reproduce the issue:**
1.Call the "GetCellRichText" method for the cell set like the attached image

* cell value
![image](https://github.com/qax-os/excelize/assets/49280202/29d6267c-7ef5-4a15-b4e5-3d3210fb9bbc)
* debug
![image](https://github.com/qax-os/excelize/assets/49280202/1991648e-68c1-47b0-9b78-a42498517cc5)

**Describe the results you received:**
Color: ""

**Describe the results you expected:**
Color: "FFFFFF"

**Output of `go version`:**

```text
go version go1.20.1 windows/amd64
```

**Excelize version or commit ID:**

```text
github.com/xuri/excelize/v2 v2.8.0
```

**Environment details (OS, Microsoft Excel™ version, physical, etc.):**

**Comment by xuri** [comment]
Thanks for your issue. There 3 kinds of colors for the text in the spreadsheet: hex color, indexed color, and theme color. The priority of these colors is hex color takes precedence over theme color, and the theme color takes precedence over indexed color. The fields: `Color`, `ColorIndexed`, and `ColorTheme` in the `Font` data type represent these 3 colors. This library just added a new function `GetBaseColor`, which supports converting and returns the preferred hex color code from these 3 colors. Please upgrade to the master branch code, and this feature will be released in the next version. In addition, the color also supports applying tint value based on the hex color, so we need to use the `ThemeColor` function to apply the tint for the based color to get the calculated hex color value. Here is an example for your reference:

```go
runs, err := f.GetCellRichText("Sheet1", "A1")
if err != nil {
    fmt.Println(err)
    return
}
for _, run := range runs {
    var hexColor string
    if run.Font != nil {
        baseColor := f.GetBaseColor(run.Font.Color, run.Font.ColorIndexed, run.Font.ColorTheme)
        hexColor = excelize.ThemeColor(baseColor, run.Font.ColorTint)
    }
    fmt.Printf("text: %s, color: %s\r\n", run.Text, hexColor)
}
```
