### ISSUE TITLE
Exporting xlsx file, there is an extra space in the first row and first column

### ISSUE THREAD

**Issue by ccaiy9** [qax-os/excelize#1806]
I encountered an issue when exporting an xlsx file, I opened it using WPS and found that a space would be added before the first data in the first column, as shown in the figure：
<img width="667" alt="image" src="https://github.com/qax-os/excelize/assets/39152125/5b089fdb-e82d-4ad8-8cae-9bb5e2938e61">

When I process with golang, I also get an error:   **strconv.ParseInt: parsing "\ufeff1": invalid syntax**

how to cancel this space by default during export？

**Comment by xuri** [comment]
Thanks for your issue. Which version of the Excelize library are you using? Could you follow the issue template and show us a complete, standalone example program or reproducible demo?

**Comment by ccaiy9** [comment]
Thanks for your reply！

**my steps to reproduce the issue:**
1. i have a producer process, read data from mysql, and transferring data to consumer processes through pipelines
2.  consumer processes receive data and and export it to xlsx，demo code：

```
func generateExcelColumn(n int) string {
	result := ""
	for n > 0 {
		remainder := (n - 1) % 26
		result = fmt.Sprintf("%c%s", 'A'+remainder, result)
		n = (n - 1) / 26
	}
	return result
}

func generateExcelCell(column, row int) string {
	columnName := generateExcelColumn(column)
	cell := fmt.Sprintf("%s%d", columnName, row)
	return cell
}


func export() {

	file := excelize.NewFile()
	_, err = file.NewSheet("Sheet1")
	reader := bufio.NewReader(os.Stdin)   // from producer process

	for {
		line, err = reader.ReadString('\n')  // read a line
		line = strings.TrimSuffix(line, "\n") // Remove line breaks at the end of a line
		fields := strings.Split(line, "\t")   // Separate fields by tab
		
		for col, field := range fields {
			cell := generateExcelCell(col+1, row)
			transField := strings.Replace(field, "\\n", "\n", -1)
			
			if err = file.SetCellValue("Sheet1", cell, transField); err != nil {
				os.Exit(-1)
			}
		}
		
		row++

	}
}

```

**the results you received:**
  When I  opened it using WPS and found that a space would be added before the first data in the first column.
Also  I get an error: strconv.ParseInt: parsing "\ufeff1": invalid syntax，  "\ ufeff1" seems to represent a space.
By the way, only the data in the first row and first column will be added with this space, and other data will not be added.


**Describe the results you expected:**
I hope that when exporting xlsx, this space will not be added by default

**Output of `go version`:**
GOVERSION="go1.19.13"

**Excelize version:**
"github.com/xuri/excelize/v2"
<img width="353" alt="image" src="https://github.com/qax-os/excelize/assets/39152125/558d8189-a3b5-4c70-bf02-8ea6d6cbeb1b">

**Comment by xuri** [comment]
Thanks for your feedback. This duplicate with issue #1778, As the [documentation of the `SetCellValue` function](https://pkg.go.dev/github.com/xuri/excelize/v2#File.SetCellValue) says, it supports multiple data types. Please convert the `transField ` variable to Go's numeric data type (int, uint, float64, etc.) in your code before setting the cell value.

**Comment by xuri** [comment]
Thanks for your feedback. This duplicate with issue #1778, As the [documentation of the `SetCellValue` function](https://pkg.go.dev/github.com/xuri/excelize/v2#File.SetCellValue) says, it supports multiple data types. Please convert the `transField` variable to Go's numeric data type (int, uint, float64, etc.) in your code before setting the cell value.

**Comment by ccaiy9** [comment]
non numeric data can also have this situation：

**Comment by ccaiy9** [comment]
My issue may be different from #1778，non numeric data can also have this situation：
<img width="112" alt="image" src="https://github.com/qax-os/excelize/assets/39152125/7ac54215-38e9-41e6-b790-1ee155637290">

**Comment by xuri** [comment]
Could you show us a complete, standalone example program or reproducible demo (with main function)? Did you confirm that the value of variable transField does not contain a blank prefix?

**Comment by xuri** [comment]
Could you show us a complete, standalone example program or reproducible demo (with main function)? Did you confirm that the value of variable `transField` does not contain a blank character prefix?

**Comment by xuri** [comment]
Could you follow the issue template and show us **a complete, standalone example program** or reproducible demo (with a main function)? Please check and confirm that the value of the variable `transField` doesn't contain a blank character prefix.

**Comment by ccaiy9** [comment]
I have a simple test：

**1. mysql data**
<img width="369" alt="image" src="https://github.com/qax-os/excelize/assets/39152125/0be52cee-790b-4264-bb9c-062069a436e5">
<img width="704" alt="image" src="https://github.com/qax-os/excelize/assets/39152125/23523c3e-d56c-4bb3-9b05-949193a38561">

**2.export result:**
<img width="378" alt="image" src="https://github.com/qax-os/excelize/assets/39152125/a5ada8d4-e770-4521-be18-781a1877d85f">


**3. I added a few lines for printing：**
```
func generateExcelColumn(n int) string {
	result := ""
	for n > 0 {
		remainder := (n - 1) % 26
		result = fmt.Sprintf("%c%s", 'A'+remainder, result)
		n = (n - 1) / 26
	}
	return result
}

func generateExcelCell(column, row int) string {
	columnName := generateExcelColumn(column)
	cell := fmt.Sprintf("%s%d", columnName, row)
	return cell
}


func export() {

	file := excelize.NewFile()
	_, err = file.NewSheet("Sheet1")
	reader := bufio.NewReader(os.Stdin)   // from producer process

	for {
		line, err = reader.ReadString('\n')  // read a line
		
		logger.Infof(ctx, "-1--------------line:%s", line)
		
		line = strings.TrimSuffix(line, "\n") // Remove line breaks at the end of a line
		fields := strings.Split(line, "\t")   // Separate fields by tab
		
		for col, field := range fields {
			
			logger.Infof(ctx, "-2--------------field:%s", field)
			
			cell := generateExcelCell(col+1, row)
			transField := strings.Replace(field, "\\n", "\n", -1)
			
			logger.Infof(ctx, "-3--------------transField:%s", transField)
			
			if err = file.SetCellValue("Sheet1", cell, transField); err != nil {
				os.Exit(-1)
			}
		}
		
		row++

	}
}
```

Print results:
```
2024-02-04 18:39:37.069 [INFO] {c52f1bd66cc19d05628bd8bf27af3ad6} -1--------------line:Quién4   1
2024-02-04 18:39:37.069 [INFO] {c52f1bd66cc19d05628bd8bf27af3ad6} -2--------------field:Quién4
2024-02-04 18:39:37.069 [INFO] {c52f1bd66cc19d05628bd8bf27af3ad6} -3--------------transField:Quién4

```


From the print results, it can be seen that from  `line, err=reader ReadString ('\ n')` reads data without spaces, and the value of the variable transField doesn't contain a blank character prefix.
So, I guess, it looks like I missed some settings when using this package?

**Comment by ccaiy9** [comment]
Seems to have found the problem.
i print with %q:
```
2024-02-04 19:55:58.175 [INFO] {c52f1bd66cc19d05628bd8bf27af3ad6} -1--------------line:"\ufeffQuien4\t1\n"
```
`Quien4` has a special character before it....
emm,  thanks for your help, 
It seems like to be caused by the use of stdout or stdin....

**Comment by xuri** [comment]
You're welcome. Please close the issue if this problem has been resolved.
