### ISSUE TITLE
CalcCellValue returns incorrect results in some case

### ISSUE THREAD

**Issue by BigtigerGG** [qax-os/excelize#1807]
我的Excel文件有两个工作表，分别为：
- Sheet1
- Sheet2

Sheet2中有一列的值使用VLOOKUP计算，公式内容为：VLOOKUP(C4,'Sheet1'!A$2:B$200,2,0)，目的是为了在Sheet1的 A$2:B$200范围内中查找Sheet2 C4单元格值，并返回Sheet1对应第二列的值

但是实际上CalcCellValue返回了 空字符串 且没有任何报错，想请教下这个问题该如何解决

**Comment by xuri** [comment]
Thanks for your issue. Which version of the Excelize library are you using? Could you follow the issue template and show us a complete, standalone example program or reproducible demo?

**Comment by BigtigerGG** [comment]
> Thanks for your issue. Which version of the Excelize library are you using? Could you follow the issue template and show us a complete, standalone example program or reproducible demo?

感谢回复🙏！
excelize版本：v2.8.0

例子：
示例文件：
[demo.xlsx](https://github.com/qax-os/excelize/files/14156087/demo.xlsx)
复现代码：

```golang
func getExcel() (*excelize.File, error) {
	f, err := excelize.OpenFile("demo.xlsx")
	if err != nil {
		fmt.Println(err)
		return nil, err
	}
	defer func() {
		if err := f.Close(); err != nil {
			fmt.Println(err)
		}
	}()
	return f, nil
}

func testCalc(_ context.Context) error {
	f, err := getExcel()
	if err != nil {
		return err
	}
	const (
		sheet1 = "Sheet1"
		sheet2 = "Sheet2"
	)

	// 打印公式
	formula, err1 := f.GetCellFormula(sheet2, "B1")
	fmt.Printf("公式:%s 错误:%s \n", formula, err1)

	// 计算公式
	calVal, err2 := f.CalcCellValue(sheet2, "B1")
	fmt.Printf("公式结果:%s 错误: %s \n", calVal, err2)
	return nil
}
```
代码结果：
公式:VLOOKUP(A1,'Sheet1'!A$1:B200,2,0) 错误:%!s(<nil>) 
公式结果: 错误: %!s(<nil>)

**Comment by BigtigerGG** [comment]
@xuri 完整的复现路径如上所示🙏🙏

**Comment by xuri** [comment]
Thanks for your feedback. This issue has been fixed. Please upgrade to the master branch code by `go get -u github.com/xuri/excelize/v2@master`, and this patch will be released in the next version.

**Comment by BigtigerGG** [comment]
感谢🙏
