### ISSUE TITLE
使用SaveAs另存为一个新文件，再读取该文件时带公式的列没有数据

### ISSUE THREAD

**Issue by chengfny** [qax-os/excelize#1808]
如标题，另存后必须要打开xlsx文件手动保存一下，再读取该文件才能正常读取到公式列的数值

**Comment by xuri** [comment]
Thanks for your issue. Which version of the Excelize library are you using? Could you follow the issue template and show us a complete, standalone example program or reproducible demo?

**Comment by chengfny** [comment]
我找到了原因，是因为我在工作中会用到Microsoft Excel，也会用到WPS Office，使用WPS时打开文件时，带公式的列不会自动计算，所以我调用了UpdateLinkedValue()方法，而调用该方法后，必须要先手动保存文件，再进行导入才可以正常读取到公式列的数值
