### ISSUE TITLE
RawCellValue doesn't work when passed in OpenReader function

### ISSUE THREAD

**Issue by vivekkairi** [qax-os/excelize#1815]
**Description**
Passing `RawCellValue: true` in excelize.OpenReader doesn't get the raw values because the `GetRows` function accepts a separate `Options` object which doesn't take in consideration the Options passed in OpenReader

**Steps to reproduce the issue:**
1. Create a excel with numeric data and prepend the data with 0 values
2.
```
f, openErr := excelize.OpenReader(reader, excelize.Options{
    RawCellValue: true,
})
rows, err := f.GetRows(sheetName)
```

**Describe the results you received:**
The rows will have columns with the 0 prefix removed

**Describe the results you expected:**
The 0 prefix should be there as RawCellValue was passed as true

**Output of `go version`:**

```text
go version go1.21.6 darwin/arm64
```

**Excelize version or commit ID:**

```v2.8.0```

**Comment by xuri** [comment]
Thanks for your issue and pull request. I've left some comments in the pull request.

**Comment by xuri** [comment]
Thanks for the contribution. This patch will be released in the next version.
