### ISSUE TITLE
AutoFilter stops working on 2.8.1 (worked on 2.8.0)

### ISSUE THREAD

**Issue by ebarped** [qax-os/excelize#1830]
**Description**

The autofilter function stops working (on both windows office & linux libreoffice calc) on `v2.8.1`, but works in `v2.8.0`.
I didnt make any code changes, only changed the version of excelize in go.mod.
The build and the execution is OK, but the output excel does not have the filters in the column headers.

I call the autofilter like this:

```go
err := f.AutoFilter("sheet1", "A1:E1", []excelize.AutoFilterOptions{})
if err != nil {
	panic(err)
}
```

**Steps to reproduce the issue:**
1. Change the go.mod excelize version to 2.8.1
2. go run main.go

**Describe the results you received:**
The excel file did not have the autofilter selector in the columns headers

**Describe the results you expected:**
The excel file should have the autofilter selector in the columns headers

**Output of `go version`:**

```text
go version go1.22.0 linux/amd64
```

**Excelize version or commit ID:**

```text
2.8.1
```

**Environment details (OS, Microsoft Excel™ version, physical, etc.):**
```text
Linux (Ubuntu 22.04)
LibreOffice 7.3.7.2
```

**Comment by mrhdias** [comment]
Some issue with 2.8.1 and ArchLinux with LibreOffice 24.2.1.2 (work with 2.8.0)

**Comment by xuri** [comment]
Thanks for your issue. This issue has been fixed, please upgrade to the master branch by go `get -u github.com/xuri/excelize/v2@master`, and this patch will be released in the next version.
