### ISSUE TITLE
dataValidations range issue

### ISSUE THREAD

**Issue by mediawall** [qax-os/excelize#1831]
[test.xlsx](https://github.com/qax-os/excelize/files/14448197/test.xlsx)

the sqref of dataValidations is a range in my excel file (xl\worksheets\sheet1.xml)
```xml
<dataValidations count="1">
  <dataValidation  sqref="G1:G3 H1:H3" .../>
</dataValidations>
```
```go
f, _ := excelize.OpenFile("test.xlsx")
defer f.Close()

sn := "Sheet 1"
if err := f.InsertRows(sn, 2, 1); err != nil {
  println(err.Error())
}
```
the error will happen
```
invalid column name "G3 H"
```

lib version: 2.8.1
go version: 1.22
os: ubuntu 22.04

**Comment by xuri** [comment]
Thanks for your issue. This issue has been fixed, please upgrade to the master branch by go `get -u github.com/xuri/excelize/v2@master`, and this patch will be released in the next version.
