### ISSUE TITLE
Flamegraph of `CalcCellValue` shows lots of time spent doing `runtime.duffcopy` inside `getSharedFormula`

### ISSUE THREAD

**Issue by paolobarbolini** [qax-os/excelize#1836]
**Description**

`runtime.duffcopy` is showing up taking a substantial amount of time in flamegraphs of `CalcCellValue`.

![image](https://github.com/qax-os/excelize/assets/6215781/1b9b9e53-130e-4898-a743-31b617f9003c)

**Steps to reproduce the issue:**
1. Open an Excel containing many formulas
2. Call `CalcCellValue` on a cell containing a formula referencing many other cells
3. The flamegraph will show `runtime.duffcopy` taking a long time

**Output of `go version`:**

```text
go version go1.22.0 linux/amd64
```

**Excelize version or commit ID:**

```text
9d4c2e60f66b
```

**Comment by xuri** [comment]
Thanks for your issue. The pull request has been merged, and this patch will be released in the next version.
