### ISSUE TITLE
Is webp (image format) supported? 

### ISSUE THREAD

**Issue by yunbai002** [qax-os/excelize#1839]
Is webp (image format) supported?

**Comment by WellOptimized** [comment]
webp is not supported currently, excelize only supports these image types:
```code
var supportedImageTypes = map[string]string{
	".bmp": ".bmp", ".emf": ".emf", ".emz": ".emz", ".gif": ".gif",
	".jpeg": ".jpeg", ".jpg": ".jpeg", ".png": ".png", ".svg": ".svg",
	".tif": ".tiff", ".tiff": ".tiff", ".wmf": ".wmf", ".wmz": ".wmz",
}```

**Comment by yunbai002** [comment]
> webp is not supported currently, excelize only supports these image types:
> 
> ```
> var supportedImageTypes = map[string]string{
> 	".bmp": ".bmp", ".emf": ".emf", ".emz": ".emz", ".gif": ".gif",
> 	".jpeg": ".jpeg", ".jpg": ".jpeg", ".png": ".png", ".svg": ".svg",
> 	".tif": ".tiff", ".tiff": ".tiff", ".wmf": ".wmf", ".wmz": ".wmz",
> }
> ```

@WellOptimized   Thanks for the reply.   Is there any plan for this?

**Comment by xuri** [comment]
Thanks for your issue. If you insert WebP files into your Office app, the Office app will convert it to PNG format, so there is no plan to add support for this. Please convert the picture to a supported image format before inserting it. I've closed this. If you have any questions, please let me know, and you can reopen this anytime.
