### ISSUE TITLE
Number format compatibility

### ISSUE THREAD

**Issue by Yiling-J** [qax-os/excelize#1847]
Some of my tests failed using google sheets built-in format code, here are the test cases, the expected results are copy from google sheets but I also check Excel web, results are same:
```go
{"43543.5448726851", "General", "43543.54487"}, // actual  : "43543.5448726851"
{
	"43543.5448726851",
	`_("$"* #,##0.00_);_("$"* \(#,##0.00\);_("$"* "-"??_);_(@_)`,
	"$ 43,543.54 ",
}, // actual  : "$43,543.54"
```

**Comment by xuri** [comment]
Thanks for your issue. This issue has been resolved. Please upgrade the master branch code by `go get -u github.com/xuri/excelize/v2@master`, and these changes will be released in the next version. Note that the number format repeat control character (*) will be ignored in the formatted result, this behavior was the same when you copied cell value with the same number format in the spreadsheet apps, so the formatted result of number 43543.5448726851 should be " $43,543.54 ".
