### ISSUE TITLE
为什么sheet不支持区分大小写？( Why does sheet not support case sensitivity?)

### ISSUE THREAD

**Issue by 15083787153** [qax-os/excelize#1856]
目前看库内部使用的strings.EqualFold来比较两个sheet的名字，但是这个函数是不支持区分大小写的。

比如我想将默认的Sheet1改成sheet1，无法直接更改，只能改成另外一个名字，再将这个名字改为sheet1

Currently, the library uses strings.EqualFold internally to compare the names of two sheets, but this function does not support case sensitivity.

For example, I want to change the default Sheet1 to sheet1. I cannot change it directly. I can only change it to another name, and then change the name to sheet1.

**Comment by xuri** [comment]
Thanks for your issue. We need to using the `target == source` instead of `strings.EqualFold` function. Would you like to create a pull request to help us fix this problem?

**Comment by xuri** [comment]
Thanks for your issue. This issue has been fixed, please upgrade to the master branch by `go get -u github.com/xuri/excelize/v2@master`, and this patch will be released in the next version.

**Comment by 15083787153** [comment]
> Thanks for your issue. This issue has been fixed, please upgrade to the master branch by `go get -u github.com/xuri/excelize/v2@master`, and this patch will be released in the next version.谢谢你的问题。该问题已修复，请通过 `go get -u github.com/xuri/excelize/v2@master` 升级到 master 分支，该补丁将在下一版本发布。
感谢的你的快速回应，如果这是一个bug的话，影响的地方不仅仅是SetSheetName这个函数，还有DeleteSheet这个函数，内部使用的是GetSheetIndex，也许还有更多地方 = =
Thank you for your quick response. If this is a bug, it affects not only the SetSheetName function, but also the DeleteSheet function, which uses GetSheetIndex internally. Maybe there are more = =

**Comment by xuri** [comment]
Thanks for your feedback. The sheet name is not case-sensitive by default, you can't create two sheet names "Sheet1" and "sheet1" on a workbook, so I think just need to change the behavior of the `SetSheetName` function.
