### ISSUE TITLE
Generated Excel files lose content partially - Error on opening 

### ISSUE THREAD

**Issue by dkwstream** [qax-os/excelize#1859]
**Description**

**Steps to reproduce the issue:**
1. Create an Excel file with your Go application
2. Open this file with Excel (not LibreOffice) on Windows or on MacOS

**Describe the results you received:**
Excel triggers an error when you open the created file. A popup "Alert..." is displayed saying some content is not retrievable but Excel propose to repair the file and try to get as much content as it can.
When repair is done the Excel has lost a lot of formatting (no more colors in cells, ...) that was saved previously.
And this is systematic, always the same error with the same "Alert".

**Describe the results you expected:**
No error when opening the file.
An Excel file with all of its original formatting

**Output of `go version`:**

```text
go version go1.21.3 linux/amd64
```

**Excelize version or commit ID:**

```text
2.8.0
```

**Environment details (OS, Microsoft Excel™ version, physical, etc.):**
Windows and MacOS

**Comment by xuri** [comment]
Thanks for your issue. Please try to upgrade the master branch code of the Excelize library. If it still doesn't work, please provide a complete, standalone example program or reproducible demo.

**Comment by dkwstream** [comment]
I followed your previous recommendations and already upgraded the master branch code of Excelize. But the same still occurs.

**Comment by xuri** [comment]
Hi @dkwstream, @chinaDL. Could you show us a complete, standalone example program or reproducible demo? If you open an existing workbook, please provide the file attachment without confidential info.

**Comment by xuri** [comment]
Hi @dkwstream, @chinaDL. There are still not have enough info of code and attachments to reproduce this issue, so I'll close this issue, if you have any questions, please let me know to reopen this anytime.
