### ISSUE TITLE
Feature request: SetRowHeight for StreamWriter

### ISSUE THREAD

**Issue by wohenbushuang** [qax-os/excelize#1863]

**Comment by xuri** [comment]
Thanks for your issue. Please reference [the example in the documentation](https://pkg.go.dev/github.com/xuri/excelize/v2#File.NewStreamWriter), you can specify row height by the `Height` field in the `RowOpts` data type when writing data in stream:

```go
if err := sw.SetRow("A1",
    []interface{}{
        excelize.Cell{StyleID: styleID, Value: "Data"},
    },
    excelize.RowOpts{Height: 45, Hidden: false}); err != nil {
    fmt.Println(err)
    return
}
```

So, we needn't add this new export function. I'll close this issue. If you have any questions, please let me know, and you can reopen this anytime.
