### ISSUE TITLE
After adding and saving images in Excel by excelize, the GetPictureCells method cannot read any values

### ISSUE THREAD

**Issue by lukeyMing** [qax-os/excelize#1872]
In the code, first perform the operation of adding pictures to save to example.xlsx, then read example.xlsx, but what is read through f.GetSheetList is empty。 When I use the computer to open example.xlsx and save, I can retrieve the values by running the code again.

version:
- go: go1.21.1
- github.com/xuri/excelize/v2 version: v2.8.2
- OS:  macOs 、win11

```
package main

import (
    "fmt"
    "github.com/xuri/excelize/v2"
    _ "image/gif"
    _ "image/jpeg"
    _ "image/png"
)

func main() {
    writeExcel()
    readExcel()
}

func writeExcel() {
    f := excelize.NewFile()
    index, err := f.NewSheet("Sheet")
    if err != nil {
        panic(err)
    }
    f.SetActiveSheet(index)
    defer func() {
        if err := f.Close(); err != nil {
            panic(err)
        }
    }()

    if err := f.AddPicture("Sheet", "A1", "aa.png", &excelize.GraphicOptions{
        AutoFit: true,
    }); err != nil {
        panic(err)
    }

    if err := f.SaveAs("example.xlsx"); err != nil {
        fmt.Println(err)
    }
}

func readExcel() {
    f, err := excelize.OpenFile("./example.xlsx")
    if err != nil {
        panic(err)
    }
    defer func() {
        if err := f.Close(); err != nil {
            panic(err)
        }
    }()

    list := f.GetSheetList()
    imgs, err := f.GetPictureCells(list[0])
    if err != nil {
        panic(err)
    }
    fmt.Println(imgs)
}
```

**Comment by xuri** [comment]
Thanks for your issue. You insert the picture in the new worksheet named `Sheet`, but when you get the picture cells with the `GetPictureCells` function, the worksheet name is `Sheet1`, so the result of the function returns is in expectations.

**Comment by xuri** [comment]
Thanks for your issue. You insert the picture in the new worksheet named `Sheet`, but when you get the picture cells with the `GetPictureCells` function, the worksheet name is `Sheet1`, so the result of the function returns is in expectations. Please use the `list[1]` instead of `list[0]` in your code. I'll close this, if you have any questions, please let me know, and you can reopen this anytime.
