### ISSUE TITLE
调用RemoveCol并保存为xlsx后，文件无法正确打开

### ISSUE THREAD

**Issue by jianxinhou** [qax-os/excelize#1879]
**Description**

开发者你好，我在使用该库的过程中，发现具有以下特点的文件：

1. 经过WPS Office打开并保存；
2. 带有序列类型的数据验证；

在调用`(f *File) RemoveCol`方法后无法使用MS Office正常打开，如**Steps to reproduce the issue**所示。

我尝试定位了问题产生的原因，发现对于数据验证的下拉列表
MS Office会将其保存为：
![image](https://github.com/qax-os/excelize/assets/51222175/ddab5d1b-299f-4e31-b15a-eca20d4a412d)
而WPS Office则会保存为：
![image](https://github.com/qax-os/excelize/assets/51222175/556d85e5-f835-4493-9c32-bb01afbcf414)

因此，对于WPS Office生成的文件，在调用`(f *File) adjustDataValidations`时，对formula的转义会不正确，进而导致该问题。

我提了一个PR以修复该问题，经过测试修复后的代码能够使xlsx文件被正确打开。但不确定会不会有别的坑是我没注意到的，烦请帮忙review一下。

**Steps to reproduce the issue:**
1. 使用WPS Office打开带有下拉列表的xlsx文件并保存（MS Office生成的文件：[test.xlsx](https://github.com/qax-os/excelize/files/15011137/test.xlsx)；经过WPS Office打开后保存的文件：[test111.xlsx](https://github.com/qax-os/excelize/files/15010990/test111.xlsx)）
2. 执行以下代码生成一个新的xlsx文件：
```golang
func TestXxx(t *testing.T) {
	bs, err := os.ReadFile("./test111.xlsx")
	assert.Nil(t, err)
	file, err := OpenReader(bytes.NewReader(bs))
	assert.Nil(t, err)

	err = file.RemoveCol("Sheet2", "A")
	assert.Nil(t, err)

	buf, err := file.WriteToBuffer()
	assert.Nil(t, err)

	err = os.WriteFile("tttt.xlsx", buf.Bytes(), 0644)
	assert.Nil(t, err)
}
```
4. 使用MS office无法正确打开生成的xlsx：
![image](https://github.com/qax-os/excelize/assets/51222175/9336f62e-2d15-455e-8967-6f3030032f13)

5. 使用 WPS office 能够打开，但下拉框无法正确下拉
![image](https://github.com/qax-os/excelize/assets/51222175/c39068db-a6c0-478e-a688-0bbbe2be3f01)

**Output of `go version`:**
```text
go version go1.21.6 darwin/arm64
```

**Excelize version or commit ID:**

```text
3e636ae7b20285d4efb3d21bba0e1c165318f9f8
```

**Environment details (OS, Microsoft Excel™ version, physical, etc.):**
![image](https://github.com/qax-os/excelize/assets/51222175/20af043a-129d-40bf-aa5a-4ea47652a5fb)
![image](https://github.com/qax-os/excelize/assets/51222175/3dd51cdb-d05b-4360-b8d6-64fdf65f64b1)

```shell
GOARCH='arm64'
GOHOSTARCH='arm64'
GOHOSTOS='darwin'
CGO_CFLAGS='-O2 -g'
CGO_CPPFLAGS=''
CGO_CXXFLAGS='-O2 -g'
CGO_FFLAGS='-O2 -g'
CGO_LDFLAGS='-O2 -g'
PKG_CONFIG='pkg-config'
GOGCCFLAGS='-fPIC -arch arm64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -ffile-prefix-map=/var/folders/30/cmv9c_5j3mq_kthx63sb1t5c0000gn/T/go-build1186998755=/tmp/go-build -gno-record-gcc-switches -fno-common'
```

**Comment by xuri** [comment]
Thanks for your issue and pull request. The pull request has been merged, and this patch will be released in the next version.
