### ISSUE TITLE
GetPictures cannot obtain the height and width

### ISSUE THREAD

**Issue by walkrunning** [qax-os/excelize#1887]
GetPictures cannot obtain the height and width of an image. As a result, the image size cannot be determined when you copy an image from one sheet to another, and the image size is incorrect when AutoFit is enabled. Can you add the method of obtaining and setting the height and width of an image?

**Comment by xuri** [comment]
Thanks for your issue. I think this was duplicate with issue #1699 and pull request #1842 (related issue #1813). I closed this, and we track two problems mentioned in your issue into the above two issues.

**Comment by xuri** [comment]
Thanks for your issue. I think this was duplicate with issue #1699 and pull request #1842 (related issue #1813). I closed this, and we track two problems mentioned in your issue into the above two issues. If you have any questions, please let me know, and you can reopen this anytime.
