### ISSUE TITLE
GetPictureCells returns an empty result

### ISSUE THREAD

**Issue by GreenHatHG** [qax-os/excelize#1888]
**Description**

**Steps to reproduce the issue:**
```
	f, _ := excelize.OpenFile("2.xlsx")
	defer f.Close()
	cell, err := f.GetPictureCells("sheet")
	fmt.Println(cell, err)
	pics, err := f.GetPictures("sheet", "A2")
	fmt.Println(pics, err)
```

**Describe the results you received:**
The function GetPictureCells returns an empty result.
**Describe the results you expected:**
There is a picture at cell A2.
**Output of `go version`:**

```text
GOVERSION='go1.22.2'
```

**Excelize version or commit ID:**

```text
github.com/xuri/excelize/v2 v2.8.1
```

**Environment details (OS, Microsoft Excel™ version, physical, etc.):**
xlsx:
[2.xlsx](https://github.com/qax-os/excelize/files/15151494/2.xlsx)

![image](https://github.com/qax-os/excelize/assets/34258355/b71da290-6407-4075-a829-a87387ab7898)

**Comment by xuri** [comment]
Thanks for your issue. I have fixed this issue. Please upgrade to the master branch code by `go get github.com/xuri/excelize/v2@master`. This patch will be released in the next version.

**Comment by xuri** [comment]
Thanks for your issue. I have fixed this issue. Please upgrade to the master branch code by `go get -u github.com/xuri/excelize/v2@master`. This patch will be released in the next version.

**Comment by xuri** [comment]
Thanks for your issue. I have fixed this issue. Please upgrade to the master branch code by `go get -u github.com/xuri/excelize/v2@master`. This patch will be released in the next version.
