### ISSUE TITLE
File is missing media type

### ISSUE THREAD

**Issue by barlevd** [qax-os/excelize#1889]
**File are missing Excel media properties**

**Steps to reproduce the issue:**
1. Create a new file, or update and exiting one
2. Export the data and save to your local computer
3. In linux / Mac OS, with the file tool `file --mime-type file.xlsx`, it reports `file.xlsx: application/octet-stream`

**Describe the results you received:**

**Describe the results you expected:**
```
file --mime-type file.xlsx
file.xlsx: application/octet-stream
```

The output should be
```
file.xlsx: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet
```

**Output of `go version`:**

```text
go version go1.22.1 darwin/amd64
```

**Excelize version or commit ID:**

```text
(paste here)
```

**Environment details (OS, Microsoft Excel™ version, physical, etc.):**

The fix is to change the sort order of the output zip file.

**Comment by xuri** [comment]
Thanks for issue. I have merged the pull request. Please upgrade to the master branch code, and this patch will be released in the next version.

**Comment by barlevd** [comment]
Thank you for the fast follow up.
