### ISSUE TITLE
How to format numbers to Accounting format?

### ISSUE THREAD

**Issue by zhangcuiZC** [qax-os/excelize#189]
From issue #80 ,I know how to format numbers to currency , but how do I format them to Accounting format? Thanks!
![image](https://user-images.githubusercontent.com/22766013/36829746-98f11634-1d5b-11e8-9e55-8309d3a17e6e.png)
(pic from #80)

**Comment by xuri** [comment]
Thanks for your issue. This library not support set Accounting number format currently. I will consider to add this feature later and also welcome to contribute to this project.

**Comment by xuri** [comment]
Sorry for my so late reply. Excelize support set custom Accounting number format, for example:

```go
f := excelize.NewFile()
if err := f.SetCellValue("Sheet1", "A1", 100); err != nil {
    fmt.Println(err)
    return
}
fmtCode := `_("$"* #,##0.00_);_("$"* \(#,##0.00\);_("$"* "-"??_);_(@_)`
styleID, err := f.NewStyle(&excelize.Style{CustomNumFmt: &fmtCode})
if err != nil {
    fmt.Println(err)
    return
}
if err := f.SetCellStyle("Sheet1", "A1", "A1", styleID); err != nil {
    fmt.Println(err)
    return
}
// Save spreadsheet by the given path.
if err := f.SaveAs("Book1.xlsx"); err != nil {
    fmt.Println(err)
}
```

I'll close this issue, if you have any questions, please let me know.
