### ISSUE TITLE
Password protected sheet or range

### ISSUE THREAD

**Issue by FranLegon** [qax-os/excelize#1891]
Excel allows for the protection of sheets and even specific ranges using a password:
![image](https://github.com/qax-os/excelize/assets/6463827/c10b401a-e684-4c96-91e4-88bdd933497a)
![image](https://github.com/qax-os/excelize/assets/6463827/1225a99f-d5b6-443b-b45f-b1da558161a3)
Can this feature be implemented into excelize?
Thanks in advance!

Note: #199 refers to password-protecting an entire xlsx file and that issue has been solved.

**Comment by xuri** [comment]
Thanks for your issue. Please reference the documentation of the [`ProtectSheet`](https://xuri.me/excelize/en/sheet.html#ProtectSheet) function. For example:

```go
err := f.ProtectSheet("Sheet1", &excelize.SheetProtectionOptions{
    Password:            "password",
    SelectUnlockedCells: true,
    SelectLockedCells:   true,
})
```

Also reference the related issues #736 and #1511. I've closed this issue, if you have any questions, please let me know, and you can reopen this anytime.

**Comment by FranLegon** [comment]
Thanks a lot! Sorry about the unnecessary request. Great work btw.

**Comment by FranLegon** [comment]
Excuse me @xuri , I can't seem to find a way to set "Fomat Cells > Protection > Locked" to false for a specific cell or range. Is this supported?
