### ISSUE TITLE
Trigger formulas automatic calculation (excel中公式不自动计算需要打开excel点击后才能出值)

### ISSUE THREAD

**Issue by dannyzdy** [qax-os/excelize#1893]
**Description**
excel中公式不自动计算需要点击后才能出值

**Steps to reproduce the issue:**
1.原excel中C列=A列+B列 
2.使用程序往A列和B列赋值
3.打开excel C列公式无效

**Describe the results you received:**

**Describe the results you expected:**

**Output of `go version`: 1.20

```text
(paste your output here)
```

**Excelize version or commit ID:**

```text
(paste here)
```

**Environment details (OS, Microsoft Excel™ version, physical, etc.):**

**Comment by xuri** [comment]
Thanks for your issue. If you are reporting a new issue, make sure that we do not have any duplicates already exist. This was duplicated with issues #634, #1195, #1322, #1793 and #1841 use the [`UpdateLinkedValue`](https://pkg.go.dev/github.com/xuri/excelize/v2#File.UpdateLinkedValue) to clean up the cell calculation cache value before saving the spreadsheet. I've closed this issue. If you have any questions, please let me know, and you can reopen this anytime.
