### ISSUE TITLE
GetPictureCells()  Fail   

### ISSUE THREAD

**Issue by zhou7507** [qax-os/excelize#1894]
**Description**

I want to get all the coordinates of column B, but GetPictureCells() only returns one part

**Steps to reproduce the issue:**
``` 
func main() {
	f, err := excelize.OpenFile("./123.xlsx")
	if err != nil {
		fmt.Println(err)
	}
	axisList, err := f.GetPictureCells("Sheet1")
	if err != nil {
		fmt.Println(err)
	}
	fmt.Println(axisList)
}
```
![image](https://github.com/qax-os/excelize/assets/51078932/37de129a-ecff-4eee-8db2-e14afae27f71)

**Describe the results you received:**
[B1 B2 B7 B8 B9]

**Describe the results you expected:**
[B1 B2 B3 B4 B5 B6 B7 B8 B9]
**Output of `go version`:**

```text
 go1.20.3 windows/amd64
```

**Excelize version or commit ID:**

```text
[v2.8.1](https://github.com/xuri/excelize/releases/latest)
```

**Environment details (OS, Microsoft Excel™ version, physical, etc.):**

**Comment by xuri** [comment]
Thanks for your issue. If you open an existing workbook, please provide the file attachment without confidential info.

**Comment by xuri** [comment]
It seems still not have enough info of code and attachments to reproduce this issue, so I'll close this issue, if you have any questions, please let me know to reopen this anytime.

**Comment by zhou7507** [comment]
[123.xlsx](https://github.com/qax-os/excelize/files/15386553/123.xlsx)
this is file. 

Describe the results you received:
[B1 B2 B4 B7 B8 B9]

Describe the results you expected:
[B1 B2 B3 B4 B5 B6 B7 B8 B9 B10 B11 B12 B13 B14 B15]
