### ISSUE TITLE
Stream while appending to io.writer

### ISSUE THREAD

**Issue by XaichengLi** [qax-os/excelize#1897]
当前虽然提供了流式写入的方法，但没有提供流式构造xlsx的方法，必须要等需要写入的数据都写入File后，才能调用File的Write（）或WriteTo（）方法将流写入的指定的io.Writer，其实是假的流式。
应该提供一种方法，当向StreamWriter中写入数据后，File应该有方法能将刚写入的数据写入到指定的io.Writer中，而不是要等StreamWriter写入完后，调用Flush才能将File数据写入到指定的io.Writer中。

**Comment by xuri** [comment]
Thanks for your issue. If you are reporting a new issue, make sure that we do not have any duplicates already exist. This was duplicated with issue #753. So I've closed this issue. If you have any questions, please let me know, and you can reopen this anytime.

**Comment by XaichengLi** [comment]
ok，thanks！
