### ISSUE TITLE
Cloudflare Radar

### ISSUE THREAD

**Issue by toderitagcristian** [qax-os/excelize#1899]
Your website is blocked by Cloudflare services with Pornography tag.
I am using Warp zero trust by Cloudflare and the site is blocked by them.
You can see on Cloudflare Radar

https://radar.cloudflare.com/domains/domain/xuri.me

**Comment by xuri** [comment]
Thanks for your feedback. I have reported miscategorization to the Cloudflare team, now waiting for the review.

**Comment by toderitagcristian** [comment]
@xuri yeah ..I also submitted a report to remove that tag.

Just checked the webiste and cloudflare radare.
All good now

Closing issue
