### ISSUE TITLE
Added picture is taking the whole sheet/view

### ISSUE THREAD

**Issue by kirqe** [qax-os/excelize#1902]
**Description**

I generate an qr with https://github.com/yeqown/go-qrcode and place it into a cell. I have tried scaling options, changing format etc 
I'm getting the following result in the preview app. The whole screen is taken by the qr.

When I create a normal screenshot and place it into a cell there're no issues

Is this the bug of this package or go-qrcode?

**Steps to reproduce the issue:**
1. Generate a qr
```go	qrc, err := qrcode.New(q.str)



	f := fmt.Sprintf("%s/%s.png", directory, filename)

	w, _ := standard.New(f, standard.WithBuiltinImageEncoder(standard.PNG_FORMAT))


	if err = qrc.Save(w); err != nil {
		log.Fatal("error saving qr: %v", err)
	}
```

2. Try to add it to some sheet with the default examples
```go
		enable, disable := true, false
		if err := f.AddPicture("Sheet1", "A2", "sample3.png",
			&excelize.GraphicOptions{
				PrintObject:     &enable,
				LockAspectRatio: false,
				OffsetX:         15,
				OffsetY:         10,
				Locked:          &disable,
			}); err != nil {
			fmt.Println(err)
			return
		}
```

**Describe the results you received:**

I add only 1 picture!

<img width="578" alt="image" src="https://github.com/qax-os/excelize/assets/5272402/8fb444ad-8418-4c94-8194-a0ed3d542825">

-

<img height="200" alt="image" src="https://github.com/qax-os/excelize/assets/5272402/cb411d61-cf43-4381-b63e-01ee217e0e36">

**Output of `go version`:**

```text
go version go1.22.3 darwin/arm64
```

**Excelize version or commit ID:**

```text
	github.com/xuri/excelize/v2 v2.8.1
	github.com/yeqown/go-qrcode/v2 v2.2.4
	github.com/yeqown/go-qrcode/writer/standard v1.2.3
```

**Comment by xuri** [comment]
Thanks for your issue. Could you show us a complete, standalone example program or reproducible demo? If you open an existing workbook, please provide the file attachment without confidential info.

**Comment by kirqe** [comment]
@xuri I figured that the qr spread to the right because I updated widths after placing the image
The problem is till there for vertical axis 
https://github.com/kirqe/issue-demo

Sorry if the way I map rows and add styles is incorrect :D
