### ISSUE TITLE
concurrent use GetCellStyle got panic:index out of range

### ISSUE THREAD

**Issue by ShowerBandV** [qax-os/excelize#1903]
**Description**
hi，I want to parse an xlsx file with 3000 rows and 50 columns. If the parsing time for each cell is too long, I will concurrently retrieve the properties of each cell by column, such as value content, style, cell type, etc. Then I found that the GetCellStyle method will report the following error in concurrent situations.

```panic: runtime error: index out of range [8] with length 8
goroutine 29 [running]:
github.com/xuri/excelize/v2.(*File).GetCellStyle(0x5a39a0?, {0x50c341?, 0xc00009df90?}, {0xc0003fe436, 0x2})
	D:/Users/xxxx/go/pkg/mod/github.com/xuri/excelize/v2@v2.8.1/styles.go:2202 +0x295
```

here is my demo code and demo file
```
func TestGetStyle(t *testing.T) {file, err := excelize.OpenFile("1.xlsx")
	if err != nil {
		panic(err)
	}
	var wg sync.WaitGroup
        rows,column:=200,24
	for i := 0; i < column; i++ {
		wg.Add(1)
		go func(i int) {
			defer wg.Done()
			for row := 0; row < rows; row++ {
				axis := AxisEncode(i, row)
				style, err := file.GetCellStyle("Sheet1", axis)
				if err != nil {
					panic(err)
				}
				fmt.Println(style)
			}

		}(i)
	}
	wg.Wait()
}
func AxisEncode(colIndex, rowIndex int) string {
	if rowIndex > excelize.TotalRows {
		rowIndex = excelize.TotalRows - 1
	}
	if colIndex > excelize.MaxColumns {
		rowIndex = excelize.MaxColumns - 1
	}
	cellName, err := excelize.CoordinatesToCellName(colIndex+1, rowIndex+1)
	if err == nil {
		return cellName
	}
	return ""
}
```
[1.xlsx](https://github.com/qax-os/excelize/files/15412459/1.xlsx)

**Comment by xuri** [comment]
Thanks for your issue. All the concurrency safe functions have been noted in the comments. Currently, the `GetCellStyle` function doesn't support calling in concurrency. I'll certainly accept that patch if somebody did that.

**Comment by xuri** [comment]
I have made functions `GetCellStyle`, `SetRowVisible` and `GetCellStyle` concurrency safe, please upgrade to the master branch code, and this feature will be released in the next version.

**Comment by xuri** [comment]
I have made functions `GetCellStyle`, `SetRowVisible` and `GetRowVisible` concurrency safe, please upgrade to the master branch code, and this feature will be released in the next version.

**Comment by xuri** [comment]
I have made functions `GetCellStyle`, `SetRowVisible` and `GetRowVisible` concurrency safe, please upgrade to the master branch code, and this feature will be released in the next version.

**Comment by xuri** [comment]
I have made function `GetCellStyle` concurrency safe, please upgrade to the master branch code, and this feature will be released in the next version.
