### ISSUE TITLE
GetCellType for date format cell value returns as Unset

### ISSUE THREAD

**Issue by Bowrna** [qax-os/excelize#1932]
I have a excel sheet with cell value set as 2:31:30 AM in cell B13.

When I tried to invoke f.GetCellType('sheet 1', 'B13') returns 0. ( which implies the CellTypeUnset).
I tried to log the response and got this
```
Cell B3: Bowrna
Cell B3 Type: String
Cell C12: TRUE
Cell C12 Type: Bool
Cell B13: 2:31:30 am
Cell B13 Type: Unset
```
Expecting result for GetCellType: CellTypeDate 

Go version
go version go1.22.4 darwin/arm64

Excelize version
github.com/xuri/excelize/v2 v2.8.1

**Environment details (OS, Microsoft Excel™ version, physical, etc.):**
Apple M1 14.5, downloaded xlsx format from google sheets

**Comment by xuri** [comment]
Thanks for your issue. This duplicated with issues #1041 and #1375.

**Comment by xuri** [comment]
I've closed this. If you have any questions, please let me know, and reopen this anytime.
