### ISSUE TITLE
Make it possible to set xlsxWorkBookView.WindowWidth and WindowHeight

### ISSUE THREAD

**Issue by mbe81** [qax-os/excelize#1934]
When generating an Excel File I would like to control the window size when the Excel sheet is opened for the first time.

I think this is controlled with WorkBookView.WindowWidth and WindowHeight. Currently those fields are filled with defaults in template.go:

`const templateWorkbook = `<workbook xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships" xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006" mc:Ignorable="x15" xmlns:x15="http://schemas.microsoft.com/office/spreadsheetml/2010/11/main"><fileVersion appName="xl" lastEdited="6" lowestEdited="6" rupBuild="14420" /><workbookPr filterPrivacy="1" defaultThemeVersion="164011" /><bookViews><workbookView xWindow="0" yWindow="0" windowWidth="14805" windowHeight="8010" /></bookViews><sheets><sheet name="Sheet1" sheetId="1" r:id="rId1" /></sheets><calcPr calcId="122211" /></workbook>`
`

It would be nice if it is possible to override those defaults.

**Comment by xuri** [comment]
Yep, you can set windows height and width for default workbook view like this: 

```go
f := excelize.NewFile()
f.WorkBook.BookViews.WorkBookView[0].WindowHeight = 95790
f.WorkBook.BookViews.WorkBookView[0].WindowWidth = 95790
```

Note that the unit of measurement for `WindowHeight` and `WindowWidth` fields value is twips (One twip is 1⁄1440 inch, or 17.64μm).

**Comment by mbe81** [comment]
Oh, thanks! I looked into the documentation and I could not find anything about it. I also was looking to af function to call but this will work. Thanks for your great work!
