### ISSUE TITLE
How to clear all the Hyperlinks in the Workbook?

### ISSUE THREAD

**Issue by hpstep** [qax-os/excelize#1940]
I used SetCellHyperLink but it didn't work.
Do you have any solutions? Thank you~

**Comment by xuri** [comment]
Thanks for your issue. Which version of the Excelize library are you using? Could you show us a complete, standalone example program or reproducible demo? Could you follow [the issue template](https://raw.githubusercontent.com/xuri/excelize/master/.github/ISSUE_TEMPLATE/bug_report.md) to provide more details? If you open an existing workbook, please provide the file attachment without confidential info.

**Comment by hpstep** [comment]
if err := f.SetCellHyperLink("Sheet1", "A3",
	    "", "External", excelize.HyperlinkOpts{
	        Display: nil,
	        Tooltip: nil,
	    }); err != nil {
	    fmt.Println(err)
	}

我使用以上代码去修改超级链接。但是用Excel打开之后，鼠标指过去还是显示有超级链接。
我想知道是否有函数清除这些超级链接，类似在Excel中右键取消超级链接一样。

**Comment by xuri** [comment]
Could you **follow [the issue template](https://raw.githubusercontent.com/xuri/excelize/master/.github/ISSUE_TEMPLATE/bug_report.md)** to provide more details? If you open an existing workbook, please provide the file attachment without confidential info.

**Comment by xuri** [comment]
Thanks for your feedback. This library doesn't support remove hyperlink for a cell, I'll consider adding support for this.

**Comment by xuri** [comment]
I added remove hyperlink support for the `SetCellHyperLink` function. Please upgrade to the master branch code by `go get -u github.com/xuri/excelize/v2@master`, now you can remove hyperlink for cell `Sheet1!A2` like this:

```go
if err := f.SetCellHyperLink("Sheet1", "A2", "", "None"); err != nil {
    fmt.Println(err)
}
```

This feature will be released in the next version.

**Comment by hpstep** [comment]
谢谢您，我可以使用了~~
