### ISSUE TITLE
How to set the cross of XAxis and YAxis using AddChart function?

### ISSUE THREAD

**Issue by ffh-zhang** [qax-os/excelize#1944]
The chart generated:
![chart_1](https://github.com/qax-os/excelize/assets/152372621/3a54c8b4-b65c-4a85-a18e-5d6dc8cf2778)

The chart I want:
![chart_2](https://github.com/qax-os/excelize/assets/152372621/87b2ad17-75de-4622-8dee-bdd979ae197d)

**Comment by xuri** [comment]
Thanks for your issue. This library added new field `TickLabelPosition` in the `ChartAxis` option to support set label position of the chart, please upgrade to the master branch code by `go get -u github.com/xuri/excelize/v2@master`, and this feature will be released in the next version. Now you can set the label position of the horizontal axis like this:

```diff
&excelize.Chart{
    Type: excelize.Line,
    XAxis: excelize.ChartAxis{
+       TickLabelPosition: excelize.ChartTickLabelLow,
        ...
    },
    ...
}
```

**Comment by ffh-zhang** [comment]
Thanks for your prompt response! I have resolved the issue.
