### ISSUE TITLE
Can excelize support obtaining cross sheet data validation dropdown options？

### ISSUE THREAD

**Issue by ShowerBandV** [qax-os/excelize#1950]
**Description**
 When verifying the data as a sequence, it was found that if the data source was another sheet, Excelize did not parse it, and this value was retained in extLst,so that I use GetDataValidations() got nil.

[Book1.xlsx](https://github.com/user-attachments/files/16186162/Book1.xlsx)

**Comment by xuri** [comment]
Thanks for your issue. It seems this duplicated with #1835. This library already support get data validations which storage in the extension lists by PR #1834. Please upgrade to the master branch code, and this change will be released in the next version. I closed this issue, if you have any questions please let me know, and you can reopen this anytime.
