### ISSUE TITLE
Can't used negative numbers when I wanna generate a chart

### ISSUE THREAD

**Issue by dongjun111111** [qax-os/excelize#1967]
As the title .
I encountered a problem where negative numbers cannot be displayed properly when I want to generate a chart.

铁子，九命呀，我用负数无法正常显示在图表里，正数倒是没问题。我找半天没找到解决方法。

**Comment by dongjun111111** [comment]
![WX20240726-161042@2x](https://github.com/user-attachments/assets/d1fc413c-cdf6-4dd2-b49b-5179c60cb9db)

**Comment by xuri** [comment]
Thanks for your issue. Which version of the Excelize library are you using? Which kind of chart do you create? Could you show us a complete, standalone example program or reproducible demo? Could you follow [the issue template](https://raw.githubusercontent.com/xuri/excelize/master/.github/ISSUE_TEMPLATE/bug_report.md) to provide more details? If you open an existing workbook, please provide the file attachment without confidential info. Not that, PR #1953 fixed missing horizontal axis in scatter chart with negative values, if you are create scatter chart, please upgrade to the master branch by `go get -u github.com/xuri/excelize/v2@master`, and that patch will be releasee in the next version.

**Comment by xuri** [comment]
Thanks for your issue. This was duplicated with 1966, please DO NOT create duplicate issues. Which version of the Excelize library are you using? Which kind of chart do you create? Could you show us a complete, standalone example program or reproducible demo? Could you follow [the issue template](https://raw.githubusercontent.com/xuri/excelize/master/.github/ISSUE_TEMPLATE/bug_report.md) to provide more details? If you open an existing workbook, please provide the file attachment without confidential info. Not that, PR #1953 fixed missing horizontal axis in scatter chart with negative values, if you are create scatter chart, please upgrade to the master branch by `go get -u github.com/xuri/excelize/v2@master`, and that patch will be releasee in the next version.

**Comment by xuri** [comment]
Thanks for your issue. This was duplicated with #1966, please DO NOT create duplicate issues. Which version of the Excelize library are you using? Which kind of chart do you create? Could you show us a complete, standalone example program or reproducible demo? Could you follow [the issue template](https://raw.githubusercontent.com/xuri/excelize/master/.github/ISSUE_TEMPLATE/bug_report.md) to provide more details? If you open an existing workbook, please provide the file attachment without confidential info. Not that, PR #1953 fixed missing horizontal axis in scatter chart with negative values, if you are create scatter chart, please upgrade to the master branch by `go get -u github.com/xuri/excelize/v2@master`, and that patch will be releasee in the next version.

**Comment by dongjun111111** [comment]
I think  it's  a mistake,  actually it's my problem,definitely.   
When I  open this excel file first time , only one line shows up, it should be two lines.  Until I clicked on the number next to it, two lines appeared.

**Comment by dongjun111111** [comment]
@xuri   So  it's my  fault，thx again!😂

**Comment by xuri** [comment]
> When I open this excel file first time , only one line shows up, it should be two lines. Until I clicked on the number next to it, two lines appeared.

Sorry, I don't understand what exactly you mean. If this issue is invalid, please close this. Thanks.

**Comment by dongjun111111** [comment]
It's a mistake
