### ISSUE TITLE
GetConditionalFormats do not return cell only Conditional Formating

### ISSUE THREAD

**Issue by OlivierMary** [qax-os/excelize#1968]
**Description**

`GetConditionalFormats` do not return cell only Conditional Formating

In this case only the first conditional Formating is return:
![image](https://github.com/user-attachments/assets/f3402979-0533-4b2a-8e15-8fd085b8a1c4)

https://github.com/qax-os/excelize/blob/688808b2b4f7bb1f338991c810cd2ee6a7bb1451/styles.go#L3200
![image](https://github.com/user-attachments/assets/8567f2ce-23bf-4471-98a3-ecdd89afe1bf)

**Steps to reproduce the issue:**
1. Create a XLSX with a conditional formating on only a cell
2. Try to get ConditionalFormating
3. nothing returned

**Describe the results you received:**

no conditional format from `GetConditionalFormats`

**Describe the results you expected:**

all the conditional format

**Output of `go version`:**

```text
go version go1.22.2 linux/amd64
```

**Excelize version or commit ID:**

```text
	github.com/xuri/excelize/v2 v2.8.1
```

**Environment details (OS, Microsoft Excel™ version, physical, etc.):**
Linux,
LibreOffice

**Comment by xuri** [comment]
Thanks for your feedback. Could you show us a complete, standalone example program or reproducible demo? If you open an existing workbook, please provide the file attachment without confidential info.

**Comment by OlivierMary** [comment]
Hi there,

while producing example, that really happen if delete a line in the `*excelize.File`:

code:

```go
package main

import "github.com/xuri/excelize/v2"

func main() {
	exampleFile, err:=excelize.OpenFile(".../example.excelize.conditional.xlsx")
	if err != nil {
		panic(err)
	}
	sheetName:=exampleFile.GetSheetName(0)



	println("before removing line")
	conditionalFromats, err := exampleFile.GetConditionalFormats(sheetName)
	if err != nil {
		panic(err)
	}

	for rangeKey, conditionalFormat := range conditionalFromats {
		println(rangeKey)
		println(len(conditionalFormat))
	}


	exampleFile.RemoveRow(sheetName, 1)
	println("after removing line")

	conditionalFromats, err = exampleFile.GetConditionalFormats(sheetName)
	if err != nil {
		panic(err)
	}

	for rangeKey, conditionalFormat := range conditionalFromats {
		println(rangeKey)
		println(len(conditionalFormat))
	}

}

```

example file:
[example.excelize.conditional.xlsx](https://github.com/user-attachments/files/16393260/example.excelize.conditional.xlsx)

with this conditional:
![image](https://github.com/user-attachments/assets/a35f0a1b-3844-434a-b413-bd469d6245a6)


I remove line `1` so not line in the conditional format,
I tested removing line 8 (after conditional in case of shifting line in cause) it's the same.

Regards,

**Comment by xuri** [comment]
Thanks for your issue. This issue has been fixed, please upgrade to the master branch code by `go get -u github.com/xuri/excelize/v2@master`, and this patch will be released in the next version.
