### ISSUE TITLE
Limit the reading of GetRows and Rows

### ISSUE THREAD

**Issue by amandaokar** [qax-os/excelize#1972]
We have a use case to restrict the user from uploading huge file. As customers are uploading huge files with blank data. So we were using GetRows to calculate the row count. But **GetRows** is taking time to read the huge file and the omitting blank columns. Which is causing ngnix to timeout.

So can we get below two features which will limit the reading of file.
1. Get row and column counts efficiently.
2. We could limit the reading of file like below
    **1. GetRows(limitRows = maxDefault, limitColumns=maxDefault)
    2. GetColumns(limitRows = maxDefault, limitColumns=maxDefault)
    3. Rows(limitColumns=maxDefault)
    4. Columns(limitRows = maxDefault)**

**Comment by xuri** [comment]
Thanks for your issue. I think you can use the rows iterator to approach this. The [`Rows`](https://xuri.me/excelize/en/sheet.html#Rows) function reads worksheet as streaming, and you can stop iterating by custom row count controls. Related issues #845, #1096, #1220, #1356, #1558, and #1775.

**Comment by xuri** [comment]
I'll close this, if you have any questions, please let me know, and you can reopen this anytime.
