### ISSUE TITLE
how real stream work?

### ISSUE THREAD

**Issue by code-innovator-zyx** [qax-os/excelize#1973]
Is it possible to use SAX mode to process the file, so that we can realize the true meaning of streaming data, the current streaming once exported millions of data, the memory will be unimaginable. The real meaning of streaming is that no matter how much data you export, its memory is within your control!

**Comment by xuri** [comment]
Thanks for your issue. For stream mode read, the SAX (Simple API for XML) algorithm is already used for lexing and parsing internal part of workbook in the [rows iterator](https://pkg.go.dev/github.com/xuri/excelize/v2#File.Rows). The excelize also provides `UnzipSizeLimit` and `UnzipXMLSizeLimit` fields in the [`Options`](https://pkg.go.dev/github.com/xuri/excelize/v2#Options) for allow you control reading resourcee usage, you can get more details from the [documentation](https://xuri.me/excelize). For stream mode write, this library has its own implementation in [stream writer](https://pkg.go.dev/github.com/xuri/excelize/v2#File.NewStreamWriter) to generate workbook. Also reference issues #753, #1052, #1429, #1739, #1782.
