### ISSUE TITLE
Feature request for HTML, CSV and PDF format support

### ISSUE THREAD

**Issue by xiaozhaofu** [qax-os/excelize#1974]
**希望添加的功能**

**功能描述**
1.  添加excel文件另存为 html、csv、pdf 功能
2. 添加截图 excel 当前表格功能，获取截取的图片

感谢大佬！

**Comment by xuri** [comment]
Thanks for your issue. This was duplicated with #636, #1277, #1494 and #1871, This feature is out of scope for this library, so there is no plan to add this feature. Please find some conversion tools working with this library. I'll close this, if you have any questions, please let me know, and you can reopen this anytime.

**Comment by xuri** [comment]
Thanks for your issue. This was duplicated with #636, #1277, #1494 and #1871, This feature is out of scope for this library, so there is no plan to add this feature. Please find some conversion tools for working with this library. Note that, you can deal with CSV / TSV files with Go's [encoding/csv](https://pkg.go.dev/encoding/csv) library. I'll close this, if you have any questions, please let me know, and you can reopen this anytime.
