### ISSUE TITLE
Panic in GetBaseColor() 

### ISSUE THREAD

**Issue by fasdalf** [qax-os/excelize#1981]
**Description**

Alternative XLSX editors can make Excelize panic on styles loading.
![Screenshot from 2024-08-28 13-58-48](https://github.com/user-attachments/assets/913fb7ca-35ec-43eb-9b36-016bd0e0859a)

**Steps to reproduce the issue:**
1. Save file with some cell background and text colors changed in alternative client "R7 Office"
2. Call GetStyle(cellStyleID)
3. 

**Describe the results you received:**
Get "invalid memory address or nil pointer dereference" panic

**Describe the results you expected:**
code continues to modify and apply new style

**Output of `go version`:**

```text
go version go1.19.13 linux/amd64
```

**Excelize version or commit ID:**

```text
github.com/xuri/excelize/v2 v2.8.1
```

**Environment details (OS, Microsoft Excel™ version, physical, etc.):**

**Comment by xuri** [comment]
Thanks for your issue. This duplicated with #1963, this issue has been fixed in the master branch, please upgrade to the master branch code by `go get -u github.com/xuri/excelize/v2@master`, and this patch will be released in the next version.

**Comment by xuri** [comment]
I'll close this, if you have any questions, please let me know, and you can reopen this anytime.
