### ISSUE TITLE
line chart 

### ISSUE THREAD

**Issue by jingc1413** [qax-os/excelize#1982]
**Description**
你好，感谢这个库的相关功能，我已经查看文档使用，但是有一些问题咨询
1, chart line name 显示异常，我已经查看示例用法
https://xuri.me/excelize/zh-hans/chart/line.html
Name:       "Sheet1!$A$2" Name字段用的是表格中的数据，是不是这里不支持用字符串表示？
![image](https://github.com/user-attachments/assets/e6fa9de1-dcc6-46bf-baaf-9751f0d69aec)
生成的文档中是 系列1 系列2
![image](https://github.com/user-attachments/assets/43882028-eee2-4e36-be60-951d31af7326)
2，问题2 折线图如何显示平均值直线，由于平均值只有一个单元格，显示出来的是一个点，这种情况如何显示一条直线？
![image](https://github.com/user-attachments/assets/41ef9f6b-d9a3-401e-8b12-16076ae7d3f8)

**Steps to reproduce the issue:**
1.
2.
3.

**Describe the results you received:**

**Describe the results you expected:**

**Output of `go version`:**
1.23.0
```text
(paste your output here)
```

**Excelize version or commit ID:**

```text
(paste here)
```

**Environment details (OS, Microsoft Excel™ version, physical, etc.):**

**Comment by xuri** [comment]
About your first question, the `Name` field accepts cell reference but also series name, so you can set legend entities (series name) of chart by specified text value. For your second question, I don't understand what's you mean. As you know, the line chart requires a line requires two data points at least.
