### ISSUE TITLE
The positiveHandler method returns an incorrect value

### ISSUE THREAD

**Issue by ying32** [qax-os/excelize#1985]
**Description**
当单元格内容为手机号时且单元格式为常规类型，此时被粗暴的转为浮点类型，造成结果不正确。  
例如`13812349876`结果将会变成`1.381234988E+10`。  
此bug由`2024/3/19 8:58:52`提交所生产的，相关提交id[9e884c798be12fc1b2b985ed2db7f09f765f990a](https://github.com/qax-os/excelize/commit/9e884c798be12fc1b2b985ed2db7f09f765f990a)，如下图：

 
![image](https://github.com/user-attachments/assets/187163ab-31c7-4d84-92e5-42cae20507e9)

**Comment by xuri** [comment]
Thanks for your issue. Could you show us a complete, standalone example program or reproducible demo? If you open an existing workbook, please provide the file attachment without confidential info.

**Comment by ying32** [comment]
ok!
[sample.xlsx](https://github.com/user-attachments/files/16827649/sample.xlsx)

**Comment by xuri** [comment]
Thanks for your feedback. This issue has been fixed, please upgrade to the master branch code by `go get -u github.com/xuri/excelize/v2@master`.
