### ISSUE TITLE
Is there an option to read blank cells as "NaN" or at least as "" instead of just skipping them?

### ISSUE THREAD

**Issue by gmohmad** [qax-os/excelize#1990]
Hey! I would want to be able to set an option to have NaN or any other identifier for blank cells instead of skipping them, so i can have consistent rows of the same length. 
Is there any way to achieve this?

**Comment by xuri** [comment]
Thanks for your issue. This is similar with issues #721, #1016, #1135, #1245, #1452, #1557, #1597, #1616 and #1812. Please check the length of each cell before getting the element in the slice. The library should return each cell of row as is, and should not modify or fill any cells value, so please check the length of each row before your access cell in it. I have made a figure in issue #1245 to explain what kind of cells will be skipped for your reference.

**Comment by gmohmad** [comment]
I got it, we can just add the missing values if need after getting the rows with GetRows. But i would be cool if you added an option for that function to read the empty cells from the tail of the row too, because it is useful sometimes)
Thanks for the response!
