### ISSUE TITLE
Bulk Remove Rows doesn't work at high volume

### ISSUE THREAD

**Issue by BenReichwein** [qax-os/excelize#1991]
**Description**

When Removing Rows of XLSX file in bulk (over 50 lines) it does not do the correct number.
For example:
```
// File has 100 rows
for i := 0; i < len(rows); i++ {
	err = f.RemoveRow(f, sheet, i)
	if err != nil {
		fmt.Println(err)
		return err
	}
}
```
This results in the xlsx file still having 50 lines.

**Output of `go version`:**1.20

**Comment by xuri** [comment]
Thanks for your issue. Which version of the Excelize library are you using? Could you show us a complete, standalone example program or reproducible demo? Could you follow the issue template to provide more details? When you delete the first row 1, the second row will become the first row. So you need to remove like this:

```go
package main

import (
    "fmt"

    "github.com/xuri/excelize/v2"
)

func main() {
    f, err := excelize.OpenFile("Book1.xlsx")
    if err != nil {
        fmt.Println(err)
        return
    }
    defer func() {
        if err := f.Close(); err != nil {
            fmt.Println(err)
        }
    }()
    sheet := "Sheet1"
    rows, err := f.GetRows(sheet)
    if err != nil {
        fmt.Println(err)
        return
    }
    for i := 1; i <= len(rows); i++ {
        if err = f.RemoveRow(sheet, 1); err != nil {
            fmt.Println(err)
            return
        }
    }
    if err := f.Save(); err != nil {
        fmt.Println(err)
    }
}
```

I'll close this, if you have any questions, please let me know, and you can reopen this anytime.

**Comment by xuri** [comment]
Thanks for your issue. Which version of the Excelize library are you using? Could you show us a complete, standalone example program or reproducible demo? Could you follow the issue template to provide more details? When you delete the first row, the second row will become the first row. So, you need to remove like this:

```go
package main

import (
    "fmt"

    "github.com/xuri/excelize/v2"
)

func main() {
    f, err := excelize.OpenFile("Book1.xlsx")
    if err != nil {
        fmt.Println(err)
        return
    }
    defer func() {
        if err := f.Close(); err != nil {
            fmt.Println(err)
        }
    }()
    sheet := "Sheet1"
    rows, err := f.GetRows(sheet)
    if err != nil {
        fmt.Println(err)
        return
    }
    for i := 1; i <= len(rows); i++ {
        if err = f.RemoveRow(sheet, 1); err != nil {
            fmt.Println(err)
            return
        }
    }
    if err := f.Save(); err != nil {
        fmt.Println(err)
    }
}
```

I'll close this, if you have any questions, please let me know, and you can reopen this anytime.

**Comment by BenReichwein** [comment]
@xuri thank you for your response. Sorry for not completing the template.

Excelize version: v2.8.1

Code snippet:
```go
func Truncate(filepath string) (err error) {
	f, err := excelize.OpenFile(filepath)
	if err != nil {
		fmt.Println(err)
		return
	}
	defer func() {
		// Close the spreadsheet.
		if err := f.Close(); err != nil {
			fmt.Println(err)
		}
	}()
	sheets := f.GetSheetMap()
	for _, sheet := range sheets {
		// Loop over sheet rows
		rows, err := f.GetRows(sheet)
		if err != nil {
			fmt.Println(err)
			return err
		}
		// Exclude all rows except the first 100
		for i := 100; i < len(rows); i++ {
			err = ExcludeRow(f, sheet, i)
			if err != nil {
				fmt.Println(err)
				return err
			}
		}
	}

	// Save spreadsheet by the given path.
	err = f.SaveAs(filepath)
	if err != nil {
		fmt.Println(err)
		return err
	}
```

What i am trying to accomplish with this code is truncating the xlsx file to preview to the user, so i only want to show the first 50 lines and remove the rest. Ive tried `f.SetSheetDimension()` but that doesnt remove any data. Do you know of any other solutions to truncate and xlsx file?

**Comment by BenReichwein** [comment]
@xuri
