### ISSUE TITLE
How to specify the line and use rows iterator read down from that line

### ISSUE THREAD

**Issue by ccaiy9** [qax-os/excelize#1995]
**Description**
e.g.
I want to skip the first 100 lines and start reading from line 101 by rows iterator

**Describe the results you received:**

**Describe the results you expected:**

**Output of `go version`:**

```text
1.19.13
```

**Excelize version or commit ID:**

```text
v2.8.0
```

**Environment details (OS, Microsoft Excel™ version, physical, etc.):**

**Comment by xuri** [comment]
Thanks for your issue. Here is an example of how to read cell value after row 100 by Excelize for your reference.


```go
package main

import (
    "fmt"

    "github.com/xuri/excelize/v2"
)

func main() {
    f, err := excelize.OpenFile("Book1.xlsx")
    if err != nil {
        fmt.Println(err)
        return
    }
    defer func() {
        if err := f.Close(); err != nil {
            fmt.Println(err)
        }
    }()
    rows, err := f.Rows("Sheet1")
    if err != nil {
        fmt.Println(err)
        return
    }
    r := 0
    for rows.Next() {
        if r++; r <= 100 { // Skip top 100 rows
            continue
        }
        cells, err := rows.Columns()
        if err != nil {
            fmt.Println(err)
            return
        }
        for _, cell := range cells {
            fmt.Print(cell, "\t")
        }
        fmt.Println()
    }
}
```

Please also reference issue #146 and #515. I'll close this, if you have any questions, please let me know, and you can reopen this anytime.
