### ISSUE TITLE
BUG: GetRows

### ISSUE THREAD

**Issue by kaylee595** [qax-os/excelize#1997]
```golang
// not work
func getFileData(filename string) ([][]string, error) {
	f, err := excelize.OpenFile(filename)
	if err != nil {
		return nil, tracerr.Wrap(err)
	}
	defer f.Close()
	return f.GetRows("sheet0")
}
```
```golang
// Successful
func getFileData(filename string) ([][]string, error) {
	f, err := excelize.OpenFile(filename)
	if err != nil {
		return nil, tracerr.Wrap(err)
	}
        _, _ = f.GetCellValue("sheet0", "A1")
	defer f.Close()
	return f.GetRows("sheet0")
}
```

I don't know why I need to get some data first before getting all the data

**Comment by chengxilo** [comment]
I tried the function which was commented not working.
```go
package main

import (
    "fmt"
    "github.com/xuri/excelize/v2"
    "log"
)

func main() {
    f, err := getFileData("Book1.xlsx")
    if err != nil {
        log.Fatal(err)
    }
    fmt.Println(f)
}

// not work
func getFileData(filename string) ([][]string, error) {
    f, err := excelize.OpenFile(filename)
    if err != nil {
        return nil, err
    }
    defer f.Close()
    return f.GetRows("sheet0")
}
```
And it actually worked. Maybe more information is needed.
![image](https://github.com/user-attachments/assets/b6aacca8-87f4-4214-ad06-fcc5dee604d2)

**Comment by xuri** [comment]
Thanks for your issue. Which version of this library are you using? What's your received and expected? Could you follow the issue template and show us a complete, standalone example program or reproducible demo? If you open an existing workbook, please provide the file attachment without confidential info.

**Comment by kaylee595** [comment]
Sorry, it's my own fault. My original code was like this:
```golang
func getFileData(filename string) ([][]string, error) {
	f, err := excelize.OpenFile(filename)
	if err != nil {
		return nil, tracerr.Wrap(err)
	}
	defer ignoreError(f.Close()) // Since the f.Close() function is passed as an argument, it is executed first without being noticed.
	return f.GetRows("sheet0")
}

func ignoreError(errs ...error) {
	for _, err := range errs {
		if err != nil {
			panic(err)
		}
	}
}
```
I was amused by my own stupidity.
When I posted the issue, I removed this step to make it look simple. Later I found that it was fine after removing it. Then I realized that it was my own problem. Thank you very much for the replies from excelize, chengxilo and xuri.
