### ISSUE TITLE
Save function excessive memory

### ISSUE THREAD

**Issue by shitingbao** [qax-os/excelize#2003]
my code example
```
func exportNotifyLinkStatis(req *ExportTask)  error {
	param := &statis.LinkDataListReq{}
	f := excelize.NewFile()
	defer f.Close()

	cols := []string{"tes1", "test2", "test3", ...........}
	if err := f.SetSheetRow("Sheet1", "A1", &cols); err != nil {
		return err
	}

// some datas
	for i := 0; (i * 500) < totalNum; i++ {
		data := []any{}
		// 行数据对应标题
		data = append(data, da1,da2............)// some data
		if err := f.SetSheetRow("Sheet1", fmt.Sprintf("A%d", idx+2+500*i), &data); err != nil {
			return err
		}
	}

	if err := f.SaveAs(filePath); err != nil {
		return err
	}

	return filePath, nil
}


```
Large memory consumption occurs at the end of the write，then，I see “SaveAs”，
```
	file, err := os.OpenFile(filepath.Clean(name), os.O_WRONLY|os.O_TRUNC|os.O_CREATE, os.ModePerm)
	if err != nil {
		return err
	}
	defer file.Close()
	return f.Write(file, opts...)
```
It writes the entire file here. Is it related to this? Why is it not a stream?

**Comment by xuri** [comment]
Thanks for your issue. Which version of the library was your using? Which version of Go language was your using? How many cells did you write, and how much memory cost? Could you follow the issue template when you create an issue to show us a standalone reproducible demo and more details? This issue also was similar with #876. The function [`StreamWriter`](https://xuri.me/excelize/en/stream.html) for generating a worksheet with massive amounts of data. Please also reference issues #753 and #1052. With the spreadsheet [specification](https://www.ecma-international.org/publications-and-standards/standards/ecma-376/) limit (OPC part), the workbook serialization should be waiting all worksheet has been ready. I will close this, if you have any questions, please me know and reopen this anytime.
