### ISSUE TITLE
time.Duration > 24 hours not working as expected

### ISSUE THREAD

**Issue by nielskrijger** [qax-os/excelize#2004]
**Description**

`time.Duration` > 24 hours is formatted differently than `time.Duration` < 24.

**Steps to reproduce the issue:**
1. See playground: https://go.dev/play/p/NNpUJCVFju8

**Describe the results you received:**

A1 is as expected (duration < 24 hours):

<img width="278" alt="Screenshot 2024-10-02 at 09 45 50" src="https://github.com/user-attachments/assets/30ae535f-dcd6-4b2b-9d4f-a4443afedb46">

A2 is not usable (duration > 24 hours):

<img width="338" alt="Screenshot 2024-10-02 at 09 45 53" src="https://github.com/user-attachments/assets/ade97320-c578-47df-81ca-34e87842d700">

**Describe the results you expected:**

A2 containing `24:51:44` (or anything equivalent in Excel that works as a duration).

In our use case we select the column and have Excel "Sum" the durations to a total. This works fine if the individual cells are formatted as `21:33:55` as long as each individual value doesn't go beyond 24 hours. Any value beyond 24 hours breaks this.

**Output of `go version`:**

```text
go1.22.3 darwin/amd64
```

**Excelize version or commit ID:**

```text
v2.8.1
```

**Environment details (OS, Microsoft Excel™ version, physical, etc.):**

Mac OS. Excel Version 16.89.1 (24091630).

**Comment by xuri** [comment]
Thanks for your issue. I have added support for applying number format for time and duration cell value. Please upgrade the master branch code by `go get -u github.com/xuri/excelize/v2@master`, and this feature will be released in the next version.
