### ISSUE TITLE
Can't install Excelize

### ISSUE THREAD

**Issue by LionelPerret** [qax-os/excelize#2006]
**Description**

I'm working in the VS Code Terminal on Windows and I'm trying to install excelize

go get github.com/xuri/excelize
     doesn't work ('go get' is no longer supported outside a module.) and I need to do :
          go install github.com/xuri/excelize@latest
     instead

go install github.com/xuri/excelize@latest
          I have the issue :
version constraints conflict:
github.com/360EntSecGroup-Skylar/excelize/v2@v2.8.1: parsing go.mod:
module declares its path as: github.com/xuri/excelize/v2
but was required as: github.com/360EntSecGroup-Skylar/excelize/v2

Thanks for your help!
**Describe the results you received:**
Error
**Describe the results you expected:**
Install ok
**Output of `go version`:**
go: github.com/xuri/excelize@latest: version constraints conflict:
        github.com/xuri/excelize@v1.4.1: parsing go.mod:
        module declares its path as: github.com/360EntSecGroup-Skylar/excelize
                but was required as: github.com/xuri/excelize
```text
go: github.com/xuri/excelize@latest: version constraints conflict:
        github.com/xuri/excelize@v1.4.1: parsing go.mod:
        module declares its path as: github.com/360EntSecGroup-Skylar/excelize
                but was required as: github.com/xuri/excelize
```

**Excelize version or commit ID:**

```text
(paste here)
```

**Environment details (OS, Microsoft Excel™ version, physical, etc.):**

**Comment by xuri** [comment]
Thanks for your issue. Please read the README or documentation. Install lasted version by the following command:

```bash
go get github.com/xuri/excelize/v2
```

**Comment by xuri** [comment]
I closed this, if you have any questions, please let me know, and you can reopen this anytime.

**Comment by LionelPerret** [comment]
go get github.com/xuri/excelize/v2 doesn't work on VS Code : 
       'go get' is no longer supported outside a module.
        To build and install a command, use 'go install' with a version,
        like 'go install example.com/cmd@latest'
        
 That is why I used : go install github.com/xuri/excelize/v2
        'go install' requires a version when current directory is not in a module
        Try 'go install github.com/xuri/excelize/v2@latest' to install the latest version
        
 So I tried : go install github.com/xuri/excelize/v2@latest
   go: downloading github.com/mohae/deepcopy v0.0.0-20170929034955-c48cc78d4826
  go: downloading github.com/richardlehane/mscfb v1.0.4
  go: downloading github.com/xuri/efp v0.0.0-20231025114914-d1ff6096ae53
  go: downloading github.com/xuri/nfp v0.0.0-20230919160717-d98342af3f05
  go: downloading golang.org/x/crypto v0.19.0
  go: downloading golang.org/x/net v0.21.0
  go: downloading golang.org/x/text v0.14.0
  go: downloading github.com/richardlehane/msoleps v1.0.3
  **package github.com/xuri/excelize/v2 is not a main package**

Thanks !

**Comment by xuri** [comment]
Please reference [the documentation](https://xuri.me/excelize/en), there is a video tutorial in the documentation for setting up Excelize project in the Visual Studio Code.

**Comment by LionelPerret** [comment]
Ok Thank you very much !
     go mod tidy
solved it !
