### ISSUE TITLE
Unable to create a Time column (hh:mm am) 

### ISSUE THREAD

**Issue by ollieparsley** [qax-os/excelize#2010]
Hello, the library is great and worked for 99% of what I need to do :). I am stuck though. I'm successfully setting cell values with correct data types, such as `time.Time` for dates, and then setting a style to format the date how I'd like it presented to the user. What I can't appear to do though is set just the time in a field. I have no date information, just a time of date in `hh:mm:ss am` format. There isn't a way (that I've found) to set the cell value to just the time and have Excel recognise it as a time, it just gets recognised as a string and treated as such.

Am I missing something? Thank you in advance!

**Comment by xuri** [comment]
Thanks for your issue. What's your received and expected? Could you follow the issue template and show us a complete, standalone example program or reproducible demo?
