### ISSUE TITLE
Field parsing broken from 2.8.1 -> 2.9.0

### ISSUE THREAD

**Issue by sblackstone** [qax-os/excelize#2011]
**Description**

This spreadsheet has a custom number format:

[$-en-US,1]$#,##0.00;($#,##0.00)

with field values like $1.23

v2.8.1 is able to parse this.

v2.9.0 returns an error unable to parse field '$1.23'

**Output of `go version`:**

go version go1.22.5 darwin/arm64

**Excelize version or commit ID:**

2.8.1 vs 2.9.0

**Environment details (OS, Microsoft Excel™ version, physical, etc.):**
Occurs on mac as well as CI/CD debian.

**Comment by xuri** [comment]
Thanks for your issue. I think v2.8.1 also doesn't support this number format code. Could you show us a complete, standalone example program or reproducible demo? If you open an existing workbook, please provide the file attachment without confidential info.

**Comment by sblackstone** [comment]
I ran some more tests, the difference is actually whether or not Excelize returns a `$` or not:

v2.9.0:
```
([][]string) (len=2 cap=64) {
 ([]string) <nil>,
 ([]string) (len=1 cap=1) {
  (string) (len=7) "$123.45"
 }
}
```

v2.8.1:
```
([][]string) (len=2 cap=271) {
 ([]string) <nil>,
 ([]string) (len=1 cap=1) {
  (string) (len=6) "123.45"
 }
}
```
[excelize-example.xlsx](https://github.com/user-attachments/files/17464993/excelize-example.xlsx)

**Comment by sblackstone** [comment]
The above was generated with:
```
	file, _ := excelize.OpenFile("./excelize-example.xlsx")
	sheets := file.GetSheetList()
	rows, _ := file.GetRows(sheets[0])
	spew.Dump(rows)
```

**Comment by xuri** [comment]
Thanks for your feedback. The cell value read by v2.9.0 is correct (the cell value should be "$123.45" not "123.45"), which is same as your see in the Excel application, so I think this issue needn't be fixed. If you want to get raw cell value without applying number format style, you can specify `RawCellValue` option, for example:

```go
file.GetRows(sheets[0], excelize.Options{RawCellValue: true})
```

**Comment by sblackstone** [comment]
Works for me, thanks.
