### ISSUE TITLE
SetCellValue changes background color of a Cell to White when writing a time.Time value into a preformatted Table

### ISSUE THREAD

**Issue by sonic-martin** [qax-os/excelize#2014]
**Description**

When writing date values to a table in a worksheet using predefined table format/style, then excelize sets a white background color.

It seems to be a new bug with excelize2.9.0, because in 2.8.1 and before its working.

**Steps to reproduce the issue:**

1. Prepare an excel file with a formatted table, using a predefined table format/style
2. `OpenReader` that file
3. Write a `String` value and a `time.Time` using `SetCellValue`
4. `SaveAs` that file

See a full reproducer here: https://github.com/sonic-martin/excelize-backgroundcolor-reproducer

**Describe the results you received:**

The cell with the Date value has a white background color.

![screenshot-2 9 0](https://github.com/user-attachments/assets/3853ede4-65d3-42ff-8764-a69e2cdb4b1e)

(Screenshot with an excel file created with Excelize 2.9.0)

**Describe the results you expected:**

Both, the cell with the String value and with the Date value, following the predefined table format/style from the template excel file.

![screenshot-2 8 1](https://github.com/user-attachments/assets/e3bf76fd-b450-452a-91ae-5e750e405cfd)

(Screenshot with an excel file created with Excelize 2.8.1)

**Output of `go version`:**

```text
go version go1.23.2 linux/amd64
```

**Excelize version or commit ID:**

```text
2.9.0
```

**Environment details (OS, Microsoft Excel™ version, physical, etc.):**

Ubuntu in WSL2

**Further remark**

Is this maybe related to the code changes for fixing https://github.com/qax-os/excelize/issues/2004?

**Comment by xuri** [comment]
Thanks for your feedback. I fixed this, please upgrade to the master branch code by `go get -u github.com/xuri/excelize/v2@master`, and this patch will be released in the next version.

**Comment by xuri** [comment]
Thanks for your feedback. I fixed this, please upgrade to the master branch code by `go get -u github.com/xuri/excelize/v2@master`, and this patch will be released in the next version.

**Comment by sonic-martin** [comment]
Hey, is it planned to have a new release soon? So far I pinned my dependency for production to `2.8.1`.

**Comment by xuri** [comment]
Next version will be released in 2025, before that you could be to use the code on the master branch version, with the Go module to lock the version.

**Comment by xuri** [comment]
The next version 2.9.1 will be released on May 15th, 2025.
