### ISSUE TITLE
Why do we need checkRow function?

### ISSUE THREAD

**Issue by huantt** [qax-os/excelize#2017]
**Description**

This function consumes too much memory, and I don't see the benefit of filling gap columns for rows. 

Let's examine the GetColumnCell function:

```go
for colIdx := range rowData.C {
			colData := &rowData.C[colIdx]
			if cell != colData.R {
				continue
			}
			val, ok, err := fn(ws, colData)
			if err != nil {
				return "", err
			}
			if ok {
				return val, nil
			}
		}
```

You are looping through the columns and checking the cell name to return a value. 
Therefore, what is the purpose of filling gap columns here?

**Comment by huantt** [comment]
<img width="655" alt="image" src="https://github.com/user-attachments/assets/5a5c4a5c-8ac6-4183-b9ff-813f21173497">

Oh, we will encounter a problem when writing to the cell. 
The `prepareCell` function will return the wrong cell. 
Can we update the logic of the prepareCell function to use a loop to find the cell instead of accessing it directly by index?

**Comment by xuri** [comment]
The library pre-allocates some consecutive cells for random set cell value. Please reference the documentation to using stream mode API (stream writer for generate worksheet, and rows iterator for reading worksheet) to reduce memory usage.

**Comment by xuri** [comment]
The library pre-allocates some consecutive cells for set cell value randomly. Please reference the documentation to using stream mode API (stream writer for generate worksheet, and rows iterator for reading worksheet) to reduce memory usage.

**Comment by huantt** [comment]
I tried using a Stream Reader (rows) and StreamW riter, but since the Stream Reader only returns an array of string values (without cell style), I cannot use them to maintain the style when writing.

**Comment by xuri** [comment]
There are no plan to change for the prepareCell recently, I dont think that use a loop to find the cell instead of accessing it directly by index can be reduce memory usage without much more time cost, if you'd like to create a pull request for this to improvement performance, that's would be great.

**Comment by xuri** [comment]
I closed this, if you have another question, please let me know, and we can reopen this anytime.
