### ISSUE TITLE
Panic in getFromStringItem

### ISSUE THREAD

**Issue by martinmr** [qax-os/excelize#2019]
In version v2.9.0 and earlier there's a panic in this function. The exact line and panic is in the comment below.

```
// getFromStringItem build shared string item offset list from system temporary
// file at one time, and return value by given to string index.
func (f *File) getFromStringItem(index int) string {
	if f.sharedStringTemp != nil {
		if len(f.sharedStringItem) <= index {
			return strconv.Itoa(index)
		}
		offsetRange := f.sharedStringItem[index]
		buf := make([]byte, offsetRange[1]-offsetRange[0]) // panic: runtime error: index out of range [1] with length 0
		if _, err := f.sharedStringTemp.ReadAt(buf, int64(offsetRange[0])); err != nil {
			return strconv.Itoa(index)
		}
		return string(buf)
	}
```

I am not really familiar with this so I don't know what the fix has to be.

**Comment by xuri** [comment]
Thanks for your issue. Could you show us a complete, standalone example program or reproducible demo? If you open an existing workbook, please provide the file attachment without confidential info.

**Comment by xuri** [comment]
It seems still not have enough info of code and attachments to reproduce this issue, so I'll close this issue, if you have any questions, please let me know to reopen this anytime.
