### ISSUE TITLE
导入25行数据的excel文件，非常慢，内存也会飘升

### ISSUE THREAD

**Issue by pihc** [qax-os/excelize#2021]
**Description**
导入25行数据的excel文件，不知道怎么回事非常慢

**Steps to reproduce the issue:**
1.
2.
3.

**Describe the results you received:**
very slow, 40 second

**Describe the results you expected:**
 fast

**Output of `go version`:**
go version go1.19.3 darwin/amd64

```text
(paste your output here)
```
![image](https://github.com/user-attachments/assets/8acf5624-2a0a-4446-b49f-0f8b936525fe)
我尝试修改了一下源码，GetRows 这个方法是变快了很多
![image](https://github.com/user-attachments/assets/987c763d-7e89-484e-9acf-168fa1ce8977)
但是调用 GetPictures 方法时，又变慢了很多 大概20s左右，但是只是循环的第一次读取慢 ，后面就变快很多
这个文件有13M,我尝试着把excel里面的内容拷贝到一个空的excel文件中，这时excel文件大小就变成了3M,上传文件就变快了很多。
这个excel是一个模版，大都是在wps编辑的，是不是每次在上面改东西导致excel里多了很多“缓存”啥的，挺头疼的，服务器因为这个问题经常挂，内存和cpu双双飙升。我升级到了最新版v2.9.0发现还是不行。
**Excelize version or commit ID:**

```text
(paste here)
```

**Environment details (OS, Microsoft Excel™ version, physical, etc.):**

**Comment by xuri** [comment]
It seems still not have enough info of code and attachments to reproduce this issue, so I'll close this issue, if you have any questions, please let me know to reopen this anytime.

**Comment by xuri** [comment]
Not have enough info of code and attachments to reproduce this issue, so I closed this issue, if you have any questions, please let me know to reopen this anytime. Please follow the issue template and show us a complete, standalone example program or reproducible demo. If you open an existing workbook, please provide the file attachment without confidential info.

**Comment by xuri** [comment]
There is not enough info of code and attachments to reproduce this issue, so I closed this issue, if you have any questions, please let me know to reopen this anytime.  I suspect this duplicated with issues #1737 and #1848. Please follow the issue template and show us a complete, standalone example program or reproducible demo. If you open an existing workbook, please provide the file attachment without confidential info.
