### ISSUE TITLE
Why is the Excel export speed slow after setting custom number formats

### ISSUE THREAD

**Issue by YiTianChiSiDun1** [qax-os/excelize#2026]
**Description**
Why is the Excel export speed slow after setting custom number formats?

In a 200*300 Excel report. The logic previously was to not fill cells with data that was 0, but the new requirement is to fill and display cells with 0 data as invisible. Upon inquiry, I found that the following method can be used to set the custom number format:
`style := excelize.Style{}
customerNumStyle := "0;-0;;@"
style.CustomNumFmt = &customerNumStyle
`
However, after setting the style, I found that the export speed of Excel has become very slow. Tasks that used to be completed in less than a second now might require waiting for three to four seconds. Is there a way to solve this?

**Steps to reproduce the issue:**
1.
2.
3.

**Describe the results you received:**

**Describe the results you expected:**

**Output of `go version`:**

```text
1.22.5
```

**Excelize version or commit ID:**

```text
v2.8.1
```

**Environment details (OS, Microsoft Excel™ version, physical, etc.):**
Windows11、Microsoft Excel 2019

**Comment by YiTianChiSiDun1** [comment]
Actual measurement shows that setting the style to something else will not affect the performance much, but setting it to `0;-0;;@` will greatly affect the performance.

**Comment by xuri** [comment]
There is not enough info of code and attachments to reproduce this issue. Could you follow the issue template to show us a complete, standalone example program or reproducible demo? If you open an existing workbook, please provide the file attachment without confidential info.

**Comment by xuri** [comment]
It seems still not have enough info of code and attachments to reproduce this issue, so I'll close this issue, if you have any questions, please let me know to reopen this anytime. Please also reference [the example of creating a HTTP server to handle upload template](https://xuri.me/excelize/en/workbook.html#OpenReader) in the documentation.
