### ISSUE TITLE
Use a faster deepcopy library

### ISSUE THREAD

**Issue by Juneezee** [qax-os/excelize#2029]
**Description**

We currently use the deepcopy function from https://github.com/mohae/deepcopy to duplicate columns, rows, and worksheets, as shown in the following references:

https://github.com/qax-os/excelize/blob/5f446f25f0a09de04d6b8b93b4dd151bdac75bd6/col.go#L536
https://github.com/qax-os/excelize/blob/5f446f25f0a09de04d6b8b93b4dd151bdac75bd6/col.go#L554
https://github.com/qax-os/excelize/blob/5f446f25f0a09de04d6b8b93b4dd151bdac75bd6/rows.go#L656
https://github.com/qax-os/excelize/blob/5f446f25f0a09de04d6b8b93b4dd151bdac75bd6/rows.go#L732
https://github.com/qax-os/excelize/blob/5f446f25f0a09de04d6b8b93b4dd151bdac75bd6/rows.go#L762
https://github.com/qax-os/excelize/blob/5f446f25f0a09de04d6b8b93b4dd151bdac75bd6/sheet.go#L127
https://github.com/qax-os/excelize/blob/5f446f25f0a09de04d6b8b93b4dd151bdac75bd6/sheet.go#L753

The https://github.com/mohae/deepcopy library has not been updated in 7 years (last commit was September 2017). We should opt for a newer deep copy library.

I suggest we switch to https://github.com/tiendc/go-deepcopy. The [benchmarks](https://github.com/tiendc/go-deepcopy?tab=readme-ov-file#benchmarks) indicate that it is faster than other popular deep copy libraries.

**Comment by xuri** [comment]
Thanks for your suggestion. I tested that library with cases [in this article](https://xuri.me/2018/06/17/deep-copy-object-with-reflecting-or-gob-in-go.html), got panic on benchmark:

```text
panic: reflect: call of reflect.Value.Set on zero Value

goroutine 42 [running]:
reflect.flag.mustBeExportedSlow(0x7826ed?)
        $GOROOT/go1.23.1/src/reflect/value.go:232 +0xb6
reflect.flag.mustBeExported(...)
        $GOROOT/go1.23.1/src/reflect/value.go:226
reflect.Value.Set({0x7a3580?, 0xc0000027f8?, 0x0?}, {0x0?, 0x0?, 0x7a3580?})
        $GOROOT/go1.23.1/src/reflect/value.go:2308 +0x9a
github.com/barkimedes/go-deepcopy._struct({0x7e2100, 0xc0000022c8}, 0xc000020630)
        $GOPATH/pkg/mod/github.com/barkimedes/go-deepcopy@v0.0.0-20220514131651-17c30cfc62df/deepcopy.go:174 +0x305
github.com/barkimedes/go-deepcopy._anything({0x7e2100, 0xc0000022c8}, 0xc000020630)
        $GOPATH/pkg/mod/github.com/barkimedes/go-deepcopy@v0.0.0-20220514131651-17c30cfc62df/deepcopy.go:77 +0x17e
github.com/barkimedes/go-deepcopy._pointer({0x78ffa0, 0x9cd700}, 0xc000020630)
        $GOPATH/pkg/mod/github.com/barkimedes/go-deepcopy@v0.0.0-20220514131651-17c30cfc62df/deepcopy.go:146 +0x1f6
github.com/barkimedes/go-deepcopy._anything({0x78ffa0, 0x9cd700}, 0xc000020630)
        $GOPATH/pkg/mod/github.com/barkimedes/go-deepcopy@v0.0.0-20220514131651-17c30cfc62df/deepcopy.go:77 +0x17e
github.com/barkimedes/go-deepcopy.Anything(...)
        $GOPATH/pkg/mod/github.com/barkimedes/go-deepcopy@v0.0.0-20220514131651-17c30cfc62df/deepcopy.go:68
...
```

So, I think we need to keep using the current stable deep copy library.

**Comment by xuri** [comment]
Thanks for your suggestion. Would you like to create a PR for this?

**Comment by Juneezee** [comment]
> Thanks for your suggestion. Would you like to create a PR for this?

@xuri Sure! :blush:
