### ISSUE TITLE
int overflow of WriteToBuffer

### ISSUE THREAD

**Issue by xxf0512** [qax-os/excelize#2031]
**Description**
int overflow of when call WriteToBuffer

**Steps to reproduce the issue:**
You can view the code directly
1. write int64 to streamWriter
2. get buffer by call WriteToBuffer
3. read content from the buffer, the value of int64 is overflow.

**Describe the results you received:**
the actual value is "6.87914389418332E+18"

**Describe the results you expected:**
the expected value should be "6879143894183324362"

**Output of `go version`:**
go version go1.22.3 darwin/arm64

```text
--- FAIL: TestWriteToBuffer (0.01s)
    /Users/xxf0512/Code/Github/excelize/stream_test.go:402: 
        	Error Trace:	/Users/xxf0512/Code/Github/excelize/stream_test.go:402
        	Error:      	Not equal: 
        	            	expected: "6879143894183324362"
        	            	actual  : "6.87914389418332E+18"
        	            	
        	            	Diff:
        	            	--- Expected
        	            	+++ Actual
        	            	@@ -1 +1 @@
        	            	-6879143894183324362
        	            	+6.87914389418332E+18
        	Test:       	TestWriteToBuffer
FAIL
FAIL	github.com/xuri/excelize/v2	0.428s
FAIL
```

**Excelize version or commit ID:**
c93618856aaf68b0c4dc1c60f8757da0b95effc4

```go
func TestWriteToBuffer(t *testing.T) {
	val := int64(6879143894183324362)

	f := NewFile()
	sw, err := f.NewStreamWriter("Sheet1")
	assert.NoError(t, err)

	err = sw.SetRow("A1", []interface{}{val})
	assert.NoError(t, err)

	buf, err := f.WriteToBuffer()
	assert.NoError(t, err)

	newFile, err := OpenReader(buf)
	assert.NoError(t, err)

	rows, err := newFile.GetRows("Sheet1")
	assert.NoError(t, err)
	
	assert.Equal(t, "6879143894183324362", rows[0][0])
}
```

**Environment details (OS, Microsoft Excel™ version, physical, etc.):**
MacOS 15.1

**Comment by xuri** [comment]
Thanks for your issue. There're some issue in your test case:

- Number 6879143894183324362 overflow numeric precision of Excel, if you open generated workbook by Excel, the number shown as `6.87914E+18`, and formula bar show `6879143894183320000`
- If you wanna disable scientific number format, please set number format style for the cell
- As documentation says: "you must call the 'Flush' method to end the streaming writing process"

So, if you made some changes for the test like this, it will passed:

```diff
func TestWriteToBuffer(t *testing.T) {
    val := int64(6879143894183324362)

    f := NewFile()
    sw, err := f.NewStreamWriter("Sheet1")
    assert.NoError(t, err)

+   styleID, err := f.NewStyle(&Style{NumFmt: 1})
+   assert.NoError(t, err)
+
-   err = sw.SetRow("A1", []interface{}{val})
+   err = sw.SetRow("A1", []interface{}{Cell{StyleID: styleID, Value: val}})
    assert.NoError(t, err)
+   assert.NoError(t, sw.Flush())

    buf, err := f.WriteToBuffer()
    assert.NoError(t, err)

    newFile, err := OpenReader(buf)
    assert.NoError(t, err)

    rows, err := newFile.GetRows("Sheet1")
    assert.NoError(t, err)

-   assert.Equal(t, "6879143894183324362", rows[0][0])
+   assert.Equal(t, "6879143894183320000", rows[0][0])
}
```

I will close this, if you have any questions, please let me know, and you can reopen this any time.
