### ISSUE TITLE
missing the last column of the current row is empty

### ISSUE THREAD

**Issue by Sadio94** [qax-os/excelize#2032]
if last column of the current row is empty，can not get the last column; The cell will be skipped

**Comment by Sadio94** [comment]
![image](https://github.com/user-attachments/assets/a478c532-c7cb-4455-8c32-9cb9953194c9)
for example，can not read F10、F11

**Comment by xuri** [comment]
Thanks for your issue. If you are reporting a new issue, make sure that we do not have any duplicates already exist. Please DO NOT create duplicate issues. This was duplicated with issues #721, #1016, #1135, #1245, #1452, #1557, #1597, #1616, #1812 and #1990. As the documentation of the [`GetRows`](https://pkg.go.dev/github.com/xuri/excelize/v2#File.GetRows) function says: "the continually blank cells in the tail of each row will be skipped, so the length of each row may be inconsistent". Please check the length of each cell before getting the element in the slice. I have made a figure in issue #1245 to explain what kind of cells will be skipped for your reference, and I closed this issue. If you have any questions, please let me know to reopen this anytime.

**Comment by lcsin** [comment]
我遇到了中间列存在连续的空白单元格时，也会跳过的问题。这个问题会导致我获取的值和表头无法对应上，请问有什么办法解决这种情况嘛？我导入的库版本为：github.com/xuri/excelize/v2 v2.8.1。

**Comment by xuri** [comment]
> 我遇到了中间列存在连续的空白单元格时，也会跳过的问题。这个问题会导致我获取的值和表头无法对应上，请问有什么办法解决这种情况嘛？我导入的库版本为：github.com/xuri/excelize/v2 v2.8.1。

Please check the length of each cell before getting the element in the slice.
