### ISSUE TITLE
How to set GapWidth when plotting Col chart using function "AddChart"?

### ISSUE THREAD

**Issue by ffh-zhang** [qax-os/excelize#2033]
**Description**

**Steps to reproduce the issue:**
1.
2.
3.

**Describe the results you received:**

**Describe the results you expected:**

**Output of `go version`:**

```text
(paste your output here)
```

**Excelize version or commit ID:**

```text
(paste here)
```

**Environment details (OS, Microsoft Excel™ version, physical, etc.):**

**Comment by xuri** [comment]
Thanks for your issue. I added new fields `GapWidth` and `Overlap` in the `Chart` data type to support set gap width and overlap of the bar and column chart, please upgrade to the master branch code by `go get -u github.com/xuri/excelize/v2@master`. This feature will be released in the next version. Now you can set the gap width of the column chart like this:

```diff
gapWidth := uint(10)
&excelize.Chart{
    Type: excelize.Col,
+   GapWidth: &gapWidth,
    ...
}
```
