### ISSUE TITLE
Is there a way to insert a picture with InsertType PictureInsertTypeDISPIMG?

### ISSUE THREAD

**Issue by QingShan-Xu** [qax-os/excelize#2035]
Is there a way to insert a picture with InsertType PictureInsertTypeDISPIMG ?
类似于wps中的图片嵌入单元格操作

**Comment by xuri** [comment]
Thanks for your issue. If you are reporting a new issue, make sure that we do not have any duplicates already exist. This was duplicated with issue #1873. As the documentation of the [`AddPicture`](https://pkg.go.dev/github.com/xuri/excelize/v2#File.AddPicture) function says: this function only supports adding pictures placed over the cells currently, and doesn't support adding pictures placed in cells or creating the Kingsoft WPS Office embedded image cells. I closed this issue. If you have any questions, please let me know to reopen this anytime.
