### ISSUE TITLE
why FitToHeight can not be 0?

### ISSUE THREAD

**Issue by HyuncheolKim2021** [qax-os/excelize#2039]
I want to set all columns of an Excel sheet to fit on one page when printing. However, the FitToHeight option can only be set to 1 or higher. What should I do in this case?
```go
// setPageLayout provides a method to set the fit to height for the worksheet.
func (p FitToHeight) setPageLayout(ps *xlsxPageSetUp) {
	if int(p) > 0 {
		ps.FitToHeight = intPtr(int(p))
	}
}
```

**Describe the results you received:**

**Describe the results you expected:**

**Output of `go version`:**

```text
go version go1.22.5 darwin/arm64
```

**Excelize version or commit ID:**

```text
github.com/xuri/excelize/v2 v2.6.1
```

**Environment details (OS, Microsoft Excel™ version, physical, etc.):**

**Comment by imirkin** [comment]
If you check the latest version, this is no longer the case. PageLayoutOptions is now a single argument to SetPageLayout and has pointers for the values you want to set.

**Comment by xuri** [comment]
Thanks for Ilia's reply. Yes, please upgrade to the latest version or use the master branch code. I will close this, if you have any other questions, please let me know, and reopen this anytime.
