### ISSUE TITLE
Sheets created with CopySheet cannot have images added 

### ISSUE THREAD

**Issue by FiodarShurankou** [qax-os/excelize#2040]
**Description**

I am aware that CloneSheet does not work with images but I tried to CloneSheet, fill with data and then add images.
Tried to do it in one go, save than open the output file and add the images afterwards but no luck.

One thing i noticed is that the file names are being changed, the sheet index and sheetId are not being handled properly
I have a template file with index sheet and a template sheet, the Index sheet has ID 508 so all the new sheets have ids 509, 510 etc...
When i inspect the unzipped folder I saw that the new sheet.xml files have the ID (509) in the name, not the index (3), after recovering the file the sheet.xml files are being renamed to have the index in the name
Before:
![image](https://github.com/user-attachments/assets/4e8a6907-b305-4500-80a2-3d08ccc7e4a1)

After:
![image](https://github.com/user-attachments/assets/b4170eee-e2dd-4593-a5b3-a07a15dfad2f)

**Steps to reproduce the issue:**
1. OpenFile
2. AddSheet
3. CloneSheet
4. AddImage to the new Sheet

**Describe the results you received:**

When I open the file in Excel:
`We found a problem with some content of 'file.xlsx'`
After clicking Ok, It's able to recover and it displays properly

**Describe the results you expected:**

File working without need to recover

**Output of `go version`:**

```text
go version go1.23.2
```

**Excelize version or commit ID:**

```text
github.com/xuri/excelize/v2 v2.9.0
```

**Environment details (OS, Microsoft Excel™ version, physical, etc.):**
go runs on Debian Linux
Excel on Windows 11

**Comment by xuri** [comment]
Thanks for your issue. This was duplicated with issues #472 and #1605. As [the documentation of the `CopySheet` function](https://pkg.go.dev/github.com/xuri/excelize/v2#File.CopySheet) says: which doesn't support duplicate workbooks that contain tables, charts or pictures. Please using `GetPictureCells`, `GetPictures` and `AddPicture` functions to copy images.
