### ISSUE TITLE
Sheets created with CopySheet cannot have images added

### ISSUE THREAD

**Issue by FedotCompot** [qax-os/excelize#2041]
**Description**

I am aware that CloneSheet does not work with images but I tried to CloneSheet, fill with data and then add images.
Tried to do it in one go, save than open the output file and add the images afterwards but no luck.

One thing i noticed is that the file names are being changed, the sheet index and sheetId are not being handled properly
I have a template file with index sheet and a template sheet, the Index sheet has ID 508 so all the new sheets have ids 509, 510 etc...
When i inspect the unzipped folder I saw that the new sheet.xml files have the ID (509) in the name, not the index (3), after recovering the file the sheet.xml files are being renamed to have the index in the name
Before:
![image](https://github.com/user-attachments/assets/4e8a6907-b305-4500-80a2-3d08ccc7e4a1)

After:
![image](https://github.com/user-attachments/assets/b4170eee-e2dd-4593-a5b3-a07a15dfad2f)

**Steps to reproduce the issue:**
1. OpenFile
2. AddSheet
3. CloneSheet
4. AddImage to the new Sheet

**Describe the results you received:**

When I open the file in Excel:
`We found a problem with some content of 'file.xlsx'`
After clicking Ok, It's able to recover and it displays properly

**Describe the results you expected:**

File working without need to recover

**Output of `go version`:**

```text
go version go1.23.2
```

**Excelize version or commit ID:**

```text
github.com/xuri/excelize/v2 v2.9.0
```

**Environment details (OS, Microsoft Excel™ version, physical, etc.):**
go runs on Debian Linux
Excel on Windows 11

**Comment by xuri** [comment]
Please don't create duplicated issue. This was duplicated with issues #472, #1605 and #2040.

**Comment by FedotCompot** [comment]
@xuri I don't believe it's a duplicate, I'm aware of the `CloneSheet` restrictions, namely, images copy not working
#2040 was created by me, but from the wrong account, so i closed it and created this one
#472 and #1605 are addressing the issue of images copy which I'm not trying to do

I'm not trying to clone a sheet with images, I'm trying to add images to a sheet that was cloned
For reference, check the reproduction steps

**Comment by xuri** [comment]
Thanks for your feedback. Could you show us a complete, standalone example program or reproducible demo?

**Comment by FedotCompot** [comment]
Due to sensitive data I could not just publish my code so I started from scratch creating a simpler template with similar characteristics, but it was working.

After some tests with the broken template I tried to remove different parts, and in the end I found the issues:
1. There is a weird behavior with notes, although notes were in the INDEX sheet, so they were not cloned when I keep them it does not work
2. There is an issue with cloning formulas

You can find all 3 templates, the code and the output in here:
https://github.com/FedotCompot/excelize-go-issue-2041

Cells that I changed between `template_broken.xlsx` and `template_fixed.xslx` are marked with red background
