### ISSUE TITLE
SetCellStr() does not set cell format to text

### ISSUE THREAD

**Issue by Morrowless** [qax-os/excelize#2043]
**Description**

SetCellStr() does not set cell format to text

**Steps to reproduce the issue:**
1. Open Excel file with cells populated with SetCellStr()
2. Confirm that cell is not Text but "General"

**Describe the results you received:**
Cell format is General

**Describe the results you expected:**
Cell format is Text
**Output of `go version`:**
1.22.6

**Excelize version or commit ID:**
v2.8.1

**Environment details (OS, Microsoft Excel™ version, physical, etc.):**
Microsoft Excel 365

**Comment by xuri** [comment]
Thanks for your issue. This was duplicated with issues #705 and #1915. I will close this.
