### ISSUE TITLE
AutoFit for row height

### ISSUE THREAD

**Issue by tea0112** [qax-os/excelize#2044]
Is there any way that I can autofit like the onlyoffice the row height as row 18?
![image](https://github.com/user-attachments/assets/6162ef1a-9fec-4bb3-9c45-e48a3b50b735)
![image](https://github.com/user-attachments/assets/ec2bd743-e0ec-4ede-a98c-4ae023440cb8)

**Comment by xuri** [comment]
This library doesn't support auto fit row height and column width, but you can set custom row height by [`SetRowHeight`](https://pkg.go.dev/github.com/xuri/excelize/v2#File.SetRowHeight) function. This was duplicated with issues #92, #204, #1209, #1351 and #2028. Please also reference PR #1386. I will close this, if you have any other questions, please let me know, to reopen this anytime.
