### ISSUE TITLE
Add a way to ignore "number stored as text" error

### ISSUE THREAD

**Issue by imirkin** [qax-os/excelize#2046]
There can be funny reasons why we have to store a number-looking thing as text. For example, this could be due to a desire to introduce rich-text formats to the cell. Excel provides a way to ignore these errors so the sheet isn't full of little error triangles:

```xml
  <ignoredErrors>
    <ignoredError sqref="D15 C18:D19" numberStoredAsText="1"/>
  </ignoredErrors>
```

There are most likely other properties whose errors can be ignored too. Not sure what the right API is -- provide a sqref + errors to ignore, or try to manage it "more optimally"...

A quick search suggests at least these errors can be ignored, no idea if this set is exhaustive: `calculatedColumn`, `emptyCellReference`, `evalError`, `formula`, `formulaRange`, `listDataValidation`, `numberStoredAsText`, `twoDigitTextYear`, `unlockedFormula`.

**Comment by xuri** [comment]
Thanks for your issue. I added a new function `AddIgnoredErrors` to support ignored error for a range of cells. This feature will be released in the next version. Please upgrade to the master branch, you can ignore "number stored as text" error on `Sheet1` for range of cells `D15 C18:D19` like this:

```go
err := f.AddIgnoredErrors("Sheet1", "D15 C18:D19", excelize.IgnoredErrorsNumberStoredAsText)
```
