### ISSUE TITLE
How can I fix the issue of cell borders disappearing from the custom table style?

### ISSUE THREAD

**Issue by DeveloperJo** [qax-os/excelize#2048]
I created a custom table style in an MS Excel sheet using the Excel program. The style includes cell borders for each cell.

![image](https://github.com/user-attachments/assets/5f61dd4d-9a5d-4eff-ba42-294221431bd7)

However, after saving and closing the Excel file, when I reopen it and save it again using Excelize, the cell borders from my custom table style disappear.

![image](https://github.com/user-attachments/assets/c7aeb215-77d0-4448-a336-76d96568595f)

Is there a way to resolve this issue?

**Comment by xuri** [comment]
Thanks for your issue. Which version of this library are you using? Could you show us a complete, standalone example program or reproducible demo? If you open an existing workbook, please provide the file attachment without confidential info.

**Comment by DeveloperJo** [comment]
I am currently using version v2.9.0.
Here is the text.xlsx file used for testing, along with the code I wrote.

```go
package main

import (
	"flag"
	"fmt"

	"github.com/xuri/excelize/v2"
)

func main() {
   file_name := flag.String("file", "", "Input file Name")
   flag.Parse()

   fmt.Println(*file_name, *order_code)

   f, err := excelize.OpenFile(*file_name)
   if err != nil {
      fmt.Println(err)
      return
   }

   tables, err := f.GetTables("Sheet1")
   if err != nil {
      fmt.Println(err)
      return
   }

   fmt.Println(tables)

   if err := f.SaveAs("test1.xlsx",); err != nil {
      fmt.Println(err)
   }
}

```

**Comment by xuri** [comment]
Thanks for your feedback. I fixed this, please upgrade to the master branch code, and this patch will be released in the next verison.

**Comment by DeveloperJo** [comment]
Thank you for your prompt response. I have confirmed that everything is working properly. Thank you again.
