### ISSUE TITLE
SUMIF doesn't work correctly for columns beyond AA

### ISSUE THREAD

**Issue by grahamorrell** [qax-os/excelize#2055]
**Description**

SUMIF( ) seems to work fine when the ranges are in columns A to Z, but returns incorrect results for ranges beyond AA

**Steps to reproduce the issue:**

**Working version :** 

![image](https://github.com/user-attachments/assets/a13c492b-a8c7-43b4-9360-fb0a86ac8e19)
=SUMIF('Test SUMIF'!N1:T1, "Fred", 'Test SUMIF'!N2:T2)
CalcCellValue(...) = 700 // This is correct

**Broken version :** 
![image](https://github.com/user-attachments/assets/b872541a-8fe6-4b75-9bbd-770ab84ce765)
(Note this is exactly the same table, just moved right to span across the AA column)
=SUMIF('Test SUMIF'!X1:AD1, "Fred", 'Test SUMIF'!X2:AD2)
CalcCellValue(...) = 400 // This is incorrect - should be 700!

**Describe the results you received:**
Received 400 when the range spanned across the AA column

**Describe the results you expected:**
Expected 700

**Output of `go version`:**
N/A

**Excelize version or commit ID:**

```text
excelize-wasm 0.0.7
```

Windows

**Comment by grahamorrell** [comment]
Added sample spreadsheet here : 

[SUMIF Issue.xlsx](https://github.com/user-attachments/files/18262661/SUMIF.Issue.xlsx)

![image](https://github.com/user-attachments/assets/85812214-20a4-4c93-8d68-2355f4873fe2)

**Comment by xuri** [comment]
Thanks for your issue. If you'd like to report an issue of WebAssembly port of this library, please create issue in the [excelize-wasm](https://github.com/xuri/excelize-wasm) repository. I tested both Go language and JavaScript with your attachment workbook by following code, and it works well. The calculate result of cell X34 is 700:

Go version go1.23.2 darwin/amd64, excelize 2.9.0

```go
package main

import (
    "fmt"

    "github.com/xuri/excelize/v2"
)

func main() {
    f, err := excelize.OpenFile("SUMIF.Issue.xlsx")
    if err != nil {
        fmt.Println(err)
        return
    }
    defer func() {
        if err := f.Close(); err != nil {
            fmt.Println(err)
        }
    }()
    cell, err := f.CalcCellValue("Test SUMIF", "X34")
    if err != nil {
        fmt.Println(err)
        return
    }
    fmt.Println(cell)
}
```

Node.js v18.12.1, excelize-wasm@0.0.7

```javascript
const { init } = require('excelize-wasm');
const fs = require('fs');

init('./node_modules/excelize-wasm/excelize.wasm.gz').then((excelize) => {
  const f = excelize.OpenReader(fs.readFileSync('SUMIF.Issue.xlsx'));
  if (f.error) {
    console.log(f.error);
    return;
  }
  const ret1 = f.CalcCellValue('Test SUMIF', 'X34');
  if (ret1.error) {
    console.log(ret1.error);
    return;
  }
  console.log(ret1.value);
});
```

**Comment by grahamorrell** [comment]
Many apologies - this was actually an issue in some client code completely unrelated to your library.  I'll be sure to provide a minimal reproduction in pure Excelize go code for any future issues.
