### ISSUE TITLE
Is some way to set bar's color?

### ISSUE THREAD

**Issue by shadow1163** [qax-os/excelize#213]
Hi, I can draw a stacked bar chart now, but I want to set the bar's color, is any way to do it?

**Comment by xuri** [comment]
Thanks for your issue. This library not support set bar's color currently, I will consider adding support for it later.

**Comment by shadow1163** [comment]
@xuri Thanks for your quick response, appreciate your help.

**Comment by xuri** [comment]
Sorry for the late reply. I have add support for set the format for the data series fill. Also reference issue #1474. Now you can set the custom solid fill format like this:

```diff
Series: []excelize.ChartSeries{
    {
        Name:       "Sheet1!$A$2",
        Categories: "Sheet1!$B$1:$D$1",
        Values:     "Sheet1!$B$2:$D$2",
+       Fill:       excelize.Fill{Color: []string{"40A9FF"}, Pattern: 1},
    },
}
```

This feature will be released in the next version.
