### ISSUE TITLE
Comments missing from Sheet

### ISSUE THREAD

**Issue by Obbi89** [qax-os/excelize#228]
Hey,
I do have an issue with a document.
It does contain v- this in `sheets4.xml.rels` but it has no relationship for the `comments%d.xml`

```xml
<Relationship Id="rId4" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/vmlDrawing" Target="../drawings/vmlDrawing2.vml"/>
```

1) I open this file with excelize it sets LegacyDrawing to this relationship for sheet4 (the sheet does not contain any comments yet).
2) I add a comment to sheet4 cell doesn't matter
3) xl/comments%d.xml gets added to file list containing the correct data
4) since LegacyDrawing is already set the comments relationship is not added to the sheets relationships
5) I save the file to disk
6) As expected excel warns me about a corrupt file and that some comments could not be displayed.

I guess there needs to be another check to see if relationships contains a valid reference to the a comments.xml for sheet x.

Btw. the source file is not considered corrupt by excel.
Libreoffice silently ignores the issue and the comments are missing there, too.

If you need more info please feel free to contact me.

**Comment by xuri** [comment]
Thanks for your issue. Please provides file attachments and code if you can.

**Comment by Obbi89** [comment]
I'll try to create new files reproducing the issue tomorrow. I cannot provide these files due to their contents.

**Comment by Obbi89** [comment]
I was not able to figure the exact issue out.
But I could construct a similar file structure (by hand) that reproduces the issue I have with a valid file.
You cannot open and save this constructed example since it will be fixed by that.
Somehow the real file I cannot share has some additional stuff I can't seem to find, since saving that file won't fix the issue.

Nonetheless you should be able to see the problem with your current approach in `AddComment`. 
I hope a fix to this issue, fixes it for the other file, too.
[issue228.zip](https://github.com/360EntSecGroup-Skylar/excelize/files/2054380/issue228.zip)

**Comment by xuri** [comment]
Could you provide the xlsx file that not add the comment, and tell me to add the comment to which cell will missing. I will try to reproduce this case and find fix it.

**Comment by Obbi89** [comment]
Hey,
 the xlsx file is included in the link i posted in the last message.

Just try to add a comment to any cell in the second sheet named `Why is this so sheety`.
It will not show up.

**Comment by xuri** [comment]
Sorry for my so late reply, the spreadsheet in the attachment is already corrupted, did you mean open an existing corrupted document and resave it? if not please provide the source file which can be open by Excel application normally. A few years later, some API has been changed in the later version, so I'm not sure if this issue still goes, I'll close this issue, if you have any questions, code, and attachments to reproduce this issue, please let me know, and reopen this issue at any time.
