### ISSUE TITLE
Radio Button

### ISSUE THREAD

**Issue by mohaprog** [qax-os/excelize#301]
I am trying to change the radioButton state by using xlsx.setCellValue in his linked cell but it show always 0.

Code :
> xlsx.SetCellValue("test", "K45", 1)

Result :
![image](https://user-images.githubusercontent.com/45336396/48981617-2211e380-f0d8-11e8-8742-e047a86e0e33.png)

The radio Buttons already exist in the excel file. I need to update the state.

Thank you

**Comment by xuri** [comment]
Thanks for your issue. The excelize library doesn't support change the radio button by set cell value currently, `x:ClientData` element in the `xl/drawings/vmlDrawing%d.vml` hasn't been maintained yet completely.

**Comment by xuri** [comment]
Thanks for your issue, and sorry for my late reply. I have initialized form control support for this library, please upgrade to the master branch code, and this feature will be released in the next version. Now we can delete the form control and add a checked radio button like this:

```go
if err := f.DeleteFormControl("Sheet1", "A1"); err != nil {
    // ...
}
if err := f.AddFormControl("Sheet1", excelize.FormControl{
    Cell:    "A1",
    Type:    excelize.FormControlRadio,
    Text:    "Option Button",
    Checked: true,
}); err != nil {
    // ...
}
```

**Comment by xuri** [comment]
Thanks for your issue, and sorry for my late reply. I have initialized form control support for this library, please upgrade to the master branch code, and this feature will be released in the next version. Now we can delete the form control and add a checked radio button like this:

```go
if err := f.DeleteFormControl("Sheet1", "A1"); err != nil {
    // ...
}
if err := f.AddFormControl("Sheet1", excelize.FormControl{
    Cell:    "A1",
    Type:    excelize.FormControlOptionButton,
    Text:    "Option Button",
    Checked: true,
}); err != nil {
    // ...
}
```
