### ISSUE TITLE
How to set chart labels font color

### ISSUE THREAD

**Issue by vasiliyaltunin** [qax-os/excelize#320]
I creating horisontal bar chart, but font color for legends is light gray and hard to read, i use Excel 2016
![shot1](https://user-images.githubusercontent.com/417082/50461713-4fea9080-09d4-11e9-9f8d-8f7b400d7052.png)

**Comment by davey06** [comment]
Any update on this? or is there any workaround to edit the axis font color?

**Comment by xuri** [comment]
Hi @vasiliyaltunin, @davey06. Please adjust the value of [lumOff](https://github.com/360EntSecGroup-Skylar/excelize/blob/cb797540684d82fdb0fab111d0efce2977b24bf3/drawing.go#L1100) temporary, I'll add support for specifying luminance shifted with custom lumOff later.

**Comment by davey06** [comment]
@xuri thanks for the fast response!

![Screen Shot 2020-03-06 at 15 43 33](https://user-images.githubusercontent.com/32833275/76067380-d54ad700-5fc1-11ea-8246-bc4a6cb55736.png)

**Comment by jholder85638** [comment]
Hi @davey06 could you share how you got the text to be black? I've tried setting the values but the text is always grey. I also checked out the revision with the above commit, same problem.

**Comment by tetsuyanh** [comment]
@xuri 
Thanks for your great work. I use this library.
I cannot fix this issue by https://github.com/IsotronicGmbH/excelize/commit/00509e578b4daaf5fcdba84b62c6008c1aa3530d.
I'm looking forward to solve this.

**Comment by xuri** [comment]
Hi @tetsuyanh, thanks for your feedback, which version of Excelize you're using? If you're using the v2.6.0 and later, please adjust the value of [`lumOff`](https://github.com/xuri/excelize/blob/a65c5846e45fece382f72465f9e858c788dfcfef/drawing.go#L1134) to `0` like this:

```go
LumOff: &attrValInt{Val: intPtr(0)},
```

**Comment by tetsuyanh** [comment]
@xuri Thanks! It works!
I use this adjustment by fork for a while.

**Comment by tetsuyanh** [comment]
@xuri Thanks, so so much!
