### ISSUE TITLE
Xlsx file writes data, but the file modification time does not change

### ISSUE THREAD

**Issue by Ranxiu** [qax-os/excelize#380]
**Description**

**Steps to reproduce the issue:**
1. open a xlsx cy file (cy.xlsx)
2. saveAs(cy.xlsx)
3.but the file modification time does not change

**Describe the results you received:**
So I can't tell if the current file has changed by using the PHP filemtime function
**Describe the results you expected:**

**Output of `go version`:**

```text
(paste your output here)
```

**Excelize version or commit ID:**

```text
(paste here)
```

**Environment details (OS, Microsoft Excel™ version, physical, etc.):**

**Comment by xuri** [comment]
Hi @Ranxiu, thanks for your issue. Please provides the version of excelize and Go you are using, and the xlsx file attachment if you can.
