### ISSUE TITLE
customize the name of the x, y axis of the 2D line chart

### ISSUE THREAD

**Issue by byteman** [qax-os/excelize#398]
希望能够为2D折线图的x，y轴添加名称

**Comment by xuri** [comment]
Thanks for your issue. Sorry for the late reply. I have added `Title` options to set primary axis titles for the `AddChart` function by commit [`f8aa3ad`](https://github.com/xuri/excelize/commit/f8aa3adf7e6dd419929feb5059f89cb97a8631cf). Please upgrade to the master branch code, and this feature will be released in the next version. Also reference issues #801 and #1553.
