### ISSUE TITLE
Need to get cell type or cell value type

### ISSUE THREAD

**Issue by Mindzy** [qax-os/excelize#417]
**Description**
GetCellStyle() only gets the style index, which is integer, of a cell. And the style index can't be related to a certain cell format.  I need to get the cell format, like general, date, time, percentage, number, text. Or cell value type like int, string, float64, bool. Since Excel stores date and time as int and float, date or time format can be return as float.

**Describe the results you expected:**

--| A | B
--|-- | --
1  | Mike | 23
2  | Sarah | 20

GetCellType(sheet, "A1")
string
GetCellType(sheet, "B1")
int

**Comment by Mindzy** [comment]
Also, some numbers in Excel can be stored as text by add ' before numbers.

-- | A | B
-- | -- | --
1 | Mike | 23
2 | Sarah | '20

GetCellType(sheet, "A1")
string
GetCellType(sheet, "B1")
int
GetCellType(sheet, "A2")
string
GetCellType(sheet, "B2")
string

**Comment by acidobinario** [comment]
no progress on this?

**Comment by xuri** [comment]
Thanks for your issue, I have added a new API `GetCellType` to support get cell data type, please upgrade to the master branch code.
