### ISSUE TITLE
Integer number '1' in a cell is read as '"1.0"

### ISSUE THREAD

**Issue by enobufs** [qax-os/excelize#430]
**Description**
I am reading spreadsheet values using GetRows() function.
I have a cell on the spreadsheet with the value 1, but when you read the corresponding value, it is "1.0".

**Steps to reproduce the issue:**
1. Open file
2. Use GetRows() then read values

**Describe the results you expected:**
I'd like to see the value as exactly what I see on the Excel.

**Output of `go version`:**
```text
go version go1.12.1 darwin/amd64
```

**Excelize version or commit ID:**

```text
github.com/360EntSecGroup-Skylar/excelize/v2 v2.0.0
```

**Environment details (OS, Microsoft Excel™ version, physical, etc.):**
```
macOS (Mojave)
```

Is there a way to know if the format of the cell is set to "General" so that I can convert it to an integer in my Go code?

Also, if you export xlsx file to csv, the value becomes 1, not "1.0".

**Comment by xuri** [comment]
This issue seems like #852, #848, could you provide code and spreadsheet attachments to reproduce this issue?

**Comment by xuri** [comment]
It seems still not to have enough info of code and attachments to reproduce this issue, so I'll close this issue, if you have any questions, please let me know.
