### ISSUE TITLE
Is there currenlty a way to read the conditional format color for a cell

### ISSUE THREAD

**Issue by nlacey** [qax-os/excelize#452]
**Description**

I need to read the conditional formatted color (font & fill) of a cell

There is currently ways to set a conditional format, but I'm not seeing a way to read the conditional format value for a cell

**Comment by xuri** [comment]
Thanks for your issue, sorry for the late reply. Four years later. I have added a new function `GetConditionalStyle` support to get the conditional format style definition, please upgrade to the master branch code, and this feature will be released in the next version. Also, reference the issue #1690.
