### ISSUE TITLE
How to make a double Y axis chart by using excelize?

### ISSUE THREAD

**Issue by JackChanw** [qax-os/excelize#518]

**Comment by JackChanw** [comment]
all the charts are single Y-axis, but i need to draw a double Y-axis chart, it is difficult  by using current excelize, do you have some ideas?

**Comment by zhouyao1124** [comment]
您好 请问这个问题您是否进行了处理？我看到您在584说会在518进行讨论，但是我在这两个问题中都没有找到答案

**Comment by xuri** [comment]
Sorry, it's still no progress, maybe taken a while to implement this feature.

**Comment by k-kurikuri** [comment]
Hi, contributors.

I would like to use a chart with a secondary axis, is there any progress on this feature?

**Comment by xuri** [comment]
Sorry for the late reply. I have added support for creating chart with a secondary series axis, please upgrade to the master branch code, and this feature will be released in the next version. Now you can specifies the series vertical axis as the secondary axis like this:

```diff
err := f.AddChart("Sheet1", "D1", &excelize.Chart{
    Type:   excelize.Col,
    Series: []excelize.ChartSeries{
        // ...
    },
    Title: excelize.ChartTitle{Name: "Chart Title"},
}, &excelize.Chart{
    Type:   excelize.Line,
    Series: []excelize.ChartSeries{
        // ...
    },
    YAxis: excelize.ChartAxis{
+        Secondary: true,
    },
})
```
