### ISSUE TITLE
Cell value not updating and showing 0 in Google Mail Preview and causing Div/0 in formula fields

### ISSUE THREAD

**Issue by chriskarlin** [qax-os/excelize#654]
**Description**
I am using SetCellValue() to insert Values into a Cells on an XLSX template. These cells are then being used by formulas (set through SetCellFormula()) in other cells to compute totals, which then in turn are being used to calculate averages in other cells. The generated file is then sent to Clients via email, which when opened in Google Mail's preview feature shows 0 in the total cells that should have computed the total. 
When the file is then being opened in an Google sheets, the values compute/update and the DIV/0 disappears. 

Found this: https://godoc.org/github.com/360EntSecGroup-Skylar/excelize#File.UpdateLinkedValue. But it would need the xlsx file to be opened to compute the values again.

What is the best way to deal with this, to fix the Values for google preview feature?

**Steps to reproduce the issue:**
1. Create xlsx file with inserted values and formula field that use the cells.
2. Send email to yourself with that file attached
3. Open file in google mail preview

**Describe the results you received:**
Formulas don't compute and show 0 from template and not  when previewed in google mail.

**Describe the results you expected:**
Fromulas to calculate and show total in google preview.

**Output of `go version`:**

```text
go version go1.14.2 darwin/amd64
```

**Excelize version or commit ID:**

```text
github.com/360EntSecGroup-Skylar/excelize v1.4.1
```

**Environment details (OS, Microsoft Excel™ version, physical, etc.):**
MAC OS, Google Mail preview, Google sheets

**Comment by xuri** [comment]
Thanks for your issue. Google Docs preview doesn't calculate formula results when you preview the spreadsheet in Gmail. SetCellFormula API doesn't calculate and storage results for the formula, to resolve this issue, we need to implement a formula engine, I'm working on it by adding new [`CalcCellValue`](https://pkg.go.dev/github.com/360EntSecGroup-Skylar/excelize/v2?tab=doc#File.CalcCellValue) API and in progress recently, also reference #65.

**Comment by ChrisKarlin** [comment]
Thank you for the answer!
I have tried using the function and received this return values for a simple 'SUM()' formula.
![Screen Shot 2020-06-22 at 3 34 34 PM](https://user-images.githubusercontent.com/46851840/85328056-092d0800-b49e-11ea-8587-4afcf3a65d50.png)

What does that indicate?

**Comment by xuri** [comment]
Thanks for your feedback. Could you provide code or attachment without confidential info?

**Comment by xuri** [comment]
Over two years later, the formula calculation engine is still working in progress, but it can support 434 formula functions. Please try to upgrade to the latest version. I'll close this issue, if you have any questions, please let me know to reopen this anytime.
