### ISSUE TITLE
How to read pictures embedded in cells

### ISSUE THREAD

**Issue by heviye** [qax-os/excelize#664]

**Comment by xuri** [comment]
Did you mean that get the picture binary content from a worksheet? please reference [GetPicture](https://xuri.me/excelize/en/image.html#GetPicture).

**Comment by heviye** [comment]
> Did you mean that get the picture binary content from a worksheet? please reference [GetPicture](https://xuri.me/excelize/en/image.html#GetPicture).

What I mean is: after inserting the picture into Excel, it can be floating or embedded, the floating one can be obtained, but the embedded one cannot be obtained

**Comment by xuri** [comment]
Thanks for your feedback. Which version of Excelize are you using, could you provide non-confidential information attachment?

**Comment by heviye** [comment]
> Thanks for your feedback. Which version of Excelize are you using, could you provide non-confidential information attachment?

v2

**Comment by xuri** [comment]
Please follow by issue template to provide code/attachments and steps to reproduce the issue, which will helpful for me quickly resolve the issue.

**Comment by heviye** [comment]
**Description** 
When inserting a picture in Excel, if you select the floating mode, you can read the picture stream, but if you select the embedded cell mode, you cannot read the picture stream

**Steps to reproduce the issue:**
```go
file, raw, err := f.GetPicture("Sheet1", "D3")
# err is nil
# raw is []
# file is empty
```

**Describe the results you received:**
```go
file, raw, err := f.GetPicture("Sheet1", "D3")
# err is nil
# raw is []byte{...}
# file is file name
```

**Output of `go version`:**

```sh
GO111MODULE="auto"
GOARCH="amd64"
GOBIN="/Users/hevi/go/bin"
GOCACHE="/Users/hevi/Library/Caches/go-build"
GOENV="/Users/hevi/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GONOPROXY="code.gz66.net"
GONOSUMDB="code.gz66.net"
GOOS="darwin"
GOPATH="/Users/hevi/go"
GOPRIVATE="code.gz66.net"
GOPROXY="https://goproxy.cn,direct"
GOROOT="/usr/local/Cellar/go/1.13.8/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.13.8/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/hevi/goWorks/code.gz66.net/sqzl/go-zl-edge/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/r0/hh7_wynx3h3dclx7x_szbdkc0000gn/T/go-build744695952=/tmp/go-build -gno-record-gcc-switches -fno-common"
```

**Environment details (OS, Microsoft Excel™ version, physical, etc.):**
* macOS Catalina 10.15.5
* WPS Office 2.4.0(3944)
* Macbook pro

**Comment by xuri** [comment]
Embedded picture in the Kingsoft WPS will set cell with formula DISPIMG, excelize not support it currently, and it can't work with other spreadsheet applications, such as Microsoft Excel, Apache OpenOffice, LibreOffice, etc, please use a floating picture instead of an embedded picture if you can.

**Comment by heviye** [comment]
> Embedded picture in the Kingsoft WPS will set cell with formula DISPIMG, excelize not support it currently, and it can't work with other spreadsheet applications, such as Microsoft Excel, Apache OpenOffice, LibreOffice, etc, please use a floating picture instead of an embedded picture if you can.

OK, Thank you!!

**Comment by ysk229** [comment]
@xuri  Hi, can you support this, all other open source is supported, the relevant programs are as follows:
https://github.com/wangguanquan/eec/issues/363
https://blog.csdn.net/maudboy/article/details/133145278
https://github.com/LaoDie1/godot-excel-reader/blob/b2ec7df610c5b0101ad1d2f23fabf49d5d0b4354/addons/excel_reader/src/workbook.gd#L20

**Comment by xuri** [comment]
Thanks for your feedback. I'll consider to add support for this.

**Comment by xuri** [comment]
The `GetPictures` function now support get embedded cell images created by Kingsoft WPS Office, please upgrade to the master branch code, and this feature will be released in the next version.

**Comment by niumowangorz** [comment]
> 该`GetPictures`功能现支持获取金山WPS Office创建的嵌入单元格图片，请升级至主分支代码，该功能将在下一版本发布。

Publish it soon

**Comment by LittleMiao** [comment]
> The `GetPictures` function now support get embedded cell images created by Kingsoft WPS Office, please upgrade to the master branch code, and this feature will be released in the next version.

When is this version expected to be released? Please let me know

**Comment by xuri** [comment]
The version 2.8.1 will be released on February 26, 2024.
