### ISSUE TITLE
Table range

### ISSUE THREAD

**Issue by drsasa** [qax-os/excelize#674]
Is there a way to change existing table range?

For example:
1. Get table by name
2. Set new range instead let's say "A1:P8000" to "A1:P1000"

Thank you in advance.

**Comment by xuri** [comment]
Sorry, this lib not support to change the table reference range currently. I have added this feature support to the [Roadmap](https://github.com/360EntSecGroup-Skylar/excelize/wiki).

**Comment by xuri** [comment]
This feature has been working in progress (as a project of the Institute of Software Chinese Academy of Sciences 2023 Open Source Promotion Plan), the library will be supported to read and remove tables in a future released version, in August, 2023.

**Comment by caokuii** [comment]
Hi there,

I am a CS student, also a prospective student interested in the OSPP 2023 project.

I came across your project on OSPP 2023 and I'm very interested in learning more. I've been exploring the world of open source software and your project seems like a great opportunity for me to contribute to a meaningful project and learn new skills at the same time.

Could you provide more information about the project? What should I do if I want to explore more?

Thanks for your time and I look forward to hearing back from you soon!

Best regards,
Cao Kui

**Comment by xuri** [comment]
Contributions are welcome! You can get more details from the [documentation website](https://xuri.me) of this project. Welcome submit project applications on the OSPP website.

**Comment by xuri** [comment]
Contributions are welcome! You can get more details from the [documentation website](https://xuri.me/excelize) of this project. Welcome submit project applications on the OSPP website.

**Comment by caokuii** [comment]
> 

I am currently very interested in this project, but I just don’t know if I can finally get the chance to participate in this project on OSPP.

**Comment by xuri** [comment]
> I am currently very interested in this project, but I just don’t know if I can finally get the chance to participate in this project on OSPP.

According to the [guide of this activity](https://summer-ospp.ac.cn/help/en/student), you can check application results on the activity's official website and system.

**Comment by taomin597715379** [comment]
The new functions `GetTables` and `DeleteTable` has been added. Now, we can get table at first, delete the table, change the range of the table, and then add the new table.  Please try to upgrade the master branch code. This feature will be released in the next version.
