### ISSUE TITLE
For performance issue

### ISSUE THREAD

**Issue by SivaramWiz** [qax-os/excelize#697]
Hey am using more the 50000 row of data. But that setCellValue() function will take so much time.
for me this could done by 1m28s.

**Comment by SivaramWiz** [comment]
And also streamWriter.Flush() will take 2s to finishe.

**Comment by SivaramWiz** [comment]
And consider merge cell will take lot of time. Is there any alternative for merge with stream

**Comment by liov** [comment]
50000 rows merge cell only 1m28s？i try 1900 rows by 1m19.62s.

**Comment by xuri** [comment]
Thanks for your feedback, in order to ensure that any operation (range overlap, adjust existing value or object on the range and etc.,) of the spreadsheet with high compatibility, Excelize has done a lot of checks internal, which will slow down, I'll consider optimizing performance for it.

**Comment by rbucker** [comment]
any progress here? A 4200 x 20 cell table takes way to long to write.

**Comment by rakesh-wrx** [comment]
@rbucker @xuri I am using the exact flow like yours and facing the performance issue. Writing 1.5 million records into the sheets taking more than 12 hrs to process. @rbucker do you found any workaround?

**Comment by rbucker** [comment]
@rakesh-wrx streaming is the only way but it creates some other challenges when trying to set the column width... I have not figured that part out yet.... the streaming took some trial and error. I would share it except it's part of a larger application and out of context would not be helpful.

**Comment by xuri** [comment]
Please reference this document and examples about [the streaming writer](https://xuri.me/excelize/en/stream.html#NewStreamWriter).

**Comment by rakesh-wrx** [comment]
Hey @xuri thanks to you and other developers who worked on developing this library. I am finally able to get the desired outcome in a very less time. For your information, I just upgraded the Excelize library from 1.4 to 2.5, and it got a massive improvement in terms of performance. Please refer to the attached image for more info. I have a question for you and am curious to know. Can you please tell me what were the major changes from the 1.4 to 2.5 version that resulted in huge performance improvement?
<img width="670" alt="Screenshot 2022-03-10 at 9 12 55 AM" src="https://user-images.githubusercontent.com/82862818/157584340-18d99ab3-dc95-4c9a-8d5c-4dcde165d65d.png">

**Comment by xuri** [comment]
There is a lot of optimization across multiple versions, please reference the [release note](https://github.com/xuri/excelize/releases) of each version and also reference the [performance benchmark report](https://github.com/xuri/excelize/wiki#working-with-memory-and-performance).
