### ISSUE TITLE
Function SaveTo to save file to writer

### ISSUE THREAD

**Issue by Donaldas** [qax-os/excelize#744]
Hi,
it would be great to have possibility to pass unlocked file to io.Writer interface. 

**Use case:**
Web service downloads excel files from cloud storage and processes it. In case excel file is password protected, service should unlock it with provided password and upload unlocked file back to cloud storage.

**Description**

Current implementation allows to save unlocked filed to the file on file system via:
`func (f *File) SaveAs(name string, opt ...Options) error`

New function **SaveTo** would allow to upload unlocked file without persisting it on file system.
`func (f *File) SaveTo(w io.Writer, opt ...Options) (int64, error)`

Other option would be to allow reset options in order to save unlocked file using:
```
func (f *File) Write(w io.Writer) error
func (f *File) WriteTo(w io.Writer) (int64, error)
func (f *File) WriteToBuffer() (*bytes.Buffer, error)
```
Thanks!

**Comment by ronna-s** [comment]
Any update on this from the contributors?

**Comment by xuri** [comment]
This library has added the [WriteTo](https://pkg.go.dev/github.com/xuri/excelize/v2#File.WriteTo) function since [version 1.4.1](https://github.com/xuri/excelize/releases/tag/v1.4.1), which can be used to save the file to the writer.

**Comment by ronna-s** [comment]
Thanks for the quick reply @xuri I see the functions but they don't seem to set the contentType using the file extension as `SaveAs` does and that functionality is not exported (`setContentTypePartProjectExtensions`). I have a case for a file upload that doesn't need local storage.

**Comment by xuri** [comment]
Okay, thanks for your feedback. I will add support for it at this week.

**Comment by ronna-s** [comment]
I can create a proposal PR. Against v2 or master?

**Comment by xuri** [comment]
Thank you. Contributions are welcome. Please create PR base on the master branch.

**Comment by xuri** [comment]
I have fixed this issue. Now the `Save`, `Write` and `WriteTo` function accept saving options, and here is [an example](https://xuri.me/excelize/en/workbook.html#OpenReader) for handle a workbook without a touch file system. Please upgrade to the master branch code, and this patch will be released in the next version.

**Comment by itmecho** [comment]
Heads up for anyone who might've had the same issue as me related to this!

I've just upgraded to `2.7.0` and this change has broken my code as the `*excelize.File` type no longer implements the standard library `io.WriterTo` interface.

I've had to implement this wrapper type to get it to work again:

```go
package server

import (
	"io"

	"github.com/xuri/excelize/v2"
)

type fileWriterTo struct {
	*excelize.File
}

// WriteTo implements io.WriterTo
func (f *fileWriterTo) WriteTo(w io.Writer) (n int64, err error) {
	return f.File.WriteTo(w)
}

func wrapFileWriteTo(f *excelize.File) io.WriterTo {
	return &fileWriterTo{f}
}
```
