### ISSUE TITLE
Add Chart Axis Labels

### ISSUE THREAD

**Issue by MarkWildey** [qax-os/excelize#801]
**Description**
Add the capability to add X & Y axis chart titles

**Steps to reproduce the issue:**
Functionality is not available yet

**Describe the results you received:**
N/A

**Describe the results you expected:**
Able to specify X & Y axis labels

**Output of `go version`:**

**Excelize version or commit ID:**

**Environment details (OS, Microsoft Excel™ version, physical, etc.):**

**Comment by xuri** [comment]
Thanks for your issue. Sorry for the late reply. I have added `Title` options to set primary axis titles for the `AddChart` function by commit [`f8aa3ad`](https://github.com/xuri/excelize/commit/f8aa3adf7e6dd419929feb5059f89cb97a8631cf). Please upgrade to the master branch code, and this feature will be released in the next version. Also reference issue #1553.

**Comment by xuri** [comment]
Thanks for your issue. Sorry for the late reply. I have added `Title` options to set primary axis titles for the `AddChart` function by commit [`f8aa3ad`](https://github.com/xuri/excelize/commit/f8aa3adf7e6dd419929feb5059f89cb97a8631cf). Please upgrade to the master branch code, and this feature will be released in the next version. Also reference issues #398 and #1553.
