### ISSUE TITLE
Create a StreamReader type

### ISSUE THREAD

**Issue by evanfuller** [qax-os/excelize#833]
**Description**

My team and I are exploring a use case that requires us to load Excel files submitted by customers. For the same reason that this project has the StreamWriter type to avoid buffering too much in memory at once, I would love if there were support for a StreamReader. Ideally, the reading from each sheet would be paginated or chunked somehow so that the memory footprint never gets beyond a configured number of rows or byte size.

**Comment by xuri** [comment]
The [column](https://xuri.me/excelize/en/sheet.html#Cols) and [row](https://xuri.me/excelize/en/sheet.html#Rows) iterator read data as streaming, with these API a small part of the XML file is only loaded in memory, but you can't specify the read chunk size currently.

**Comment by evanfuller** [comment]
Thanks for the docs reference, I missed these functions.

Perhaps I'm misunderstanding, but I don't know that the row iterator actually saves on the in-memory footprint. It looks like it loads a sheet from a given name [on this line](https://github.com/360EntSecGroup-Skylar/excelize/blob/master/rows.go#L204), but the definition of this function appears to [load that entire sheet into memory](https://github.com/360EntSecGroup-Skylar/excelize/blob/438fd4b3f958dc3edbbe4915e866ac639a3135f1/lib.go#L51-L59). Have I read this code correctly? Is there support for reading in a sheet in incremental chunks?

**Comment by xuri** [comment]
Stream parser can avoid loads the whole XML document object model (DOM) in memory, has significantly improved performance, but extracts ZIP and loads a whole XML file into the memory is still required currently. I'll consider if extracts the XML files into the hard disk in the future.

**Comment by xuri** [comment]
Hi @evanfuller, I have improved the streaming reader performance for the rows iterator, memory usage decrease by about 93.7%. Please upgrade to the master branch code. This is a breaking change, the user should be close the stream after using the row's iterator, and close the spreadsheet after opening an existing spreadsheet like this:

```go
package main

import (
    "fmt"

    "github.com/xuri/excelize/v2"
)

func main() {
    f, err := excelize.OpenFile("Book1.xlsx")
    if err != nil {
        fmt.Println(err)
        return
    }
    rows, err := f.Rows("Sheet1")
    if err != nil {
        fmt.Println(err)
        return
    }
    for rows.Next() {
        row, err := rows.Columns()
        if err != nil {
            fmt.Println(err)
        }
        for _, colCell := range row {
            fmt.Print(colCell, "\t")
        }
        fmt.Println()
    }
    // Close the stream
    if err = rows.Close(); err != nil {
        fmt.Println(err)
    }
    // Close the workbook
    if err := f.Close(); err != nil {
        fmt.Println(err)
    }
}
```

**Comment by wlxwlxwlx** [comment]
我发现在使用excelize.OpenFile函数的时候内存会出现一个很高的峰值，是否就是您上面提到的解压缩的时候会把整个XML加载到了内存里，请问现在有提供方法把解压缩后的XML直接保存到文件中，再从文件中按块加载的方法吗？
我现在有一个需求，流式读取一个超大的excel文件，但机器内存比较小，当执行excelize.OpenFile函数的时候服务就直接OOM了。
