### ISSUE TITLE
add function to remove or update comment in a cell 

### ISSUE THREAD

**Issue by coreyzzp** [qax-os/excelize#849]

**Comment by coreyzzp** [comment]
when we try to add comment to a cell with comment, when open the excel file, the excel program will complain about 'there is an error occur, but we has recovery from it'

**Comment by xuri** [comment]
Hi @coreyzzp, thanks for your feedback, could you provide any code and attachments to reproduce this issue?

**Comment by coreyzzp** [comment]
func TestCreateExcelAndUpdateComment(t *testing.T) {
	target := "test.xlsx"
	target2 := "test-after.xlsx"
	{
		var err error
		fd := excelize.NewFile()
		err = fd.AddComment("Sheet1", "A1", fmt.Sprintf(`{"author":"Excelize: ","text":"This is a comment" }`))
		require.Nil(t, err)
		err = fd.SaveAs(target)
		require.Nil(t, err)
		// here open test.xlsx is find
	}

	{
		fd, err := excelize.OpenFile(target)
		require.Nil(t, err)
		err = fd.AddComment("Sheet1", "A1", fmt.Sprintf(`{"author":"Excelize: ","text":"hello world"}`))
		require.Nil(t, err)
		err = fd.SaveAs(target2)
		require.Nil(t, err)
		// now open test-after.xlsx an error popup
	}
}

open test.xlsx
![image](https://user-images.githubusercontent.com/43430714/119787997-56162b80-bf04-11eb-8ed1-9fb2a5023d27.png)

open test-after.xlsx

![image](https://user-images.githubusercontent.com/43430714/119788081-69c19200-bf04-11eb-9fe3-540f04f28f13.png)
![image](https://user-images.githubusercontent.com/43430714/119788102-6e864600-bf04-11eb-87da-6a904cae2bbe.png)

**Comment by coreyzzp** [comment]
it will be good to has a method to delete or update comment  in a cell

**Comment by xuri** [comment]
This lib doesn't support modify comment and set the comment repeatedly on one cell currently. I've add this feature support in the [Roadmap](https://github.com/360EntSecGroup-Skylar/excelize/wiki#roadmap).

**Comment by coreyzzp** [comment]
thx~

**Comment by Jonham** [comment]
find an article about "comments" and "notes": [The difference between threaded comments and notes](https://support.microsoft.com/en-us/office/the-difference-between-threaded-comments-and-notes-75a51eec-4092-42ab-abf8-7669077b7be3)

**Comment by FoeverA0** [comment]
[WeOpen Star] I would like to help

**Comment by NaturalGao** [comment]
[WeOpen Star] I would like to help
