### ISSUE TITLE
Drop-down list items are not XML escaped

### ISSUE THREAD

**Issue by Arnie97** [qax-os/excelize#971]
### Description

If any of the XML special characters `<`, `>`, `&`, `"` were used in `SetDropList()` choices, the produced file will be reported as corrupted.

### Steps to reproduce the issue:

```go
package main

import (
	"github.com/360EntSecGroup-Skylar/excelize/v2"
)

func main() {
	var jobs = []string{"R&D", "PM", "UX", "HR"}
	newWorkbookWithDropList(jobs)
}

func newWorkbookWithDropList(choices []string) {
	f := excelize.NewFile()
	dv := excelize.NewDataValidation(false)
	dv.Sqref = "A:A"
	if err := dv.SetDropList(choices); err != nil {
		panic(err)
	}
	f.AddDataValidation(f.GetSheetName(0), dv)
	f.SaveAs("TestDropList.xlsx")
}
```

### Describe the results you received:

![image](https://user-images.githubusercontent.com/10341686/127224174-1e1419de-0ce5-4f32-a6f5-9472b387affe.png)

![image](https://user-images.githubusercontent.com/10341686/127224181-5cdf4813-e7ea-4c66-9b52-dee8eee8a3a1.png)

### Describe the results you expected:

![image](https://user-images.githubusercontent.com/10341686/127224205-4a6c3bed-1454-4765-9d67-246f07ee17ef.png)

### Output of `go version`:

```text
go version go1.17rc1 linux/amd64
```

### Excelize version or commit ID:

* master (e9ae9b4)
* v2.4.0 (d42834f)
* v2.1.0 (e51aff2)

### Environment details (OS, Microsoft Excel™ version, etc.):

The following official implementation were tested, and all of them could reproduce this issue:

* Microsoft Office 365 for Mac, 16.49 (21050901)
* Microsoft Office 365 for Windows, 2102 (Build 13801.20808)
* Microsoft Office 2019 Professional Plus for Windows, 2105 (Build 14026.20302)
* Microsoft Office 2013 Professional Plus for Windows, 15.0.4919.1002

The following third-party implementations were also tested, but none of them was affected by the issue:
* Kingsoft WPS
* Apple Numbers
* Google Sheets
* LibreOffice

**Comment by xuri** [comment]
Thanks for your feedback, I have fixed it, please try to use the master branch code, and this patch will be released in the next version.
