### ISSUE TITLE
Go Get Failed

### ISSUE THREAD

**Issue by AngangGuo** [qax-os/excelize#973]
I can run this command successfully:
```
go get github.com/360EntSecGroup-Skylar/excelize/v2
```

But this command failed:
```
go get github.com/xuri/excelize/v2
go get: github.com/xuri/excelize/v2@none updating to
        github.com/xuri/excelize/v2@v2.4.0: parsing go.mod:
        module declares its path as: github.com/360EntSecGroup-Skylar/excelize/v2
                but was required as: github.com/xuri/excelize/v2
```

```
\> go env
set GO111MODULE=auto
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\cxx00\AppData\Local\go-build
set GOENV=C:\Users\cxx00\AppData\Roaming\go\env
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GOMODCACHE=C:\Users\cxx00\go\pkg\mod
set GOOS=windows
set GOPATH=C:\Users\cxx00\go
set GOPROXY=https://proxy.golang.org,direct
set GOROOT=C:\Users\cxx00\sdk\go1.16.2
...
```

**Comment by xuri** [comment]
The new go modules import path will take effect after the next version 2.4.1 released.

**Comment by eaglexiang** [comment]
Think about:

```shell
go mod edit -replace=github.com/360EntSecGroup-Skylar/excelize/v2@master=github.com/xuri/excelize/v2@master

```

just for now.

**Comment by hunterhug** [comment]
smile.... what the ***

**Comment by ikhin** [comment]
go mod vendor should try `go get github.com/xuri/excelize/v2@master `, it's like the author said, will get `v2.4.1` 
the go.mod result is `github.com/xuri/excelize/v2 v2.4.1-0.20210728160357-7dbf88f221f2`

**Comment by Arnie97** [comment]
The breaking change was introduced in e9ae9b45b20a5df7e3aa15afcfac83ecb13394c6.
Did the author leave Qi-anxin (formerly @360EntSecGroup-Skylar) and start his new career in @alibaba? ;-)

**Comment by xuri** [comment]
The repo URL has changed twice for some reason, I'm sorry for bringing you inconvenience, I still maintain this project and welcome contributions.

**Comment by rishu2403** [comment]
> The repo URL has changed twice for some reason, I'm sorry for bringing you inconvenience, I still maintain this project and welcome contributions.

Can you please give updates on this issue? 

 github.com/xuri/excelize/v2: github.com/xuri/excelize/v2@v2.4.0: parsing go.mod:
        module declares its path as: github.com/360EntSecGroup-Skylar/excelize/v2
                but was required as: github.com/xuri/excelize/v2

**Comment by hunterhug** [comment]
> > The repo URL has changed twice for some reason, I'm sorry for bringing you inconvenience, I still maintain this project and welcome contributions.
> 
> Can you please give updates on this issue?
> 
> `github.com/xuri/excelize/v2: github.com/xuri/excelize/v2@v2.4.0: parsing go.mod: module declares its path as: github.com/360EntSecGroup-Skylar/excelize/v2 but was required as: github.com/xuri/excelize/v2`

Try `go get github.com/360EntSecGroup-Skylar/excelize/v2` will work.

**Comment by xuri** [comment]
> > The repo URL has changed twice for some reason, I'm sorry for bringing you inconvenience, I still maintain this project and welcome contributions.
> 
> Can you please give updates on this issue?
> 
> `github.com/xuri/excelize/v2: github.com/xuri/excelize/v2@v2.4.0: parsing go.mod: module declares its path as: github.com/360EntSecGroup-Skylar/excelize/v2 but was required as: github.com/xuri/excelize/v2`

The [next version](../projects) 2.4.1 will be released on August 2nd, 2021.

**Comment by llqgit** [comment]
> The repo URL has changed twice for some reason, I'm sorry for bringing you inconvenience, I still maintain this project and welcome contributions.

As you say, so can you make sure would not change the name again? It's not friendly at all.

**Comment by xuri** [comment]
Sorry, I can't make sure the organization name if will be changed in the future, but the original repo address (`https://github.com/xuri/excelize`) and go module name (`github.com/xuri/excelize/v2`) won't be changed.

**Comment by eaglexiang** [comment]
Any way, we just need a stable path to import. Both `xuri/*` and `any_org/*` are OK. :)
