### ISSUE TITLE
Not able to get excelcize module

### ISSUE THREAD

**Issue by qascade** [qax-os/excelize#977]
**Description**
Whenever I try to add a go dependency in go.mod using `go get` command it fails. 

 
**Steps to reproduce the issue:**
1.``` src git:(master) go get github.com/xuri/excelize/v2
          ```


**Describe the results you received:**
```
go get: github.com/xuri/excelize/v2@master: invalid version: Get "https://proxy.golang.org/github.com/xuri/excelize/v2/@v/master.info": unexpected EOF
```
**Describe the results you expected:**
 I wanted the module to be successfully downloaded and installed
**Output of `go version`:**
```go version go1.16.6 darwin/amd64```




**Environment details (OS, Microsoft Excel™ version, physical, etc.):**
OS = Mac OS Big Sur 
Physical Device = Mac Book Pro 2021

**Comment by Arnie97** [comment]
Please refer to #973.

**Comment by qascade** [comment]
```
go get github.com/360EntSecGroup-Skylar/excelize/v2
go get: module github.com/360EntSecGroup-Skylar/excelize/v2: Get "https://proxy.golang.org/github.com/360%21ent%21sec%21group-%21skylar/excelize/v2/@v/list": unexpected EOF
```

Infact, my whole work is stuck. I get this error for every module I try to include. I tried reinstalling go, but even that didn't work.

**Comment by xuri** [comment]
Please delete go mod cache `$GOPATH/pkg/mod/cache` and try again.

**Comment by qascade** [comment]
I created a new directory for GOPATH and it worked.
