### ISSUE TITLE
DeleteDataValidation doesn't  really delete the specified cell range

### ISSUE THREAD

**Issue by codefire53** [qax-os/excelize#979]
Hello, 

I'm facing an issue when using the DeleteDataValidation. The excel file I'm using can be described as following:

- The excel consists of 5 columns
- Each column has its own datavalidation
- First column has different datavalidation than the rest
- Last column has different datavalidation than the rest
- Column 2,3,4 have similar datavalidations. Their datavalidation are different from datavalidation in first & last column.
When I try to delete First & Last columns, the function deleted those datavalidation successfully, however when I deleted columns 2-4, the datavalidations still persist. Does anyone experience the same problem as mine? If this's really a bug can anyone fix this issue. Thanks in advance.

**Comment by xuri** [comment]
Thanks for your issue, I have fixed it, please try to use the master branch code.
