### ISSUE TITLE
file.GetCellValue() has a number of problems....

### ISSUE THREAD

**Issue by rbucker** [qax-os/excelize#984]
GetCellValue does not seem to return the formatted value. Nor does it return the RAW value in the RAW datatype that was Set(). The SetCellValue() takes an interface{} value that it uses to determine which formatting to apply. That too is confusing... if the source was text then the type determination is on my code. But that it is not returned plain or formatted consistently is a challenge.

Thanks

**Comment by xuri** [comment]
Thanks for your issue, this library doesn't support all number formats currently, according to the documentation, [`GetCellValue`](https://pkg.go.dev/github.com/xuri/excelize/v2#File.GetCellValue) will try to get formatted value from a cell, if it is possible to apply a format to the cell value, it will do so, if not will return the raw value of the cell. The `SetCellValue` always sets the raw value for the cell If you wanna set the number format of the cell, create a new style with the number format by `NewStyle` and then bind style with the cell by `SetCellStyle`, also ref #862.

**Comment by rbucker** [comment]
In this particular case I was given a spreadsheet from a 3rd party and I dumped the rows and cols in TSV format. When the file was opened in Excel or google sheet there was an integer column that was presented as integer but getcellvalue returned a trailing '.0'.

I understand the reply. If this is not a bug or feature please feel free to close.

**Comment by xuri** [comment]
Did you mean `GetCellValue` returns incorrect number precision of decimal type value? Could you provide more details or a spreadsheet xlsx attachment without confidential info?

**Comment by rbucker** [comment]
The value in the spreadsheet cell was '12345' but when I pulled the value with GetCellValue()... it returned '12345.0'. Sorry I do not have a working example.

**Comment by xuri** [comment]
I have tested it seems to work well, I'll close this issue, if you have any questions, info of code, and attachments to reproduce this issue, please let me know, and reopen this issue at any time.
