### ISSUE TITLE
why SetSqrefDropList remove tag "<formula1></formula1>" in v2.4.1，it cause the dropList does't work

### ISSUE THREAD

**Issue by xieping5555** [qax-os/excelize#986]
https://github.com/qax-os/excelize/blob/933159f9391f9be1b41b51e85885722124f8a7aa/datavalidation.go#L157

**Comment by xuri** [comment]
Thanks for your feedback, this issue was caused by commit [`7dbf88f`](https://github.com/xuri/excelize/commit/7dbf88f221f278075d4ff9e153b21236d0826c33), I'll fix it later.

**Comment by xuri** [comment]
I have fixed it, please try to use the master branch code.
