### ISSUE TITLE
If the last column in excel is empty, GetRows(sheet) causes the length of the array to be reduced by 1

### ISSUE THREAD

**Issue by yhinan** [qax-os/excelize#989]
If the last column in excel is empty, GetRows(sheet) causes the length of the array to be reduced by 1；
How to make the array length consistent

**Comment by xuri** [comment]
`GetRows` fetched the rows with value cells, the tail continuously empty cell will be skipped.

**Comment by yhinan** [comment]
I think all the column numbers in excel should be the same, or customize the read column range;

```
        rows, err := f.Rows(sheetName)
	rows.Next()
	header, err := rows.Columns()
	for rows.Next() {
		row, _ := rows.Columns()
		if len(row) < len(header) {
			row = append(row, "")
		}
		res = append(res, row)
	}

**Comment by echarrod** [comment]
Was this fixed? It still seems an issue for me when using v2.8.1. 
Was going to write a potential fix, but wanted to check I wasn't missing something first. 

I'm doing:
```go
xlsx, err := excelize.OpenReader(r)
if err != nil {
	return nil, err
}

allRows, err := xlsx.GetRows(xlsx.GetSheetName(0))
```

**Comment by echarrod** [comment]
I see your suggestion on https://github.com/qax-os/excelize/issues/1245 which is to manually add. 

Was wondering if it might be possible to define this behaviour in an option passed in to GetRows, so that I wouldn't have to iterate through each row again after retrieving the result with GetRows 🙏
