### ISSUE TITLE
When I set cell styles, the file size goes really larger

### ISSUE THREAD

**Issue by 873310466** [qax-os/excelize#990]
**Description**
I set cell styles to make cell unlocked so that I can protect the sheet by specifying range .
But when I set cell styles(A1:W20000), the file size goes really larger( maybe 15kb -> 900kb )

style content is like below
```json
{
		 "alignment": {
		   "vertical": "top",
		   "wrap_text": true
		 },
		 "protection": {
		   "locked": false
		 },
		 "font": {
		   "family": "Times New Roman"
		 }
}
```

**Steps to reproduce the issue:**
0. read a excel that already existed
1. use NewStyle()
2. use SetStyle()
3. use WriteToBuff()
4. use ioutil.WriteFile to make buff a file

**Describe the results you received:**
1. the excel file size goes larger(15kb -> 900kb)
2. some styles are set to default value.(e.g. alignment.vertical=bottom ) 

**Describe the results you expected:**
can i receive a small size excel file?

or if there's another way to lock the Sheet?

Thanks !

**Output of `go version`:**
1.16

**Comment by xuri** [comment]
`SetCellStyle` binding style for each cell in the specified range, so the document size will grow, same as the spreadsheet created by the Excel application.

**Comment by 873310466** [comment]
> `SetCellStyle` binding style for each cell in the specified range, so the document size will grow, same as the spreadsheet created by the Excel application.

when I set cell styles**(just unlocked or locked)** in Excel. The file's size won't be changed from 15kb -> 900kb.
but when I used excelize to do this, the files size really confused me.

**Comment by xuri** [comment]
If you wanna set the style for all cells of the worksheet (as a select range by Ctrl+A), like this:

```go
f.SetColStyle("Sheet1","A:XFD",styleID)
```

and this library doesn't support set single rows style currently, I'll add support `SetRowStyle` later.

**Comment by 873310466** [comment]
> If you wanna set the style for all cells of the worksheet (as a select range by Ctrl+A), like this:
> 
> ```go
> f.SetColStyle("Sheet1","A:XFD",styleID)
> ```
> 
> and this library doesn't support set single rows style currently, I'll add support `SetRowStyle` later.

Thanks a lot .
But why i set cell style like below, it will change my default cell style(e.g. font color from red to black).
```json
{
		 "protection": {
		   "locked": false
                  }
}
```

**Comment by xuri** [comment]
Note that `SetColStyle` and `SetCellStyle` will overwrite the style for the cell, it won't append or merge style with existing styles, so you can create a style that contains font color and protection.

**Comment by 873310466** [comment]
> Note that `SetColStyle` and `SetCellStyle` will overwrite the style for the cell, it won't append or merge style with existing styles, so you can create a style that contains font color and protection.

Thanks ❤️

**Comment by xuri** [comment]
I have added a new API: `SetRowStyle` support for set style for the rows, please try to upgrade the master branch code.
