### ISSUE TITLE
有打算支持加载模板导出excel这种功能吗?

### ISSUE THREAD

**Issue by MasterJoyHunan** [qax-os/excelize#992]
类似于 java 的 jxls 类库

**Comment by xuri** [comment]
Thanks for your issue, there is no plan for that, this library provides a set of basic functions to allow you to read and writing spreadsheet documents, you can open an existing spreadsheet as a template and save it as another document after data has been modifying, or binding value by custom structures as discussed in issue #619, and you can also easy to implement value replace of the cell by existing APIs.
