### ISSUE TITLE
CalcCellValue does not handle dates

### ISSUE THREAD

**Issue by stanim** [qax-os/excelize#998]
[date.zip](https://github.com/qax-os/excelize/files/7011125/date.zip)
**Description**

CalcCellValue treats dates as strings. As a consequence CalcCellValue is unable to process dates in formulas:

- mathemical expressions give parsing error
- comparison fails: "19-08-2021" > "20-07-2022", but should be the opposite

**Steps to reproduce the issue:**

1. Download date.zip and unzip it
2. Run the go file: go run ./date.go

**Describe the results you received:**

```
> go run ./date.go

date.xlsx
Sheet1!C2: error: strconv.ParseFloat: parsing "03/08/21": invalid syntax
Sheet1!C3: error: strconv.ParseFloat: parsing "19/08/21": invalid syntax
```

**Describe the results you expected:**

```
> go run ./date.go

date.xlsx
Sheet1!C2: sucess: "05-08-21"
Sheet1!C3: should be true: "true"
```

**Output of `go version`:**

```text
go version go1.16.7 linux/amd64
```

**Excelize version or commit ID:**

```text
> git log
commit a55f354eb3d0c6c1b9a543ff8ff98227aa6063a6 (HEAD -> lookup, origin/master, origin/HEAD, master)
Author: xuri <xuri.me@gmail.com>
Date:   Tue Aug 17 00:01:44 2021 +0800

    This closes #989, closes #990
    
    New API: `SetRowStyle` support for set style for the rows
    Update documentation for the `GetRows`, `SetCellStyle` and `SetColStyle`
```

**Environment details (OS, Microsoft Excel™ version, physical, etc.):**
- OS: Archlinux 5.13.10-arch1-1
- WPS Spreadsheets (version wps-office 11.1.0.10702-1)
- LibreCalc (version libreoffice-fresh 7.1.5-2)

**Comment by xuri** [comment]
Thanks for your issue, I have added text comparison support, please try to upgrade to the master branch.
