### ISSUE TITLE
考虑增加跨行，跨列支持吗？

### ISSUE THREAD

**Issue by wwhai** [qax-os/excelize#999]
希望增加这种类型的表格支持：
![image](https://user-images.githubusercontent.com/20577297/130005334-cdae6168-6dad-4361-86c1-2ed3bd3bd4ab.png)
有跨列显示

**Comment by xuri** [comment]
Please reference the documentation for [MergeCells](https://xuri.me/excelize/zh-hans/cell.html#MergeCell).
